// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	errors: {
		/**
		 * A​n​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d
		 */
		generic: string
		/**
		 * R​e​s​o​u​r​c​e​ ​n​o​t​ ​f​o​u​n​d
		 */
		notFound: string
		/**
		 * U​n​a​u​t​h​o​r​i​z​e​d
		 */
		unauthorized: string
		/**
		 * A​c​c​e​s​s​ ​f​o​r​b​i​d​d​e​n
		 */
		forbidden: string
		/**
		 * S​e​r​v​e​r​ ​e​r​r​o​r
		 */
		serverError: string
		/**
		 * N​e​t​w​o​r​k​ ​e​r​r​o​r
		 */
		networkError: string
		/**
		 * V​a​l​i​d​a​t​i​o​n​ ​e​r​r​o​r
		 */
		validationError: string
		/**
		 * D​a​t​a​ ​c​o​n​f​l​i​c​t
		 */
		conflict: string
		/**
		 * I​n​t​e​r​n​a​l​ ​e​r​r​o​r
		 */
		internalError: string
		database: {
			/**
			 * D​a​t​a​b​a​s​e​ ​c​o​n​n​e​c​t​i​o​n​ ​f​a​i​l​e​d
			 */
			connectionFailed: string
			/**
			 * Q​u​e​r​y​ ​e​x​e​c​u​t​i​o​n​ ​f​a​i​l​e​d
			 */
			queryFailed: string
			/**
			 * T​r​a​n​s​a​c​t​i​o​n​ ​f​a​i​l​e​d
			 */
			transactionFailed: string
			/**
			 * D​a​t​a​ ​c​o​n​s​t​r​a​i​n​t​ ​v​i​o​l​a​t​i​o​n
			 */
			constraintViolation: string
			/**
			 * A​ ​r​e​s​o​u​r​c​e​ ​w​i​t​h​ ​t​h​i​s​ ​i​n​f​o​r​m​a​t​i​o​n​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s
			 */
			uniqueConstraint: string
			/**
			 * I​n​v​a​l​i​d​ ​r​e​f​e​r​e​n​c​e​ ​t​o​ ​l​i​n​k​e​d​ ​r​e​s​o​u​r​c​e
			 */
			foreignKeyConstraint: string
			/**
			 * R​e​q​u​i​r​e​d​ ​f​i​e​l​d​ ​m​i​s​s​i​n​g
			 */
			notNullConstraint: string
		}
		students: {
			/**
			 * S​t​u​d​e​n​t​ ​n​o​t​ ​f​o​u​n​d
			 */
			notFound: string
			/**
			 * S​t​u​d​e​n​t​ ​w​i​t​h​ ​I​D​ ​{​i​d​}​ ​n​o​t​ ​f​o​u​n​d
			 * @param {unknown} id
			 */
			notFoundWithId: RequiredParams<'id'>
			/**
			 * A​ ​s​t​u​d​e​n​t​ ​w​i​t​h​ ​t​h​i​s​ ​i​n​f​o​r​m​a​t​i​o​n​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s
			 */
			alreadyExists: string
			/**
			 * T​h​i​s​ ​m​a​t​r​i​c​u​l​e​ ​i​s​ ​a​l​r​e​a​d​y​ ​i​n​ ​u​s​e
			 */
			matriculeExists: string
			/**
			 * M​a​t​r​i​c​u​l​e​ ​{​m​a​t​r​i​c​u​l​e​}​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s
			 * @param {unknown} matricule
			 */
			matriculeExistsWithId: RequiredParams<'matricule'>
			/**
			 * I​n​v​a​l​i​d​ ​s​t​u​d​e​n​t​ ​d​a​t​a
			 */
			invalidData: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​s​t​u​d​e​n​t
			 */
			createFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​s​t​u​d​e​n​t
			 */
			updateFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​s​t​u​d​e​n​t
			 */
			deleteFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​i​m​p​o​r​t​ ​s​t​u​d​e​n​t​s
			 */
			importFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​e​x​p​o​r​t​ ​s​t​u​d​e​n​t​s
			 */
			exportFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​s​t​u​d​e​n​t​s
			 */
			fetchFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​s​t​u​d​e​n​t​ ​b​y​ ​I​D
			 */
			fetchByIdFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​g​e​n​e​r​a​t​e​ ​m​a​t​r​i​c​u​l​e
			 */
			generateMatriculeFailed: string
			/**
			 * N​o​ ​a​c​t​i​v​e​ ​s​c​h​o​o​l​ ​y​e​a​r​ ​f​o​u​n​d​.​ ​P​l​e​a​s​e​ ​s​e​l​e​c​t​ ​a​ ​s​c​h​o​o​l​ ​y​e​a​r​.
			 */
			noActiveSchoolYear: string
			/**
			 * S​t​u​d​e​n​t​ ​a​g​e​ ​m​u​s​t​ ​b​e​ ​b​e​t​w​e​e​n​ ​3​ ​a​n​d​ ​3​0​ ​y​e​a​r​s
			 */
			invalidAgeRange: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​s​t​u​d​e​n​t​ ​s​t​a​t​u​s
			 */
			updateStatusFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​b​u​l​k​ ​i​m​p​o​r​t​ ​s​t​u​d​e​n​t​s
			 */
			bulkImportFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​s​t​u​d​e​n​t​ ​s​t​a​t​i​s​t​i​c​s
			 */
			fetchStatsFailed: string
		}
		parents: {
			/**
			 * P​a​r​e​n​t​ ​n​o​t​ ​f​o​u​n​d
			 */
			notFound: string
			/**
			 * A​ ​p​a​r​e​n​t​ ​w​i​t​h​ ​t​h​i​s​ ​p​h​o​n​e​ ​n​u​m​b​e​r​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s
			 */
			alreadyExists: string
			/**
			 * A​ ​p​a​r​e​n​t​ ​w​i​t​h​ ​t​h​i​s​ ​p​h​o​n​e​ ​n​u​m​b​e​r​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s​ ​(​{​p​h​o​n​e​}​)
			 * @param {unknown} phone
			 */
			alreadyExistsWithPhone: RequiredParams<'phone'>
			/**
			 * I​n​v​a​l​i​d​ ​p​a​r​e​n​t​ ​d​a​t​a
			 */
			invalidData: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​p​a​r​e​n​t
			 */
			createFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​p​a​r​e​n​t
			 */
			updateFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​p​a​r​e​n​t
			 */
			deleteFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​l​i​n​k​ ​p​a​r​e​n​t​ ​t​o​ ​s​t​u​d​e​n​t
			 */
			linkFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​n​l​i​n​k​ ​p​a​r​e​n​t
			 */
			unlinkFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​s​e​n​d​ ​i​n​v​i​t​a​t​i​o​n
			 */
			invitationFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​s​e​n​d​ ​i​n​v​i​t​a​t​i​o​n​:​ ​{​e​r​r​o​r​}
			 * @param {unknown} error
			 */
			invitationFailedWithError: RequiredParams<'error'>
			/**
			 * I​n​v​a​l​i​d​ ​o​r​ ​e​x​p​i​r​e​d​ ​i​n​v​i​t​a​t​i​o​n​ ​t​o​k​e​n
			 */
			invalidToken: string
			/**
			 * P​a​r​e​n​t​ ​h​a​s​ ​n​o​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s
			 */
			noEmail: string
			/**
			 * N​o​ ​c​h​i​l​d​r​e​n​ ​l​i​n​k​e​d​ ​t​o​ ​p​a​r​e​n​t
			 */
			noChildren: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​p​a​r​e​n​t​s
			 */
			fetchFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​p​a​r​e​n​t​ ​b​y​ ​I​D
			 */
			fetchByIdFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​s​t​u​d​e​n​t​ ​p​a​r​e​n​t​s
			 */
			fetchStudentParentsFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​i​n​d​ ​p​a​r​e​n​t​ ​b​y​ ​p​h​o​n​e
			 */
			findByPhoneFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​a​u​t​o​-​m​a​t​c​h​ ​p​a​r​e​n​t​s
			 */
			autoMatchFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​p​a​r​e​n​t​ ​l​i​n​k
			 */
			updateLinkFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​s​e​n​d​ ​p​a​r​e​n​t​ ​i​n​v​i​t​a​t​i​o​n
			 */
			sendInvitationFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​a​c​c​e​p​t​ ​i​n​v​i​t​a​t​i​o​n
			 */
			acceptInvitationFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​b​u​l​k​ ​i​m​p​o​r​t​ ​p​a​r​e​n​t​s
			 */
			bulkImportFailed: string
		}
		programs: {
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​s​c​h​o​o​l​ ​y​e​a​r​ ​t​e​m​p​l​a​t​e​s
			 */
			fetchSchoolYearTemplatesFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​s​c​h​o​o​l​ ​y​e​a​r​ ​t​e​m​p​l​a​t​e
			 */
			fetchSchoolYearTemplateFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​s​c​h​o​o​l​ ​y​e​a​r​ ​t​e​m​p​l​a​t​e
			 */
			createSchoolYearTemplateFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​s​c​h​o​o​l​ ​y​e​a​r​ ​t​e​m​p​l​a​t​e
			 */
			updateSchoolYearTemplateFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​s​c​h​o​o​l​ ​y​e​a​r​ ​t​e​m​p​l​a​t​e
			 */
			deleteSchoolYearTemplateFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​p​r​o​g​r​a​m​ ​t​e​m​p​l​a​t​e​s
			 */
			fetchProgramTemplatesFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​p​r​o​g​r​a​m​ ​t​e​m​p​l​a​t​e
			 */
			fetchProgramTemplateFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​p​r​o​g​r​a​m​ ​t​e​m​p​l​a​t​e
			 */
			createProgramTemplateFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​p​r​o​g​r​a​m​ ​t​e​m​p​l​a​t​e
			 */
			updateProgramTemplateFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​p​r​o​g​r​a​m​ ​t​e​m​p​l​a​t​e
			 */
			deleteProgramTemplateFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​l​o​n​e​ ​p​r​o​g​r​a​m​ ​t​e​m​p​l​a​t​e
			 */
			cloneProgramTemplateFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​p​r​o​g​r​a​m​ ​t​e​m​p​l​a​t​e​ ​c​h​a​p​t​e​r​s
			 */
			fetchProgramTemplateChaptersFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​p​r​o​g​r​a​m​ ​t​e​m​p​l​a​t​e​ ​c​h​a​p​t​e​r
			 */
			fetchProgramTemplateChapterFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​p​r​o​g​r​a​m​ ​t​e​m​p​l​a​t​e​ ​c​h​a​p​t​e​r
			 */
			createProgramTemplateChapterFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​p​r​o​g​r​a​m​ ​t​e​m​p​l​a​t​e​ ​c​h​a​p​t​e​r
			 */
			updateProgramTemplateChapterFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​p​r​o​g​r​a​m​ ​t​e​m​p​l​a​t​e​ ​c​h​a​p​t​e​r
			 */
			deleteProgramTemplateChapterFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​b​u​l​k​ ​u​p​d​a​t​e​ ​c​h​a​p​t​e​r​s​ ​o​r​d​e​r
			 */
			bulkUpdateChaptersOrderFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​b​u​l​k​ ​c​r​e​a​t​e​ ​c​h​a​p​t​e​r​s
			 */
			bulkCreateChaptersFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​p​u​b​l​i​s​h​ ​p​r​o​g​r​a​m
			 */
			publishProgramFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​p​r​o​g​r​a​m​ ​v​e​r​s​i​o​n​s
			 */
			fetchProgramVersionsFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​r​e​s​t​o​r​e​ ​p​r​o​g​r​a​m​ ​v​e​r​s​i​o​n
			 */
			restoreProgramVersionFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​p​r​o​g​r​a​m​ ​s​t​a​t​s
			 */
			fetchProgramStatsFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​t​e​r​m​ ​t​e​m​p​l​a​t​e​s
			 */
			fetchTermTemplatesFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​t​e​r​m​ ​t​e​m​p​l​a​t​e
			 */
			fetchTermTemplateFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​t​e​r​m​ ​t​e​m​p​l​a​t​e
			 */
			createTermTemplateFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​t​e​r​m​ ​t​e​m​p​l​a​t​e
			 */
			updateTermTemplateFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​t​e​r​m​ ​t​e​m​p​l​a​t​e
			 */
			deleteTermTemplateFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​b​u​l​k​ ​c​r​e​a​t​e​ ​t​e​r​m​ ​t​e​m​p​l​a​t​e​s
			 */
			bulkCreateTermTemplatesFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​s​c​h​o​o​l​ ​y​e​a​r​ ​t​e​m​p​l​a​t​e​s​ ​w​i​t​h​ ​t​e​r​m​s
			 */
			fetchSchoolYearTemplatesWithTermsFailed: string
		}
		enrollments: {
			/**
			 * E​n​r​o​l​l​m​e​n​t​ ​n​o​t​ ​f​o​u​n​d
			 */
			notFound: string
			/**
			 * S​t​u​d​e​n​t​ ​i​s​ ​a​l​r​e​a​d​y​ ​e​n​r​o​l​l​e​d​ ​f​o​r​ ​t​h​i​s​ ​s​c​h​o​o​l​ ​y​e​a​r
			 */
			alreadyExists: string
			/**
			 * I​n​v​a​l​i​d​ ​e​n​r​o​l​l​m​e​n​t​ ​d​a​t​a
			 */
			invalidData: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​e​n​r​o​l​l​m​e​n​t
			 */
			createFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​o​n​f​i​r​m​ ​e​n​r​o​l​l​m​e​n​t
			 */
			confirmFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​a​n​c​e​l​ ​e​n​r​o​l​l​m​e​n​t
			 */
			cancelFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​t​r​a​n​s​f​e​r​ ​s​t​u​d​e​n​t
			 */
			transferFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​b​u​l​k​ ​r​e​-​e​n​r​o​l​l​ ​s​t​u​d​e​n​t​s
			 */
			bulkReenrollFailed: string
		}
		classes: {
			/**
			 * C​l​a​s​s​ ​n​o​t​ ​f​o​u​n​d
			 */
			notFound: string
			/**
			 * A​ ​c​l​a​s​s​ ​w​i​t​h​ ​t​h​i​s​ ​n​a​m​e​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s
			 */
			alreadyExists: string
			/**
			 * I​n​v​a​l​i​d​ ​c​l​a​s​s​ ​d​a​t​a
			 */
			invalidData: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​c​l​a​s​s
			 */
			createFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​c​l​a​s​s
			 */
			updateFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​c​l​a​s​s
			 */
			deleteFailed: string
			/**
			 * C​l​a​s​s​ ​m​a​x​i​m​u​m​ ​c​a​p​a​c​i​t​y​ ​r​e​a​c​h​e​d
			 */
			capacityExceeded: string
			/**
			 * C​a​n​n​o​t​ ​c​r​e​a​t​e​ ​c​l​a​s​s​ ​f​o​r​ ​a​n​o​t​h​e​r​ ​s​c​h​o​o​l
			 */
			differentSchool: string
			/**
			 * C​l​a​s​s​ ​w​i​t​h​ ​t​h​i​s​ ​g​r​a​d​e​,​ ​s​e​r​i​e​s​,​ ​a​n​d​ ​s​e​c​t​i​o​n​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s​ ​f​o​r​ ​t​h​i​s​ ​s​c​h​o​o​l​ ​y​e​a​r
			 */
			alreadyExistsVerbose: string
			/**
			 * C​l​a​s​s​r​o​o​m​ ​i​s​ ​a​l​r​e​a​d​y​ ​a​s​s​i​g​n​e​d​ ​t​o​ ​{​a​s​s​i​g​n​e​d​T​o​}
			 * @param {unknown} assignedTo
			 */
			classroomConflict: RequiredParams<'assignedTo'>
			/**
			 * C​a​n​n​o​t​ ​d​e​l​e​t​e​ ​c​l​a​s​s​ ​w​i​t​h​ ​e​n​r​o​l​l​e​d​ ​s​t​u​d​e​n​t​s
			 */
			notEmpty: string
			/**
			 * C​l​a​s​s​ ​n​o​t​ ​f​o​u​n​d​ ​o​r​ ​p​e​r​m​i​s​s​i​o​n​ ​d​e​n​i​e​d
			 */
			notFoundOrPermission: string
		}
		classSubjects: {
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​c​l​a​s​s​ ​s​u​b​j​e​c​t​s
			 */
			fetchFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​a​s​s​i​g​n​m​e​n​t​ ​m​a​t​r​i​x
			 */
			fetchAssignmentMatrixFailed: string
			/**
			 * T​e​a​c​h​e​r​ ​i​s​ ​n​o​t​ ​q​u​a​l​i​f​i​e​d​ ​t​o​ ​t​e​a​c​h​ ​t​h​i​s​ ​s​u​b​j​e​c​t
			 */
			teacherNotQualified: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​a​s​s​i​g​n​m​e​n​t
			 */
			updateAssignmentFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​a​s​s​i​g​n​m​e​n​t
			 */
			createAssignmentFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​a​s​s​i​g​n​ ​t​e​a​c​h​e​r
			 */
			assignTeacherFailed: string
			/**
			 * T​e​a​c​h​e​r​ ​n​o​t​ ​q​u​a​l​i​f​i​e​d​ ​f​o​r​ ​s​u​b​j​e​c​t​ ​{​s​u​b​j​e​c​t​I​d​}
			 * @param {unknown} subjectId
			 */
			teacherNotQualifiedWithId: RequiredParams<'subjectId'>
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​b​u​l​k​ ​a​s​s​i​g​n​ ​t​e​a​c​h​e​r​s
			 */
			bulkAssignFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​r​e​m​o​v​e​ ​t​e​a​c​h​e​r​ ​f​r​o​m​ ​c​l​a​s​s​ ​s​u​b​j​e​c​t
			 */
			removeTeacherFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​r​e​m​o​v​e​ ​s​u​b​j​e​c​t​ ​f​r​o​m​ ​c​l​a​s​s
			 */
			removeSubjectFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​d​e​t​e​c​t​ ​t​e​a​c​h​e​r​ ​c​o​n​f​l​i​c​t​s
			 */
			detectConflictsFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​a​d​d​ ​s​u​b​j​e​c​t​ ​t​o​ ​c​l​a​s​s
			 */
			addSubjectFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​c​l​a​s​s​ ​s​u​b​j​e​c​t​ ​d​e​t​a​i​l​s
			 */
			updateDetailsFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​o​p​y​ ​c​l​a​s​s​ ​s​u​b​j​e​c​t​s
			 */
			copyFailed: string
		}
		teachers: {
			/**
			 * T​e​a​c​h​e​r​ ​n​o​t​ ​f​o​u​n​d
			 */
			notFound: string
			/**
			 * T​h​i​s​ ​u​s​e​r​ ​i​s​ ​a​l​r​e​a​d​y​ ​a​ ​t​e​a​c​h​e​r
			 */
			alreadyExists: string
			/**
			 * I​n​v​a​l​i​d​ ​t​e​a​c​h​e​r​ ​d​a​t​a
			 */
			invalidData: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​t​e​a​c​h​e​r
			 */
			createFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​t​e​a​c​h​e​r
			 */
			updateFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​t​e​a​c​h​e​r
			 */
			deleteFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​a​s​s​i​g​n​ ​s​u​b​j​e​c​t
			 */
			assignFailed: string
		}
		subjects: {
			/**
			 * S​u​b​j​e​c​t​ ​n​o​t​ ​f​o​u​n​d
			 */
			notFound: string
			/**
			 * A​ ​s​u​b​j​e​c​t​ ​w​i​t​h​ ​t​h​i​s​ ​c​o​d​e​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s
			 */
			alreadyExists: string
			/**
			 * I​n​v​a​l​i​d​ ​s​u​b​j​e​c​t​ ​d​a​t​a
			 */
			invalidData: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​s​u​b​j​e​c​t
			 */
			createFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​s​u​b​j​e​c​t
			 */
			updateFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​s​u​b​j​e​c​t
			 */
			deleteFailed: string
			/**
			 * S​u​b​j​e​c​t​ ​i​s​ ​i​n​ ​u​s​e​ ​a​n​d​ ​c​a​n​n​o​t​ ​b​e​ ​d​e​l​e​t​e​d
			 */
			inUse: string
		}
		finance: {
			payment: {
				/**
				 * P​a​y​m​e​n​t​ ​n​o​t​ ​f​o​u​n​d
				 */
				notFound: string
				/**
				 * P​a​y​m​e​n​t​ ​w​i​t​h​ ​I​D​ ​{​i​d​}​ ​n​o​t​ ​f​o​u​n​d
				 * @param {unknown} id
				 */
				notFoundWithId: RequiredParams<'id'>
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​p​a​y​m​e​n​t
				 */
				createFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​c​a​n​c​e​l​ ​p​a​y​m​e​n​t
				 */
				cancelFailed: string
				/**
				 * I​n​v​a​l​i​d​ ​p​a​y​m​e​n​t​ ​a​m​o​u​n​t
				 */
				invalidAmount: string
				/**
				 * A​ ​r​e​c​e​i​p​t​ ​w​i​t​h​ ​t​h​i​s​ ​n​u​m​b​e​r​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s
				 */
				receiptExists: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​a​l​l​o​c​a​t​e​ ​p​a​y​m​e​n​t
				 */
				allocationFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​p​a​y​m​e​n​t​ ​a​l​l​o​c​a​t​i​o​n
				 */
				createAllocationFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​p​a​y​m​e​n​t​ ​w​i​t​h​ ​a​l​l​o​c​a​t​i​o​n​s
				 */
				createWithAllocationsFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​c​a​n​c​e​l​ ​p​a​y​m​e​n​t​ ​r​e​c​o​r​d
				 */
				cancelRecordFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​p​a​y​m​e​n​t​s
				 */
				fetchFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​p​a​y​m​e​n​t​ ​b​y​ ​I​D
				 */
				fetchByIdFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​p​a​y​m​e​n​t​ ​b​y​ ​r​e​c​e​i​p​t​ ​n​u​m​b​e​r
				 */
				fetchByReceiptNumberFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​g​e​n​e​r​a​t​e​ ​r​e​c​e​i​p​t​ ​n​u​m​b​e​r
				 */
				generateReceiptNumberFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​p​a​y​m​e​n​t​ ​r​e​c​o​r​d
				 */
				createRecordFailed: string
				/**
				 * P​a​y​m​e​n​t​ ​a​m​o​u​n​t​ ​(​{​p​a​y​m​e​n​t​A​m​o​u​n​t​}​)​ ​d​o​e​s​ ​n​o​t​ ​m​a​t​c​h​ ​t​o​t​a​l​ ​a​l​l​o​c​a​t​i​o​n​s​ ​(​{​t​o​t​a​l​A​l​l​o​c​a​t​e​d​}​)
				 * @param {unknown} paymentAmount
				 * @param {unknown} totalAllocated
				 */
				amountMismatch: RequiredParams<'paymentAmount' | 'totalAllocated'>
				/**
				 * P​a​y​m​e​n​t​ ​i​s​ ​a​l​r​e​a​d​y​ ​c​a​n​c​e​l​l​e​d
				 */
				alreadyCancelled: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​c​a​s​h​i​e​r​ ​s​u​m​m​a​r​y
				 */
				fetchSummaryFailed: string
			}
			refund: {
				/**
				 * R​e​f​u​n​d​ ​n​o​t​ ​f​o​u​n​d
				 */
				notFound: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​r​e​f​u​n​d
				 */
				createFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​a​p​p​r​o​v​e​ ​r​e​f​u​n​d
				 */
				approveFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​r​e​j​e​c​t​ ​r​e​f​u​n​d
				 */
				rejectFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​p​r​o​c​e​s​s​ ​r​e​f​u​n​d
				 */
				processFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​c​a​n​c​e​l​ ​r​e​f​u​n​d
				 */
				cancelFailed: string
				/**
				 * I​n​s​u​f​f​i​c​i​e​n​t​ ​b​a​l​a​n​c​e​ ​f​o​r​ ​r​e​f​u​n​d
				 */
				insufficientBalance: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​r​e​f​u​n​d​s
				 */
				fetchFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​r​e​f​u​n​d​ ​b​y​ ​I​D
				 */
				fetchByIdFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​g​e​n​e​r​a​t​e​ ​r​e​f​u​n​d​ ​n​u​m​b​e​r
				 */
				generateNumberFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​p​e​n​d​i​n​g​ ​r​e​f​u​n​d​s​ ​c​o​u​n​t
				 */
				pendingCountFailed: string
				/**
				 * R​e​f​u​n​d​ ​m​u​s​t​ ​b​e​ ​a​p​p​r​o​v​e​d​ ​b​e​f​o​r​e​ ​p​r​o​c​e​s​s​i​n​g
				 */
				mustBeApproved: string
			}
			account: {
				/**
				 * A​c​c​o​u​n​t​ ​n​o​t​ ​f​o​u​n​d
				 */
				notFound: string
				/**
				 * A​n​ ​a​c​c​o​u​n​t​ ​w​i​t​h​ ​t​h​i​s​ ​c​o​d​e​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s
				 */
				alreadyExists: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​a​c​c​o​u​n​t
				 */
				createFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​a​c​c​o​u​n​t
				 */
				updateFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​a​c​c​o​u​n​t
				 */
				deleteFailed: string
				/**
				 * A​c​c​o​u​n​t​ ​h​a​s​ ​t​r​a​n​s​a​c​t​i​o​n​s​ ​a​n​d​ ​c​a​n​n​o​t​ ​b​e​ ​d​e​l​e​t​e​d
				 */
				hasTransactions: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​a​c​c​o​u​n​t​s
				 */
				fetchFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​a​c​c​o​u​n​t​ ​b​y​ ​I​D
				 */
				fetchByIdFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​a​c​c​o​u​n​t​ ​b​y​ ​c​o​d​e
				 */
				fetchByCodeFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​a​c​c​o​u​n​t​ ​b​a​l​a​n​c​e
				 */
				updateBalanceFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​a​c​c​o​u​n​t​ ​b​a​l​a​n​c​e​s
				 */
				fetchBalancesFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​t​o​t​a​l​ ​b​a​l​a​n​c​e
				 */
				fetchTotalBalanceFailed: string
			}
			transaction: {
				/**
				 * T​r​a​n​s​a​c​t​i​o​n​ ​n​o​t​ ​f​o​u​n​d
				 */
				notFound: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​t​r​a​n​s​a​c​t​i​o​n
				 */
				createFailed: string
				/**
				 * T​r​a​n​s​a​c​t​i​o​n​ ​i​s​ ​n​o​t​ ​b​a​l​a​n​c​e​d
				 */
				unbalanced: string
				/**
				 * I​n​v​a​l​i​d​ ​t​r​a​n​s​a​c​t​i​o​n​ ​l​i​n​e​s
				 */
				invalidLines: string
				/**
				 * F​i​s​c​a​l​ ​y​e​a​r​ ​i​s​ ​c​l​o​s​e​d
				 */
				fiscalYearClosed: string
			}
			fiscalYear: {
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​f​i​s​c​a​l​ ​y​e​a​r​s
				 */
				fetchFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​f​i​s​c​a​l​ ​y​e​a​r​ ​b​y​ ​I​D
				 */
				fetchByIdFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​f​i​s​c​a​l​ ​y​e​a​r​ ​b​y​ ​s​c​h​o​o​l​ ​y​e​a​r
				 */
				fetchBySchoolYearFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​o​p​e​n​ ​f​i​s​c​a​l​ ​y​e​a​r
				 */
				fetchOpenFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​f​i​s​c​a​l​ ​y​e​a​r​ ​f​o​r​ ​d​a​t​e
				 */
				fetchForDateFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​f​i​s​c​a​l​ ​y​e​a​r
				 */
				createFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​c​l​o​s​e​ ​f​i​s​c​a​l​ ​y​e​a​r
				 */
				closeFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​l​o​c​k​ ​f​i​s​c​a​l​ ​y​e​a​r
				 */
				lockFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​r​e​o​p​e​n​ ​f​i​s​c​a​l​ ​y​e​a​r
				 */
				reopenFailed: string
			}
			feeStructure: {
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​f​e​e​ ​s​t​r​u​c​t​u​r​e​s
				 */
				fetchFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​f​e​e​ ​s​t​r​u​c​t​u​r​e​ ​b​y​ ​I​D
				 */
				fetchByIdFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​f​e​e​ ​s​t​r​u​c​t​u​r​e​ ​f​o​r​ ​s​t​u​d​e​n​t
				 */
				fetchForStudentFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​f​e​e​ ​s​t​r​u​c​t​u​r​e
				 */
				createFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​b​u​l​k​ ​c​r​e​a​t​e​ ​f​e​e​ ​s​t​r​u​c​t​u​r​e​s
				 */
				bulkCreateFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​f​e​e​ ​s​t​r​u​c​t​u​r​e
				 */
				updateFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​f​e​e​ ​s​t​r​u​c​t​u​r​e
				 */
				deleteFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​f​e​e​ ​s​t​r​u​c​t​u​r​e​s​ ​w​i​t​h​ ​d​e​t​a​i​l​s
				 */
				fetchWithDetailsFailed: string
			}
			fee: {
				/**
				 * F​e​e​ ​n​o​t​ ​f​o​u​n​d
				 */
				notFound: string
				/**
				 * A​ ​f​e​e​ ​w​i​t​h​ ​t​h​i​s​ ​c​o​d​e​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s
				 */
				alreadyExists: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​f​e​e
				 */
				createFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​f​e​e
				 */
				updateFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​f​e​e
				 */
				deleteFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​a​s​s​i​g​n​ ​f​e​e
				 */
				assignFailed: string
			}
			installment: {
				/**
				 * I​n​s​t​a​l​l​m​e​n​t​ ​n​o​t​ ​f​o​u​n​d
				 */
				notFound: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​i​n​s​t​a​l​l​m​e​n​t
				 */
				createFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​w​a​i​v​e​ ​i​n​s​t​a​l​l​m​e​n​t
				 */
				waiveFailed: string
				/**
				 * I​n​s​t​a​l​l​m​e​n​t​ ​i​s​ ​a​l​r​e​a​d​y​ ​p​a​i​d
				 */
				alreadyPaid: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​i​n​s​t​a​l​l​m​e​n​t​s
				 */
				fetchFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​i​n​s​t​a​l​l​m​e​n​t​ ​b​y​ ​I​D
				 */
				fetchByIdFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​i​n​s​t​a​l​l​m​e​n​t​s​ ​b​y​ ​p​a​y​m​e​n​t​ ​p​l​a​n
				 */
				fetchByPaymentPlanFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​b​u​l​k​ ​c​r​e​a​t​e​ ​i​n​s​t​a​l​l​m​e​n​t​s
				 */
				bulkCreateFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​o​v​e​r​d​u​e​ ​i​n​s​t​a​l​l​m​e​n​t​s
				 */
				fetchOverdueFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​o​v​e​r​d​u​e​ ​i​n​s​t​a​l​l​m​e​n​t​s
				 */
				updateOverdueFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​o​v​e​r​d​u​e​ ​i​n​s​t​a​l​l​m​e​n​t​s​ ​w​i​t​h​ ​s​t​u​d​e​n​t​s
				 */
				fetchOverdueWithStudentsFailed: string
			}
			paymentPlan: {
				/**
				 * P​a​y​m​e​n​t​ ​p​l​a​n​ ​n​o​t​ ​f​o​u​n​d
				 */
				notFound: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​p​a​y​m​e​n​t​ ​p​l​a​n
				 */
				createFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​p​a​y​m​e​n​t​ ​p​l​a​n
				 */
				updateFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​c​a​n​c​e​l​ ​p​a​y​m​e​n​t​ ​p​l​a​n
				 */
				cancelFailed: string
				/**
				 * A​ ​p​a​y​m​e​n​t​ ​p​l​a​n​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s​ ​f​o​r​ ​t​h​i​s​ ​s​t​u​d​e​n​t
				 */
				alreadyExists: string
			}
		}
		attendance: {
			/**
			 * A​t​t​e​n​d​a​n​c​e​ ​r​e​c​o​r​d​ ​n​o​t​ ​f​o​u​n​d
			 */
			notFound: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​a​t​t​e​n​d​a​n​c​e
			 */
			createFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​a​t​t​e​n​d​a​n​c​e
			 */
			updateFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​a​t​t​e​n​d​a​n​c​e
			 */
			deleteFailed: string
			/**
			 * A​n​ ​a​t​t​e​n​d​a​n​c​e​ ​r​e​c​o​r​d​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s​ ​f​o​r​ ​t​h​i​s​ ​d​a​t​e
			 */
			alreadyExists: string
			/**
			 * I​n​v​a​l​i​d​ ​a​t​t​e​n​d​a​n​c​e​ ​s​t​a​t​u​s
			 */
			invalidStatus: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​b​u​l​k​ ​c​r​e​a​t​e​ ​a​t​t​e​n​d​a​n​c​e​ ​r​e​c​o​r​d​s
			 */
			bulkCreateFailed: string
		}
		attendanceAlerts: {
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​a​c​t​i​v​e​ ​a​l​e​r​t​s
			 */
			fetchActiveFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​a​l​e​r​t​s
			 */
			fetchFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​a​l​e​r​t
			 */
			createFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​h​e​c​k​ ​e​x​i​s​t​i​n​g​ ​a​l​e​r​t
			 */
			checkExistingFailed: string
			/**
			 * A​l​e​r​t​ ​n​o​t​ ​f​o​u​n​d
			 */
			notFound: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​a​c​k​n​o​w​l​e​d​g​e​ ​a​l​e​r​t
			 */
			acknowledgeFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​r​e​s​o​l​v​e​ ​a​l​e​r​t
			 */
			resolveFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​d​i​s​m​i​s​s​ ​a​l​e​r​t
			 */
			dismissFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​a​l​e​r​t
			 */
			deleteFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​a​l​e​r​t​ ​c​o​u​n​t​s
			 */
			fetchCountsFailed: string
		}
		grades: {
			/**
			 * G​r​a​d​e​ ​n​o​t​ ​f​o​u​n​d
			 */
			notFound: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​g​r​a​d​e
			 */
			createFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​g​r​a​d​e
			 */
			updateFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​g​r​a​d​e
			 */
			deleteFailed: string
			/**
			 * I​n​v​a​l​i​d​ ​g​r​a​d​e​ ​v​a​l​u​e
			 */
			invalidValue: string
			/**
			 * G​r​a​d​e​ ​i​s​ ​o​u​t​ ​o​f​ ​a​l​l​o​w​e​d​ ​r​a​n​g​e
			 */
			outOfRange: string
			/**
			 * C​o​e​f​f​i​c​i​e​n​t​ ​n​o​t​ ​f​o​u​n​d​ ​f​o​r​ ​t​h​i​s​ ​s​u​b​j​e​c​t
			 */
			coefficientNotFound: string
		}
		timetables: {
			/**
			 * T​i​m​e​t​a​b​l​e​ ​n​o​t​ ​f​o​u​n​d
			 */
			notFound: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​t​i​m​e​t​a​b​l​e
			 */
			createFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​t​i​m​e​t​a​b​l​e
			 */
			updateFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​t​i​m​e​t​a​b​l​e
			 */
			deleteFailed: string
			/**
			 * S​c​h​e​d​u​l​e​ ​c​o​n​f​l​i​c​t​ ​d​e​t​e​c​t​e​d
			 */
			conflict: string
			/**
			 * T​e​a​c​h​e​r​ ​a​l​r​e​a​d​y​ ​h​a​s​ ​a​ ​c​l​a​s​s​ ​a​t​ ​t​h​i​s​ ​t​i​m​e
			 */
			teacherConflict: string
			/**
			 * C​l​a​s​s​r​o​o​m​ ​i​s​ ​a​l​r​e​a​d​y​ ​o​c​c​u​p​i​e​d​ ​a​t​ ​t​h​i​s​ ​t​i​m​e
			 */
			classroomConflict: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​t​i​m​e​t​a​b​l​e​ ​b​y​ ​c​l​a​s​s
			 */
			fetchByClassFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​t​i​m​e​t​a​b​l​e​ ​b​y​ ​t​e​a​c​h​e​r
			 */
			fetchByTeacherFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​t​i​m​e​t​a​b​l​e​ ​b​y​ ​c​l​a​s​s​r​o​o​m
			 */
			fetchByClassroomFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​t​i​m​e​t​a​b​l​e​ ​s​e​s​s​i​o​n​ ​b​y​ ​I​D
			 */
			fetchByIdFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​b​u​l​k​ ​c​r​e​a​t​e​ ​t​i​m​e​t​a​b​l​e
			 */
			bulkCreateFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​c​l​a​s​s​ ​t​i​m​e​t​a​b​l​e
			 */
			deleteClassTimetableFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​d​e​t​e​c​t​ ​c​o​n​f​l​i​c​t​s
			 */
			detectConflictsFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​a​l​l​ ​c​o​n​f​l​i​c​t​s
			 */
			fetchAllConflictsFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​t​e​a​c​h​e​r​ ​w​e​e​k​l​y​ ​h​o​u​r​s
			 */
			fetchTeacherWeeklyHoursFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​t​e​a​c​h​e​r​ ​a​v​a​i​l​a​b​i​l​i​t​y
			 */
			fetchTeacherAvailabilityFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​c​l​a​s​s​r​o​o​m​ ​a​v​a​i​l​a​b​i​l​i​t​y
			 */
			fetchClassroomAvailabilityFailed: string
		}
		school: {
			/**
			 * S​c​h​o​o​l​ ​n​o​t​ ​f​o​u​n​d
			 */
			notFound: string
			/**
			 * A​ ​s​c​h​o​o​l​ ​w​i​t​h​ ​t​h​i​s​ ​n​a​m​e​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s
			 */
			alreadyExists: string
			/**
			 * I​n​v​a​l​i​d​ ​s​c​h​o​o​l​ ​d​a​t​a
			 */
			invalidData: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​s​c​h​o​o​l
			 */
			createFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​s​c​h​o​o​l
			 */
			updateFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​s​c​h​o​o​l
			 */
			deleteFailed: string
		}
		schoolYear: {
			/**
			 * S​c​h​o​o​l​ ​y​e​a​r​ ​n​o​t​ ​f​o​u​n​d
			 */
			notFound: string
			/**
			 * A​ ​s​c​h​o​o​l​ ​y​e​a​r​ ​w​i​t​h​ ​t​h​i​s​ ​n​a​m​e​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s
			 */
			alreadyExists: string
			/**
			 * I​n​v​a​l​i​d​ ​s​c​h​o​o​l​ ​y​e​a​r​ ​d​a​t​a
			 */
			invalidData: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​s​c​h​o​o​l​ ​y​e​a​r
			 */
			createFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​s​c​h​o​o​l​ ​y​e​a​r
			 */
			updateFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​s​c​h​o​o​l​ ​y​e​a​r
			 */
			deleteFailed: string
			/**
			 * S​c​h​o​o​l​ ​y​e​a​r​ ​h​a​s​ ​e​n​r​o​l​l​m​e​n​t​s​ ​a​n​d​ ​c​a​n​n​o​t​ ​b​e​ ​d​e​l​e​t​e​d
			 */
			hasEnrollments: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​s​c​h​o​o​l​ ​y​e​a​r​s
			 */
			fetchFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​s​c​h​o​o​l​ ​y​e​a​r​ ​b​y​ ​I​D
			 */
			fetchByIdFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​a​c​t​i​v​e​ ​s​c​h​o​o​l​ ​y​e​a​r
			 */
			fetchActiveFailed: string
			/**
			 * N​o​ ​s​c​h​o​o​l​ ​c​o​n​t​e​x​t​ ​p​r​o​v​i​d​e​d
			 */
			noSchoolContext: string
		}
		users: {
			/**
			 * U​s​e​r​ ​n​o​t​ ​f​o​u​n​d
			 */
			notFound: string
			/**
			 * A​ ​u​s​e​r​ ​w​i​t​h​ ​t​h​i​s​ ​e​m​a​i​l​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s
			 */
			alreadyExists: string
			/**
			 * I​n​v​a​l​i​d​ ​u​s​e​r​ ​d​a​t​a
			 */
			invalidData: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​u​s​e​r
			 */
			createFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​u​s​e​r
			 */
			updateFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​u​s​e​r
			 */
			deleteFailed: string
			/**
			 * T​h​i​s​ ​e​m​a​i​l​ ​i​s​ ​a​l​r​e​a​d​y​ ​i​n​ ​u​s​e
			 */
			emailExists: string
		}
		roles: {
			/**
			 * R​o​l​e​ ​n​o​t​ ​f​o​u​n​d
			 */
			notFound: string
			/**
			 * A​ ​r​o​l​e​ ​w​i​t​h​ ​t​h​i​s​ ​n​a​m​e​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s
			 */
			alreadyExists: string
			/**
			 * I​n​v​a​l​i​d​ ​r​o​l​e​ ​d​a​t​a
			 */
			invalidData: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​r​o​l​e
			 */
			createFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​r​o​l​e
			 */
			updateFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​r​o​l​e
			 */
			deleteFailed: string
			/**
			 * S​y​s​t​e​m​ ​r​o​l​e​s​ ​c​a​n​n​o​t​ ​b​e​ ​m​o​d​i​f​i​e​d​ ​o​r​ ​d​e​l​e​t​e​d
			 */
			systemRole: string
		}
		permissions: {
			/**
			 * P​e​r​m​i​s​s​i​o​n​ ​d​e​n​i​e​d
			 */
			denied: string
			/**
			 * I​n​s​u​f​f​i​c​i​e​n​t​ ​p​e​r​m​i​s​s​i​o​n​s​ ​f​o​r​ ​t​h​i​s​ ​a​c​t​i​o​n
			 */
			insufficient: string
			/**
			 * I​n​v​a​l​i​d​ ​p​e​r​m​i​s​s​i​o​n​ ​s​c​o​p​e
			 */
			invalidScope: string
		}
		auth: {
			/**
			 * I​n​v​a​l​i​d​ ​c​r​e​d​e​n​t​i​a​l​s
			 */
			invalidCredentials: string
			/**
			 * S​e​s​s​i​o​n​ ​e​x​p​i​r​e​d
			 */
			sessionExpired: string
			/**
			 * I​n​v​a​l​i​d​ ​t​o​k​e​n
			 */
			tokenInvalid: string
			/**
			 * U​n​a​u​t​h​o​r​i​z​e​d
			 */
			unauthorized: string
			/**
			 * A​c​c​e​s​s​ ​f​o​r​b​i​d​d​e​n
			 */
			forbidden: string
			/**
			 * N​o​ ​s​c​h​o​o​l​ ​c​o​n​t​e​x​t
			 */
			noSchoolContext: string
			/**
			 * I​n​v​a​l​i​d​ ​s​c​h​o​o​l​ ​c​o​n​t​e​x​t
			 */
			invalidSchoolContext: string
		}
		validation: {
			/**
			 * T​h​i​s​ ​f​i​e​l​d​ ​i​s​ ​r​e​q​u​i​r​e​d
			 */
			required: string
			/**
			 * I​n​v​a​l​i​d​ ​f​o​r​m​a​t
			 */
			invalidFormat: string
			/**
			 * I​n​v​a​l​i​d​ ​d​a​t​a​ ​t​y​p​e
			 */
			invalidType: string
			/**
			 * T​o​o​ ​s​h​o​r​t​ ​(​m​i​n​i​m​u​m​ ​{​m​i​n​}​ ​c​h​a​r​a​c​t​e​r​s​)
			 * @param {unknown} min
			 */
			tooShort: RequiredParams<'min'>
			/**
			 * T​o​o​ ​l​o​n​g​ ​(​m​a​x​i​m​u​m​ ​{​m​a​x​}​ ​c​h​a​r​a​c​t​e​r​s​)
			 * @param {unknown} max
			 */
			tooLong: RequiredParams<'max'>
			/**
			 * I​n​v​a​l​i​d​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s
			 */
			invalidEmail: string
			/**
			 * I​n​v​a​l​i​d​ ​p​h​o​n​e​ ​n​u​m​b​e​r
			 */
			invalidPhone: string
			/**
			 * I​n​v​a​l​i​d​ ​d​a​t​e
			 */
			invalidDate: string
			/**
			 * D​a​t​e​ ​m​u​s​t​ ​b​e​ ​i​n​ ​t​h​e​ ​f​u​t​u​r​e
			 */
			futureDate: string
			/**
			 * D​a​t​e​ ​m​u​s​t​ ​b​e​ ​i​n​ ​t​h​e​ ​p​a​s​t
			 */
			pastDate: string
			/**
			 * I​n​v​a​l​i​d​ ​n​u​m​b​e​r
			 */
			invalidNumber: string
			/**
			 * N​u​m​b​e​r​ ​c​a​n​n​o​t​ ​b​e​ ​n​e​g​a​t​i​v​e
			 */
			negativeNumber: string
			/**
			 * V​a​l​u​e​ ​c​a​n​n​o​t​ ​b​e​ ​z​e​r​o
			 */
			zeroNotAllowed: string
		}
		file: {
			/**
			 * F​i​l​e​ ​n​o​t​ ​f​o​u​n​d
			 */
			notFound: string
			/**
			 * F​i​l​e​ ​t​o​o​ ​l​a​r​g​e
			 */
			tooLarge: string
			/**
			 * I​n​v​a​l​i​d​ ​f​i​l​e​ ​t​y​p​e
			 */
			invalidType: string
			/**
			 * U​p​l​o​a​d​ ​f​a​i​l​e​d
			 */
			uploadFailed: string
			/**
			 * D​o​w​n​l​o​a​d​ ​f​a​i​l​e​d
			 */
			downloadFailed: string
			/**
			 * F​i​l​e​ ​p​a​r​s​i​n​g​ ​f​a​i​l​e​d
			 */
			parseFailed: string
		}
		'import': {
			/**
			 * I​m​p​o​r​t​ ​f​a​i​l​e​d
			 */
			failed: string
			/**
			 * I​n​v​a​l​i​d​ ​f​i​l​e​ ​f​o​r​m​a​t
			 */
			invalidFormat: string
			/**
			 * R​e​q​u​i​r​e​d​ ​c​o​l​u​m​n​s​ ​m​i​s​s​i​n​g
			 */
			missingColumns: string
			/**
			 * N​o​ ​v​a​l​i​d​ ​r​o​w​s​ ​f​o​u​n​d
			 */
			noValidRows: string
			/**
			 * I​m​p​o​r​t​ ​p​a​r​t​i​a​l​l​y​ ​s​u​c​c​e​s​s​f​u​l
			 */
			partialSuccess: string
		}
		'export': {
			/**
			 * E​x​p​o​r​t​ ​f​a​i​l​e​d
			 */
			failed: string
			/**
			 * N​o​ ​d​a​t​a​ ​t​o​ ​e​x​p​o​r​t
			 */
			noData: string
			/**
			 * F​i​l​e​ ​g​e​n​e​r​a​t​i​o​n​ ​f​a​i​l​e​d
			 */
			formatFailed: string
		}
		bulk: {
			/**
			 * B​u​l​k​ ​o​p​e​r​a​t​i​o​n​ ​f​a​i​l​e​d
			 */
			failed: string
			/**
			 * O​p​e​r​a​t​i​o​n​ ​p​a​r​t​i​a​l​l​y​ ​s​u​c​c​e​s​s​f​u​l
			 */
			partialSuccess: string
			/**
			 * N​o​ ​i​t​e​m​s​ ​s​e​l​e​c​t​e​d
			 */
			noItems: string
		}
		teacherApp: {
			session: {
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​c​l​a​s​s​ ​s​e​s​s​i​o​n
				 */
				createFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​c​o​m​p​l​e​t​e​ ​c​l​a​s​s​ ​s​e​s​s​i​o​n
				 */
				completeFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​g​e​t​ ​c​l​a​s​s​ ​s​e​s​s​i​o​n
				 */
				getFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​g​e​t​ ​s​e​s​s​i​o​n​ ​h​i​s​t​o​r​y
				 */
				historyFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​g​e​t​ ​a​c​t​i​v​e​ ​s​e​s​s​i​o​n
				 */
				activeFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​g​e​t​ ​d​a​y​ ​s​c​h​e​d​u​l​e
				 */
				dayScheduleFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​g​e​t​ ​w​e​e​k​l​y​ ​s​c​h​e​d​u​l​e
				 */
				weeklyScheduleFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​g​e​t​ ​c​u​r​r​e​n​t​ ​t​e​r​m
				 */
				termFailed: string
			}
			students: {
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​g​e​t​ ​c​l​a​s​s​ ​s​t​u​d​e​n​t​s
				 */
				getFailed: string
			}
			participation: {
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​u​p​s​e​r​t​ ​p​a​r​t​i​c​i​p​a​t​i​o​n​ ​g​r​a​d​e​s
				 */
				upsertFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​g​e​t​ ​p​a​r​t​i​c​i​p​a​t​i​o​n​ ​g​r​a​d​e​s
				 */
				getFailed: string
			}
			classes: {
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​g​e​t​ ​a​s​s​i​g​n​e​d​ ​c​l​a​s​s​e​s
				 */
				listFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​g​e​t​ ​s​c​h​o​o​l​s
				 */
				schoolsFailed: string
			}
			homework: {
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​h​o​m​e​w​o​r​k
				 */
				createFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​g​e​t​ ​h​o​m​e​w​o​r​k​ ​l​i​s​t
				 */
				listFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​g​e​t​ ​h​o​m​e​w​o​r​k​ ​d​e​t​a​i​l​s
				 */
				getFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​h​o​m​e​w​o​r​k
				 */
				updateFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​h​o​m​e​w​o​r​k
				 */
				deleteFailed: string
			}
			messaging: {
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​g​e​t​ ​m​e​s​s​a​g​e​s
				 */
				listFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​g​e​t​ ​m​e​s​s​a​g​e​ ​d​e​t​a​i​l​s
				 */
				detailsFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​s​e​n​d​ ​m​e​s​s​a​g​e
				 */
				sendFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​m​a​r​k​ ​m​e​s​s​a​g​e​ ​a​s​ ​r​e​a​d
				 */
				markReadFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​g​e​t​ ​m​e​s​s​a​g​e​ ​t​e​m​p​l​a​t​e​s
				 */
				templatesFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​g​e​t​ ​u​n​r​e​a​d​ ​m​e​s​s​a​g​e​s​ ​c​o​u​n​t
				 */
				unreadCountFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​g​e​t​ ​r​e​c​e​n​t​ ​m​e​s​s​a​g​e​s
				 */
				recentFailed: string
			}
			parents: {
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​s​e​a​r​c​h​ ​p​a​r​e​n​t​s
				 */
				searchFailed: string
			}
			grades: {
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​s​u​b​m​i​t​ ​g​r​a​d​e​s
				 */
				submitFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​g​e​t​ ​p​e​n​d​i​n​g​ ​g​r​a​d​e​s​ ​c​o​u​n​t
				 */
				pendingCountFailed: string
			}
			notifications: {
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​g​e​t​ ​n​o​t​i​f​i​c​a​t​i​o​n​s
				 */
				listFailed: string
			}
		}
		catalogs: {
			educationLevels: {
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​e​d​u​c​a​t​i​o​n​ ​l​e​v​e​l​s
				 */
				fetchFailed: string
			}
			tracks: {
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​t​r​a​c​k​s
				 */
				fetchFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​t​r​a​c​k​ ​b​y​ ​I​D
				 */
				fetchByIdFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​t​r​a​c​k
				 */
				createFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​t​r​a​c​k
				 */
				updateFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​t​r​a​c​k
				 */
				deleteFailed: string
			}
			grades: {
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​g​r​a​d​e​s
				 */
				fetchFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​g​r​a​d​e​ ​b​y​ ​I​D
				 */
				fetchByIdFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​g​r​a​d​e
				 */
				createFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​g​r​a​d​e
				 */
				updateFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​g​r​a​d​e
				 */
				deleteFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​b​u​l​k​ ​u​p​d​a​t​e​ ​g​r​a​d​e​s​ ​o​r​d​e​r
				 */
				bulkUpdateOrderFailed: string
			}
			series: {
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​s​e​r​i​e​s
				 */
				fetchFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​s​e​r​i​e​ ​b​y​ ​I​D
				 */
				fetchByIdFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​s​e​r​i​e
				 */
				createFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​s​e​r​i​e
				 */
				updateFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​s​e​r​i​e
				 */
				deleteFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​b​u​l​k​ ​c​r​e​a​t​e​ ​s​e​r​i​e​s
				 */
				bulkCreateFailed: string
			}
			subjects: {
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​s​u​b​j​e​c​t​s
				 */
				fetchFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​s​u​b​j​e​c​t​ ​b​y​ ​I​D
				 */
				fetchByIdFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​s​u​b​j​e​c​t
				 */
				createFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​s​u​b​j​e​c​t
				 */
				updateFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​s​u​b​j​e​c​t
				 */
				deleteFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​b​u​l​k​ ​c​r​e​a​t​e​ ​s​u​b​j​e​c​t​s
				 */
				bulkCreateFailed: string
			}
			schoolSubjects: {
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​s​c​h​o​o​l​ ​s​u​b​j​e​c​t​s
				 */
				fetchFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​a​v​a​i​l​a​b​l​e​ ​c​o​r​e​ ​s​u​b​j​e​c​t​s
				 */
				fetchAvailableCoreFailed: string
				/**
				 * N​o​ ​a​c​t​i​v​e​ ​s​c​h​o​o​l​ ​y​e​a​r​ ​f​o​u​n​d
				 */
				noActiveSchoolYear: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​a​d​d​ ​s​u​b​j​e​c​t​s​ ​t​o​ ​s​c​h​o​o​l
				 */
				addFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​t​o​g​g​l​e​ ​s​u​b​j​e​c​t​ ​s​t​a​t​u​s
				 */
				toggleStatusFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​s​c​h​o​o​l​ ​s​u​b​j​e​c​t
				 */
				deleteFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​s​u​b​j​e​c​t​ ​u​s​a​g​e​ ​s​t​a​t​s
				 */
				fetchUsageStatsFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​s​c​h​o​o​l​ ​s​u​b​j​e​c​t​ ​b​y​ ​I​D
				 */
				fetchByIdFailed: string
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​c​h​e​c​k​ ​s​u​b​j​e​c​t​ ​i​n​ ​u​s​e
				 */
				checkInUseFailed: string
			}
			stats: {
				/**
				 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​c​a​t​a​l​o​g​ ​s​t​a​t​s
				 */
				fetchFailed: string
			}
		}
		curriculum: {
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​c​l​a​s​s​ ​s​e​s​s​i​o​n​s
			 */
			fetchSessionsFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​c​l​a​s​s​ ​s​e​s​s​i​o​n​ ​b​y​ ​I​D
			 */
			fetchSessionByIdFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​c​l​a​s​s​ ​s​e​s​s​i​o​n
			 */
			createSessionFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​c​l​a​s​s​ ​s​e​s​s​i​o​n
			 */
			updateSessionFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​d​e​l​e​t​e​ ​c​l​a​s​s​ ​s​e​s​s​i​o​n
			 */
			deleteSessionFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​m​a​r​k​ ​s​e​s​s​i​o​n​ ​c​o​m​p​l​e​t​e​d
			 */
			markSessionCompletedFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​c​h​a​p​t​e​r​ ​c​o​m​p​l​e​t​i​o​n​s
			 */
			fetchChapterCompletionsFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​m​a​r​k​ ​c​h​a​p​t​e​r​ ​c​o​m​p​l​e​t​e
			 */
			markChapterCompleteFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​n​m​a​r​k​ ​c​h​a​p​t​e​r​ ​c​o​m​p​l​e​t​e
			 */
			unmarkChapterCompleteFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​h​e​c​k​ ​i​f​ ​c​h​a​p​t​e​r​ ​i​s​ ​c​o​m​p​l​e​t​e​d
			 */
			checkChapterCompletedFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​c​u​r​r​i​c​u​l​u​m​ ​p​r​o​g​r​e​s​s
			 */
			fetchProgressFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​p​r​o​g​r​e​s​s​ ​o​v​e​r​v​i​e​w
			 */
			fetchOverviewFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​c​l​a​s​s​e​s​ ​b​e​h​i​n​d​ ​s​c​h​e​d​u​l​e
			 */
			fetchBehindScheduleFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​c​u​r​r​i​c​u​l​u​m​ ​p​r​o​g​r​e​s​s
			 */
			updateProgressFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​c​u​r​r​i​c​u​l​u​m​ ​p​r​o​g​r​e​s​s
			 */
			createProgressFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​s​e​r​t​ ​c​u​r​r​i​c​u​l​u​m​ ​p​r​o​g​r​e​s​s
			 */
			upsertProgressFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​a​l​c​u​l​a​t​e​ ​p​r​o​g​r​e​s​s
			 */
			calculateProgressFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​p​r​o​g​r​e​s​s​ ​s​t​a​t​s​ ​b​y​ ​s​t​a​t​u​s
			 */
			fetchStatsByStatusFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​p​r​o​g​r​e​s​s​ ​b​y​ ​s​u​b​j​e​c​t
			 */
			fetchProgressBySubjectFailed: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​f​e​t​c​h​ ​t​e​a​c​h​e​r​ ​p​r​o​g​r​e​s​s​ ​s​u​m​m​a​r​y
			 */
			fetchTeacherSummaryFailed: string
		}
	}
}

export type TranslationFunctions = {
	errors: {
		/**
		 * An error occurred
		 */
		generic: () => LocalizedString
		/**
		 * Resource not found
		 */
		notFound: () => LocalizedString
		/**
		 * Unauthorized
		 */
		unauthorized: () => LocalizedString
		/**
		 * Access forbidden
		 */
		forbidden: () => LocalizedString
		/**
		 * Server error
		 */
		serverError: () => LocalizedString
		/**
		 * Network error
		 */
		networkError: () => LocalizedString
		/**
		 * Validation error
		 */
		validationError: () => LocalizedString
		/**
		 * Data conflict
		 */
		conflict: () => LocalizedString
		/**
		 * Internal error
		 */
		internalError: () => LocalizedString
		database: {
			/**
			 * Database connection failed
			 */
			connectionFailed: () => LocalizedString
			/**
			 * Query execution failed
			 */
			queryFailed: () => LocalizedString
			/**
			 * Transaction failed
			 */
			transactionFailed: () => LocalizedString
			/**
			 * Data constraint violation
			 */
			constraintViolation: () => LocalizedString
			/**
			 * A resource with this information already exists
			 */
			uniqueConstraint: () => LocalizedString
			/**
			 * Invalid reference to linked resource
			 */
			foreignKeyConstraint: () => LocalizedString
			/**
			 * Required field missing
			 */
			notNullConstraint: () => LocalizedString
		}
		students: {
			/**
			 * Student not found
			 */
			notFound: () => LocalizedString
			/**
			 * Student with ID {id} not found
			 */
			notFoundWithId: (arg: { id: unknown }) => LocalizedString
			/**
			 * A student with this information already exists
			 */
			alreadyExists: () => LocalizedString
			/**
			 * This matricule is already in use
			 */
			matriculeExists: () => LocalizedString
			/**
			 * Matricule {matricule} already exists
			 */
			matriculeExistsWithId: (arg: { matricule: unknown }) => LocalizedString
			/**
			 * Invalid student data
			 */
			invalidData: () => LocalizedString
			/**
			 * Failed to create student
			 */
			createFailed: () => LocalizedString
			/**
			 * Failed to update student
			 */
			updateFailed: () => LocalizedString
			/**
			 * Failed to delete student
			 */
			deleteFailed: () => LocalizedString
			/**
			 * Failed to import students
			 */
			importFailed: () => LocalizedString
			/**
			 * Failed to export students
			 */
			exportFailed: () => LocalizedString
			/**
			 * Failed to fetch students
			 */
			fetchFailed: () => LocalizedString
			/**
			 * Failed to fetch student by ID
			 */
			fetchByIdFailed: () => LocalizedString
			/**
			 * Failed to generate matricule
			 */
			generateMatriculeFailed: () => LocalizedString
			/**
			 * No active school year found. Please select a school year.
			 */
			noActiveSchoolYear: () => LocalizedString
			/**
			 * Student age must be between 3 and 30 years
			 */
			invalidAgeRange: () => LocalizedString
			/**
			 * Failed to update student status
			 */
			updateStatusFailed: () => LocalizedString
			/**
			 * Failed to bulk import students
			 */
			bulkImportFailed: () => LocalizedString
			/**
			 * Failed to fetch student statistics
			 */
			fetchStatsFailed: () => LocalizedString
		}
		parents: {
			/**
			 * Parent not found
			 */
			notFound: () => LocalizedString
			/**
			 * A parent with this phone number already exists
			 */
			alreadyExists: () => LocalizedString
			/**
			 * A parent with this phone number already exists ({phone})
			 */
			alreadyExistsWithPhone: (arg: { phone: unknown }) => LocalizedString
			/**
			 * Invalid parent data
			 */
			invalidData: () => LocalizedString
			/**
			 * Failed to create parent
			 */
			createFailed: () => LocalizedString
			/**
			 * Failed to update parent
			 */
			updateFailed: () => LocalizedString
			/**
			 * Failed to delete parent
			 */
			deleteFailed: () => LocalizedString
			/**
			 * Failed to link parent to student
			 */
			linkFailed: () => LocalizedString
			/**
			 * Failed to unlink parent
			 */
			unlinkFailed: () => LocalizedString
			/**
			 * Failed to send invitation
			 */
			invitationFailed: () => LocalizedString
			/**
			 * Failed to send invitation: {error}
			 */
			invitationFailedWithError: (arg: { error: unknown }) => LocalizedString
			/**
			 * Invalid or expired invitation token
			 */
			invalidToken: () => LocalizedString
			/**
			 * Parent has no email address
			 */
			noEmail: () => LocalizedString
			/**
			 * No children linked to parent
			 */
			noChildren: () => LocalizedString
			/**
			 * Failed to fetch parents
			 */
			fetchFailed: () => LocalizedString
			/**
			 * Failed to fetch parent by ID
			 */
			fetchByIdFailed: () => LocalizedString
			/**
			 * Failed to fetch student parents
			 */
			fetchStudentParentsFailed: () => LocalizedString
			/**
			 * Failed to find parent by phone
			 */
			findByPhoneFailed: () => LocalizedString
			/**
			 * Failed to auto-match parents
			 */
			autoMatchFailed: () => LocalizedString
			/**
			 * Failed to update parent link
			 */
			updateLinkFailed: () => LocalizedString
			/**
			 * Failed to send parent invitation
			 */
			sendInvitationFailed: () => LocalizedString
			/**
			 * Failed to accept invitation
			 */
			acceptInvitationFailed: () => LocalizedString
			/**
			 * Failed to bulk import parents
			 */
			bulkImportFailed: () => LocalizedString
		}
		programs: {
			/**
			 * Failed to fetch school year templates
			 */
			fetchSchoolYearTemplatesFailed: () => LocalizedString
			/**
			 * Failed to fetch school year template
			 */
			fetchSchoolYearTemplateFailed: () => LocalizedString
			/**
			 * Failed to create school year template
			 */
			createSchoolYearTemplateFailed: () => LocalizedString
			/**
			 * Failed to update school year template
			 */
			updateSchoolYearTemplateFailed: () => LocalizedString
			/**
			 * Failed to delete school year template
			 */
			deleteSchoolYearTemplateFailed: () => LocalizedString
			/**
			 * Failed to fetch program templates
			 */
			fetchProgramTemplatesFailed: () => LocalizedString
			/**
			 * Failed to fetch program template
			 */
			fetchProgramTemplateFailed: () => LocalizedString
			/**
			 * Failed to create program template
			 */
			createProgramTemplateFailed: () => LocalizedString
			/**
			 * Failed to update program template
			 */
			updateProgramTemplateFailed: () => LocalizedString
			/**
			 * Failed to delete program template
			 */
			deleteProgramTemplateFailed: () => LocalizedString
			/**
			 * Failed to clone program template
			 */
			cloneProgramTemplateFailed: () => LocalizedString
			/**
			 * Failed to fetch program template chapters
			 */
			fetchProgramTemplateChaptersFailed: () => LocalizedString
			/**
			 * Failed to fetch program template chapter
			 */
			fetchProgramTemplateChapterFailed: () => LocalizedString
			/**
			 * Failed to create program template chapter
			 */
			createProgramTemplateChapterFailed: () => LocalizedString
			/**
			 * Failed to update program template chapter
			 */
			updateProgramTemplateChapterFailed: () => LocalizedString
			/**
			 * Failed to delete program template chapter
			 */
			deleteProgramTemplateChapterFailed: () => LocalizedString
			/**
			 * Failed to bulk update chapters order
			 */
			bulkUpdateChaptersOrderFailed: () => LocalizedString
			/**
			 * Failed to bulk create chapters
			 */
			bulkCreateChaptersFailed: () => LocalizedString
			/**
			 * Failed to publish program
			 */
			publishProgramFailed: () => LocalizedString
			/**
			 * Failed to fetch program versions
			 */
			fetchProgramVersionsFailed: () => LocalizedString
			/**
			 * Failed to restore program version
			 */
			restoreProgramVersionFailed: () => LocalizedString
			/**
			 * Failed to fetch program stats
			 */
			fetchProgramStatsFailed: () => LocalizedString
			/**
			 * Failed to fetch term templates
			 */
			fetchTermTemplatesFailed: () => LocalizedString
			/**
			 * Failed to fetch term template
			 */
			fetchTermTemplateFailed: () => LocalizedString
			/**
			 * Failed to create term template
			 */
			createTermTemplateFailed: () => LocalizedString
			/**
			 * Failed to update term template
			 */
			updateTermTemplateFailed: () => LocalizedString
			/**
			 * Failed to delete term template
			 */
			deleteTermTemplateFailed: () => LocalizedString
			/**
			 * Failed to bulk create term templates
			 */
			bulkCreateTermTemplatesFailed: () => LocalizedString
			/**
			 * Failed to fetch school year templates with terms
			 */
			fetchSchoolYearTemplatesWithTermsFailed: () => LocalizedString
		}
		enrollments: {
			/**
			 * Enrollment not found
			 */
			notFound: () => LocalizedString
			/**
			 * Student is already enrolled for this school year
			 */
			alreadyExists: () => LocalizedString
			/**
			 * Invalid enrollment data
			 */
			invalidData: () => LocalizedString
			/**
			 * Failed to create enrollment
			 */
			createFailed: () => LocalizedString
			/**
			 * Failed to confirm enrollment
			 */
			confirmFailed: () => LocalizedString
			/**
			 * Failed to cancel enrollment
			 */
			cancelFailed: () => LocalizedString
			/**
			 * Failed to transfer student
			 */
			transferFailed: () => LocalizedString
			/**
			 * Failed to bulk re-enroll students
			 */
			bulkReenrollFailed: () => LocalizedString
		}
		classes: {
			/**
			 * Class not found
			 */
			notFound: () => LocalizedString
			/**
			 * A class with this name already exists
			 */
			alreadyExists: () => LocalizedString
			/**
			 * Invalid class data
			 */
			invalidData: () => LocalizedString
			/**
			 * Failed to create class
			 */
			createFailed: () => LocalizedString
			/**
			 * Failed to update class
			 */
			updateFailed: () => LocalizedString
			/**
			 * Failed to delete class
			 */
			deleteFailed: () => LocalizedString
			/**
			 * Class maximum capacity reached
			 */
			capacityExceeded: () => LocalizedString
			/**
			 * Cannot create class for another school
			 */
			differentSchool: () => LocalizedString
			/**
			 * Class with this grade, series, and section already exists for this school year
			 */
			alreadyExistsVerbose: () => LocalizedString
			/**
			 * Classroom is already assigned to {assignedTo}
			 */
			classroomConflict: (arg: { assignedTo: unknown }) => LocalizedString
			/**
			 * Cannot delete class with enrolled students
			 */
			notEmpty: () => LocalizedString
			/**
			 * Class not found or permission denied
			 */
			notFoundOrPermission: () => LocalizedString
		}
		classSubjects: {
			/**
			 * Failed to fetch class subjects
			 */
			fetchFailed: () => LocalizedString
			/**
			 * Failed to fetch assignment matrix
			 */
			fetchAssignmentMatrixFailed: () => LocalizedString
			/**
			 * Teacher is not qualified to teach this subject
			 */
			teacherNotQualified: () => LocalizedString
			/**
			 * Failed to update assignment
			 */
			updateAssignmentFailed: () => LocalizedString
			/**
			 * Failed to create assignment
			 */
			createAssignmentFailed: () => LocalizedString
			/**
			 * Failed to assign teacher
			 */
			assignTeacherFailed: () => LocalizedString
			/**
			 * Teacher not qualified for subject {subjectId}
			 */
			teacherNotQualifiedWithId: (arg: { subjectId: unknown }) => LocalizedString
			/**
			 * Failed to bulk assign teachers
			 */
			bulkAssignFailed: () => LocalizedString
			/**
			 * Failed to remove teacher from class subject
			 */
			removeTeacherFailed: () => LocalizedString
			/**
			 * Failed to remove subject from class
			 */
			removeSubjectFailed: () => LocalizedString
			/**
			 * Failed to detect teacher conflicts
			 */
			detectConflictsFailed: () => LocalizedString
			/**
			 * Failed to add subject to class
			 */
			addSubjectFailed: () => LocalizedString
			/**
			 * Failed to update class subject details
			 */
			updateDetailsFailed: () => LocalizedString
			/**
			 * Failed to copy class subjects
			 */
			copyFailed: () => LocalizedString
		}
		teachers: {
			/**
			 * Teacher not found
			 */
			notFound: () => LocalizedString
			/**
			 * This user is already a teacher
			 */
			alreadyExists: () => LocalizedString
			/**
			 * Invalid teacher data
			 */
			invalidData: () => LocalizedString
			/**
			 * Failed to create teacher
			 */
			createFailed: () => LocalizedString
			/**
			 * Failed to update teacher
			 */
			updateFailed: () => LocalizedString
			/**
			 * Failed to delete teacher
			 */
			deleteFailed: () => LocalizedString
			/**
			 * Failed to assign subject
			 */
			assignFailed: () => LocalizedString
		}
		subjects: {
			/**
			 * Subject not found
			 */
			notFound: () => LocalizedString
			/**
			 * A subject with this code already exists
			 */
			alreadyExists: () => LocalizedString
			/**
			 * Invalid subject data
			 */
			invalidData: () => LocalizedString
			/**
			 * Failed to create subject
			 */
			createFailed: () => LocalizedString
			/**
			 * Failed to update subject
			 */
			updateFailed: () => LocalizedString
			/**
			 * Failed to delete subject
			 */
			deleteFailed: () => LocalizedString
			/**
			 * Subject is in use and cannot be deleted
			 */
			inUse: () => LocalizedString
		}
		finance: {
			payment: {
				/**
				 * Payment not found
				 */
				notFound: () => LocalizedString
				/**
				 * Payment with ID {id} not found
				 */
				notFoundWithId: (arg: { id: unknown }) => LocalizedString
				/**
				 * Failed to create payment
				 */
				createFailed: () => LocalizedString
				/**
				 * Failed to cancel payment
				 */
				cancelFailed: () => LocalizedString
				/**
				 * Invalid payment amount
				 */
				invalidAmount: () => LocalizedString
				/**
				 * A receipt with this number already exists
				 */
				receiptExists: () => LocalizedString
				/**
				 * Failed to allocate payment
				 */
				allocationFailed: () => LocalizedString
				/**
				 * Failed to create payment allocation
				 */
				createAllocationFailed: () => LocalizedString
				/**
				 * Failed to create payment with allocations
				 */
				createWithAllocationsFailed: () => LocalizedString
				/**
				 * Failed to cancel payment record
				 */
				cancelRecordFailed: () => LocalizedString
				/**
				 * Failed to fetch payments
				 */
				fetchFailed: () => LocalizedString
				/**
				 * Failed to fetch payment by ID
				 */
				fetchByIdFailed: () => LocalizedString
				/**
				 * Failed to fetch payment by receipt number
				 */
				fetchByReceiptNumberFailed: () => LocalizedString
				/**
				 * Failed to generate receipt number
				 */
				generateReceiptNumberFailed: () => LocalizedString
				/**
				 * Failed to create payment record
				 */
				createRecordFailed: () => LocalizedString
				/**
				 * Payment amount ({paymentAmount}) does not match total allocations ({totalAllocated})
				 */
				amountMismatch: (arg: { paymentAmount: unknown, totalAllocated: unknown }) => LocalizedString
				/**
				 * Payment is already cancelled
				 */
				alreadyCancelled: () => LocalizedString
				/**
				 * Failed to fetch cashier summary
				 */
				fetchSummaryFailed: () => LocalizedString
			}
			refund: {
				/**
				 * Refund not found
				 */
				notFound: () => LocalizedString
				/**
				 * Failed to create refund
				 */
				createFailed: () => LocalizedString
				/**
				 * Failed to approve refund
				 */
				approveFailed: () => LocalizedString
				/**
				 * Failed to reject refund
				 */
				rejectFailed: () => LocalizedString
				/**
				 * Failed to process refund
				 */
				processFailed: () => LocalizedString
				/**
				 * Failed to cancel refund
				 */
				cancelFailed: () => LocalizedString
				/**
				 * Insufficient balance for refund
				 */
				insufficientBalance: () => LocalizedString
				/**
				 * Failed to fetch refunds
				 */
				fetchFailed: () => LocalizedString
				/**
				 * Failed to fetch refund by ID
				 */
				fetchByIdFailed: () => LocalizedString
				/**
				 * Failed to generate refund number
				 */
				generateNumberFailed: () => LocalizedString
				/**
				 * Failed to fetch pending refunds count
				 */
				pendingCountFailed: () => LocalizedString
				/**
				 * Refund must be approved before processing
				 */
				mustBeApproved: () => LocalizedString
			}
			account: {
				/**
				 * Account not found
				 */
				notFound: () => LocalizedString
				/**
				 * An account with this code already exists
				 */
				alreadyExists: () => LocalizedString
				/**
				 * Failed to create account
				 */
				createFailed: () => LocalizedString
				/**
				 * Failed to update account
				 */
				updateFailed: () => LocalizedString
				/**
				 * Failed to delete account
				 */
				deleteFailed: () => LocalizedString
				/**
				 * Account has transactions and cannot be deleted
				 */
				hasTransactions: () => LocalizedString
				/**
				 * Failed to fetch accounts
				 */
				fetchFailed: () => LocalizedString
				/**
				 * Failed to fetch account by ID
				 */
				fetchByIdFailed: () => LocalizedString
				/**
				 * Failed to fetch account by code
				 */
				fetchByCodeFailed: () => LocalizedString
				/**
				 * Failed to update account balance
				 */
				updateBalanceFailed: () => LocalizedString
				/**
				 * Failed to fetch account balances
				 */
				fetchBalancesFailed: () => LocalizedString
				/**
				 * Failed to fetch total balance
				 */
				fetchTotalBalanceFailed: () => LocalizedString
			}
			transaction: {
				/**
				 * Transaction not found
				 */
				notFound: () => LocalizedString
				/**
				 * Failed to create transaction
				 */
				createFailed: () => LocalizedString
				/**
				 * Transaction is not balanced
				 */
				unbalanced: () => LocalizedString
				/**
				 * Invalid transaction lines
				 */
				invalidLines: () => LocalizedString
				/**
				 * Fiscal year is closed
				 */
				fiscalYearClosed: () => LocalizedString
			}
			fiscalYear: {
				/**
				 * Failed to fetch fiscal years
				 */
				fetchFailed: () => LocalizedString
				/**
				 * Failed to fetch fiscal year by ID
				 */
				fetchByIdFailed: () => LocalizedString
				/**
				 * Failed to fetch fiscal year by school year
				 */
				fetchBySchoolYearFailed: () => LocalizedString
				/**
				 * Failed to fetch open fiscal year
				 */
				fetchOpenFailed: () => LocalizedString
				/**
				 * Failed to fetch fiscal year for date
				 */
				fetchForDateFailed: () => LocalizedString
				/**
				 * Failed to create fiscal year
				 */
				createFailed: () => LocalizedString
				/**
				 * Failed to close fiscal year
				 */
				closeFailed: () => LocalizedString
				/**
				 * Failed to lock fiscal year
				 */
				lockFailed: () => LocalizedString
				/**
				 * Failed to reopen fiscal year
				 */
				reopenFailed: () => LocalizedString
			}
			feeStructure: {
				/**
				 * Failed to fetch fee structures
				 */
				fetchFailed: () => LocalizedString
				/**
				 * Failed to fetch fee structure by ID
				 */
				fetchByIdFailed: () => LocalizedString
				/**
				 * Failed to fetch fee structure for student
				 */
				fetchForStudentFailed: () => LocalizedString
				/**
				 * Failed to create fee structure
				 */
				createFailed: () => LocalizedString
				/**
				 * Failed to bulk create fee structures
				 */
				bulkCreateFailed: () => LocalizedString
				/**
				 * Failed to update fee structure
				 */
				updateFailed: () => LocalizedString
				/**
				 * Failed to delete fee structure
				 */
				deleteFailed: () => LocalizedString
				/**
				 * Failed to fetch fee structures with details
				 */
				fetchWithDetailsFailed: () => LocalizedString
			}
			fee: {
				/**
				 * Fee not found
				 */
				notFound: () => LocalizedString
				/**
				 * A fee with this code already exists
				 */
				alreadyExists: () => LocalizedString
				/**
				 * Failed to create fee
				 */
				createFailed: () => LocalizedString
				/**
				 * Failed to update fee
				 */
				updateFailed: () => LocalizedString
				/**
				 * Failed to delete fee
				 */
				deleteFailed: () => LocalizedString
				/**
				 * Failed to assign fee
				 */
				assignFailed: () => LocalizedString
			}
			installment: {
				/**
				 * Installment not found
				 */
				notFound: () => LocalizedString
				/**
				 * Failed to create installment
				 */
				createFailed: () => LocalizedString
				/**
				 * Failed to waive installment
				 */
				waiveFailed: () => LocalizedString
				/**
				 * Installment is already paid
				 */
				alreadyPaid: () => LocalizedString
				/**
				 * Failed to fetch installments
				 */
				fetchFailed: () => LocalizedString
				/**
				 * Failed to fetch installment by ID
				 */
				fetchByIdFailed: () => LocalizedString
				/**
				 * Failed to fetch installments by payment plan
				 */
				fetchByPaymentPlanFailed: () => LocalizedString
				/**
				 * Failed to bulk create installments
				 */
				bulkCreateFailed: () => LocalizedString
				/**
				 * Failed to fetch overdue installments
				 */
				fetchOverdueFailed: () => LocalizedString
				/**
				 * Failed to update overdue installments
				 */
				updateOverdueFailed: () => LocalizedString
				/**
				 * Failed to fetch overdue installments with students
				 */
				fetchOverdueWithStudentsFailed: () => LocalizedString
			}
			paymentPlan: {
				/**
				 * Payment plan not found
				 */
				notFound: () => LocalizedString
				/**
				 * Failed to create payment plan
				 */
				createFailed: () => LocalizedString
				/**
				 * Failed to update payment plan
				 */
				updateFailed: () => LocalizedString
				/**
				 * Failed to cancel payment plan
				 */
				cancelFailed: () => LocalizedString
				/**
				 * A payment plan already exists for this student
				 */
				alreadyExists: () => LocalizedString
			}
		}
		attendance: {
			/**
			 * Attendance record not found
			 */
			notFound: () => LocalizedString
			/**
			 * Failed to create attendance
			 */
			createFailed: () => LocalizedString
			/**
			 * Failed to update attendance
			 */
			updateFailed: () => LocalizedString
			/**
			 * Failed to delete attendance
			 */
			deleteFailed: () => LocalizedString
			/**
			 * An attendance record already exists for this date
			 */
			alreadyExists: () => LocalizedString
			/**
			 * Invalid attendance status
			 */
			invalidStatus: () => LocalizedString
			/**
			 * Failed to bulk create attendance records
			 */
			bulkCreateFailed: () => LocalizedString
		}
		attendanceAlerts: {
			/**
			 * Failed to fetch active alerts
			 */
			fetchActiveFailed: () => LocalizedString
			/**
			 * Failed to fetch alerts
			 */
			fetchFailed: () => LocalizedString
			/**
			 * Failed to create alert
			 */
			createFailed: () => LocalizedString
			/**
			 * Failed to check existing alert
			 */
			checkExistingFailed: () => LocalizedString
			/**
			 * Alert not found
			 */
			notFound: () => LocalizedString
			/**
			 * Failed to acknowledge alert
			 */
			acknowledgeFailed: () => LocalizedString
			/**
			 * Failed to resolve alert
			 */
			resolveFailed: () => LocalizedString
			/**
			 * Failed to dismiss alert
			 */
			dismissFailed: () => LocalizedString
			/**
			 * Failed to delete alert
			 */
			deleteFailed: () => LocalizedString
			/**
			 * Failed to fetch alert counts
			 */
			fetchCountsFailed: () => LocalizedString
		}
		grades: {
			/**
			 * Grade not found
			 */
			notFound: () => LocalizedString
			/**
			 * Failed to create grade
			 */
			createFailed: () => LocalizedString
			/**
			 * Failed to update grade
			 */
			updateFailed: () => LocalizedString
			/**
			 * Failed to delete grade
			 */
			deleteFailed: () => LocalizedString
			/**
			 * Invalid grade value
			 */
			invalidValue: () => LocalizedString
			/**
			 * Grade is out of allowed range
			 */
			outOfRange: () => LocalizedString
			/**
			 * Coefficient not found for this subject
			 */
			coefficientNotFound: () => LocalizedString
		}
		timetables: {
			/**
			 * Timetable not found
			 */
			notFound: () => LocalizedString
			/**
			 * Failed to create timetable
			 */
			createFailed: () => LocalizedString
			/**
			 * Failed to update timetable
			 */
			updateFailed: () => LocalizedString
			/**
			 * Failed to delete timetable
			 */
			deleteFailed: () => LocalizedString
			/**
			 * Schedule conflict detected
			 */
			conflict: () => LocalizedString
			/**
			 * Teacher already has a class at this time
			 */
			teacherConflict: () => LocalizedString
			/**
			 * Classroom is already occupied at this time
			 */
			classroomConflict: () => LocalizedString
			/**
			 * Failed to fetch timetable by class
			 */
			fetchByClassFailed: () => LocalizedString
			/**
			 * Failed to fetch timetable by teacher
			 */
			fetchByTeacherFailed: () => LocalizedString
			/**
			 * Failed to fetch timetable by classroom
			 */
			fetchByClassroomFailed: () => LocalizedString
			/**
			 * Failed to fetch timetable session by ID
			 */
			fetchByIdFailed: () => LocalizedString
			/**
			 * Failed to bulk create timetable
			 */
			bulkCreateFailed: () => LocalizedString
			/**
			 * Failed to delete class timetable
			 */
			deleteClassTimetableFailed: () => LocalizedString
			/**
			 * Failed to detect conflicts
			 */
			detectConflictsFailed: () => LocalizedString
			/**
			 * Failed to fetch all conflicts
			 */
			fetchAllConflictsFailed: () => LocalizedString
			/**
			 * Failed to fetch teacher weekly hours
			 */
			fetchTeacherWeeklyHoursFailed: () => LocalizedString
			/**
			 * Failed to fetch teacher availability
			 */
			fetchTeacherAvailabilityFailed: () => LocalizedString
			/**
			 * Failed to fetch classroom availability
			 */
			fetchClassroomAvailabilityFailed: () => LocalizedString
		}
		school: {
			/**
			 * School not found
			 */
			notFound: () => LocalizedString
			/**
			 * A school with this name already exists
			 */
			alreadyExists: () => LocalizedString
			/**
			 * Invalid school data
			 */
			invalidData: () => LocalizedString
			/**
			 * Failed to create school
			 */
			createFailed: () => LocalizedString
			/**
			 * Failed to update school
			 */
			updateFailed: () => LocalizedString
			/**
			 * Failed to delete school
			 */
			deleteFailed: () => LocalizedString
		}
		schoolYear: {
			/**
			 * School year not found
			 */
			notFound: () => LocalizedString
			/**
			 * A school year with this name already exists
			 */
			alreadyExists: () => LocalizedString
			/**
			 * Invalid school year data
			 */
			invalidData: () => LocalizedString
			/**
			 * Failed to create school year
			 */
			createFailed: () => LocalizedString
			/**
			 * Failed to update school year
			 */
			updateFailed: () => LocalizedString
			/**
			 * Failed to delete school year
			 */
			deleteFailed: () => LocalizedString
			/**
			 * School year has enrollments and cannot be deleted
			 */
			hasEnrollments: () => LocalizedString
			/**
			 * Failed to fetch school years
			 */
			fetchFailed: () => LocalizedString
			/**
			 * Failed to fetch school year by ID
			 */
			fetchByIdFailed: () => LocalizedString
			/**
			 * Failed to fetch active school year
			 */
			fetchActiveFailed: () => LocalizedString
			/**
			 * No school context provided
			 */
			noSchoolContext: () => LocalizedString
		}
		users: {
			/**
			 * User not found
			 */
			notFound: () => LocalizedString
			/**
			 * A user with this email already exists
			 */
			alreadyExists: () => LocalizedString
			/**
			 * Invalid user data
			 */
			invalidData: () => LocalizedString
			/**
			 * Failed to create user
			 */
			createFailed: () => LocalizedString
			/**
			 * Failed to update user
			 */
			updateFailed: () => LocalizedString
			/**
			 * Failed to delete user
			 */
			deleteFailed: () => LocalizedString
			/**
			 * This email is already in use
			 */
			emailExists: () => LocalizedString
		}
		roles: {
			/**
			 * Role not found
			 */
			notFound: () => LocalizedString
			/**
			 * A role with this name already exists
			 */
			alreadyExists: () => LocalizedString
			/**
			 * Invalid role data
			 */
			invalidData: () => LocalizedString
			/**
			 * Failed to create role
			 */
			createFailed: () => LocalizedString
			/**
			 * Failed to update role
			 */
			updateFailed: () => LocalizedString
			/**
			 * Failed to delete role
			 */
			deleteFailed: () => LocalizedString
			/**
			 * System roles cannot be modified or deleted
			 */
			systemRole: () => LocalizedString
		}
		permissions: {
			/**
			 * Permission denied
			 */
			denied: () => LocalizedString
			/**
			 * Insufficient permissions for this action
			 */
			insufficient: () => LocalizedString
			/**
			 * Invalid permission scope
			 */
			invalidScope: () => LocalizedString
		}
		auth: {
			/**
			 * Invalid credentials
			 */
			invalidCredentials: () => LocalizedString
			/**
			 * Session expired
			 */
			sessionExpired: () => LocalizedString
			/**
			 * Invalid token
			 */
			tokenInvalid: () => LocalizedString
			/**
			 * Unauthorized
			 */
			unauthorized: () => LocalizedString
			/**
			 * Access forbidden
			 */
			forbidden: () => LocalizedString
			/**
			 * No school context
			 */
			noSchoolContext: () => LocalizedString
			/**
			 * Invalid school context
			 */
			invalidSchoolContext: () => LocalizedString
		}
		validation: {
			/**
			 * This field is required
			 */
			required: () => LocalizedString
			/**
			 * Invalid format
			 */
			invalidFormat: () => LocalizedString
			/**
			 * Invalid data type
			 */
			invalidType: () => LocalizedString
			/**
			 * Too short (minimum {min} characters)
			 */
			tooShort: (arg: { min: unknown }) => LocalizedString
			/**
			 * Too long (maximum {max} characters)
			 */
			tooLong: (arg: { max: unknown }) => LocalizedString
			/**
			 * Invalid email address
			 */
			invalidEmail: () => LocalizedString
			/**
			 * Invalid phone number
			 */
			invalidPhone: () => LocalizedString
			/**
			 * Invalid date
			 */
			invalidDate: () => LocalizedString
			/**
			 * Date must be in the future
			 */
			futureDate: () => LocalizedString
			/**
			 * Date must be in the past
			 */
			pastDate: () => LocalizedString
			/**
			 * Invalid number
			 */
			invalidNumber: () => LocalizedString
			/**
			 * Number cannot be negative
			 */
			negativeNumber: () => LocalizedString
			/**
			 * Value cannot be zero
			 */
			zeroNotAllowed: () => LocalizedString
		}
		file: {
			/**
			 * File not found
			 */
			notFound: () => LocalizedString
			/**
			 * File too large
			 */
			tooLarge: () => LocalizedString
			/**
			 * Invalid file type
			 */
			invalidType: () => LocalizedString
			/**
			 * Upload failed
			 */
			uploadFailed: () => LocalizedString
			/**
			 * Download failed
			 */
			downloadFailed: () => LocalizedString
			/**
			 * File parsing failed
			 */
			parseFailed: () => LocalizedString
		}
		'import': {
			/**
			 * Import failed
			 */
			failed: () => LocalizedString
			/**
			 * Invalid file format
			 */
			invalidFormat: () => LocalizedString
			/**
			 * Required columns missing
			 */
			missingColumns: () => LocalizedString
			/**
			 * No valid rows found
			 */
			noValidRows: () => LocalizedString
			/**
			 * Import partially successful
			 */
			partialSuccess: () => LocalizedString
		}
		'export': {
			/**
			 * Export failed
			 */
			failed: () => LocalizedString
			/**
			 * No data to export
			 */
			noData: () => LocalizedString
			/**
			 * File generation failed
			 */
			formatFailed: () => LocalizedString
		}
		bulk: {
			/**
			 * Bulk operation failed
			 */
			failed: () => LocalizedString
			/**
			 * Operation partially successful
			 */
			partialSuccess: () => LocalizedString
			/**
			 * No items selected
			 */
			noItems: () => LocalizedString
		}
		teacherApp: {
			session: {
				/**
				 * Failed to create class session
				 */
				createFailed: () => LocalizedString
				/**
				 * Failed to complete class session
				 */
				completeFailed: () => LocalizedString
				/**
				 * Failed to get class session
				 */
				getFailed: () => LocalizedString
				/**
				 * Failed to get session history
				 */
				historyFailed: () => LocalizedString
				/**
				 * Failed to get active session
				 */
				activeFailed: () => LocalizedString
				/**
				 * Failed to get day schedule
				 */
				dayScheduleFailed: () => LocalizedString
				/**
				 * Failed to get weekly schedule
				 */
				weeklyScheduleFailed: () => LocalizedString
				/**
				 * Failed to get current term
				 */
				termFailed: () => LocalizedString
			}
			students: {
				/**
				 * Failed to get class students
				 */
				getFailed: () => LocalizedString
			}
			participation: {
				/**
				 * Failed to upsert participation grades
				 */
				upsertFailed: () => LocalizedString
				/**
				 * Failed to get participation grades
				 */
				getFailed: () => LocalizedString
			}
			classes: {
				/**
				 * Failed to get assigned classes
				 */
				listFailed: () => LocalizedString
				/**
				 * Failed to get schools
				 */
				schoolsFailed: () => LocalizedString
			}
			homework: {
				/**
				 * Failed to create homework
				 */
				createFailed: () => LocalizedString
				/**
				 * Failed to get homework list
				 */
				listFailed: () => LocalizedString
				/**
				 * Failed to get homework details
				 */
				getFailed: () => LocalizedString
				/**
				 * Failed to update homework
				 */
				updateFailed: () => LocalizedString
				/**
				 * Failed to delete homework
				 */
				deleteFailed: () => LocalizedString
			}
			messaging: {
				/**
				 * Failed to get messages
				 */
				listFailed: () => LocalizedString
				/**
				 * Failed to get message details
				 */
				detailsFailed: () => LocalizedString
				/**
				 * Failed to send message
				 */
				sendFailed: () => LocalizedString
				/**
				 * Failed to mark message as read
				 */
				markReadFailed: () => LocalizedString
				/**
				 * Failed to get message templates
				 */
				templatesFailed: () => LocalizedString
				/**
				 * Failed to get unread messages count
				 */
				unreadCountFailed: () => LocalizedString
				/**
				 * Failed to get recent messages
				 */
				recentFailed: () => LocalizedString
			}
			parents: {
				/**
				 * Failed to search parents
				 */
				searchFailed: () => LocalizedString
			}
			grades: {
				/**
				 * Failed to submit grades
				 */
				submitFailed: () => LocalizedString
				/**
				 * Failed to get pending grades count
				 */
				pendingCountFailed: () => LocalizedString
			}
			notifications: {
				/**
				 * Failed to get notifications
				 */
				listFailed: () => LocalizedString
			}
		}
		catalogs: {
			educationLevels: {
				/**
				 * Failed to fetch education levels
				 */
				fetchFailed: () => LocalizedString
			}
			tracks: {
				/**
				 * Failed to fetch tracks
				 */
				fetchFailed: () => LocalizedString
				/**
				 * Failed to fetch track by ID
				 */
				fetchByIdFailed: () => LocalizedString
				/**
				 * Failed to create track
				 */
				createFailed: () => LocalizedString
				/**
				 * Failed to update track
				 */
				updateFailed: () => LocalizedString
				/**
				 * Failed to delete track
				 */
				deleteFailed: () => LocalizedString
			}
			grades: {
				/**
				 * Failed to fetch grades
				 */
				fetchFailed: () => LocalizedString
				/**
				 * Failed to fetch grade by ID
				 */
				fetchByIdFailed: () => LocalizedString
				/**
				 * Failed to create grade
				 */
				createFailed: () => LocalizedString
				/**
				 * Failed to update grade
				 */
				updateFailed: () => LocalizedString
				/**
				 * Failed to delete grade
				 */
				deleteFailed: () => LocalizedString
				/**
				 * Failed to bulk update grades order
				 */
				bulkUpdateOrderFailed: () => LocalizedString
			}
			series: {
				/**
				 * Failed to fetch series
				 */
				fetchFailed: () => LocalizedString
				/**
				 * Failed to fetch serie by ID
				 */
				fetchByIdFailed: () => LocalizedString
				/**
				 * Failed to create serie
				 */
				createFailed: () => LocalizedString
				/**
				 * Failed to update serie
				 */
				updateFailed: () => LocalizedString
				/**
				 * Failed to delete serie
				 */
				deleteFailed: () => LocalizedString
				/**
				 * Failed to bulk create series
				 */
				bulkCreateFailed: () => LocalizedString
			}
			subjects: {
				/**
				 * Failed to fetch subjects
				 */
				fetchFailed: () => LocalizedString
				/**
				 * Failed to fetch subject by ID
				 */
				fetchByIdFailed: () => LocalizedString
				/**
				 * Failed to create subject
				 */
				createFailed: () => LocalizedString
				/**
				 * Failed to update subject
				 */
				updateFailed: () => LocalizedString
				/**
				 * Failed to delete subject
				 */
				deleteFailed: () => LocalizedString
				/**
				 * Failed to bulk create subjects
				 */
				bulkCreateFailed: () => LocalizedString
			}
			schoolSubjects: {
				/**
				 * Failed to fetch school subjects
				 */
				fetchFailed: () => LocalizedString
				/**
				 * Failed to fetch available core subjects
				 */
				fetchAvailableCoreFailed: () => LocalizedString
				/**
				 * No active school year found
				 */
				noActiveSchoolYear: () => LocalizedString
				/**
				 * Failed to add subjects to school
				 */
				addFailed: () => LocalizedString
				/**
				 * Failed to toggle subject status
				 */
				toggleStatusFailed: () => LocalizedString
				/**
				 * Failed to delete school subject
				 */
				deleteFailed: () => LocalizedString
				/**
				 * Failed to fetch subject usage stats
				 */
				fetchUsageStatsFailed: () => LocalizedString
				/**
				 * Failed to fetch school subject by ID
				 */
				fetchByIdFailed: () => LocalizedString
				/**
				 * Failed to check subject in use
				 */
				checkInUseFailed: () => LocalizedString
			}
			stats: {
				/**
				 * Failed to fetch catalog stats
				 */
				fetchFailed: () => LocalizedString
			}
		}
		curriculum: {
			/**
			 * Failed to fetch class sessions
			 */
			fetchSessionsFailed: () => LocalizedString
			/**
			 * Failed to fetch class session by ID
			 */
			fetchSessionByIdFailed: () => LocalizedString
			/**
			 * Failed to create class session
			 */
			createSessionFailed: () => LocalizedString
			/**
			 * Failed to update class session
			 */
			updateSessionFailed: () => LocalizedString
			/**
			 * Failed to delete class session
			 */
			deleteSessionFailed: () => LocalizedString
			/**
			 * Failed to mark session completed
			 */
			markSessionCompletedFailed: () => LocalizedString
			/**
			 * Failed to fetch chapter completions
			 */
			fetchChapterCompletionsFailed: () => LocalizedString
			/**
			 * Failed to mark chapter complete
			 */
			markChapterCompleteFailed: () => LocalizedString
			/**
			 * Failed to unmark chapter complete
			 */
			unmarkChapterCompleteFailed: () => LocalizedString
			/**
			 * Failed to check if chapter is completed
			 */
			checkChapterCompletedFailed: () => LocalizedString
			/**
			 * Failed to fetch curriculum progress
			 */
			fetchProgressFailed: () => LocalizedString
			/**
			 * Failed to fetch progress overview
			 */
			fetchOverviewFailed: () => LocalizedString
			/**
			 * Failed to fetch classes behind schedule
			 */
			fetchBehindScheduleFailed: () => LocalizedString
			/**
			 * Failed to update curriculum progress
			 */
			updateProgressFailed: () => LocalizedString
			/**
			 * Failed to create curriculum progress
			 */
			createProgressFailed: () => LocalizedString
			/**
			 * Failed to upsert curriculum progress
			 */
			upsertProgressFailed: () => LocalizedString
			/**
			 * Failed to calculate progress
			 */
			calculateProgressFailed: () => LocalizedString
			/**
			 * Failed to fetch progress stats by status
			 */
			fetchStatsByStatusFailed: () => LocalizedString
			/**
			 * Failed to fetch progress by subject
			 */
			fetchProgressBySubjectFailed: () => LocalizedString
			/**
			 * Failed to fetch teacher progress summary
			 */
			fetchTeacherSummaryFailed: () => LocalizedString
		}
	}
}

export type Formatters = {}
