packages:
  - packages/*
  - apps/*

catalog:
  '@aws-sdk/client-s3': ^3.974.0
  '@aws-sdk/s3-request-presigner': ^3.974.0
  '@base-ui/react': ^1.1.0
  '@chronicstone/typed-xlsx': ^0.2.17
  '@cloudflare/vite-plugin': ^1.21.2
  '@cloudflare/vitest-pool-workers': ^0.12.6
  '@cloudflare/workers-types': ^4.20260123.0
  '@dnd-kit/core': ^6.3.1
  '@dnd-kit/sortable': ^10.0.0
  '@dnd-kit/utilities': ^3.2.2
  '@electric-sql/pglite': ^0.3.15
  '@hookform/resolvers': ^5.2.2
  '@logtape/logtape': ^2.0.1
  '@neondatabase/serverless': ^1.0.2
  '@planetscale/database': ^1.19.0
  '@playwright/test': ^1.57.0
  '@polar-sh/better-auth': ^1.6.4
  '@polar-sh/sdk': ^0.42.2
  '@polar-sh/tanstack-start': ^0.4.3
  '@tabler/icons-react': ^3.36.1
  '@tailwindcss/typography': ^0.5.19
  '@tailwindcss/vite': ^4.1.18
  '@tanstack/react-form': ^0.41.2
  '@tanstack/react-query': ^5.90.19
  '@tanstack/react-query-devtools': ^5.91.2
  '@tanstack/react-router': ^1.154.13
  '@tanstack/react-router-devtools': ^1.154.13
  '@tanstack/react-router-ssr-query': ^1.154.13
  '@tanstack/react-start': ^1.154.13
  '@tanstack/react-table': ^8.21.3
  '@tanstack/react-virtual': ^3.13.18
  '@tanstack/zod-form-adapter': ^0.41.2
  '@testing-library/dom': ^10.4.1
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.2
  '@testing-library/user-event': ^14.6.1
  '@types/better-sqlite3': ^7.6.13
  '@types/dompurify': ^3.2.0
  '@types/node': ^25.0.10
  '@types/pg': ^8.16.0
  '@types/react': ^19.2.9
  '@types/react-dom': ^19.2.3
  '@types/remark-prism': ^1.3.7
  '@types/scrypt-js': ^3.0.1
  '@types/xlsx': ^0.0.36
  '@vitejs/plugin-react': ^5.1.2
  '@vitest/coverage-v8': 2.1.9
  aws4fetch: ^1.0.20
  better-auth: ^1.4.17
  better-sqlite3: ^12.6.2
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: ^1.1.1
  date-fns: ^4.1.0
  dompurify: ^3.3.1
  dotenv: ^17.2.3
  drizzle-kit: ^0.31.8
  drizzle-orm: ^0.45.1
  embla-carousel-react: ^8.6.0
  eslint: ^9.39.2
  eslint-plugin-format: ^1.3.1
  highlight.js: ^11.11.1
  hono: ^4.11.5
  i18next: ^25.8.0
  i18next-browser-languagedetector: ^8.2.0
  input-otp: ^1.4.2
  jsdom: ^27.4.0
  lucide-react: ^0.563.0
  motion: ^12.29.0
  mysql2: ^3.16.1
  neverthrow: ^8.2.0
  next-themes: ^0.4.6
  pg: ^8.17.2
  playwright: ^1.57.0
  postgres: ^3.4.8
  react: ^19.0.3
  react-day-picker: ^9.13.0
  react-dom: ^19.0.3
  react-hook-form: ^7.71.1
  react-i18next: ^16.5.4
  react-icons: ^5.5.0
  react-image-crop: ^11.0.10
  react-markdown: ^10.1.0
  react-resizable-panels: ^4.0.7
  recharts: ^2.15.4
  rehype-highlight: ^7.0.2
  remark-breaks: ^4.0.0
  remark-gfm: ^4.0.1
  resend: ^6.8.0
  scrypt-js: ^3.0.1
  sonner: ^2.0.7
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  tsc-alias: ^1.8.16
  tsup: ^8.5.1
  tw-animate-css: ^1.4.0
  typesafe-i18n: ^5.26.2
  typescript: ^5.9.3
  vaul: ^1.1.2
  vite: 7.1.2
  vite-tsconfig-paths: ^6.0.4
  vitest: ^4.0.18
  web-vitals: ^5.1.0
  wrangler: ^4.60.0
  xlsx: ^0.18.5
  zod: ^4.3.6

catalogs:
  conflicts_react-day-picker_h9_13_0:
    react-day-picker: ^9.13.0
  conflicts_vitest_t4_0_15:
    vitest: ~4.0.18

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - workerd
