packages:
  - packages/*
  - apps/*

catalog:
  '@aws-sdk/client-s3': ^3.995.0
  '@aws-sdk/s3-request-presigner': ^3.995.0
  '@base-ui/react': ^1.2.0
  '@chronicstone/typed-xlsx': ^0.2.17
  '@cloudflare/vite-plugin': ^1.25.2
  '@cloudflare/vitest-pool-workers': ^0.12.14
  '@cloudflare/workers-types': ^4.20260228.0
  '@dnd-kit/core': ^6.3.1
  '@dnd-kit/sortable': ^10.0.0
  '@dnd-kit/utilities': ^3.2.2
  '@electric-sql/pglite': ^0.3.15
  '@fontsource-variable/inter': ^5.2.8
  '@fontsource-variable/plus-jakarta-sans': ^5.2.8
  '@hookform/resolvers': ^5.2.2
  '@logtape/logtape': ^2.0.2
  '@neondatabase/serverless': ^1.0.2
  '@planetscale/database': ^1.19.0
  '@playwright/test': ^1.58.2
  '@polar-sh/better-auth': ^1.8.1
  '@polar-sh/sdk': ^0.43.1
  '@polar-sh/tanstack-start': ^0.4.3
  '@praha/byethrow': ^0.10.0
  '@tabler/icons-react': ^3.37.1
  '@tailwindcss/typography': ^0.5.19
  '@tailwindcss/vite': ^4.2.0
  '@tanstack/react-form': ^1.28.3
  '@tanstack/react-query': ^5.90.21
  '@tanstack/react-query-devtools': ^5.91.3
  '@tanstack/react-router': ^1.162.4
  '@tanstack/react-router-devtools': ^1.162.4
  '@tanstack/react-router-ssr-query': ^1.162.4
  '@tanstack/react-start': ^1.162.4
  '@tanstack/react-table': ^8.21.3
  '@tanstack/react-virtual': ^3.13.18
  '@tanstack/zod-form-adapter': ^0.42.1
  '@testing-library/dom': ^10.4.1
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.2
  '@testing-library/user-event': ^14.6.1
  '@types/better-sqlite3': ^7.6.13
  '@types/dompurify': ^3.2.0
  '@types/node': ^25.3.0
  '@types/pg': ^8.16.0
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@types/remark-prism': ^1.3.7
  '@types/scrypt-js': ^3.0.1
  '@types/xlsx': ^0.0.36
  '@vitejs/plugin-react': ^5.1.4
  '@vitest/coverage-v8': 2.1.9
  aws4fetch: ^1.0.20
  better-auth: ^1.4.18
  better-sqlite3: ^12.6.2
  class-variance-authority: ^0.7.1
  cloudflare: ^5.2.0
  clsx: ^2.1.1
  cmdk: ^1.1.1
  date-fns: ^4.1.0
  dompurify: ^3.3.1
  dotenv: ^17.3.1
  drizzle-kit: ^0.31.9
  drizzle-orm: ^0.45.1
  embla-carousel-react: ^8.6.0
  eslint: ^10.0.1
  eslint-plugin-format: ^1.4.0
  eslint-plugin-react-refresh: ^0.5.0
  highlight.js: ^11.11.1
  hono: ^4.12.1
  i18next: ^25.8.13
  i18next-browser-languagedetector: ^8.2.1
  input-otp: ^1.4.2
  jsdom: ^28.1.0
  knip: ^5.85.0
  lucide-react: ^0.575.0
  motion: ^12.34.3
  mysql2: ^3.17.4
  next-themes: ^0.4.6
  pg: ^8.18.0
  playwright: ^1.58.2
  postgres: ^3.4.8
  react: ^19.0.4
  react-day-picker: ^9.13.2
  react-dom: ^19.0.4
  react-hook-form: ^7.71.2
  react-i18next: ^16.5.4
  react-icons: ^5.5.0
  react-image-crop: ^11.0.10
  react-markdown: ^10.1.0
  libphonenumber-js: ^1.12.37
  react-phone-number-input: ^3.4.14
  react-resizable-panels: ^4.6.5
  recharts: ^3.7.0
  rehype-highlight: ^7.0.2
  remark-breaks: ^4.0.0
  remark-gfm: ^4.0.1
  resend: ^6.9.2
  rollup-plugin-visualizer: ^7.0.0
  scrypt-js: ^3.0.1
  sonner: ^2.0.7
  tailwind-merge: ^3.5.0
  tailwindcss: ^4.2.0
  tsc-alias: ^1.8.16
  tsup: ^8.5.1
  tw-animate-css: ^1.4.0
  typesafe-i18n: ^5.27.1
  typescript: ^5.9.3
  vaul: ^1.1.2
  vite: 7.1.2
  vite-tsconfig-paths: ^6.1.1
  vitest: ^4.0.18
  web-vitals: ^5.1.0
  wrangler: ^4.68.1
  xlsx: ^0.18.5
  zod: ^4.3.6

catalogs:
  conflicts_react-day-picker_h9_13_0:
    react-day-picker: ^9.13.2
  conflicts_vitest_t4_0_15:
    vitest: ~4.0.18

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - workerd

patchedDependencies: null
