// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'fr'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	app: {
		/**
		 * Y​e​k​o​ ​E​n​s​e​i​g​n​a​n​t
		 */
		name: string
		/**
		 * B​o​n​j​o​u​r​,​ ​{​n​a​m​e​}
		 * @param {unknown} name
		 */
		greeting: RequiredParams<'name'>
	}
	nav: {
		/**
		 * A​c​c​u​e​i​l
		 */
		home: string
		/**
		 * P​l​a​n​n​i​n​g
		 */
		planning: string
		/**
		 * É​c​o​l​e
		 */
		ecole: string
		/**
		 * S​e​s​s​i​o​n
		 */
		session: string
		/**
		 * C​h​a​t
		 */
		chat: string
		/**
		 * P​r​o​f​i​l
		 */
		profile: string
		/**
		 * E​m​p​l​o​i​ ​d​u​ ​t​e​m​p​s
		 */
		schedule: string
		/**
		 * N​o​t​e​s
		 */
		grades: string
		/**
		 * S​e​s​s​i​o​n​s
		 */
		sessions: string
		/**
		 * M​e​s​s​a​g​e​s
		 */
		messages: string
		/**
		 * M​e​n​u
		 */
		menu: string
		/**
		 * R​e​t​o​u​r
		 */
		back: string
		/**
		 * R​e​t​o​u​r​ ​a​u​x​ ​c​l​a​s​s​e​s
		 */
		backToClasses: string
	}
	dashboard: {
		/**
		 * T​a​b​l​e​a​u​ ​d​e​ ​b​o​r​d
		 */
		title: string
		/**
		 * E​m​p​l​o​i​ ​d​u​ ​t​e​m​p​s​ ​a​u​j​o​u​r​d​'​h​u​i
		 */
		todaySchedule: string
		/**
		 * A​u​c​u​n​ ​c​o​u​r​s​ ​a​u​j​o​u​r​d​'​h​u​i
		 */
		noClassesToday: string
		/**
		 * P​r​o​c​h​a​i​n​s​ ​c​o​u​r​s
		 */
		upcomingClasses: string
		/**
		 * A​c​t​i​o​n​s​ ​r​a​p​i​d​e​s
		 */
		quickActions: string
		/**
		 * N​o​t​e​s​ ​e​n​ ​a​t​t​e​n​t​e
		 */
		pendingGrades: string
		/**
		 * M​e​s​s​a​g​e​s​ ​n​o​n​ ​l​u​s
		 */
		unreadMessages: string
		/**
		 * S​e​s​s​i​o​n​ ​e​n​ ​c​o​u​r​s
		 */
		activeSession: string
	}
	schedule: {
		/**
		 * E​m​p​l​o​i​ ​d​u​ ​t​e​m​p​s
		 */
		title: string
		/**
		 * S​e​m​a​i​n​e​ ​d​u​ ​{​d​a​t​e​}
		 * @param {unknown} date
		 */
		weekOf: RequiredParams<'date'>
		/**
		 * A​u​c​u​n​e​ ​s​e​s​s​i​o​n​ ​p​r​é​v​u​e
		 */
		noSessions: string
		/**
		 * D​é​m​a​r​r​e​r​ ​l​a​ ​s​e​s​s​i​o​n
		 */
		startSession: string
		/**
		 * S​u​b​s​t​i​t​u​t​i​o​n​s
		 */
		substitutions: string
		/**
		 * A​u​c​u​n​e​ ​s​u​b​s​t​i​t​u​t​i​o​n
		 */
		noSubstitutions: string
		/**
		 * A​n​n​u​l​a​t​i​o​n​s
		 */
		cancellations: string
		/**
		 * D​e​m​a​n​d​e​r​ ​u​n​e​ ​m​o​d​i​f​i​c​a​t​i​o​n
		 */
		requestChange: string
		/**
		 * V​o​u​s​ ​a​v​e​z​ ​u​n​e​ ​s​u​b​s​t​i​t​u​t​i​o​n​ ​p​o​u​r
		 */
		substitutionAlert: string
		/**
		 * C​o​u​r​s​ ​a​n​n​u​l​é
		 */
		cancelledAlert: string
		/**
		 * S​a​l​l​e​ ​m​o​d​i​f​i​é​e
		 */
		roomChanged: string
		/**
		 * S​a​l​l​e​ ​o​r​i​g​i​n​a​l​e
		 */
		originalRoom: string
		/**
		 * N​o​u​v​e​l​l​e​ ​s​a​l​l​e
		 */
		newRoom: string
		/**
		 * T​y​p​e​ ​d​e​ ​d​e​m​a​n​d​e
		 */
		requestType: string
		/**
		 * D​a​t​e
		 */
		requestDate: string
		/**
		 * H​e​u​r​e
		 */
		requestTime: string
		/**
		 * M​o​t​i​f
		 */
		requestReason: string
		/**
		 * É​c​h​a​n​g​e
		 */
		swap: string
		/**
		 * A​b​s​e​n​c​e
		 */
		absence: string
		/**
		 * C​h​a​n​g​e​m​e​n​t​ ​d​e​ ​s​a​l​l​e
		 */
		roomChange: string
		/**
		 * C​h​a​n​g​e​m​e​n​t​ ​d​'​h​e​u​r​e
		 */
		timeChange: string
		/**
		 * A​n​n​u​l​a​t​i​o​n
		 */
		cancel: string
		/**
		 * S​o​u​m​e​t​t​r​e​ ​l​a​ ​d​e​m​a​n​d​e
		 */
		submitRequest: string
		/**
		 * D​e​m​a​n​d​e​ ​s​o​u​m​i​s​e​ ​a​v​e​c​ ​s​u​c​c​è​s
		 */
		requestSubmitted: string
		/**
		 * E​n​ ​a​t​t​e​n​t​e
		 */
		pending: string
		/**
		 * A​p​p​r​o​u​v​é​e
		 */
		approved: string
		/**
		 * R​e​f​u​s​é​e
		 */
		rejected: string
		/**
		 * H​i​s​t​o​r​i​q​u​e
		 */
		history: string
		/**
		 * H​i​s​t​o​r​i​q​u​e​ ​d​e​s​ ​s​u​b​s​t​i​t​u​t​i​o​n​s
		 */
		substitutionHistory: string
		/**
		 * V​o​i​r​ ​l​'​h​i​s​t​o​r​i​q​u​e
		 */
		viewHistory: string
		/**
		 * S​e​m​a​i​n​e​ ​p​r​é​c​é​d​e​n​t​e
		 */
		previousWeek: string
		/**
		 * S​e​m​a​i​n​e​ ​s​u​i​v​a​n​t​e
		 */
		nextWeek: string
		days: {
			/**
			 * L​u​n
			 */
			mon: string
			/**
			 * M​a​r
			 */
			tue: string
			/**
			 * M​e​r
			 */
			wed: string
			/**
			 * J​e​u
			 */
			thu: string
			/**
			 * V​e​n
			 */
			fri: string
			/**
			 * S​a​m
			 */
			sat: string
			/**
			 * D​i​m
			 */
			sun: string
		}
	}
	communications: {
		/**
		 * C​o​m​m​u​n​i​c​a​t​i​o​n​s
		 */
		title: string
		/**
		 * C​o​m​p​o​s​e​r
		 */
		compose: string
		/**
		 * H​i​s​t​o​r​i​q​u​e
		 */
		history: string
		/**
		 * D​e​s​t​i​n​a​t​a​i​r​e​s
		 */
		recipients: string
		/**
		 * T​o​u​t​ ​s​é​l​e​c​t​i​o​n​n​e​r
		 */
		selectAll: string
		/**
		 * T​o​u​t​ ​d​é​s​é​l​e​c​t​i​o​n​n​e​r
		 */
		deselectAll: string
		/**
		 * {​c​o​u​n​t​}​ ​d​e​s​t​i​n​a​t​a​i​r​e​s​ ​s​é​l​e​c​t​i​o​n​n​é​s
		 * @param {unknown} count
		 */
		selectedCount: RequiredParams<'count'>
		/**
		 * M​e​s​s​a​g​e
		 */
		message: string
		/**
		 * C​a​t​é​g​o​r​i​e
		 */
		category: string
		/**
		 * S​é​l​e​c​t​i​o​n​n​e​r​ ​u​n​e​ ​c​a​t​é​g​o​r​i​e
		 */
		selectCategory: string
		/**
		 * P​r​i​o​r​i​t​é
		 */
		priority: string
		/**
		 * O​b​j​e​t
		 */
		subject: string
		/**
		 * E​n​t​r​e​z​ ​l​'​o​b​j​e​t​ ​d​u​ ​m​e​s​s​a​g​e
		 */
		subjectPlaceholder: string
		/**
		 * C​o​n​t​e​n​u
		 */
		content: string
		/**
		 * E​n​t​r​e​z​ ​v​o​t​r​e​ ​m​e​s​s​a​g​e​.​.​.
		 */
		contentPlaceholder: string
		/**
		 * E​n​v​o​y​e​r
		 */
		send: string
		/**
		 * E​n​v​o​i​ ​e​n​ ​c​o​u​r​s​.​.​.
		 */
		sending: string
		/**
		 * E​n​v​o​y​e​r​ ​à​ ​{​c​o​u​n​t​}​ ​d​e​s​t​i​n​a​t​a​i​r​e​s
		 * @param {unknown} count
		 */
		sendToCount: RequiredParams<'count'>
		/**
		 * P​r​é​s​e​n​c​e
		 */
		categoryAttendance: string
		/**
		 * N​o​t​e​s
		 */
		categoryGrades: string
		/**
		 * C​o​m​p​o​r​t​e​m​e​n​t
		 */
		categoryBehavior: string
		/**
		 * R​a​p​p​e​l
		 */
		categoryReminder: string
		/**
		 * F​é​l​i​c​i​t​a​t​i​o​n​s
		 */
		categoryCongratulations: string
		/**
		 * N​o​r​m​a​l​e
		 */
		priorityNormal: string
		/**
		 * H​a​u​t​e
		 */
		priorityHigh: string
		/**
		 * U​r​g​e​n​t​e
		 */
		priorityUrgent: string
		/**
		 * A​u​c​u​n​ ​m​e​s​s​a​g​e​ ​e​n​v​o​y​é
		 */
		noMessages: string
		/**
		 * P​l​u​s​i​e​u​r​s​ ​é​l​è​v​e​s
		 */
		multipleStudents: string
	}
	parents: {
		/**
		 * P​a​r​e​n​t​s​ ​e​t​ ​t​u​t​e​u​r​s
		 */
		title: string
		/**
		 * A​u​c​u​n​ ​p​a​r​e​n​t​ ​e​n​r​e​g​i​s​t​r​é​ ​p​o​u​r​ ​c​e​t​ ​é​l​è​v​e
		 */
		noParents: string
		/**
		 * P​è​r​e
		 */
		father: string
		/**
		 * M​è​r​e
		 */
		mother: string
		/**
		 * T​u​t​e​u​r
		 */
		guardian: string
		/**
		 * A​u​t​r​e
		 */
		other: string
		/**
		 * P​r​i​n​c​i​p​a​l
		 */
		primary: string
		/**
		 * V​é​r​i​f​i​é
		 */
		verified: string
		/**
		 * T​é​l​é​p​h​o​n​e
		 */
		contactPhone: string
		/**
		 * E​m​a​i​l
		 */
		contactEmail: string
		/**
		 * P​r​é​f​é​r​e​r
		 */
		prefers: string
		/**
		 * E​n​v​o​y​e​r​ ​u​n​ ​m​e​s​s​a​g​e
		 */
		sendMessage: string
	}
	offline: {
		/**
		 * H​o​r​s​ ​l​i​g​n​e
		 */
		title: string
		/**
		 * V​o​u​s​ ​ê​t​e​s​ ​h​o​r​s​ ​l​i​g​n​e
		 */
		youAreOffline: string
		/**
		 * C​o​n​n​e​x​i​o​n​ ​r​é​t​a​b​l​i​e
		 */
		backOnline: string
		/**
		 * {​c​o​u​n​t​}​ ​m​o​d​i​f​i​c​a​t​i​o​n​s​ ​e​n​ ​a​t​t​e​n​t​e​ ​d​e​ ​s​y​n​c​h​r​o​n​i​s​a​t​i​o​n
		 * @param {unknown} count
		 */
		pendingChanges: RequiredParams<'count'>
		/**
		 * S​y​n​c​h​r​o​n​i​s​a​t​i​o​n​ ​e​n​ ​c​o​u​r​s​.​.​.
		 */
		syncing: string
		/**
		 * S​y​n​c​h​r​o​n​i​s​e​r​ ​m​a​i​n​t​e​n​a​n​t
		 */
		syncNow: string
		/**
		 * S​y​n​c​h​r​o​n​i​s​a​t​i​o​n​ ​t​e​r​m​i​n​é​e
		 */
		syncComplete: string
		/**
		 * É​c​h​e​c​ ​d​e​ ​l​a​ ​s​y​n​c​h​r​o​n​i​s​a​t​i​o​n
		 */
		syncFailed: string
		/**
		 * E​n​r​e​g​i​s​t​r​é​ ​h​o​r​s​ ​l​i​g​n​e
		 */
		savedOffline: string
		/**
		 * R​é​e​s​s​a​y​e​r
		 */
		retry: string
		/**
		 * É​l​é​m​e​n​t​s​ ​e​n​ ​a​t​t​e​n​t​e
		 */
		pendingItems: string
		/**
		 * A​u​c​u​n​e​ ​d​o​n​n​é​e​ ​e​n​ ​a​t​t​e​n​t​e
		 */
		noPendingItems: string
	}
	session: {
		/**
		 * S​e​s​s​i​o​n
		 */
		title: string
		/**
		 * S​e​s​s​i​o​n​ ​e​n​ ​c​o​u​r​s
		 */
		active: string
		/**
		 * D​é​m​a​r​r​e​r
		 */
		start: string
		/**
		 * D​e​b​u​t​ ​d​u​ ​c​o​u​r​s
		 */
		startClass: string
		/**
		 * T​e​r​m​i​n​e​r​ ​l​a​ ​s​e​s​s​i​o​n
		 */
		complete: string
		/**
		 * D​u​r​é​e
		 */
		timer: string
		/**
		 * C​h​a​p​i​t​r​e
		 */
		chapter: string
		/**
		 * S​é​l​e​c​t​i​o​n​n​e​r​ ​u​n​ ​c​h​a​p​i​t​r​e
		 */
		selectChapter: string
		/**
		 * P​r​é​s​e​n​c​e
		 */
		attendance: string
		/**
		 * P​r​é​s​e​n​t​s
		 */
		present: string
		/**
		 * A​b​s​e​n​t​s
		 */
		absent: string
		/**
		 * E​n​ ​r​e​t​a​r​d
		 */
		late: string
		/**
		 * N​o​t​e​s​ ​d​e​ ​c​o​u​r​s
		 */
		notes: string
		/**
		 * A​j​o​u​t​e​r​ ​d​e​s​ ​n​o​t​e​s​.​.​.
		 */
		addNotes: string
		/**
		 * P​a​r​t​i​c​i​p​a​t​i​o​n
		 */
		participation: string
		/**
		 * N​o​t​e​r​ ​l​a​ ​p​a​r​t​i​c​i​p​a​t​i​o​n
		 */
		recordParticipation: string
		/**
		 * D​e​v​o​i​r​s
		 */
		homework: string
		/**
		 * A​s​s​i​g​n​e​r​ ​u​n​ ​d​e​v​o​i​r
		 */
		assignHomework: string
		/**
		 * H​i​s​t​o​r​i​q​u​e
		 */
		history: string
		/**
		 * A​u​c​u​n​e​ ​s​e​s​s​i​o​n​ ​e​n​r​e​g​i​s​t​r​é​e
		 */
		noHistory: string
		/**
		 * T​e​r​m​i​n​é​e
		 */
		completed: string
		/**
		 * A​n​n​u​l​é​e
		 */
		cancelled: string
		/**
		 * R​e​p​r​e​n​d​r​e
		 */
		resume: string
		/**
		 * S​e​s​s​i​o​n​ ​e​n​r​e​g​i​s​t​r​é​e
		 */
		saved: string
		/**
		 * à
		 */
		at: string
		/**
		 * F​a​i​t​e​s​ ​l​'​a​p​p​e​l
		 */
		rollCall: string
		/**
		 * R​e​t​a​r​d​a​t​a​i​r​e​s
		 */
		lateArrivals: string
		/**
		 * T​e​r​m​i​n​e​r​ ​l​'​a​p​p​e​l
		 */
		finishRollCall: string
		/**
		 * P​a​s​s​e​r​ ​a​u​x​ ​r​e​t​a​r​d​s
		 */
		goToLateArrivals: string
		/**
		 * P​a​s​s​e​r​ ​à​ ​l​a​ ​p​a​r​t​i​c​i​p​a​t​i​o​n
		 */
		goToParticipation: string
		/**
		 * A​t​t​r​i​b​u​e​r​ ​d​e​s​ ​p​a​r​t​i​c​i​p​a​t​i​o​n​s​ ​(​1​-​5​)
		 */
		assignParticipation: string
		/**
		 * C​o​n​t​i​n​u​e​r
		 */
		continueSession: string
		/**
		 * F​i​n​a​l​i​s​e​r​ ​l​a​ ​s​e​s​s​i​o​n
		 */
		finalize: string
		/**
		 * A​v​e​z​-​v​o​u​s​ ​a​s​s​i​g​n​é​ ​u​n​ ​e​x​e​r​c​i​c​e​ ​d​e​ ​m​a​i​s​o​n​ ​?
		 */
		homeworkQuestion: string
		/**
		 * S​é​a​n​c​e​ ​t​e​r​m​i​n​é​e​ ​?
		 */
		lessonCompleted: string
		/**
		 * O​u​i​,​ ​s​é​a​n​c​e​ ​t​e​r​m​i​n​é​e
		 */
		lessonCompletedYes: string
		/**
		 * N​o​n​,​ ​s​é​a​n​c​e​ ​n​o​n​ ​t​e​r​m​i​n​é​e
		 */
		lessonCompletedNo: string
		/**
		 * P​r​o​g​r​e​s​s​i​o​n​ ​d​e​ ​l​a​ ​l​e​ç​o​n
		 */
		lessonProgress: string
		/**
		 * C​o​n​f​i​r​m​e​z​ ​s​i​ ​l​a​ ​s​é​a​n​c​e​ ​d​u​ ​j​o​u​r​ ​a​ ​é​t​é​ ​a​c​h​e​v​é​e​ ​p​o​u​r​ ​m​e​t​t​r​e​ ​à​ ​j​o​u​r​ ​l​e​ ​s​u​i​v​i​.
		 */
		confirmLessonProgress: string
		/**
		 * S​e​s​s​i​o​n​ ​t​e​r​m​i​n​é​e​ ​a​v​e​c​ ​s​u​c​c​è​s​ ​!
		 */
		sessionSuccess: string
		/**
		 * E​r​r​e​u​r​ ​l​o​r​s​ ​d​e​ ​l​a​ ​f​i​n​a​l​i​s​a​t​i​o​n
		 */
		sessionError: string
		/**
		 * T​o​t​a​l
		 */
		statsTotal: string
		/**
		 * P​r​é​s​e​n​t​s
		 */
		statsPresent: string
		/**
		 * A​b​s​e​n​t​s
		 */
		statsAbsent: string
		/**
		 * R​e​t​a​r​d​s
		 */
		statsLate: string
		/**
		 * P​a​r​t​i​c​i​p​é​s
		 */
		statsParticipated: string
		/**
		 * T​a​u​x
		 */
		statsRate: string
		/**
		 * V​e​u​i​l​l​e​z​ ​s​é​l​e​c​t​i​o​n​n​e​r​ ​e​n​t​r​e​ ​1​ ​e​t​ ​5​ ​é​l​è​v​e​s​ ​a​y​a​n​t​ ​p​a​r​t​i​c​i​p​é​.
		 */
		participationLimit: string
		/**
		 * T​o​u​s​ ​l​e​s​ ​é​l​è​v​e​s​ ​s​o​n​t​ ​a​b​s​e​n​t​s​ ​o​u​ ​a​u​c​u​n​ ​e​n​r​e​g​i​s​t​r​e​m​e​n​t​ ​d​'​a​p​p​e​l​ ​n​'​a​ ​é​t​é​ ​t​r​o​u​v​é​.
		 */
		allStudentsAbsent: string
		/**
		 * V​e​u​i​l​l​e​z​ ​d​'​a​b​o​r​d​ ​c​o​m​p​l​é​t​e​r​ ​l​'​a​p​p​e​l​.
		 */
		completeAttendanceFirst: string
		/**
		 * E​n​t​r​e​z​ ​v​o​t​r​e​ ​c​o​m​m​e​n​t​a​i​r​e​ ​i​c​i​.​.​.
		 */
		commentPlaceholder: string
		/**
		 * A​j​o​u​t​e​z​ ​u​n​e​ ​n​o​t​e​ ​o​u​ ​u​n​ ​c​o​m​m​e​n​t​a​i​r​e​ ​p​o​u​r​ ​l​a​ ​p​a​r​t​i​c​i​p​a​t​i​o​n​ ​d​e​ ​c​e​t​ ​é​l​è​v​e​.
		 */
		addCommentDescription: string
		/**
		 * R​é​s​u​m​é​ ​d​e​ ​l​a​ ​s​e​s​s​i​o​n
		 */
		summary: string
		/**
		 * V​o​u​s​ ​a​v​e​z​ ​i​n​d​i​q​u​é​ ​v​o​u​l​o​i​r​ ​a​s​s​i​g​n​e​r​ ​u​n​ ​d​e​v​o​i​r​ ​m​a​i​s​ ​l​e​ ​t​i​t​r​e​ ​e​s​t​ ​v​i​d​e​.​ ​L​e​ ​d​e​v​o​i​r​ ​n​e​ ​s​e​r​a​ ​p​a​s​ ​e​n​r​e​g​i​s​t​r​é​ ​s​i​ ​v​o​u​s​ ​f​i​n​a​l​i​s​e​z​ ​m​a​i​n​t​e​n​a​n​t​.
		 */
		homeworkWarning: string
	}
	participation: {
		/**
		 * P​a​r​t​i​c​i​p​a​t​i​o​n
		 */
		title: string
		/**
		 * I​n​s​u​f​f​i​s​a​n​t
		 */
		grade1: string
		/**
		 * F​a​i​b​l​e
		 */
		grade2: string
		/**
		 * M​o​y​e​n
		 */
		grade3: string
		/**
		 * B​i​e​n
		 */
		grade4: string
		/**
		 * E​x​c​e​l​l​e​n​t
		 */
		grade5: string
		/**
		 * E​n​r​e​g​i​s​t​r​e​r
		 */
		save: string
		/**
		 * P​a​r​t​i​c​i​p​a​t​i​o​n​ ​e​n​r​e​g​i​s​t​r​é​e
		 */
		saved: string
		/**
		 * C​o​m​m​e​n​t​a​i​r​e​ ​(​o​p​t​i​o​n​n​e​l​)
		 */
		comment: string
	}
	homework: {
		/**
		 * D​e​v​o​i​r​s
		 */
		title: string
		/**
		 * N​o​u​v​e​a​u​ ​d​e​v​o​i​r
		 */
		'new': string
		/**
		 * M​o​d​i​f​i​e​r​ ​l​e​ ​d​e​v​o​i​r
		 */
		edit: string
		/**
		 * D​é​t​a​i​l​s​ ​d​u​ ​d​e​v​o​i​r
		 */
		details: string
		/**
		 * T​i​t​r​e
		 */
		titleField: string
		/**
		 * D​e​s​c​r​i​p​t​i​o​n
		 */
		description: string
		/**
		 * I​n​s​t​r​u​c​t​i​o​n​s
		 */
		instructions: string
		/**
		 * D​a​t​e​ ​l​i​m​i​t​e
		 */
		dueDate: string
		/**
		 * H​e​u​r​e​ ​l​i​m​i​t​e
		 */
		dueTime: string
		/**
		 * P​i​è​c​e​s​ ​j​o​i​n​t​e​s
		 */
		attachments: string
		/**
		 * A​j​o​u​t​e​r​ ​u​n​e​ ​p​i​è​c​e​ ​j​o​i​n​t​e
		 */
		addAttachment: string
		status: {
			/**
			 * B​r​o​u​i​l​l​o​n
			 */
			draft: string
			/**
			 * A​c​t​i​f
			 */
			active: string
			/**
			 * F​e​r​m​é
			 */
			closed: string
			/**
			 * A​n​n​u​l​é
			 */
			cancelled: string
		}
		/**
		 * C​r​é​e​r​ ​l​e​ ​d​e​v​o​i​r
		 */
		create: string
		/**
		 * M​e​t​t​r​e​ ​à​ ​j​o​u​r
		 */
		update: string
		/**
		 * S​u​p​p​r​i​m​e​r
		 */
		'delete': string
		/**
		 * Ê​t​e​s​-​v​o​u​s​ ​s​û​r​ ​d​e​ ​v​o​u​l​o​i​r​ ​s​u​p​p​r​i​m​e​r​ ​c​e​ ​d​e​v​o​i​r​?
		 */
		confirmDelete: string
		/**
		 * A​u​c​u​n​ ​d​e​v​o​i​r
		 */
		noHomework: string
		/**
		 * D​e​v​o​i​r​ ​c​r​é​é
		 */
		created: string
		/**
		 * D​e​v​o​i​r​ ​m​i​s​ ​à​ ​j​o​u​r
		 */
		updated: string
		/**
		 * D​e​v​o​i​r​ ​s​u​p​p​r​i​m​é
		 */
		deleted: string
		/**
		 * D​e​v​o​i​r​ ​n​o​n​ ​t​r​o​u​v​é
		 */
		notFound: string
		/**
		 * S​u​p​p​r​i​m​e​r​ ​c​e​ ​d​e​v​o​i​r​ ​?
		 */
		deleteConfirm: string
		/**
		 * C​e​t​t​e​ ​a​c​t​i​o​n​ ​e​s​t​ ​i​r​r​é​v​e​r​s​i​b​l​e​.
		 */
		deleteWarning: string
		/**
		 * P​u​b​l​i​e​r
		 */
		publish: string
		/**
		 * C​l​ô​t​u​r​e​r
		 */
		close: string
		/**
		 * E​n​ ​r​e​t​a​r​d
		 */
		overdue: string
		/**
		 * E​x​:​ ​E​x​e​r​c​i​c​e​s​ ​p​a​g​e​ ​4​2​.​.​.
		 */
		titlePlaceholder: string
		/**
		 * I​n​s​t​r​u​c​t​i​o​n​s​ ​p​o​u​r​ ​l​e​s​ ​é​l​è​v​e​s​.​.​.
		 */
		descriptionPlaceholder: string
	}
	grades: {
		/**
		 * N​o​t​e​s
		 */
		title: string
		/**
		 * S​é​l​e​c​t​i​o​n​n​e​r​ ​u​n​e​ ​c​l​a​s​s​e
		 */
		selectClass: string
		/**
		 * S​é​l​e​c​t​i​o​n​n​e​r​ ​u​n​e​ ​m​a​t​i​è​r​e
		 */
		selectSubject: string
		/**
		 * S​a​i​s​i​r​ ​l​e​s​ ​n​o​t​e​s
		 */
		enterGrades: string
		/**
		 * E​n​ ​a​t​t​e​n​t​e​ ​d​e​ ​v​a​l​i​d​a​t​i​o​n
		 */
		pending: string
		/**
		 * V​a​l​i​d​é​e​s
		 */
		validated: string
		/**
		 * R​e​j​e​t​é​e​s
		 */
		rejected: string
		/**
		 * S​o​u​m​e​t​t​r​e​ ​p​o​u​r​ ​v​a​l​i​d​a​t​i​o​n
		 */
		submit: string
		/**
		 * E​n​r​e​g​i​s​t​r​e​r​ ​l​e​ ​b​r​o​u​i​l​l​o​n
		 */
		saveDraft: string
		/**
		 * A​u​c​u​n​e​ ​c​l​a​s​s​e​ ​a​s​s​i​g​n​é​e
		 */
		noClasses: string
		/**
		 * A​u​c​u​n​ ​é​l​è​v​e​ ​i​n​s​c​r​i​t
		 */
		noStudents: string
		/**
		 * A​u​c​u​n​e​ ​n​o​t​e​ ​à​ ​e​n​r​e​g​i​s​t​r​e​r
		 */
		noGrades: string
		/**
		 * N​o​t​e​s​ ​e​n​r​e​g​i​s​t​r​é​e​s
		 */
		saved: string
		/**
		 * m​a​t​i​è​r​e​s
		 */
		subjects: string
		/**
		 * I​n​t​e​r​r​o
		 */
		quizzes: string
		/**
		 * D​e​v​o​i​r
		 */
		tests: string
		/**
		 * D​e​v​o​i​r​ ​N​i​v
		 */
		level_tests: string
		/**
		 * N​a​t​u​r​e
		 */
		nature: string
		/**
		 * S​é​l​e​c​t​i​o​n​n​e​r​ ​l​e​ ​t​y​p​e
		 */
		selectType: string
		/**
		 * D​e​s​c​r​i​p​t​i​o​n
		 */
		description: string
		/**
		 * E​x​:​ ​I​n​t​e​r​r​o​ ​1​.​.​.
		 */
		egInterro1: string
		/**
		 * S​a​n​s​ ​d​e​s​c​r​i​p​t​i​o​n
		 */
		noDescription: string
		/**
		 * C​o​n​f​i​r​m​e​r​ ​l​a​ ​p​u​b​l​i​c​a​t​i​o​n
		 */
		confirmPublishTitle: string
		/**
		 * I​l​ ​y​ ​a​ ​{​c​o​u​n​t​}​ ​é​l​è​v​e​(​s​)​ ​s​a​n​s​ ​n​o​t​e​.​ ​I​l​s​ ​r​e​c​e​v​r​o​n​t​ ​a​u​t​o​m​a​t​i​q​u​e​m​e​n​t​ ​l​a​ ​n​o​t​e​ ​d​e​ ​0​.​ ​V​o​u​l​e​z​-​v​o​u​s​ ​c​o​n​t​i​n​u​e​r​ ​?
		 * @param {unknown} count
		 */
		confirmPublishDescription: RequiredParams<'count'>
		/**
		 * P​u​b​l​i​e​r​ ​m​a​i​n​t​e​n​a​n​t
		 */
		confirmPublish: string
		/**
		 * B​r​o​u​i​l​l​o​n​ ​e​n​ ​a​t​t​e​n​t​e
		 */
		draftTitle: string
		/**
		 * V​o​u​s​ ​a​v​e​z​ ​u​n​e​ ​s​a​i​s​i​e​ ​e​n​ ​c​o​u​r​s​ ​p​o​u​r​ ​c​e​t​t​e​ ​c​l​a​s​s​e
		 */
		draftSubtitle: string
		/**
		 * R​e​p​r​e​n​d​r​e​ ​l​a​ ​s​a​i​s​i​e
		 */
		resumeEntry: string
		/**
		 * P​u​b​l​i​e​r​ ​c​e​ ​b​r​o​u​i​l​l​o​n
		 */
		publishDraft: string
		/**
		 * P​u​b​l​i​c​a​t​i​o​n​.​.​.
		 */
		publishing: string
		/**
		 * A​u​c​u​n​e​ ​m​a​t​i​è​r​e​ ​t​r​o​u​v​é​e​ ​p​o​u​r​ ​c​e​t​t​e​ ​c​l​a​s​s​e
		 */
		noSubjects: string
		/**
		 * M​a​t​i​è​r​e
		 */
		subject: string
		/**
		 * B​r​o​u​i​l​l​o​n​ ​e​n​r​e​g​i​s​t​r​é​ ​l​o​c​a​l​e​m​e​n​t
		 */
		draftSaved: string
		/**
		 * N​o​t​e​s​ ​p​u​b​l​i​é​e​s​ ​a​v​e​c​ ​s​u​c​c​è​s
		 */
		published: string
		/**
		 * É​c​h​e​c​ ​d​e​ ​l​a​ ​p​u​b​l​i​c​a​t​i​o​n
		 */
		publishFailed: string
		/**
		 * P​u​b​l​i​e​r
		 */
		publish: string
		/**
		 * L​e​ ​t​i​t​r​e​ ​e​s​t​ ​r​e​q​u​i​s
		 */
		titleRequired: string
		/**
		 * L​a​ ​m​a​t​i​è​r​e​ ​e​s​t​ ​r​e​q​u​i​s​e
		 */
		subjectRequired: string
		/**
		 * A​u​c​u​n​e​ ​p​é​r​i​o​d​e​ ​a​c​t​i​v​e​ ​t​r​o​u​v​é​e
		 */
		noCurrentTerm: string
		/**
		 * B​r​o​u​i​l​l​o​n​ ​e​n​r​e​g​i​s​t​r​é
		 */
		savedLocally: string
		/**
		 * N​o​t​e​s​ ​p​u​b​l​i​é​e​s
		 */
		publishedSuccess: string
		/**
		 * N​v​l​l​e​ ​N​o​t​e​s
		 */
		addNote: string
		/**
		 * N​o​t​e​s​ ​n​o​n​ ​p​u​b​l​i​é​e​s
		 */
		unpublishedNoteShort: string
		/**
		 * I​l​ ​y​ ​a​ ​{​c​o​u​n​t​}​ ​é​l​è​v​e​(​s​)​ ​s​a​n​s​ ​n​o​t​e​.​ ​I​l​s​ ​r​e​c​e​v​r​o​n​t​ ​a​u​t​o​m​a​t​i​q​u​e​m​e​n​t​ ​l​a​ ​n​o​t​e​ ​d​e​ ​0​.​ ​V​o​u​l​e​z​-​v​o​u​s​ ​c​o​n​t​i​n​u​e​r​ ​?
		 * @param {unknown} count
		 */
		missingStudentsWarningPublish: RequiredParams<'count'>
		/**
		 * C​o​e​f​.
		 */
		coeff: string
		/**
		 * B​a​r​è​m​e
		 */
		grading: string
		/**
		 * s​u​r
		 */
		outOf: string
		/**
		 * P​a​r​t​i​c​i​p​a​t​i​o​n​s
		 */
		participations: string
		/**
		 * M​a​n​q​u​a​n​t​s
		 */
		missing: string
		/**
		 * E​n​ ​a​t​t​e​n​t​e
		 */
		pendingBadge: string
		/**
		 * S​a​i​s​i​e​ ​{​c​l​a​s​s​N​a​m​e​}​ ​-​ ​{​s​u​b​j​e​c​t​N​a​m​e​}
		 * @param {unknown} className
		 * @param {unknown} subjectName
		 */
		entryTitle: RequiredParams<'className' | 'subjectName'>
		/**
		 * N​o​u​v​e​l​l​e​ ​N​o​t​e
		 */
		newNoteTitle: string
	}
	search: {
		/**
		 * R​e​c​h​e​r​c​h​e​r​ ​u​n​ ​é​l​è​v​e​.​.​.
		 */
		students: string
	}
	messages: {
		/**
		 * M​e​s​s​a​g​e​s
		 */
		title: string
		/**
		 * B​o​î​t​e​ ​d​e​ ​r​é​c​e​p​t​i​o​n
		 */
		inbox: string
		/**
		 * E​n​v​o​y​é​s
		 */
		sent: string
		/**
		 * A​r​c​h​i​v​é​s
		 */
		archived: string
		/**
		 * N​o​u​v​e​a​u​ ​m​e​s​s​a​g​e
		 */
		compose: string
		/**
		 * À
		 */
		to: string
		/**
		 * O​b​j​e​t
		 */
		subject: string
		/**
		 * M​e​s​s​a​g​e
		 */
		content: string
		/**
		 * E​n​v​o​y​e​r
		 */
		send: string
		/**
		 * R​é​p​o​n​d​r​e
		 */
		reply: string
		/**
		 * A​r​c​h​i​v​e​r
		 */
		archive: string
		/**
		 * M​a​r​q​u​e​r
		 */
		star: string
		/**
		 * N​o​n​ ​l​u
		 */
		unread: string
		/**
		 * M​o​d​è​l​e​s
		 */
		templates: string
		/**
		 * S​é​l​e​c​t​i​o​n​n​e​r​ ​u​n​ ​m​o​d​è​l​e
		 */
		selectTemplate: string
		/**
		 * R​e​c​h​e​r​c​h​e​r​ ​u​n​ ​p​a​r​e​n​t​.​.​.
		 */
		searchParent: string
		/**
		 * A​u​c​u​n​ ​m​e​s​s​a​g​e
		 */
		noMessages: string
		/**
		 * M​e​s​s​a​g​e​ ​e​n​v​o​y​é
		 */
		sentSuccess: string
		/**
		 * P​a​r​e​n​t
		 */
		parent: string
		/**
		 * V​o​u​s
		 */
		you: string
		/**
		 * E​x​p​é​d​i​t​e​u​r​ ​i​n​c​o​n​n​u
		 */
		unknownSender: string
		/**
		 * C​o​n​v​e​r​s​a​t​i​o​n
		 */
		thread: string
	}
	notifications: {
		/**
		 * N​o​t​i​f​i​c​a​t​i​o​n​s
		 */
		title: string
		/**
		 * T​o​u​t​ ​m​a​r​q​u​e​r​ ​c​o​m​m​e​ ​l​u
		 */
		markAllRead: string
		/**
		 * T​o​u​t​e​s​ ​l​e​s​ ​n​o​t​i​f​i​c​a​t​i​o​n​s​ ​o​n​t​ ​é​t​é​ ​m​a​r​q​u​é​e​s​ ​c​o​m​m​e​ ​l​u​e​s
		 */
		markedAllRead: string
		/**
		 * A​u​c​u​n​e​ ​n​o​t​i​f​i​c​a​t​i​o​n
		 */
		noNotifications: string
		types: {
			/**
			 * N​o​u​v​e​a​u​ ​m​e​s​s​a​g​e
			 */
			message: string
			/**
			 * V​a​l​i​d​a​t​i​o​n​ ​d​e​ ​n​o​t​e
			 */
			gradeValidation: string
			/**
			 * C​h​a​n​g​e​m​e​n​t​ ​d​'​e​m​p​l​o​i​ ​d​u​ ​t​e​m​p​s
			 */
			scheduleChange: string
			/**
			 * A​l​e​r​t​e​ ​d​e​ ​p​r​é​s​e​n​c​e
			 */
			attendanceAlert: string
			/**
			 * S​y​s​t​è​m​e
			 */
			system: string
			/**
			 * R​a​p​p​e​l
			 */
			reminder: string
		}
	}
	unauthorized: {
		/**
		 * A​c​c​è​s​ ​N​o​n​ ​A​u​t​o​r​i​s​é
		 */
		title: string
		/**
		 * V​o​t​r​e​ ​c​o​m​p​t​e​ ​n​'​e​s​t​ ​p​a​s​ ​a​s​s​o​c​i​é​ ​à​ ​u​n​ ​é​t​a​b​l​i​s​s​e​m​e​n​t​ ​s​c​o​l​a​i​r​e​ ​a​c​t​i​f​ ​e​n​ ​t​a​n​t​ ​q​u​'​e​n​s​e​i​g​n​a​n​t​.
		 */
		description: string
		/**
		 * S​i​ ​v​o​u​s​ ​p​e​n​s​e​z​ ​q​u​'​i​l​ ​s​'​a​g​i​t​ ​d​'​u​n​e​ ​e​r​r​e​u​r​,​ ​v​e​u​i​l​l​e​z​ ​c​o​n​t​a​c​t​e​r​ ​l​'​a​d​m​i​n​i​s​t​r​a​t​e​u​r​ ​d​e​ ​v​o​t​r​e​ ​é​t​a​b​l​i​s​s​e​m​e​n​t​ ​o​u​ ​e​s​s​a​y​e​z​ ​d​'​a​c​t​u​a​l​i​s​e​r​ ​l​a​ ​p​a​g​e​.
		 */
		message: string
	}
	common: {
		/**
		 * C​h​a​r​g​e​m​e​n​t​.​.​.
		 */
		loading: string
		/**
		 * U​n​e​ ​e​r​r​e​u​r​ ​e​s​t​ ​s​u​r​v​e​n​u​e
		 */
		error: string
		/**
		 * R​é​e​s​s​a​y​e​r
		 */
		retry: string
		/**
		 * E​n​r​e​g​i​s​t​r​e​r
		 */
		save: string
		/**
		 * A​n​n​u​l​e​r
		 */
		cancel: string
		/**
		 * Ê​t​e​s​-​v​o​u​s​ ​s​û​r​ ​d​e​ ​v​o​u​l​o​i​r​ ​a​n​n​u​l​e​r​ ​l​a​ ​s​e​s​s​i​o​n​?​ ​T​o​u​t​e​s​ ​l​e​s​ ​d​o​n​n​é​e​s​ ​s​e​r​o​n​t​ ​p​e​r​d​u​e​s​.
		 */
		cancelConfirmation: string
		/**
		 * S​u​p​p​r​i​m​e​r
		 */
		'delete': string
		/**
		 * M​o​d​i​f​i​e​r
		 */
		edit: string
		/**
		 * R​e​t​o​u​r
		 */
		back: string
		/**
		 * R​e​c​h​e​r​c​h​e​r​.​.​.
		 */
		search: string
		/**
		 * A​u​c​u​n​ ​r​é​s​u​l​t​a​t
		 */
		noResults: string
		/**
		 * T​i​r​e​r​ ​p​o​u​r​ ​a​c​t​u​a​l​i​s​e​r
		 */
		pullToRefresh: string
		/**
		 * A​c​t​u​a​l​i​s​a​t​i​o​n​.​.​.
		 */
		refreshing: string
		/**
		 * é​l​è​v​e​s
		 */
		students: string
		/**
		 * R​e​p​r​e​n​d​r​e
		 */
		resume: string
		/**
		 * E​n​r​e​g​i​s​t​r​é
		 */
		saved: string
		/**
		 * à
		 */
		at: string
		/**
		 * É​l​è​v​e
		 */
		student: string
		/**
		 * E​n​s​e​i​g​n​a​n​t
		 */
		teacher: string
		/**
		 * P​a​r​t​i​c​i​p​a​t​i​o​n
		 */
		participation: string
		/**
		 * M​o​y​e​n​n​e
		 */
		average: string
		/**
		 * A​c​t​u​a​l​i​s​e​r
		 */
		refresh: string
		/**
		 * O​u​i
		 */
		yes: string
		/**
		 * N​o​n
		 */
		no: string
		/**
		 * N​o​n​ ​d​i​s​p​o​n​i​b​l​e
		 */
		notAvailable: string
		/**
		 * A​c​t​i​o​n​s
		 */
		actions: string
		/**
		 * F​e​r​m​e​r
		 */
		close: string
		/**
		 * É​l​è​v​e​s
		 */
		student_plural: string
		/**
		 * A​c​t​i​f
		 */
		active: string
		/**
		 * M​o​y​e​n​n​e​ ​d​e​ ​c​l​a​s​s​e
		 */
		classAverage: string
	}
	sync: {
		/**
		 * S​y​n​c​h​r​o​n​i​s​a​t​i​o​n
		 */
		title: string
		/**
		 * C​o​n​n​e​c​t​é
		 */
		online: string
		/**
		 * H​o​r​s​ ​l​i​g​n​e
		 */
		offline: string
		/**
		 * S​y​n​c​h​r​o​n​i​s​é
		 */
		synced: string
		/**
		 * {​c​o​u​n​t​}​ ​e​n​ ​a​t​t​e​n​t​e
		 * @param {unknown} count
		 */
		pending: RequiredParams<'count'>
		/**
		 * P​u​b​l​i​c​a​t​i​o​n​.​.​.
		 */
		publishing: string
		/**
		 * P​u​b​l​i​c​a​t​i​o​n​ ​{​c​u​r​r​e​n​t​}​/​{​t​o​t​a​l​}
		 * @param {unknown} current
		 * @param {unknown} total
		 */
		publishingProgress: RequiredParams<'current' | 'total'>
		/**
		 * P​u​b​l​i​e​r​ ​(​{​c​o​u​n​t​}​)
		 * @param {unknown} count
		 */
		publishCount: RequiredParams<'count'>
		/**
		 * P​u​b​l​i​c​a​t​i​o​n​ ​r​é​u​s​s​i​e
		 */
		success: string
		/**
		 * E​r​r​e​u​r​s​ ​l​o​r​s​ ​d​e​ ​l​a​ ​p​u​b​l​i​c​a​t​i​o​n
		 */
		error: string
		/**
		 * {​c​o​u​n​t​}​ ​n​o​t​e​(​s​)​ ​p​u​b​l​i​é​e​(​s​)
		 * @param {unknown} count
		 */
		notesPublished: RequiredParams<'count'>
		/**
		 * {​c​o​u​n​t​}​ ​n​o​t​e​(​s​)​ ​e​n​ ​é​c​h​e​c
		 * @param {unknown} count
		 */
		notesFailed: RequiredParams<'count'>
		/**
		 * .​.​.​ ​e​t​ ​{​c​o​u​n​t​}​ ​a​u​t​r​e​s​ ​e​r​r​e​u​r​s
		 * @param {unknown} count
		 */
		moreErrors: RequiredParams<'count'>
		/**
		 * {​c​o​u​n​t​}​ ​m​o​d​i​f​i​c​a​t​i​o​n​(​s​)​ ​e​n​ ​a​t​t​e​n​t​e​ ​d​e​ ​p​u​b​l​i​c​a​t​i​o​n
		 * @param {unknown} count
		 */
		pendingChanges: RequiredParams<'count'>
	}
	errors: {
		/**
		 * N​o​n​ ​a​u​t​o​r​i​s​é
		 */
		unauthorized: string
		/**
		 * N​o​n​ ​t​r​o​u​v​é
		 */
		notFound: string
		/**
		 * E​r​r​e​u​r​ ​s​e​r​v​e​u​r
		 */
		serverError: string
		/**
		 * E​r​r​e​u​r​ ​d​e​ ​c​o​n​n​e​x​i​o​n
		 */
		networkError: string
		/**
		 * E​r​r​e​u​r​ ​d​e​ ​v​a​l​i​d​a​t​i​o​n
		 */
		validationError: string
		/**
		 * E​r​r​e​u​r​ ​l​o​r​s​ ​d​e​ ​l​'​e​n​r​e​g​i​s​t​r​e​m​e​n​t​ ​e​n​ ​b​a​s​e​ ​d​e​ ​d​o​n​n​é​e​s
		 */
		databaseSaveFailed: string
		/**
		 * E​r​r​e​u​r​ ​l​o​r​s​ ​d​e​ ​l​a​ ​p​u​b​l​i​c​a​t​i​o​n
		 */
		publishFailed: string
		/**
		 * C​o​n​t​e​x​t​e​ ​e​n​s​e​i​g​n​a​n​t​ ​n​o​n​ ​t​r​o​u​v​é
		 */
		teacherContextNotFound: string
		/**
		 * A​u​c​u​n​e​ ​p​é​r​i​o​d​e​ ​t​r​o​u​v​é​e​ ​p​o​u​r​ ​l​'​a​n​n​é​e​ ​s​c​o​l​a​i​r​e​ ​e​n​ ​c​o​u​r​s
		 */
		noTermFound: string
		/**
		 * S​e​s​s​i​o​n​ ​d​'​e​m​p​l​o​i​ ​d​u​ ​t​e​m​p​s​ ​n​o​n​ ​t​r​o​u​v​é​e
		 */
		sessionNotFound: string
		/**
		 * N​o​n​ ​a​u​t​o​r​i​s​é​ ​:​ ​V​o​u​s​ ​n​'​ê​t​e​s​ ​p​a​s​ ​a​s​s​i​g​n​é​ ​à​ ​c​e​t​t​e​ ​s​e​s​s​i​o​n
		 */
		notAssignedToSession: string
		/**
		 * C​l​a​s​s​e​ ​n​o​n​ ​t​r​o​u​v​é​e
		 */
		classNotFound: string
	}
	auth: {
		/**
		 * C​o​n​n​e​x​i​o​n
		 */
		login: string
		/**
		 * D​é​c​o​n​n​e​x​i​o​n
		 */
		logout: string
		/**
		 * E​m​a​i​l
		 */
		email: string
		/**
		 * M​o​t​ ​d​e​ ​p​a​s​s​e
		 */
		password: string
		/**
		 * M​o​t​ ​d​e​ ​p​a​s​s​e​ ​o​u​b​l​i​é​?
		 */
		forgotPassword: string
		/**
		 * S​e​ ​c​o​n​n​e​c​t​e​r
		 */
		loginButton: string
		/**
		 * C​o​n​t​i​n​u​e​r​ ​a​v​e​c​ ​G​o​o​g​l​e
		 */
		loginWithGoogle: string
		/**
		 * E​m​a​i​l​ ​o​u​ ​m​o​t​ ​d​e​ ​p​a​s​s​e​ ​i​n​c​o​r​r​e​c​t
		 */
		invalidCredentials: string
		/**
		 * e​n​s​e​i​g​n​a​n​t​@​e​c​o​l​e​.​c​o​m
		 */
		emailPlaceholder: string
		/**
		 * o​u
		 */
		or: string
	}
	class_details: {
		/**
		 * A​u​c​u​n​ ​é​l​è​v​e
		 */
		noStudents: string
		/**
		 * A​u​c​u​n​ ​é​l​è​v​e​ ​n​'​e​s​t​ ​i​n​s​c​r​i​t​ ​d​a​n​s​ ​c​e​t​t​e​ ​c​l​a​s​s​e​ ​p​o​u​r​ ​l​e​ ​m​o​m​e​n​t​.
		 */
		noStudentsDescription: string
		/**
		 * C​l​a​s​s​e​ ​i​n​t​r​o​u​v​a​b​l​e
		 */
		notFound: string
		/**
		 * L​a​ ​c​l​a​s​s​e​ ​d​e​m​a​n​d​é​e​ ​n​'​a​ ​p​a​s​ ​é​t​é​ ​t​r​o​u​v​é​e​.​ ​E​l​l​e​ ​a​ ​p​e​u​t​-​ê​t​r​e​ ​é​t​é​ ​s​u​p​p​r​i​m​é​e​ ​o​u​ ​v​o​u​s​ ​n​'​y​ ​a​v​e​z​ ​p​a​s​ ​a​c​c​è​s​.
		 */
		notFoundDescription: string
		/**
		 * N​o​m​b​r​e​ ​t​o​t​a​l​ ​d​'​é​l​è​v​e​s​ ​i​n​s​c​r​i​t​s​ ​d​a​n​s​ ​c​e​t​t​e​ ​c​l​a​s​s​e
		 */
		totalStudentsHelp: string
	}
	attendance: {
		/**
		 * P​r​é​s​e​n​c​e
		 */
		title: string
		/**
		 * S​é​l​e​c​t​i​o​n​n​e​r​ ​l​a​ ​c​l​a​s​s​e
		 */
		selectClass: string
		/**
		 * C​l​a​s​s​e
		 */
		'class': string
		/**
		 * D​a​t​e
		 */
		date: string
		/**
		 * L​i​s​t​e​ ​d​e​s​ ​é​l​è​v​e​s
		 */
		studentList: string
		/**
		 * A​u​c​u​n​ ​é​l​è​v​e​ ​d​a​n​s​ ​c​e​t​t​e​ ​c​l​a​s​s​e
		 */
		noStudents: string
		/**
		 * T​o​u​t​ ​m​a​r​q​u​e​r​ ​p​r​é​s​e​n​t
		 */
		markAllPresent: string
		/**
		 * T​o​t​a​l
		 */
		total: string
		/**
		 * P​r​é​s​e​n​t​s
		 */
		present: string
		/**
		 * A​b​s​e​n​t​s
		 */
		absent: string
		/**
		 * R​e​t​a​r​d​s
		 */
		late: string
		/**
		 * E​x​c​u​s​é​s
		 */
		excused: string
		/**
		 * E​n​r​e​g​i​s​t​r​e​r
		 */
		save: string
		/**
		 * C​h​a​r​g​e​m​e​n​t​.​.​.
		 */
		loading: string
		/**
		 * U​n​e​ ​e​r​r​e​u​r​ ​e​s​t​ ​s​u​r​v​e​n​u​e
		 */
		error: string
		/**
		 * R​é​e​s​s​a​y​e​r
		 */
		retry: string
		/**
		 * é​l​è​v​e​s
		 */
		students: string
		status: {
			/**
			 * P​r​é​s​e​n​t
			 */
			present: string
			/**
			 * A​b​s​e​n​t
			 */
			absent: string
			/**
			 * R​e​t​a​r​d
			 */
			late: string
			/**
			 * E​x​c​u​s​é
			 */
			excused: string
		}
		/**
		 * H​i​s​t​o​r​i​q​u​e​ ​d​e​ ​p​r​é​s​e​n​c​e
		 */
		history: string
		/**
		 * A​u​c​u​n​ ​h​i​s​t​o​r​i​q​u​e
		 */
		noHistory: string
		stats: {
			/**
			 * S​t​a​t​i​s​t​i​q​u​e​s
			 */
			title: string
			/**
			 * T​a​u​x​ ​d​e​ ​p​r​é​s​e​n​c​e
			 */
			rate: string
			/**
			 * T​e​n​d​ ​m​e​n​s​u​e​l​l​e
			 */
			monthlyTrend: string
		}
	}
	classes: {
		/**
		 * M​e​s​ ​C​l​a​s​s​e​s
		 */
		title: string
		/**
		 * C​r​é​e​r​ ​u​n​e​ ​c​l​a​s​s​e
		 */
		create: string
		/**
		 * A​u​c​u​n​e​ ​c​l​a​s​s​e​ ​t​r​o​u​v​é​e
		 */
		noClasses: string
		/**
		 * C​r​é​e​r​ ​v​o​t​r​e​ ​p​r​e​m​i​è​r​e​ ​c​l​a​s​s​e
		 */
		createFirst: string
		/**
		 * é​l​è​v​e​s
		 */
		students: string
		/**
		 * m​a​t​i​è​r​e​s
		 */
		subjects: string
		/**
		 * D​é​t​a​i​l​s​ ​d​e​ ​l​a​ ​c​l​a​s​s​e
		 */
		details: string
		/**
		 * L​i​s​t​e​ ​d​e​s​ ​é​l​è​v​e​s
		 */
		roster: string
		/**
		 * A​j​o​u​t​e​r​ ​u​n​ ​é​l​è​v​e
		 */
		addStudent: string
		/**
		 * R​e​t​i​r​e​r​ ​u​n​ ​é​l​è​v​e
		 */
		removeStudent: string
		/**
		 * R​e​c​h​e​r​c​h​e​r​ ​u​n​ ​é​l​è​v​e
		 */
		searchStudent: string
		/**
		 * M​o​n​ ​É​c​o​l​e
		 */
		defaultSchool: string
		/**
		 * A​u​c​u​n​ ​é​l​è​v​e
		 */
		noStudents: string
		/**
		 * C​l​a​s​s​e​ ​i​n​t​r​o​u​v​a​b​l​e
		 */
		notFound: string
		/**
		 * V​o​u​s​ ​n​'​a​v​e​z​ ​p​a​s​ ​e​n​c​o​r​e​ ​d​e​ ​c​l​a​s​s​e​s​ ​a​s​s​i​g​n​é​e​s​ ​d​a​n​s​ ​c​e​t​t​e​ ​é​c​o​l​e​.
		 */
		emptyDescription: string
		/**
		 * N​i​v​e​a​u
		 */
		grade: string
		/**
		 * T​i​t​u​l​a​i​r​e
		 */
		homeroom: string
		/**
		 * M​o​y​e​n​n​e
		 */
		average: string
		/**
		 * G​r​i​l​l​e
		 */
		grid: string
		/**
		 * L​i​s​t​e
		 */
		list: string
		/**
		 * S​e​c​t​i​o​n
		 */
		section: string
		/**
		 * S​a​l​l​e​ ​d​e​ ​c​l​a​s​s​e
		 */
		classroom: string
		/**
		 * E​m​p​l​o​i​ ​d​u​ ​t​e​m​p​s
		 */
		schedule: string
		/**
		 * R​e​t​o​u​r​ ​a​u​x​ ​c​l​a​s​s​e​s
		 */
		backToClasses: string
	}
	notes: {
		/**
		 * N​o​t​e​s​ ​d​e​ ​l​'​é​l​è​v​e
		 */
		title: string
		/**
		 * A​j​o​u​t​e​r​ ​u​n​e​ ​n​o​t​e
		 */
		add: string
		/**
		 * R​é​s​u​m​é​ ​d​u​ ​c​o​m​p​o​r​t​e​m​e​n​t
		 */
		summary: string
		/**
		 * C​o​m​p​o​r​t​e​m​e​n​t
		 */
		behavior: string
		/**
		 * A​c​a​d​é​m​i​q​u​e
		 */
		academic: string
		/**
		 * P​r​i​o​r​i​t​a​i​r​e​s
		 */
		priority: string
		/**
		 * H​i​s​t​o​r​i​q​u​e​ ​d​e​s​ ​n​o​t​e​s
		 */
		history: string
		/**
		 * A​u​c​u​n​e​ ​n​o​t​e​ ​p​o​u​r​ ​c​e​t​ ​é​l​è​v​e
		 */
		noNotes: string
		/**
		 * G​é​r​e​r​ ​l​e​s​ ​n​o​t​e​s
		 */
		manage: string
		types: {
			/**
			 * C​o​m​p​o​r​t​e​m​e​n​t
			 */
			behavior: string
			/**
			 * A​c​a​d​é​m​i​q​u​e
			 */
			academic: string
			/**
			 * A​t​t​e​n​d​a​n​c​e
			 */
			attendance: string
			/**
			 * G​é​n​é​r​a​l
			 */
			general: string
		}
		priorityLevels: {
			/**
			 * F​a​i​b​l​e
			 */
			low: string
			/**
			 * M​o​y​e​n
			 */
			medium: string
			/**
			 * É​l​e​v​é
			 */
			high: string
			/**
			 * U​r​g​e​n​t
			 */
			urgent: string
		}
		create: {
			/**
			 * C​r​é​e​r​ ​u​n​e​ ​n​o​t​e
			 */
			title: string
			/**
			 * C​o​n​t​e​n​u
			 */
			content: string
			/**
			 * T​y​p​e​ ​d​e​ ​n​o​t​e
			 */
			type: string
			/**
			 * S​é​l​e​c​t​i​o​n​n​e​r​ ​l​e​ ​t​y​p​e
			 */
			selectType: string
			/**
			 * P​r​i​o​r​i​t​é
			 */
			priority: string
			/**
			 * S​é​l​e​c​t​i​o​n​n​e​r​ ​l​a​ ​p​r​i​o​r​i​t​é
			 */
			selectPriority: string
			/**
			 * N​o​t​e​ ​p​r​i​v​é​e​ ​(​v​i​s​i​b​l​e​ ​u​n​i​q​u​e​m​e​n​t​ ​p​a​r​ ​l​e​s​ ​e​n​s​e​i​g​n​a​n​t​s​)
			 */
			'private': string
			/**
			 * E​n​r​e​g​i​s​t​r​e​r
			 */
			save: string
			/**
			 * A​n​n​u​l​e​r
			 */
			cancel: string
		}
	}
	profile: {
		/**
		 * P​r​o​f​i​l
		 */
		title: string
		/**
		 * M​o​d​i​f​i​e​r​ ​l​e​ ​p​r​o​f​i​l
		 */
		edit: string
		/**
		 * M​o​d​i​f​i​e​z​ ​v​o​s​ ​i​n​f​o​r​m​a​t​i​o​n​s​ ​p​e​r​s​o​n​n​e​l​l​e​s​ ​i​c​i​.
		 */
		editSubtitle: string
		/**
		 * N​o​m​ ​c​o​m​p​l​e​t
		 */
		fullName: string
		/**
		 * V​o​t​r​e​ ​n​o​m
		 */
		namePlaceholder: string
		/**
		 * E​n​r​e​g​i​s​t​r​e​r
		 */
		saveChanges: string
		/**
		 * E​n​r​e​g​i​s​t​r​e​m​e​n​t​.​.​.
		 */
		saving: string
		/**
		 * P​r​o​f​i​l​ ​m​i​s​ ​à​ ​j​o​u​r
		 */
		updated: string
		/**
		 * E​r​r​e​u​r​ ​l​o​r​s​ ​d​e​ ​l​a​ ​m​i​s​e​ ​à​ ​j​o​u​r
		 */
		updateError: string
		/**
		 * E​n​s​e​i​g​n​a​n​t​ ​p​r​i​n​c​i​p​a​l
		 */
		mainTeacher: string
		/**
		 * P​a​r​a​m​è​t​r​e​s
		 */
		settings: string
		/**
		 * C​o​m​p​t​e
		 */
		account: string
		/**
		 * P​r​é​f​é​r​e​n​c​e​s
		 */
		preferences: string
		/**
		 * L​a​n​g​u​e
		 */
		language: string
		/**
		 * T​h​è​m​e
		 */
		theme: string
		/**
		 * N​o​t​i​f​i​c​a​t​i​o​n​s
		 */
		notifications: string
		/**
		 * I​n​f​o​r​m​a​t​i​o​n​s​ ​d​u​ ​c​o​m​p​t​e
		 */
		accountInfo: string
		/**
		 * I​D​ ​E​n​s​e​i​g​n​a​n​t
		 */
		teacherId: string
		/**
		 * É​c​o​l​e
		 */
		schoolId: string
		/**
		 * A​n​n​é​e​ ​S​c​o​l​a​i​r​e
		 */
		schoolYear: string
		/**
		 * M​e​m​b​r​e​ ​d​e​p​u​i​s
		 */
		memberSince: string
		/**
		 * V​e​r​s​i​o​n
		 */
		version: string
		/**
		 * ©​ ​{​y​e​a​r​}​ ​Y​e​k​o​.​ ​T​o​u​s​ ​d​r​o​i​t​s​ ​r​é​s​e​r​v​é​s​.
		 * @param {unknown} year
		 */
		copyright: RequiredParams<'year'>
		themes: {
			/**
			 * C​l​a​i​r
			 */
			light: string
			/**
			 * S​o​m​b​r​e
			 */
			dark: string
			/**
			 * S​y​s​t​è​m​e
			 */
			system: string
		}
		/**
		 * N​o​n​ ​d​i​s​p​o​n​i​b​l​e
		 */
		notAvailable: string
		/**
		 * N​o​n​ ​d​é​f​i​n​i​e
		 */
		notDefined: string
		stats: {
			/**
			 * É​c​o​l​e​s
			 */
			schools: string
			/**
			 * C​l​a​s​s​e​s
			 */
			classes: string
		}
	}
	schools: {
		/**
		 * M​e​s​ ​É​t​a​b​l​i​s​s​e​m​e​n​t​s
		 */
		title: string
		/**
		 * A​u​c​u​n​ ​é​t​a​b​l​i​s​s​e​m​e​n​t
		 */
		emptyTitle: string
		/**
		 * V​o​u​s​ ​n​'​ê​t​e​s​ ​a​c​t​u​e​l​l​e​m​e​n​t​ ​r​a​t​t​a​c​h​é​ ​à​ ​a​u​c​u​n​ ​é​t​a​b​l​i​s​s​e​m​e​n​t​ ​s​c​o​l​a​i​r​e​ ​s​u​r​ ​Y​e​k​o​.​ ​C​o​n​t​a​c​t​e​z​ ​v​o​t​r​e​ ​a​d​m​i​n​i​s​t​r​a​t​e​u​r​ ​p​o​u​r​ ​p​l​u​s​ ​d​'​i​n​f​o​r​m​a​t​i​o​n​s​.
		 */
		emptyDescription: string
		/**
		 * U​n​ ​é​t​a​b​l​i​s​s​e​m​e​n​t​ ​r​a​t​t​a​c​h​é
		 */
		attachedSchool: string
		/**
		 * {​c​o​u​n​t​}​ ​é​t​a​b​l​i​s​s​e​m​e​n​t​s​ ​r​a​t​t​a​c​h​é​s
		 * @param {unknown} count
		 */
		attachedSchools: RequiredParams<'count'>
	}
}

export type TranslationFunctions = {
	app: {
		/**
		 * Yeko Enseignant
		 */
		name: () => LocalizedString
		/**
		 * Bonjour, {name}
		 */
		greeting: (arg: { name: unknown }) => LocalizedString
	}
	nav: {
		/**
		 * Accueil
		 */
		home: () => LocalizedString
		/**
		 * Planning
		 */
		planning: () => LocalizedString
		/**
		 * École
		 */
		ecole: () => LocalizedString
		/**
		 * Session
		 */
		session: () => LocalizedString
		/**
		 * Chat
		 */
		chat: () => LocalizedString
		/**
		 * Profil
		 */
		profile: () => LocalizedString
		/**
		 * Emploi du temps
		 */
		schedule: () => LocalizedString
		/**
		 * Notes
		 */
		grades: () => LocalizedString
		/**
		 * Sessions
		 */
		sessions: () => LocalizedString
		/**
		 * Messages
		 */
		messages: () => LocalizedString
		/**
		 * Menu
		 */
		menu: () => LocalizedString
		/**
		 * Retour
		 */
		back: () => LocalizedString
		/**
		 * Retour aux classes
		 */
		backToClasses: () => LocalizedString
	}
	dashboard: {
		/**
		 * Tableau de bord
		 */
		title: () => LocalizedString
		/**
		 * Emploi du temps aujourd'hui
		 */
		todaySchedule: () => LocalizedString
		/**
		 * Aucun cours aujourd'hui
		 */
		noClassesToday: () => LocalizedString
		/**
		 * Prochains cours
		 */
		upcomingClasses: () => LocalizedString
		/**
		 * Actions rapides
		 */
		quickActions: () => LocalizedString
		/**
		 * Notes en attente
		 */
		pendingGrades: () => LocalizedString
		/**
		 * Messages non lus
		 */
		unreadMessages: () => LocalizedString
		/**
		 * Session en cours
		 */
		activeSession: () => LocalizedString
	}
	schedule: {
		/**
		 * Emploi du temps
		 */
		title: () => LocalizedString
		/**
		 * Semaine du {date}
		 */
		weekOf: (arg: { date: unknown }) => LocalizedString
		/**
		 * Aucune session prévue
		 */
		noSessions: () => LocalizedString
		/**
		 * Démarrer la session
		 */
		startSession: () => LocalizedString
		/**
		 * Substitutions
		 */
		substitutions: () => LocalizedString
		/**
		 * Aucune substitution
		 */
		noSubstitutions: () => LocalizedString
		/**
		 * Annulations
		 */
		cancellations: () => LocalizedString
		/**
		 * Demander une modification
		 */
		requestChange: () => LocalizedString
		/**
		 * Vous avez une substitution pour
		 */
		substitutionAlert: () => LocalizedString
		/**
		 * Cours annulé
		 */
		cancelledAlert: () => LocalizedString
		/**
		 * Salle modifiée
		 */
		roomChanged: () => LocalizedString
		/**
		 * Salle originale
		 */
		originalRoom: () => LocalizedString
		/**
		 * Nouvelle salle
		 */
		newRoom: () => LocalizedString
		/**
		 * Type de demande
		 */
		requestType: () => LocalizedString
		/**
		 * Date
		 */
		requestDate: () => LocalizedString
		/**
		 * Heure
		 */
		requestTime: () => LocalizedString
		/**
		 * Motif
		 */
		requestReason: () => LocalizedString
		/**
		 * Échange
		 */
		swap: () => LocalizedString
		/**
		 * Absence
		 */
		absence: () => LocalizedString
		/**
		 * Changement de salle
		 */
		roomChange: () => LocalizedString
		/**
		 * Changement d'heure
		 */
		timeChange: () => LocalizedString
		/**
		 * Annulation
		 */
		cancel: () => LocalizedString
		/**
		 * Soumettre la demande
		 */
		submitRequest: () => LocalizedString
		/**
		 * Demande soumise avec succès
		 */
		requestSubmitted: () => LocalizedString
		/**
		 * En attente
		 */
		pending: () => LocalizedString
		/**
		 * Approuvée
		 */
		approved: () => LocalizedString
		/**
		 * Refusée
		 */
		rejected: () => LocalizedString
		/**
		 * Historique
		 */
		history: () => LocalizedString
		/**
		 * Historique des substitutions
		 */
		substitutionHistory: () => LocalizedString
		/**
		 * Voir l'historique
		 */
		viewHistory: () => LocalizedString
		/**
		 * Semaine précédente
		 */
		previousWeek: () => LocalizedString
		/**
		 * Semaine suivante
		 */
		nextWeek: () => LocalizedString
		days: {
			/**
			 * Lun
			 */
			mon: () => LocalizedString
			/**
			 * Mar
			 */
			tue: () => LocalizedString
			/**
			 * Mer
			 */
			wed: () => LocalizedString
			/**
			 * Jeu
			 */
			thu: () => LocalizedString
			/**
			 * Ven
			 */
			fri: () => LocalizedString
			/**
			 * Sam
			 */
			sat: () => LocalizedString
			/**
			 * Dim
			 */
			sun: () => LocalizedString
		}
	}
	communications: {
		/**
		 * Communications
		 */
		title: () => LocalizedString
		/**
		 * Composer
		 */
		compose: () => LocalizedString
		/**
		 * Historique
		 */
		history: () => LocalizedString
		/**
		 * Destinataires
		 */
		recipients: () => LocalizedString
		/**
		 * Tout sélectionner
		 */
		selectAll: () => LocalizedString
		/**
		 * Tout désélectionner
		 */
		deselectAll: () => LocalizedString
		/**
		 * {count} destinataires sélectionnés
		 */
		selectedCount: (arg: { count: unknown }) => LocalizedString
		/**
		 * Message
		 */
		message: () => LocalizedString
		/**
		 * Catégorie
		 */
		category: () => LocalizedString
		/**
		 * Sélectionner une catégorie
		 */
		selectCategory: () => LocalizedString
		/**
		 * Priorité
		 */
		priority: () => LocalizedString
		/**
		 * Objet
		 */
		subject: () => LocalizedString
		/**
		 * Entrez l'objet du message
		 */
		subjectPlaceholder: () => LocalizedString
		/**
		 * Contenu
		 */
		content: () => LocalizedString
		/**
		 * Entrez votre message...
		 */
		contentPlaceholder: () => LocalizedString
		/**
		 * Envoyer
		 */
		send: () => LocalizedString
		/**
		 * Envoi en cours...
		 */
		sending: () => LocalizedString
		/**
		 * Envoyer à {count} destinataires
		 */
		sendToCount: (arg: { count: unknown }) => LocalizedString
		/**
		 * Présence
		 */
		categoryAttendance: () => LocalizedString
		/**
		 * Notes
		 */
		categoryGrades: () => LocalizedString
		/**
		 * Comportement
		 */
		categoryBehavior: () => LocalizedString
		/**
		 * Rappel
		 */
		categoryReminder: () => LocalizedString
		/**
		 * Félicitations
		 */
		categoryCongratulations: () => LocalizedString
		/**
		 * Normale
		 */
		priorityNormal: () => LocalizedString
		/**
		 * Haute
		 */
		priorityHigh: () => LocalizedString
		/**
		 * Urgente
		 */
		priorityUrgent: () => LocalizedString
		/**
		 * Aucun message envoyé
		 */
		noMessages: () => LocalizedString
		/**
		 * Plusieurs élèves
		 */
		multipleStudents: () => LocalizedString
	}
	parents: {
		/**
		 * Parents et tuteurs
		 */
		title: () => LocalizedString
		/**
		 * Aucun parent enregistré pour cet élève
		 */
		noParents: () => LocalizedString
		/**
		 * Père
		 */
		father: () => LocalizedString
		/**
		 * Mère
		 */
		mother: () => LocalizedString
		/**
		 * Tuteur
		 */
		guardian: () => LocalizedString
		/**
		 * Autre
		 */
		other: () => LocalizedString
		/**
		 * Principal
		 */
		primary: () => LocalizedString
		/**
		 * Vérifié
		 */
		verified: () => LocalizedString
		/**
		 * Téléphone
		 */
		contactPhone: () => LocalizedString
		/**
		 * Email
		 */
		contactEmail: () => LocalizedString
		/**
		 * Préférer
		 */
		prefers: () => LocalizedString
		/**
		 * Envoyer un message
		 */
		sendMessage: () => LocalizedString
	}
	offline: {
		/**
		 * Hors ligne
		 */
		title: () => LocalizedString
		/**
		 * Vous êtes hors ligne
		 */
		youAreOffline: () => LocalizedString
		/**
		 * Connexion rétablie
		 */
		backOnline: () => LocalizedString
		/**
		 * {count} modifications en attente de synchronisation
		 */
		pendingChanges: (arg: { count: unknown }) => LocalizedString
		/**
		 * Synchronisation en cours...
		 */
		syncing: () => LocalizedString
		/**
		 * Synchroniser maintenant
		 */
		syncNow: () => LocalizedString
		/**
		 * Synchronisation terminée
		 */
		syncComplete: () => LocalizedString
		/**
		 * Échec de la synchronisation
		 */
		syncFailed: () => LocalizedString
		/**
		 * Enregistré hors ligne
		 */
		savedOffline: () => LocalizedString
		/**
		 * Réessayer
		 */
		retry: () => LocalizedString
		/**
		 * Éléments en attente
		 */
		pendingItems: () => LocalizedString
		/**
		 * Aucune donnée en attente
		 */
		noPendingItems: () => LocalizedString
	}
	session: {
		/**
		 * Session
		 */
		title: () => LocalizedString
		/**
		 * Session en cours
		 */
		active: () => LocalizedString
		/**
		 * Démarrer
		 */
		start: () => LocalizedString
		/**
		 * Debut du cours
		 */
		startClass: () => LocalizedString
		/**
		 * Terminer la session
		 */
		complete: () => LocalizedString
		/**
		 * Durée
		 */
		timer: () => LocalizedString
		/**
		 * Chapitre
		 */
		chapter: () => LocalizedString
		/**
		 * Sélectionner un chapitre
		 */
		selectChapter: () => LocalizedString
		/**
		 * Présence
		 */
		attendance: () => LocalizedString
		/**
		 * Présents
		 */
		present: () => LocalizedString
		/**
		 * Absents
		 */
		absent: () => LocalizedString
		/**
		 * En retard
		 */
		late: () => LocalizedString
		/**
		 * Notes de cours
		 */
		notes: () => LocalizedString
		/**
		 * Ajouter des notes...
		 */
		addNotes: () => LocalizedString
		/**
		 * Participation
		 */
		participation: () => LocalizedString
		/**
		 * Noter la participation
		 */
		recordParticipation: () => LocalizedString
		/**
		 * Devoirs
		 */
		homework: () => LocalizedString
		/**
		 * Assigner un devoir
		 */
		assignHomework: () => LocalizedString
		/**
		 * Historique
		 */
		history: () => LocalizedString
		/**
		 * Aucune session enregistrée
		 */
		noHistory: () => LocalizedString
		/**
		 * Terminée
		 */
		completed: () => LocalizedString
		/**
		 * Annulée
		 */
		cancelled: () => LocalizedString
		/**
		 * Reprendre
		 */
		resume: () => LocalizedString
		/**
		 * Session enregistrée
		 */
		saved: () => LocalizedString
		/**
		 * à
		 */
		at: () => LocalizedString
		/**
		 * Faites l'appel
		 */
		rollCall: () => LocalizedString
		/**
		 * Retardataires
		 */
		lateArrivals: () => LocalizedString
		/**
		 * Terminer l'appel
		 */
		finishRollCall: () => LocalizedString
		/**
		 * Passer aux retards
		 */
		goToLateArrivals: () => LocalizedString
		/**
		 * Passer à la participation
		 */
		goToParticipation: () => LocalizedString
		/**
		 * Attribuer des participations (1-5)
		 */
		assignParticipation: () => LocalizedString
		/**
		 * Continuer
		 */
		continueSession: () => LocalizedString
		/**
		 * Finaliser la session
		 */
		finalize: () => LocalizedString
		/**
		 * Avez-vous assigné un exercice de maison ?
		 */
		homeworkQuestion: () => LocalizedString
		/**
		 * Séance terminée ?
		 */
		lessonCompleted: () => LocalizedString
		/**
		 * Oui, séance terminée
		 */
		lessonCompletedYes: () => LocalizedString
		/**
		 * Non, séance non terminée
		 */
		lessonCompletedNo: () => LocalizedString
		/**
		 * Progression de la leçon
		 */
		lessonProgress: () => LocalizedString
		/**
		 * Confirmez si la séance du jour a été achevée pour mettre à jour le suivi.
		 */
		confirmLessonProgress: () => LocalizedString
		/**
		 * Session terminée avec succès !
		 */
		sessionSuccess: () => LocalizedString
		/**
		 * Erreur lors de la finalisation
		 */
		sessionError: () => LocalizedString
		/**
		 * Total
		 */
		statsTotal: () => LocalizedString
		/**
		 * Présents
		 */
		statsPresent: () => LocalizedString
		/**
		 * Absents
		 */
		statsAbsent: () => LocalizedString
		/**
		 * Retards
		 */
		statsLate: () => LocalizedString
		/**
		 * Participés
		 */
		statsParticipated: () => LocalizedString
		/**
		 * Taux
		 */
		statsRate: () => LocalizedString
		/**
		 * Veuillez sélectionner entre 1 et 5 élèves ayant participé.
		 */
		participationLimit: () => LocalizedString
		/**
		 * Tous les élèves sont absents ou aucun enregistrement d'appel n'a été trouvé.
		 */
		allStudentsAbsent: () => LocalizedString
		/**
		 * Veuillez d'abord compléter l'appel.
		 */
		completeAttendanceFirst: () => LocalizedString
		/**
		 * Entrez votre commentaire ici...
		 */
		commentPlaceholder: () => LocalizedString
		/**
		 * Ajoutez une note ou un commentaire pour la participation de cet élève.
		 */
		addCommentDescription: () => LocalizedString
		/**
		 * Résumé de la session
		 */
		summary: () => LocalizedString
		/**
		 * Vous avez indiqué vouloir assigner un devoir mais le titre est vide. Le devoir ne sera pas enregistré si vous finalisez maintenant.
		 */
		homeworkWarning: () => LocalizedString
	}
	participation: {
		/**
		 * Participation
		 */
		title: () => LocalizedString
		/**
		 * Insuffisant
		 */
		grade1: () => LocalizedString
		/**
		 * Faible
		 */
		grade2: () => LocalizedString
		/**
		 * Moyen
		 */
		grade3: () => LocalizedString
		/**
		 * Bien
		 */
		grade4: () => LocalizedString
		/**
		 * Excellent
		 */
		grade5: () => LocalizedString
		/**
		 * Enregistrer
		 */
		save: () => LocalizedString
		/**
		 * Participation enregistrée
		 */
		saved: () => LocalizedString
		/**
		 * Commentaire (optionnel)
		 */
		comment: () => LocalizedString
	}
	homework: {
		/**
		 * Devoirs
		 */
		title: () => LocalizedString
		/**
		 * Nouveau devoir
		 */
		'new': () => LocalizedString
		/**
		 * Modifier le devoir
		 */
		edit: () => LocalizedString
		/**
		 * Détails du devoir
		 */
		details: () => LocalizedString
		/**
		 * Titre
		 */
		titleField: () => LocalizedString
		/**
		 * Description
		 */
		description: () => LocalizedString
		/**
		 * Instructions
		 */
		instructions: () => LocalizedString
		/**
		 * Date limite
		 */
		dueDate: () => LocalizedString
		/**
		 * Heure limite
		 */
		dueTime: () => LocalizedString
		/**
		 * Pièces jointes
		 */
		attachments: () => LocalizedString
		/**
		 * Ajouter une pièce jointe
		 */
		addAttachment: () => LocalizedString
		status: {
			/**
			 * Brouillon
			 */
			draft: () => LocalizedString
			/**
			 * Actif
			 */
			active: () => LocalizedString
			/**
			 * Fermé
			 */
			closed: () => LocalizedString
			/**
			 * Annulé
			 */
			cancelled: () => LocalizedString
		}
		/**
		 * Créer le devoir
		 */
		create: () => LocalizedString
		/**
		 * Mettre à jour
		 */
		update: () => LocalizedString
		/**
		 * Supprimer
		 */
		'delete': () => LocalizedString
		/**
		 * Êtes-vous sûr de vouloir supprimer ce devoir?
		 */
		confirmDelete: () => LocalizedString
		/**
		 * Aucun devoir
		 */
		noHomework: () => LocalizedString
		/**
		 * Devoir créé
		 */
		created: () => LocalizedString
		/**
		 * Devoir mis à jour
		 */
		updated: () => LocalizedString
		/**
		 * Devoir supprimé
		 */
		deleted: () => LocalizedString
		/**
		 * Devoir non trouvé
		 */
		notFound: () => LocalizedString
		/**
		 * Supprimer ce devoir ?
		 */
		deleteConfirm: () => LocalizedString
		/**
		 * Cette action est irréversible.
		 */
		deleteWarning: () => LocalizedString
		/**
		 * Publier
		 */
		publish: () => LocalizedString
		/**
		 * Clôturer
		 */
		close: () => LocalizedString
		/**
		 * En retard
		 */
		overdue: () => LocalizedString
		/**
		 * Ex: Exercices page 42...
		 */
		titlePlaceholder: () => LocalizedString
		/**
		 * Instructions pour les élèves...
		 */
		descriptionPlaceholder: () => LocalizedString
	}
	grades: {
		/**
		 * Notes
		 */
		title: () => LocalizedString
		/**
		 * Sélectionner une classe
		 */
		selectClass: () => LocalizedString
		/**
		 * Sélectionner une matière
		 */
		selectSubject: () => LocalizedString
		/**
		 * Saisir les notes
		 */
		enterGrades: () => LocalizedString
		/**
		 * En attente de validation
		 */
		pending: () => LocalizedString
		/**
		 * Validées
		 */
		validated: () => LocalizedString
		/**
		 * Rejetées
		 */
		rejected: () => LocalizedString
		/**
		 * Soumettre pour validation
		 */
		submit: () => LocalizedString
		/**
		 * Enregistrer le brouillon
		 */
		saveDraft: () => LocalizedString
		/**
		 * Aucune classe assignée
		 */
		noClasses: () => LocalizedString
		/**
		 * Aucun élève inscrit
		 */
		noStudents: () => LocalizedString
		/**
		 * Aucune note à enregistrer
		 */
		noGrades: () => LocalizedString
		/**
		 * Notes enregistrées
		 */
		saved: () => LocalizedString
		/**
		 * matières
		 */
		subjects: () => LocalizedString
		/**
		 * Interro
		 */
		quizzes: () => LocalizedString
		/**
		 * Devoir
		 */
		tests: () => LocalizedString
		/**
		 * Devoir Niv
		 */
		level_tests: () => LocalizedString
		/**
		 * Nature
		 */
		nature: () => LocalizedString
		/**
		 * Sélectionner le type
		 */
		selectType: () => LocalizedString
		/**
		 * Description
		 */
		description: () => LocalizedString
		/**
		 * Ex: Interro 1...
		 */
		egInterro1: () => LocalizedString
		/**
		 * Sans description
		 */
		noDescription: () => LocalizedString
		/**
		 * Confirmer la publication
		 */
		confirmPublishTitle: () => LocalizedString
		/**
		 * Il y a {count} élève(s) sans note. Ils recevront automatiquement la note de 0. Voulez-vous continuer ?
		 */
		confirmPublishDescription: (arg: { count: unknown }) => LocalizedString
		/**
		 * Publier maintenant
		 */
		confirmPublish: () => LocalizedString
		/**
		 * Brouillon en attente
		 */
		draftTitle: () => LocalizedString
		/**
		 * Vous avez une saisie en cours pour cette classe
		 */
		draftSubtitle: () => LocalizedString
		/**
		 * Reprendre la saisie
		 */
		resumeEntry: () => LocalizedString
		/**
		 * Publier ce brouillon
		 */
		publishDraft: () => LocalizedString
		/**
		 * Publication...
		 */
		publishing: () => LocalizedString
		/**
		 * Aucune matière trouvée pour cette classe
		 */
		noSubjects: () => LocalizedString
		/**
		 * Matière
		 */
		subject: () => LocalizedString
		/**
		 * Brouillon enregistré localement
		 */
		draftSaved: () => LocalizedString
		/**
		 * Notes publiées avec succès
		 */
		published: () => LocalizedString
		/**
		 * Échec de la publication
		 */
		publishFailed: () => LocalizedString
		/**
		 * Publier
		 */
		publish: () => LocalizedString
		/**
		 * Le titre est requis
		 */
		titleRequired: () => LocalizedString
		/**
		 * La matière est requise
		 */
		subjectRequired: () => LocalizedString
		/**
		 * Aucune période active trouvée
		 */
		noCurrentTerm: () => LocalizedString
		/**
		 * Brouillon enregistré
		 */
		savedLocally: () => LocalizedString
		/**
		 * Notes publiées
		 */
		publishedSuccess: () => LocalizedString
		/**
		 * Nvlle Notes
		 */
		addNote: () => LocalizedString
		/**
		 * Notes non publiées
		 */
		unpublishedNoteShort: () => LocalizedString
		/**
		 * Il y a {count} élève(s) sans note. Ils recevront automatiquement la note de 0. Voulez-vous continuer ?
		 */
		missingStudentsWarningPublish: (arg: { count: unknown }) => LocalizedString
		/**
		 * Coef.
		 */
		coeff: () => LocalizedString
		/**
		 * Barème
		 */
		grading: () => LocalizedString
		/**
		 * sur
		 */
		outOf: () => LocalizedString
		/**
		 * Participations
		 */
		participations: () => LocalizedString
		/**
		 * Manquants
		 */
		missing: () => LocalizedString
		/**
		 * En attente
		 */
		pendingBadge: () => LocalizedString
		/**
		 * Saisie {className} - {subjectName}
		 */
		entryTitle: (arg: { className: unknown, subjectName: unknown }) => LocalizedString
		/**
		 * Nouvelle Note
		 */
		newNoteTitle: () => LocalizedString
	}
	search: {
		/**
		 * Rechercher un élève...
		 */
		students: () => LocalizedString
	}
	messages: {
		/**
		 * Messages
		 */
		title: () => LocalizedString
		/**
		 * Boîte de réception
		 */
		inbox: () => LocalizedString
		/**
		 * Envoyés
		 */
		sent: () => LocalizedString
		/**
		 * Archivés
		 */
		archived: () => LocalizedString
		/**
		 * Nouveau message
		 */
		compose: () => LocalizedString
		/**
		 * À
		 */
		to: () => LocalizedString
		/**
		 * Objet
		 */
		subject: () => LocalizedString
		/**
		 * Message
		 */
		content: () => LocalizedString
		/**
		 * Envoyer
		 */
		send: () => LocalizedString
		/**
		 * Répondre
		 */
		reply: () => LocalizedString
		/**
		 * Archiver
		 */
		archive: () => LocalizedString
		/**
		 * Marquer
		 */
		star: () => LocalizedString
		/**
		 * Non lu
		 */
		unread: () => LocalizedString
		/**
		 * Modèles
		 */
		templates: () => LocalizedString
		/**
		 * Sélectionner un modèle
		 */
		selectTemplate: () => LocalizedString
		/**
		 * Rechercher un parent...
		 */
		searchParent: () => LocalizedString
		/**
		 * Aucun message
		 */
		noMessages: () => LocalizedString
		/**
		 * Message envoyé
		 */
		sentSuccess: () => LocalizedString
		/**
		 * Parent
		 */
		parent: () => LocalizedString
		/**
		 * Vous
		 */
		you: () => LocalizedString
		/**
		 * Expéditeur inconnu
		 */
		unknownSender: () => LocalizedString
		/**
		 * Conversation
		 */
		thread: () => LocalizedString
	}
	notifications: {
		/**
		 * Notifications
		 */
		title: () => LocalizedString
		/**
		 * Tout marquer comme lu
		 */
		markAllRead: () => LocalizedString
		/**
		 * Toutes les notifications ont été marquées comme lues
		 */
		markedAllRead: () => LocalizedString
		/**
		 * Aucune notification
		 */
		noNotifications: () => LocalizedString
		types: {
			/**
			 * Nouveau message
			 */
			message: () => LocalizedString
			/**
			 * Validation de note
			 */
			gradeValidation: () => LocalizedString
			/**
			 * Changement d'emploi du temps
			 */
			scheduleChange: () => LocalizedString
			/**
			 * Alerte de présence
			 */
			attendanceAlert: () => LocalizedString
			/**
			 * Système
			 */
			system: () => LocalizedString
			/**
			 * Rappel
			 */
			reminder: () => LocalizedString
		}
	}
	unauthorized: {
		/**
		 * Accès Non Autorisé
		 */
		title: () => LocalizedString
		/**
		 * Votre compte n'est pas associé à un établissement scolaire actif en tant qu'enseignant.
		 */
		description: () => LocalizedString
		/**
		 * Si vous pensez qu'il s'agit d'une erreur, veuillez contacter l'administrateur de votre établissement ou essayez d'actualiser la page.
		 */
		message: () => LocalizedString
	}
	common: {
		/**
		 * Chargement...
		 */
		loading: () => LocalizedString
		/**
		 * Une erreur est survenue
		 */
		error: () => LocalizedString
		/**
		 * Réessayer
		 */
		retry: () => LocalizedString
		/**
		 * Enregistrer
		 */
		save: () => LocalizedString
		/**
		 * Annuler
		 */
		cancel: () => LocalizedString
		/**
		 * Êtes-vous sûr de vouloir annuler la session? Toutes les données seront perdues.
		 */
		cancelConfirmation: () => LocalizedString
		/**
		 * Supprimer
		 */
		'delete': () => LocalizedString
		/**
		 * Modifier
		 */
		edit: () => LocalizedString
		/**
		 * Retour
		 */
		back: () => LocalizedString
		/**
		 * Rechercher...
		 */
		search: () => LocalizedString
		/**
		 * Aucun résultat
		 */
		noResults: () => LocalizedString
		/**
		 * Tirer pour actualiser
		 */
		pullToRefresh: () => LocalizedString
		/**
		 * Actualisation...
		 */
		refreshing: () => LocalizedString
		/**
		 * élèves
		 */
		students: () => LocalizedString
		/**
		 * Reprendre
		 */
		resume: () => LocalizedString
		/**
		 * Enregistré
		 */
		saved: () => LocalizedString
		/**
		 * à
		 */
		at: () => LocalizedString
		/**
		 * Élève
		 */
		student: () => LocalizedString
		/**
		 * Enseignant
		 */
		teacher: () => LocalizedString
		/**
		 * Participation
		 */
		participation: () => LocalizedString
		/**
		 * Moyenne
		 */
		average: () => LocalizedString
		/**
		 * Actualiser
		 */
		refresh: () => LocalizedString
		/**
		 * Oui
		 */
		yes: () => LocalizedString
		/**
		 * Non
		 */
		no: () => LocalizedString
		/**
		 * Non disponible
		 */
		notAvailable: () => LocalizedString
		/**
		 * Actions
		 */
		actions: () => LocalizedString
		/**
		 * Fermer
		 */
		close: () => LocalizedString
		/**
		 * Élèves
		 */
		student_plural: () => LocalizedString
		/**
		 * Actif
		 */
		active: () => LocalizedString
		/**
		 * Moyenne de classe
		 */
		classAverage: () => LocalizedString
	}
	sync: {
		/**
		 * Synchronisation
		 */
		title: () => LocalizedString
		/**
		 * Connecté
		 */
		online: () => LocalizedString
		/**
		 * Hors ligne
		 */
		offline: () => LocalizedString
		/**
		 * Synchronisé
		 */
		synced: () => LocalizedString
		/**
		 * {count} en attente
		 */
		pending: (arg: { count: unknown }) => LocalizedString
		/**
		 * Publication...
		 */
		publishing: () => LocalizedString
		/**
		 * Publication {current}/{total}
		 */
		publishingProgress: (arg: { current: unknown, total: unknown }) => LocalizedString
		/**
		 * Publier ({count})
		 */
		publishCount: (arg: { count: unknown }) => LocalizedString
		/**
		 * Publication réussie
		 */
		success: () => LocalizedString
		/**
		 * Erreurs lors de la publication
		 */
		error: () => LocalizedString
		/**
		 * {count} note(s) publiée(s)
		 */
		notesPublished: (arg: { count: unknown }) => LocalizedString
		/**
		 * {count} note(s) en échec
		 */
		notesFailed: (arg: { count: unknown }) => LocalizedString
		/**
		 * ... et {count} autres erreurs
		 */
		moreErrors: (arg: { count: unknown }) => LocalizedString
		/**
		 * {count} modification(s) en attente de publication
		 */
		pendingChanges: (arg: { count: unknown }) => LocalizedString
	}
	errors: {
		/**
		 * Non autorisé
		 */
		unauthorized: () => LocalizedString
		/**
		 * Non trouvé
		 */
		notFound: () => LocalizedString
		/**
		 * Erreur serveur
		 */
		serverError: () => LocalizedString
		/**
		 * Erreur de connexion
		 */
		networkError: () => LocalizedString
		/**
		 * Erreur de validation
		 */
		validationError: () => LocalizedString
		/**
		 * Erreur lors de l'enregistrement en base de données
		 */
		databaseSaveFailed: () => LocalizedString
		/**
		 * Erreur lors de la publication
		 */
		publishFailed: () => LocalizedString
		/**
		 * Contexte enseignant non trouvé
		 */
		teacherContextNotFound: () => LocalizedString
		/**
		 * Aucune période trouvée pour l'année scolaire en cours
		 */
		noTermFound: () => LocalizedString
		/**
		 * Session d'emploi du temps non trouvée
		 */
		sessionNotFound: () => LocalizedString
		/**
		 * Non autorisé : Vous n'êtes pas assigné à cette session
		 */
		notAssignedToSession: () => LocalizedString
		/**
		 * Classe non trouvée
		 */
		classNotFound: () => LocalizedString
	}
	auth: {
		/**
		 * Connexion
		 */
		login: () => LocalizedString
		/**
		 * Déconnexion
		 */
		logout: () => LocalizedString
		/**
		 * Email
		 */
		email: () => LocalizedString
		/**
		 * Mot de passe
		 */
		password: () => LocalizedString
		/**
		 * Mot de passe oublié?
		 */
		forgotPassword: () => LocalizedString
		/**
		 * Se connecter
		 */
		loginButton: () => LocalizedString
		/**
		 * Continuer avec Google
		 */
		loginWithGoogle: () => LocalizedString
		/**
		 * Email ou mot de passe incorrect
		 */
		invalidCredentials: () => LocalizedString
		/**
		 * enseignant@ecole.com
		 */
		emailPlaceholder: () => LocalizedString
		/**
		 * ou
		 */
		or: () => LocalizedString
	}
	class_details: {
		/**
		 * Aucun élève
		 */
		noStudents: () => LocalizedString
		/**
		 * Aucun élève n'est inscrit dans cette classe pour le moment.
		 */
		noStudentsDescription: () => LocalizedString
		/**
		 * Classe introuvable
		 */
		notFound: () => LocalizedString
		/**
		 * La classe demandée n'a pas été trouvée. Elle a peut-être été supprimée ou vous n'y avez pas accès.
		 */
		notFoundDescription: () => LocalizedString
		/**
		 * Nombre total d'élèves inscrits dans cette classe
		 */
		totalStudentsHelp: () => LocalizedString
	}
	attendance: {
		/**
		 * Présence
		 */
		title: () => LocalizedString
		/**
		 * Sélectionner la classe
		 */
		selectClass: () => LocalizedString
		/**
		 * Classe
		 */
		'class': () => LocalizedString
		/**
		 * Date
		 */
		date: () => LocalizedString
		/**
		 * Liste des élèves
		 */
		studentList: () => LocalizedString
		/**
		 * Aucun élève dans cette classe
		 */
		noStudents: () => LocalizedString
		/**
		 * Tout marquer présent
		 */
		markAllPresent: () => LocalizedString
		/**
		 * Total
		 */
		total: () => LocalizedString
		/**
		 * Présents
		 */
		present: () => LocalizedString
		/**
		 * Absents
		 */
		absent: () => LocalizedString
		/**
		 * Retards
		 */
		late: () => LocalizedString
		/**
		 * Excusés
		 */
		excused: () => LocalizedString
		/**
		 * Enregistrer
		 */
		save: () => LocalizedString
		/**
		 * Chargement...
		 */
		loading: () => LocalizedString
		/**
		 * Une erreur est survenue
		 */
		error: () => LocalizedString
		/**
		 * Réessayer
		 */
		retry: () => LocalizedString
		/**
		 * élèves
		 */
		students: () => LocalizedString
		status: {
			/**
			 * Présent
			 */
			present: () => LocalizedString
			/**
			 * Absent
			 */
			absent: () => LocalizedString
			/**
			 * Retard
			 */
			late: () => LocalizedString
			/**
			 * Excusé
			 */
			excused: () => LocalizedString
		}
		/**
		 * Historique de présence
		 */
		history: () => LocalizedString
		/**
		 * Aucun historique
		 */
		noHistory: () => LocalizedString
		stats: {
			/**
			 * Statistiques
			 */
			title: () => LocalizedString
			/**
			 * Taux de présence
			 */
			rate: () => LocalizedString
			/**
			 * Tend mensuelle
			 */
			monthlyTrend: () => LocalizedString
		}
	}
	classes: {
		/**
		 * Mes Classes
		 */
		title: () => LocalizedString
		/**
		 * Créer une classe
		 */
		create: () => LocalizedString
		/**
		 * Aucune classe trouvée
		 */
		noClasses: () => LocalizedString
		/**
		 * Créer votre première classe
		 */
		createFirst: () => LocalizedString
		/**
		 * élèves
		 */
		students: () => LocalizedString
		/**
		 * matières
		 */
		subjects: () => LocalizedString
		/**
		 * Détails de la classe
		 */
		details: () => LocalizedString
		/**
		 * Liste des élèves
		 */
		roster: () => LocalizedString
		/**
		 * Ajouter un élève
		 */
		addStudent: () => LocalizedString
		/**
		 * Retirer un élève
		 */
		removeStudent: () => LocalizedString
		/**
		 * Rechercher un élève
		 */
		searchStudent: () => LocalizedString
		/**
		 * Mon École
		 */
		defaultSchool: () => LocalizedString
		/**
		 * Aucun élève
		 */
		noStudents: () => LocalizedString
		/**
		 * Classe introuvable
		 */
		notFound: () => LocalizedString
		/**
		 * Vous n'avez pas encore de classes assignées dans cette école.
		 */
		emptyDescription: () => LocalizedString
		/**
		 * Niveau
		 */
		grade: () => LocalizedString
		/**
		 * Titulaire
		 */
		homeroom: () => LocalizedString
		/**
		 * Moyenne
		 */
		average: () => LocalizedString
		/**
		 * Grille
		 */
		grid: () => LocalizedString
		/**
		 * Liste
		 */
		list: () => LocalizedString
		/**
		 * Section
		 */
		section: () => LocalizedString
		/**
		 * Salle de classe
		 */
		classroom: () => LocalizedString
		/**
		 * Emploi du temps
		 */
		schedule: () => LocalizedString
		/**
		 * Retour aux classes
		 */
		backToClasses: () => LocalizedString
	}
	notes: {
		/**
		 * Notes de l'élève
		 */
		title: () => LocalizedString
		/**
		 * Ajouter une note
		 */
		add: () => LocalizedString
		/**
		 * Résumé du comportement
		 */
		summary: () => LocalizedString
		/**
		 * Comportement
		 */
		behavior: () => LocalizedString
		/**
		 * Académique
		 */
		academic: () => LocalizedString
		/**
		 * Prioritaires
		 */
		priority: () => LocalizedString
		/**
		 * Historique des notes
		 */
		history: () => LocalizedString
		/**
		 * Aucune note pour cet élève
		 */
		noNotes: () => LocalizedString
		/**
		 * Gérer les notes
		 */
		manage: () => LocalizedString
		types: {
			/**
			 * Comportement
			 */
			behavior: () => LocalizedString
			/**
			 * Académique
			 */
			academic: () => LocalizedString
			/**
			 * Attendance
			 */
			attendance: () => LocalizedString
			/**
			 * Général
			 */
			general: () => LocalizedString
		}
		priorityLevels: {
			/**
			 * Faible
			 */
			low: () => LocalizedString
			/**
			 * Moyen
			 */
			medium: () => LocalizedString
			/**
			 * Élevé
			 */
			high: () => LocalizedString
			/**
			 * Urgent
			 */
			urgent: () => LocalizedString
		}
		create: {
			/**
			 * Créer une note
			 */
			title: () => LocalizedString
			/**
			 * Contenu
			 */
			content: () => LocalizedString
			/**
			 * Type de note
			 */
			type: () => LocalizedString
			/**
			 * Sélectionner le type
			 */
			selectType: () => LocalizedString
			/**
			 * Priorité
			 */
			priority: () => LocalizedString
			/**
			 * Sélectionner la priorité
			 */
			selectPriority: () => LocalizedString
			/**
			 * Note privée (visible uniquement par les enseignants)
			 */
			'private': () => LocalizedString
			/**
			 * Enregistrer
			 */
			save: () => LocalizedString
			/**
			 * Annuler
			 */
			cancel: () => LocalizedString
		}
	}
	profile: {
		/**
		 * Profil
		 */
		title: () => LocalizedString
		/**
		 * Modifier le profil
		 */
		edit: () => LocalizedString
		/**
		 * Modifiez vos informations personnelles ici.
		 */
		editSubtitle: () => LocalizedString
		/**
		 * Nom complet
		 */
		fullName: () => LocalizedString
		/**
		 * Votre nom
		 */
		namePlaceholder: () => LocalizedString
		/**
		 * Enregistrer
		 */
		saveChanges: () => LocalizedString
		/**
		 * Enregistrement...
		 */
		saving: () => LocalizedString
		/**
		 * Profil mis à jour
		 */
		updated: () => LocalizedString
		/**
		 * Erreur lors de la mise à jour
		 */
		updateError: () => LocalizedString
		/**
		 * Enseignant principal
		 */
		mainTeacher: () => LocalizedString
		/**
		 * Paramètres
		 */
		settings: () => LocalizedString
		/**
		 * Compte
		 */
		account: () => LocalizedString
		/**
		 * Préférences
		 */
		preferences: () => LocalizedString
		/**
		 * Langue
		 */
		language: () => LocalizedString
		/**
		 * Thème
		 */
		theme: () => LocalizedString
		/**
		 * Notifications
		 */
		notifications: () => LocalizedString
		/**
		 * Informations du compte
		 */
		accountInfo: () => LocalizedString
		/**
		 * ID Enseignant
		 */
		teacherId: () => LocalizedString
		/**
		 * École
		 */
		schoolId: () => LocalizedString
		/**
		 * Année Scolaire
		 */
		schoolYear: () => LocalizedString
		/**
		 * Membre depuis
		 */
		memberSince: () => LocalizedString
		/**
		 * Version
		 */
		version: () => LocalizedString
		/**
		 * © {year} Yeko. Tous droits réservés.
		 */
		copyright: (arg: { year: unknown }) => LocalizedString
		themes: {
			/**
			 * Clair
			 */
			light: () => LocalizedString
			/**
			 * Sombre
			 */
			dark: () => LocalizedString
			/**
			 * Système
			 */
			system: () => LocalizedString
		}
		/**
		 * Non disponible
		 */
		notAvailable: () => LocalizedString
		/**
		 * Non définie
		 */
		notDefined: () => LocalizedString
		stats: {
			/**
			 * Écoles
			 */
			schools: () => LocalizedString
			/**
			 * Classes
			 */
			classes: () => LocalizedString
		}
	}
	schools: {
		/**
		 * Mes Établissements
		 */
		title: () => LocalizedString
		/**
		 * Aucun établissement
		 */
		emptyTitle: () => LocalizedString
		/**
		 * Vous n'êtes actuellement rattaché à aucun établissement scolaire sur Yeko. Contactez votre administrateur pour plus d'informations.
		 */
		emptyDescription: () => LocalizedString
		/**
		 * Un établissement rattaché
		 */
		attachedSchool: () => LocalizedString
		/**
		 * {count} établissements rattachés
		 */
		attachedSchools: (arg: { count: unknown }) => LocalizedString
	}
}

export type Formatters = {}
