import type { KnipConfig } from 'knip'

const config: KnipConfig = {
  entry: ['src/start.tsx', 'src/server.ts', 'src/router.tsx'],
  project: ['src/**/*.{ts,tsx}'],
  ignore: [
    // Auto-generated by typesafe-i18n
    'src/i18n/i18n-types.ts',
    'src/i18n/i18n-util.ts',
    'src/i18n/i18n-util.sync.ts',
    'src/i18n/i18n-util.async.ts',
    'src/i18n/formatters.ts',
  ],
  ignoreDependencies: [
    // Monorepo workspace packages used via Vite/Tailwind/build tooling
    '@workspace/ui',
    '@repo/data-ops',
    '@repo/logger',
    '@repo/background-tasks',
    '@yeko/eslint-config',
    // Used by @workspace/ui or Tailwind CSS v4
    'tailwindcss',
    'tw-animate-css',
    '@tailwindcss/typography',
    'class-variance-authority',
    // Used by @workspace/ui components (transitive)
    'cmdk',
    'embla-carousel-react',
    'input-otp',
    'next-themes',
    'react-day-picker',
    'react-resizable-panels',
    'vaul',
    // Transitive monorepo deps (re-exported from @repo/data-ops)
    '@praha/byethrow',
    '@base-ui/react',
    // CF Workers types — used via wrangler cf-typegen
    'cloudflare',
  ],
}

export default config
