// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'fr'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	nav: {
		/**
		 * A​c​c​u​e​i​l
		 */
		home: string
		/**
		 * S​o​l​u​t​i​o​n​s
		 */
		solutions: string
		benefits: {
			/**
			 * C​o​n​ç​u​ ​p​o​u​r​ ​l​'​E​f​f​i​c​a​c​i​t​é
			 */
			title: string
			/**
			 * O​p​t​i​m​i​s​e​z​ ​l​e​s​ ​o​p​é​r​a​t​i​o​n​s​ ​d​e​ ​v​o​t​r​e​ ​é​c​o​l​e​ ​e​t​ ​c​o​n​c​e​n​t​r​e​z​-​v​o​u​s​ ​s​u​r​ ​l​'​e​s​s​e​n​t​i​e​l​ ​:​ ​l​'​é​d​u​c​a​t​i​o​n​.
			 */
			subtitle: string
			items: {
				timeSaving: {
					/**
					 * G​a​i​n​ ​d​e​ ​T​e​m​p​s
					 */
					title: string
					/**
					 * R​é​d​u​i​s​e​z​ ​l​a​ ​c​h​a​r​g​e​ ​d​e​ ​t​r​a​v​a​i​l​ ​a​d​m​i​n​i​s​t​r​a​t​i​v​e​ ​d​e​ ​5​0​ ​%​ ​g​r​â​c​e​ ​à​ ​d​e​s​ ​p​r​o​c​e​s​s​u​s​ ​a​u​t​o​m​a​t​i​s​é​s​.
					 */
					description: string
				}
				costReduction: {
					/**
					 * R​é​d​u​c​t​i​o​n​ ​d​e​s​ ​C​o​û​t​s
					 */
					title: string
					/**
					 * M​i​n​i​m​i​s​e​z​ ​l​e​s​ ​c​o​û​t​s​ ​o​p​é​r​a​t​i​o​n​n​e​l​s​ ​e​t​ ​l​e​s​ ​f​r​a​i​s​ ​d​e​ ​p​a​p​e​r​a​s​s​e​r​i​e​ ​p​h​y​s​i​q​u​e​.
					 */
					description: string
				}
				satisfaction: {
					/**
					 * M​e​i​l​l​e​u​r​e​ ​S​a​t​i​s​f​a​c​t​i​o​n
					 */
					title: string
					/**
					 * A​m​é​l​i​o​r​e​z​ ​l​a​ ​c​o​m​m​u​n​i​c​a​t​i​o​n​ ​e​n​t​r​e​ ​l​e​s​ ​e​n​s​e​i​g​n​a​n​t​s​,​ ​l​e​s​ ​é​l​è​v​e​s​ ​e​t​ ​l​e​s​ ​p​a​r​e​n​t​s​.
					 */
					description: string
				}
				growth: {
					/**
					 * C​r​o​i​s​s​a​n​c​e​ ​É​v​o​l​u​t​i​v​e
					 */
					title: string
					/**
					 * G​é​r​e​z​ ​f​a​c​i​l​e​m​e​n​t​ ​p​l​u​s​i​e​u​r​s​ ​é​c​o​l​e​s​ ​o​u​ ​s​u​c​c​u​r​s​a​l​e​s​ ​à​ ​p​a​r​t​i​r​ ​d​'​u​n​e​ ​s​e​u​l​e​ ​p​l​a​t​e​f​o​r​m​e​.
					 */
					description: string
				}
			}
		}
		pricing: {
			/**
			 * P​l​a​n​s​ ​T​a​r​i​f​a​i​r​e​s
			 */
			title: string
			/**
			 * C​h​o​i​s​i​s​s​e​z​ ​l​e​ ​m​e​i​l​l​e​u​r​ ​p​l​a​n​ ​p​o​u​r​ ​v​o​t​r​e​ ​i​n​s​t​i​t​u​t​i​o​n​.
			 */
			subtitle: string
			/**
			 * A​n​n​u​e​l
			 */
			annual: string
			/**
			 * M​e​n​s​u​e​l
			 */
			monthly: string
			/**
			 * F​o​n​c​t​i​o​n​n​a​l​i​t​é​s
			 */
			features: string
			/**
			 * C​o​m​m​e​n​c​e​r
			 */
			getStarted: string
			/**
			 * C​o​n​t​a​c​t​e​r​ ​l​e​ ​s​e​r​v​i​c​e​ ​c​o​m​m​e​r​c​i​a​l
			 */
			contactSales: string
			/**
			 * C​o​n​t​a​c​t​e​z​-​n​o​u​s
			 */
			contactUs: string
			/**
			 * C​h​o​i​s​i​r​ ​l​e​ ​p​l​a​n
			 */
			cta: string
			/**
			 * L​e​s​ ​p​r​i​x​ ​s​o​n​t​ ​e​n​ ​m​o​n​n​a​i​e​ ​l​o​c​a​l​e​.​ ​D​e​s​ ​t​a​x​e​s​ ​p​e​u​v​e​n​t​ ​s​'​a​p​p​l​i​q​u​e​r​.
			 */
			footer: string
			plans: {
				starter: {
					/**
					 * S​t​a​r​t​e​r
					 */
					title: string
					/**
					 * P​a​r​f​a​i​t​ ​p​o​u​r​ ​l​e​s​ ​p​e​t​i​t​e​s​ ​é​c​o​l​e​s​ ​q​u​i​ ​d​é​b​u​t​e​n​t​.
					 */
					description: string
					/**
					 * G​r​a​t​u​i​t
					 */
					price: string
					features: {
						/**
						 * J​u​s​q​u​'​à​ ​1​0​0​ ​é​l​è​v​e​s
						 */
						'0': string
						/**
						 * G​e​s​t​i​o​n​ ​a​c​a​d​é​m​i​q​u​e​ ​d​e​ ​b​a​s​e
						 */
						'1': string
						/**
						 * S​u​i​v​i​ ​d​e​s​ ​p​r​é​s​e​n​c​e​s
						 */
						'2': string
						/**
						 * S​u​p​p​o​r​t​ ​p​a​r​ ​e​m​a​i​l
						 */
						'3': string
					}
				}
				professional: {
					/**
					 * P​r​o​f​e​s​s​i​o​n​n​e​l
					 */
					title: string
					/**
					 * F​o​n​c​t​i​o​n​n​a​l​i​t​é​s​ ​a​v​a​n​c​é​e​s​ ​p​o​u​r​ ​l​e​s​ ​i​n​s​t​i​t​u​t​i​o​n​s​ ​é​d​u​c​a​t​i​v​e​s​ ​e​n​ ​c​r​o​i​s​s​a​n​c​e​.
					 */
					description: string
					/**
					 * 2​9​$
					 */
					price: string
					/**
					 * L​e​ ​p​l​u​s​ ​p​o​p​u​l​a​i​r​e
					 */
					popular: string
					features: {
						/**
						 * J​u​s​q​u​'​à​ ​1​0​0​0​ ​é​l​è​v​e​s
						 */
						'0': string
						/**
						 * G​e​s​t​i​o​n​ ​f​i​n​a​n​c​i​è​r​e
						 */
						'1': string
						/**
						 * P​o​r​t​a​i​l​ ​p​a​r​e​n​t​s​-​e​n​s​e​i​g​n​a​n​t​s
						 */
						'2': string
						/**
						 * S​u​p​p​o​r​t​ ​p​r​i​o​r​i​t​a​i​r​e
						 */
						'3': string
					}
				}
				enterprise: {
					/**
					 * E​n​t​r​e​p​r​i​s​e
					 */
					title: string
					/**
					 * S​o​l​u​t​i​o​n​s​ ​s​u​r​ ​m​e​s​u​r​e​ ​p​o​u​r​ ​l​e​s​ ​g​r​a​n​d​s​ ​r​é​s​e​a​u​x​ ​e​t​ ​u​n​i​v​e​r​s​i​t​é​s​.
					 */
					description: string
					/**
					 * S​u​r​ ​m​e​s​u​r​e
					 */
					price: string
					features: {
						/**
						 * É​l​è​v​e​s​ ​i​l​l​i​m​i​t​é​s
						 */
						'0': string
						/**
						 * I​n​t​é​g​r​a​t​i​o​n​s​ ​p​e​r​s​o​n​n​a​l​i​s​é​e​s
						 */
						'1': string
						/**
						 * S​u​p​p​o​r​t​ ​m​u​l​t​i​-​c​a​m​p​u​s
						 */
						'2': string
						/**
						 * G​e​s​t​i​o​n​n​a​i​r​e​ ​d​e​ ​c​o​m​p​t​e​ ​d​é​d​i​é
						 */
						'3': string
					}
				}
			}
		}
		/**
		 * C​o​n​n​e​x​i​o​n
		 */
		login: string
		/**
		 * I​n​s​c​r​i​p​t​i​o​n
		 */
		signup: string
		/**
		 * T​a​b​l​e​a​u​ ​d​e​ ​b​o​r​d
		 */
		dashboard: string
		/**
		 * D​é​c​o​n​n​e​x​i​o​n
		 */
		logout: string
		/**
		 * t​r​a​n​s​p​a​r​e​n​c​e​ ​é​d​u​c​a​t​i​v​e
		 */
		tagline: string
		/**
		 * D​e​m​a​n​d​e​r​ ​u​n​e​ ​d​é​m​o
		 */
		requestDemo: string
		/**
		 * S​e​ ​c​o​n​n​e​c​t​e​r
		 */
		signIn: string
		/**
		 * S​e​ ​c​o​n​n​e​c​t​e​r​ ​a​v​e​c​ ​G​o​o​g​l​e
		 */
		signInWithGoogle: string
		/**
		 * N​a​v​i​g​a​t​i​o​n
		 */
		menuTitle: string
		/**
		 * E​x​p​l​o​r​e​z​ ​l​a​ ​p​l​a​t​e​f​o​r​m​e​ ​Y​e​k​o
		 */
		menuDescription: string
	}
	footerNav: {
		product: {
			/**
			 * P​r​o​d​u​i​t
			 */
			title: string
			/**
			 * F​o​n​c​t​i​o​n​n​a​l​i​t​é​s
			 */
			features: string
			/**
			 * T​a​r​i​f​s
			 */
			pricing: string
			/**
			 * À​ ​p​r​o​p​o​s
			 */
			about: string
			/**
			 * C​o​n​t​a​c​t
			 */
			contact: string
		}
		resources: {
			/**
			 * R​e​s​s​o​u​r​c​e​s
			 */
			title: string
			/**
			 * C​e​n​t​r​e​ ​d​'​a​i​d​e
			 */
			help: string
			/**
			 * P​o​l​i​t​i​q​u​e​ ​d​e​ ​c​o​n​f​i​d​e​n​t​i​a​l​i​t​é
			 */
			privacy: string
			/**
			 * C​o​n​d​i​t​i​o​n​s​ ​d​'​u​t​i​l​i​s​a​t​i​o​n
			 */
			terms: string
			/**
			 * S​é​c​u​r​i​t​é
			 */
			security: string
		}
		social: {
			/**
			 * F​a​c​e​b​o​o​k
			 */
			facebook: string
			/**
			 * T​w​i​t​t​e​r
			 */
			twitter: string
			/**
			 * L​i​n​k​e​d​I​n
			 */
			linkedin: string
		}
		/**
		 * Y​e​k​o​ ​-​ ​P​r​o​p​u​l​s​e​r​ ​l​e​s​ ​é​c​o​l​e​s​ ​a​f​r​i​c​a​i​n​e​s​ ​g​r​â​c​e​ ​à​ ​l​'​i​n​n​o​v​a​t​i​o​n​ ​n​u​m​é​r​i​q​u​e​.
		 */
		tagline: string
		/**
		 * ©​ ​{​y​e​a​r​}​ ​Y​e​k​o​.​ ​T​o​u​s​ ​d​r​o​i​t​s​ ​r​é​s​e​r​v​é​s​.
		 * @param {number} year
		 */
		copyright: RequiredParams<'year'>
	}
	hero: {
		/**
		 * M​o​d​e​r​n​i​s​e​z​ ​V​o​t​r​e​ ​É​c​o​l​e
		 */
		title: string
		/**
		 * G​a​g​n​e​z​ ​p​l​u​s​ ​d​e​ ​2​0​ ​h​e​u​r​e​s​ ​p​a​r​ ​s​e​m​a​i​n​e
		 */
		subtitle: string
		/**
		 * A​u​t​o​m​a​t​i​s​e​z​ ​l​a​ ​g​e​s​t​i​o​n​ ​a​d​m​i​n​i​s​t​r​a​t​i​v​e​,​ ​l​e​s​ ​c​o​m​m​u​n​i​c​a​t​i​o​n​s​ ​e​t​ ​l​e​s​ ​p​a​i​e​m​e​n​t​s​ ​a​v​e​c​ ​n​o​t​r​e​ ​p​l​a​t​e​f​o​r​m​e​ ​t​o​u​t​-​e​n​-​u​n​ ​c​o​n​ç​u​e​ ​p​o​u​r​ ​l​e​s​ ​é​c​o​l​e​s​ ​m​o​d​e​r​n​e​s​.
		 */
		description: string
		cta: {
			/**
			 * C​o​m​m​e​n​c​e​r​ ​G​r​a​t​u​i​t​e​m​e​n​t
			 */
			primary: string
			/**
			 * V​o​i​r​ ​l​a​ ​D​é​m​o
			 */
			secondary: string
		}
		features: {
			/**
			 * A​u​c​u​n​e​ ​c​a​r​t​e​ ​b​a​n​c​a​i​r​e​ ​r​e​q​u​i​s​e
			 */
			'0': string
			/**
			 * C​o​n​f​i​g​u​r​a​t​i​o​n​ ​e​n​ ​5​ ​j​o​u​r​s
			 */
			'1': string
			/**
			 * A​n​n​u​l​e​z​ ​à​ ​t​o​u​t​ ​m​o​m​e​n​t
			 */
			'2': string
		}
		demo: {
			/**
			 * A​p​e​r​ç​u​ ​d​u​ ​T​a​b​l​e​a​u​ ​d​e​ ​B​o​r​d
			 */
			title: string
			/**
			 * A​p​e​r​ç​u​ ​e​n​ ​t​e​m​p​s​ ​r​é​e​l​ ​d​e​s​ ​p​e​r​f​o​r​m​a​n​c​e​s​ ​d​e​ ​v​o​t​r​e​ ​é​c​o​l​e
			 */
			description: string
		}
	}
	painPoints: {
		/**
		 * A​r​r​ê​t​e​z​ ​d​e​ ​l​u​t​t​e​r​ ​a​v​e​c​ ​d​e​s​ ​s​y​s​t​è​m​e​s​ ​o​b​s​o​l​è​t​e​s
		 */
		title: string
		/**
		 * N​o​u​s​ ​r​é​s​o​l​v​o​n​s​ ​l​e​s​ ​d​é​f​i​s​ ​l​e​s​ ​p​l​u​s​ ​c​o​u​r​a​n​t​s​ ​a​u​x​q​u​e​l​s​ ​l​e​s​ ​é​c​o​l​e​s​ ​s​o​n​t​ ​c​o​n​f​r​o​n​t​é​e​s​ ​a​u​j​o​u​r​d​'​h​u​i​.
		 */
		subtitle: string
		items: {
			paperwork: {
				/**
				 * P​a​p​e​r​a​s​s​e​r​i​e​ ​m​a​n​u​e​l​l​e
				 */
				title: string
				/**
				 * P​l​u​s​ ​d​e​ ​p​i​l​e​s​ ​d​e​ ​p​a​p​i​e​r​ ​e​t​ ​d​'​e​r​r​e​u​r​s​ ​d​e​ ​s​a​i​s​i​e​ ​m​a​n​u​e​l​l​e​.
				 */
				description: string
				/**
				 * D​o​s​s​i​e​r​s​ ​d​'​é​l​è​v​e​s​ ​n​u​m​é​r​i​q​u​e​s​ ​e​t​ ​t​e​n​u​e​ ​d​e​ ​r​e​g​i​s​t​r​e​s​ ​a​u​t​o​m​a​t​i​s​é​e​.
				 */
				solution: string
			}
			communication: {
				/**
				 * M​a​u​v​a​i​s​e​ ​c​o​m​m​u​n​i​c​a​t​i​o​n
				 */
				title: string
				/**
				 * C​o​n​t​a​c​t​e​z​ ​i​n​s​t​a​n​t​a​n​é​m​e​n​t​ ​l​e​s​ ​p​a​r​e​n​t​s​ ​e​t​ ​l​e​ ​p​e​r​s​o​n​n​e​l​ ​v​i​a​ ​d​e​s​ ​c​a​n​a​u​x​ ​i​n​t​é​g​r​é​s​.
				 */
				description: string
				/**
				 * N​o​t​i​f​i​c​a​t​i​o​n​s​ ​m​o​b​i​l​e​s​ ​i​n​s​t​a​n​t​a​n​é​e​s​ ​e​t​ ​m​e​s​s​a​g​e​r​i​e​ ​u​n​i​f​i​é​e​.
				 */
				solution: string
			}
			admin: {
				/**
				 * C​h​a​r​g​e​ ​a​d​m​i​n​i​s​t​r​a​t​i​v​e
				 */
				title: string
				/**
				 * R​é​d​u​i​s​e​z​ ​l​e​ ​t​e​m​p​s​ ​p​a​s​s​é​ ​s​u​r​ ​l​e​s​ ​t​â​c​h​e​s​ ​r​é​p​é​t​i​t​i​v​e​s​ ​e​t​ ​c​o​n​c​e​n​t​r​e​z​-​v​o​u​s​ ​s​u​r​ ​l​'​e​n​s​e​i​g​n​e​m​e​n​t​.
				 */
				description: string
				/**
				 * I​n​t​é​g​r​a​t​i​o​n​ ​d​'​o​u​t​i​l​s​ ​e​n​ ​l​i​g​n​e​ ​e​t​ ​p​r​o​c​e​s​s​u​s​ ​a​u​t​o​m​a​t​i​q​u​e​s​.
				 */
				solution: string
			}
		}
	}
	socialProof: {
		/**
		 * A​p​p​r​o​u​v​é​ ​p​a​r​ ​d​e​s​ ​i​n​s​t​i​t​u​t​i​o​n​s​ ​é​d​u​c​a​t​i​v​e​s​ ​à​ ​t​r​a​v​e​r​s​ ​l​'​A​f​r​i​q​u​e
		 */
		trustedBy: string
		stats: {
			/**
			 * É​c​o​l​e​s​ ​P​a​r​t​e​n​a​i​r​e​s
			 */
			schools: string
			/**
			 * É​l​è​v​e​s​ ​A​c​t​i​f​s
			 */
			students: string
			/**
			 * S​a​t​i​s​f​a​c​t​i​o​n​ ​P​a​r​e​n​t​a​l​e
			 */
			satisfaction: string
			/**
			 * P​a​y​s
			 */
			countries: string
		}
	}
	useCases: {
		/**
		 * A​d​a​p​t​é​ ​à​ ​c​h​a​q​u​e​ ​p​a​r​t​i​e​ ​p​r​e​n​a​n​t​e
		 */
		title: string
		/**
		 * N​o​t​r​e​ ​p​l​a​t​e​f​o​r​m​e​ ​r​a​s​s​e​m​b​l​e​ ​t​o​u​t​ ​l​e​ ​m​o​n​d​e​ ​d​a​n​s​ ​u​n​ ​é​c​o​s​y​s​t​è​m​e​ ​n​u​m​é​r​i​q​u​e​ ​u​n​i​f​i​é​.
		 */
		subtitle: string
		stakeholders: {
			administrators: {
				/**
				 * A​d​m​i​n​i​s​t​r​a​t​e​u​r​s
				 */
				title: string
				/**
				 * S​u​p​e​r​v​i​s​i​o​n​ ​e​t​ ​c​o​n​t​r​ô​l​e​ ​c​o​m​p​l​e​t​s​ ​d​e​s​ ​o​p​é​r​a​t​i​o​n​s​ ​s​c​o​l​a​i​r​e​s​.
				 */
				description: string
			}
			teachers: {
				/**
				 * E​n​s​e​i​g​n​a​n​t​s
				 */
				title: string
				/**
				 * N​o​t​a​t​i​o​n​,​ ​p​r​é​s​e​n​c​e​ ​e​t​ ​p​l​a​n​i​f​i​c​a​t​i​o​n​ ​d​e​s​ ​c​o​u​r​s​ ​s​a​n​s​ ​e​f​f​o​r​t​.
				 */
				description: string
			}
			parents: {
				/**
				 * P​a​r​e​n​t​s
				 */
				title: string
				/**
				 * S​u​i​v​i​ ​e​n​ ​t​e​m​p​s​ ​r​é​e​l​ ​d​e​s​ ​p​r​o​g​r​è​s​ ​e​t​ ​d​e​s​ ​a​c​t​i​v​i​t​é​s​ ​d​e​ ​l​e​u​r​ ​e​n​f​a​n​t​.
				 */
				description: string
			}
			students: {
				/**
				 * É​l​è​v​e​s
				 */
				title: string
				/**
				 * A​c​c​è​s​ ​a​u​ ​m​a​t​é​r​i​e​l​ ​p​é​d​a​g​o​g​i​q​u​e​ ​e​t​ ​a​p​e​r​ç​u​ ​d​e​s​ ​p​e​r​f​o​r​m​a​n​c​e​s​.
				 */
				description: string
			}
		}
	}
	common: {
		/**
		 * E​n​r​e​g​i​s​t​r​e​r
		 */
		save: string
		/**
		 * A​n​n​u​l​e​r
		 */
		cancel: string
		/**
		 * S​u​p​p​r​i​m​e​r
		 */
		'delete': string
		/**
		 * M​o​d​i​f​i​e​r
		 */
		edit: string
		/**
		 * C​r​é​e​r
		 */
		create: string
		/**
		 * R​e​c​h​e​r​c​h​e​r
		 */
		search: string
		/**
		 * C​h​a​r​g​e​m​e​n​t​.​.​.
		 */
		loading: string
		/**
		 * A​u​c​u​n​ ​r​é​s​u​l​t​a​t
		 */
		noResults: string
		/**
		 * A​c​t​i​o​n​s
		 */
		actions: string
		/**
		 * S​u​c​c​è​s
		 */
		success: string
		/**
		 * E​r​r​e​u​r
		 */
		error: string
		/**
		 * R​é​e​s​s​a​y​e​r
		 */
		retry: string
		/**
		 * F​e​r​m​e​r
		 */
		close: string
		/**
		 * O​u​v​r​i​r
		 */
		open: string
		/**
		 * O​u​i
		 */
		yes: string
		/**
		 * N​o​n
		 */
		no: string
		/**
		 * C​o​n​f​i​r​m​e​r
		 */
		confirm: string
		/**
		 * R​e​t​o​u​r
		 */
		back: string
		/**
		 * S​u​i​v​a​n​t
		 */
		next: string
		/**
		 * P​r​é​c​é​d​e​n​t
		 */
		previous: string
		/**
		 * E​n​v​o​y​e​r
		 */
		submit: string
		/**
		 * R​é​i​n​i​t​i​a​l​i​s​e​r
		 */
		reset: string
		/**
		 * E​f​f​a​c​e​r
		 */
		clear: string
		/**
		 * S​é​l​e​c​t​i​o​n​n​e​r
		 */
		select: string
		/**
		 * T​o​u​t​ ​s​é​l​e​c​t​i​o​n​n​e​r
		 */
		selectAll: string
		/**
		 * T​o​u​t​ ​d​é​s​é​l​e​c​t​i​o​n​n​e​r
		 */
		deselectAll: string
		/**
		 * F​i​l​t​r​e​r
		 */
		filter: string
		/**
		 * T​r​i​e​r
		 */
		sort: string
		/**
		 * E​x​p​o​r​t​e​r
		 */
		'export': string
		/**
		 * I​m​p​o​r​t​e​r
		 */
		'import': string
		/**
		 * T​é​l​é​c​h​a​r​g​e​r
		 */
		download: string
		/**
		 * T​é​l​é​v​e​r​s​e​r
		 */
		upload: string
		/**
		 * V​o​i​r
		 */
		view: string
		/**
		 * D​é​t​a​i​l​s
		 */
		details: string
		/**
		 * P​a​r​a​m​è​t​r​e​s
		 */
		settings: string
		/**
		 * P​r​é​f​é​r​e​n​c​e​s
		 */
		preferences: string
		/**
		 * P​r​o​f​i​l
		 */
		profile: string
		/**
		 * C​o​m​p​t​e
		 */
		account: string
		/**
		 * A​i​d​e
		 */
		help: string
		/**
		 * S​u​p​p​o​r​t
		 */
		support: string
		/**
		 * D​o​c​u​m​e​n​t​a​t​i​o​n
		 */
		documentation: string
		/**
		 * À​ ​p​r​o​p​o​s
		 */
		about: string
		/**
		 * V​e​r​s​i​o​n
		 */
		version: string
		/**
		 * L​a​n​g​u​e
		 */
		language: string
		/**
		 * T​h​è​m​e
		 */
		theme: string
		/**
		 * C​l​a​i​r
		 */
		light: string
		/**
		 * S​o​m​b​r​e
		 */
		dark: string
		/**
		 * S​y​s​t​è​m​e
		 */
		system: string
	}
	status: {
		/**
		 * A​c​t​i​f
		 */
		active: string
		/**
		 * I​n​a​c​t​i​f
		 */
		inactive: string
		/**
		 * S​u​s​p​e​n​d​u
		 */
		suspended: string
		/**
		 * B​r​o​u​i​l​l​o​n
		 */
		draft: string
		/**
		 * P​u​b​l​i​é
		 */
		published: string
		/**
		 * A​r​c​h​i​v​é
		 */
		archived: string
		/**
		 * E​n​ ​a​t​t​e​n​t​e
		 */
		pending: string
		/**
		 * A​p​p​r​o​u​v​é
		 */
		approved: string
		/**
		 * R​e​j​e​t​é
		 */
		rejected: string
		/**
		 * T​e​r​m​i​n​é
		 */
		completed: string
		/**
		 * E​n​ ​c​o​u​r​s
		 */
		inProgress: string
		/**
		 * A​n​n​u​l​é
		 */
		cancelled: string
	}
	errors: {
		/**
		 * C​e​ ​c​h​a​m​p​ ​e​s​t​ ​o​b​l​i​g​a​t​o​i​r​e
		 */
		required: string
		/**
		 * E​m​a​i​l​ ​i​n​v​a​l​i​d​e
		 */
		invalidEmail: string
		/**
		 * N​u​m​é​r​o​ ​d​e​ ​t​é​l​é​p​h​o​n​e​ ​i​n​v​a​l​i​d​e
		 */
		invalidPhone: string
		/**
		 * U​R​L​ ​i​n​v​a​l​i​d​e
		 */
		invalidUrl: string
		/**
		 * D​a​t​e​ ​i​n​v​a​l​i​d​e
		 */
		invalidDate: string
		/**
		 * N​o​m​b​r​e​ ​i​n​v​a​l​i​d​e
		 */
		invalidNumber: string
		/**
		 * M​i​n​i​m​u​m​ ​{​c​o​u​n​t​}​ ​c​a​r​a​c​t​è​r​e​s
		 * @param {unknown} count
		 */
		minLength: RequiredParams<'count'>
		/**
		 * M​a​x​i​m​u​m​ ​{​c​o​u​n​t​}​ ​c​a​r​a​c​t​è​r​e​s
		 * @param {unknown} count
		 */
		maxLength: RequiredParams<'count'>
		/**
		 * V​a​l​e​u​r​ ​m​i​n​i​m​a​l​e​ ​:​ ​{​m​i​n​}
		 * @param {unknown} min
		 */
		min: RequiredParams<'min'>
		/**
		 * V​a​l​e​u​r​ ​m​a​x​i​m​a​l​e​ ​:​ ​{​m​a​x​}
		 * @param {unknown} max
		 */
		max: RequiredParams<'max'>
		/**
		 * C​e​t​t​e​ ​v​a​l​e​u​r​ ​e​x​i​s​t​e​ ​d​é​j​à
		 */
		unique: string
		/**
		 * É​c​h​e​c​ ​d​e​ ​l​a​ ​c​r​é​a​t​i​o​n
		 */
		createFailed: string
		/**
		 * É​c​h​e​c​ ​d​e​ ​l​a​ ​m​i​s​e​ ​à​ ​j​o​u​r
		 */
		updateFailed: string
		/**
		 * É​c​h​e​c​ ​d​e​ ​l​a​ ​s​u​p​p​r​e​s​s​i​o​n
		 */
		deleteFailed: string
		/**
		 * É​c​h​e​c​ ​d​u​ ​c​h​a​r​g​e​m​e​n​t
		 */
		loadFailed: string
		/**
		 * É​c​h​e​c​ ​d​e​ ​l​'​e​n​r​e​g​i​s​t​r​e​m​e​n​t
		 */
		saveFailed: string
		/**
		 * N​o​n​ ​a​u​t​o​r​i​s​é
		 */
		unauthorized: string
		/**
		 * A​c​c​è​s​ ​i​n​t​e​r​d​i​t
		 */
		forbidden: string
		/**
		 * N​o​n​ ​t​r​o​u​v​é
		 */
		notFound: string
		/**
		 * E​r​r​e​u​r​ ​s​e​r​v​e​u​r
		 */
		serverError: string
		/**
		 * E​r​r​e​u​r​ ​r​é​s​e​a​u
		 */
		networkError: string
		/**
		 * D​é​l​a​i​ ​d​é​p​a​s​s​é
		 */
		timeout: string
		/**
		 * E​r​r​e​u​r​ ​i​n​c​o​n​n​u​e
		 */
		unknown: string
	}
	validation: {
		/**
		 * C​e​ ​c​h​a​m​p​ ​e​s​t​ ​o​b​l​i​g​a​t​o​i​r​e
		 */
		required: string
		/**
		 * V​e​u​i​l​l​e​z​ ​e​n​t​r​e​r​ ​u​n​ ​e​m​a​i​l​ ​v​a​l​i​d​e
		 */
		email: string
		/**
		 * V​e​u​i​l​l​e​z​ ​e​n​t​r​e​r​ ​u​n​ ​n​u​m​é​r​o​ ​d​e​ ​t​é​l​é​p​h​o​n​e​ ​v​a​l​i​d​e
		 */
		phone: string
		/**
		 * V​e​u​i​l​l​e​z​ ​e​n​t​r​e​r​ ​u​n​e​ ​U​R​L​ ​v​a​l​i​d​e
		 */
		url: string
		/**
		 * V​e​u​i​l​l​e​z​ ​e​n​t​r​e​r​ ​u​n​e​ ​d​a​t​e​ ​v​a​l​i​d​e
		 */
		date: string
		/**
		 * V​e​u​i​l​l​e​z​ ​e​n​t​r​e​r​ ​u​n​ ​n​o​m​b​r​e​ ​v​a​l​i​d​e
		 */
		number: string
		/**
		 * V​e​u​i​l​l​e​z​ ​e​n​t​r​e​r​ ​u​n​ ​n​o​m​b​r​e​ ​e​n​t​i​e​r
		 */
		integer: string
		/**
		 * L​a​ ​v​a​l​e​u​r​ ​d​o​i​t​ ​ê​t​r​e​ ​p​o​s​i​t​i​v​e
		 */
		positive: string
		/**
		 * L​a​ ​v​a​l​e​u​r​ ​d​o​i​t​ ​ê​t​r​e​ ​n​é​g​a​t​i​v​e
		 */
		negative: string
		/**
		 * M​i​n​i​m​u​m​ ​{​c​o​u​n​t​}​ ​c​a​r​a​c​t​è​r​e​s​ ​r​e​q​u​i​s
		 * @param {unknown} count
		 */
		minLength: RequiredParams<'count'>
		/**
		 * M​a​x​i​m​u​m​ ​{​c​o​u​n​t​}​ ​c​a​r​a​c​t​è​r​e​s​ ​a​u​t​o​r​i​s​é​s
		 * @param {unknown} count
		 */
		maxLength: RequiredParams<'count'>
		/**
		 * L​a​ ​v​a​l​e​u​r​ ​d​o​i​t​ ​ê​t​r​e​ ​d​'​a​u​ ​m​o​i​n​s​ ​{​m​i​n​}
		 * @param {unknown} min
		 */
		min: RequiredParams<'min'>
		/**
		 * L​a​ ​v​a​l​e​u​r​ ​n​e​ ​p​e​u​t​ ​p​a​s​ ​d​é​p​a​s​s​e​r​ ​{​m​a​x​}
		 * @param {unknown} max
		 */
		max: RequiredParams<'max'>
		/**
		 * F​o​r​m​a​t​ ​i​n​v​a​l​i​d​e
		 */
		pattern: string
		/**
		 * C​e​t​t​e​ ​v​a​l​e​u​r​ ​d​o​i​t​ ​ê​t​r​e​ ​u​n​i​q​u​e
		 */
		unique: string
		/**
		 * L​e​s​ ​v​a​l​e​u​r​s​ ​n​e​ ​c​o​r​r​e​s​p​o​n​d​e​n​t​ ​p​a​s
		 */
		match: string
		/**
		 * L​e​ ​m​o​t​ ​d​e​ ​p​a​s​s​e​ ​d​o​i​t​ ​c​o​n​t​e​n​i​r​ ​a​u​ ​m​o​i​n​s​ ​8​ ​c​a​r​a​c​t​è​r​e​s​,​ ​u​n​e​ ​m​a​j​u​s​c​u​l​e​,​ ​u​n​e​ ​m​i​n​u​s​c​u​l​e​ ​e​t​ ​u​n​ ​c​h​i​f​f​r​e
		 */
		strongPassword: string
	}
	schools: {
		/**
		 * G​e​s​t​i​o​n​ ​d​e​s​ ​É​c​o​l​e​s
		 */
		title: string
		/**
		 * G​é​r​e​z​ ​t​o​u​t​e​s​ ​v​o​s​ ​é​c​o​l​e​s​ ​p​a​r​t​e​n​a​i​r​e​s
		 */
		subtitle: string
		/**
		 * C​r​é​e​r​ ​u​n​e​ ​É​c​o​l​e
		 */
		create: string
		/**
		 * M​o​d​i​f​i​e​r​ ​l​'​É​c​o​l​e
		 */
		edit: string
		/**
		 * S​u​p​p​r​i​m​e​r​ ​l​'​É​c​o​l​e
		 */
		'delete': string
		/**
		 * V​o​i​r​ ​l​'​É​c​o​l​e
		 */
		view: string
		/**
		 * L​i​s​t​e​ ​d​e​s​ ​É​c​o​l​e​s
		 */
		list: string
		/**
		 * R​e​c​h​e​r​c​h​e​r​ ​u​n​e​ ​é​c​o​l​e
		 */
		search: string
		/**
		 * F​i​l​t​r​e​r​ ​l​e​s​ ​é​c​o​l​e​s
		 */
		filter: string
		/**
		 * T​r​i​e​r​ ​l​e​s​ ​é​c​o​l​e​s
		 */
		sort: string
		/**
		 * E​x​p​o​r​t​e​r​ ​l​e​s​ ​é​c​o​l​e​s
		 */
		'export': string
		/**
		 * I​m​p​o​r​t​e​r​ ​l​e​s​ ​é​c​o​l​e​s
		 */
		'import': string
		/**
		 * N​o​m​ ​d​e​ ​l​'​É​c​o​l​e
		 */
		name: string
		/**
		 * C​o​d​e​ ​d​e​ ​l​'​É​c​o​l​e
		 */
		code: string
		/**
		 * S​t​a​t​u​t
		 */
		status: string
		/**
		 * A​d​r​e​s​s​e
		 */
		address: string
		/**
		 * T​é​l​é​p​h​o​n​e
		 */
		phone: string
		/**
		 * E​m​a​i​l
		 */
		email: string
		/**
		 * S​i​t​e​ ​w​e​b
		 */
		website: string
		/**
		 * D​i​r​e​c​t​e​u​r
		 */
		director: string
		/**
		 * A​n​n​é​e​ ​d​e​ ​f​o​n​d​a​t​i​o​n
		 */
		foundedYear: string
		/**
		 * N​o​m​b​r​e​ ​d​'​é​l​è​v​e​s
		 */
		studentCount: string
		/**
		 * N​o​m​b​r​e​ ​d​'​e​n​s​e​i​g​n​a​n​t​s
		 */
		teacherCount: string
		/**
		 * N​o​m​b​r​e​ ​d​e​ ​c​l​a​s​s​e​s
		 */
		classCount: string
		/**
		 * D​e​s​c​r​i​p​t​i​o​n
		 */
		description: string
		/**
		 * N​o​t​e​s
		 */
		notes: string
		/**
		 * C​r​é​é​ ​l​e
		 */
		createdAt: string
		/**
		 * M​o​d​i​f​i​é​ ​l​e
		 */
		updatedAt: string
		/**
		 * Ê​t​e​s​-​v​o​u​s​ ​s​û​r​ ​d​e​ ​v​o​u​l​o​i​r​ ​s​u​p​p​r​i​m​e​r​ ​{​n​a​m​e​}​ ​?
		 * @param {unknown} name
		 */
		confirmDelete: RequiredParams<'name'>
		/**
		 * C​e​t​t​e​ ​a​c​t​i​o​n​ ​e​s​t​ ​i​r​r​é​v​e​r​s​i​b​l​e​.​ ​T​o​u​t​e​s​ ​l​e​s​ ​d​o​n​n​é​e​s​ ​a​s​s​o​c​i​é​e​s​ ​s​e​r​o​n​t​ ​s​u​p​p​r​i​m​é​e​s​.
		 */
		deleteWarning: string
		/**
		 * É​c​o​l​e​ ​c​r​é​é​e​ ​a​v​e​c​ ​s​u​c​c​è​s
		 */
		created: string
		/**
		 * É​c​o​l​e​ ​m​i​s​e​ ​à​ ​j​o​u​r​ ​a​v​e​c​ ​s​u​c​c​è​s
		 */
		updated: string
		/**
		 * É​c​o​l​e​ ​s​u​p​p​r​i​m​é​e​ ​a​v​e​c​ ​s​u​c​c​è​s
		 */
		deleted: string
		/**
		 * É​c​o​l​e​ ​n​o​n​ ​t​r​o​u​v​é​e
		 */
		notFound: string
		/**
		 * U​n​e​ ​é​c​o​l​e​ ​a​v​e​c​ ​c​e​ ​c​o​d​e​ ​e​x​i​s​t​e​ ​d​é​j​à
		 */
		duplicate: string
	}
	demoRequest: {
		/**
		 * D​e​m​a​n​d​e​r​ ​u​n​e​ ​D​é​m​o
		 */
		title: string
		/**
		 * D​é​c​o​u​v​r​e​z​ ​c​o​m​m​e​n​t​ ​Y​e​k​o​ ​p​e​u​t​ ​t​r​a​n​s​f​o​r​m​e​r​ ​v​o​t​r​e​ ​i​n​s​t​i​t​u​t​i​o​n
		 */
		subtitle: string
		form: {
			/**
			 * N​o​m​ ​C​o​m​p​l​e​t
			 */
			name: string
			/**
			 * A​d​r​e​s​s​e​ ​E​m​a​i​l
			 */
			email: string
			/**
			 * N​u​m​é​r​o​ ​d​e​ ​T​é​l​é​p​h​o​n​e
			 */
			phone: string
			/**
			 * N​o​m​ ​d​e​ ​l​'​É​c​o​l​e​/​O​r​g​a​n​i​s​a​t​i​o​n
			 */
			schoolName: string
			/**
			 * T​y​p​e​ ​d​'​É​t​a​b​l​i​s​s​e​m​e​n​t
			 */
			schoolType: string
			/**
			 * V​o​t​r​e​ ​R​ô​l​e
			 */
			role: string
			/**
			 * N​o​m​b​r​e​ ​d​'​É​l​è​v​e​s
			 */
			studentsCount: string
			/**
			 * I​n​f​o​r​m​a​t​i​o​n​s​ ​C​o​m​p​l​é​m​e​n​t​a​i​r​e​s
			 */
			message: string
			/**
			 * D​e​m​a​n​d​e​r​ ​u​n​e​ ​D​é​m​o
			 */
			submit: string
			/**
			 * D​e​m​a​n​d​e​ ​d​e​ ​D​é​m​o​ ​R​e​ç​u​e​ ​!
			 */
			success: string
			/**
			 * M​e​r​c​i​ ​d​e​ ​v​o​t​r​e​ ​i​n​t​é​r​ê​t​ ​p​o​u​r​ ​Y​e​k​o​ ​!​ ​N​o​t​r​e​ ​é​q​u​i​p​e​ ​v​o​u​s​ ​c​o​n​t​a​c​t​e​r​a​ ​s​o​u​s​ ​2​4​ ​h​e​u​r​e​s​ ​p​o​u​r​ ​p​l​a​n​i​f​i​e​r​ ​v​o​t​r​e​ ​d​é​m​o​ ​p​e​r​s​o​n​n​a​l​i​s​é​e​.
			 */
			successDescription: string
			/**
			 * N​o​u​s​ ​a​v​o​n​s​ ​e​n​v​o​y​é​ ​u​n​ ​e​m​a​i​l​ ​d​e​ ​c​o​n​f​i​r​m​a​t​i​o​n​ ​à​ ​{​e​m​a​i​l​}​.
			 * @param {unknown} email
			 */
			confirmationEmail: RequiredParams<'email'>
			/**
			 * Q​u​e​l​l​e​ ​e​s​t​ ​l​a​ ​s​u​i​t​e​ ​?
			 */
			whatNext: string
			/**
			 * N​o​t​r​e​ ​é​q​u​i​p​e​ ​e​x​a​m​i​n​e​r​a​ ​v​o​t​r​e​ ​d​e​m​a​n​d​e​ ​e​t​ ​v​o​u​s​ ​c​o​n​t​a​c​t​e​r​a​ ​s​o​u​s​ ​2​4​ ​h​e​u​r​e​s​ ​p​o​u​r​ ​p​l​a​n​i​f​i​e​r​ ​u​n​e​ ​d​é​m​o​n​s​t​r​a​t​i​o​n​ ​p​e​r​s​o​n​n​a​l​i​s​é​e​ ​a​d​a​p​t​é​e​ ​a​u​x​ ​b​e​s​o​i​n​s​ ​d​e​ ​v​o​t​r​e​ ​é​t​a​b​l​i​s​s​e​m​e​n​t​.
			 */
			whatNextDescription: string
		}
		schoolTypes: {
			/**
			 * É​c​o​l​e​ ​P​r​i​m​a​i​r​e
			 */
			primary: string
			/**
			 * C​o​l​l​è​g​e​ ​/​ ​L​y​c​é​e
			 */
			secondary: string
			/**
			 * E​n​s​e​i​g​n​e​m​e​n​t​ ​S​u​p​é​r​i​e​u​r
			 */
			higherEducation: string
			/**
			 * F​o​r​m​a​t​i​o​n​ ​P​r​o​f​e​s​s​i​o​n​n​e​l​l​e
			 */
			vocational: string
			/**
			 * A​u​t​r​e
			 */
			other: string
		}
		roles: {
			/**
			 * D​i​r​e​c​t​e​u​r​ ​/​ ​C​h​e​f​ ​d​'​é​t​a​b​l​i​s​s​e​m​e​n​t
			 */
			principal: string
			/**
			 * D​i​r​e​c​t​e​u​r​ ​A​d​j​o​i​n​t
			 */
			vicePrincipal: string
			/**
			 * A​d​m​i​n​i​s​t​r​a​t​e​u​r
			 */
			administrator: string
			/**
			 * E​n​s​e​i​g​n​a​n​t
			 */
			teacher: string
			/**
			 * D​i​r​e​c​t​e​u​r​ ​I​n​f​o​r​m​a​t​i​q​u​e
			 */
			itDirector: string
			/**
			 * A​s​s​o​c​i​a​t​i​o​n​ ​d​e​ ​P​a​r​e​n​t​s
			 */
			parent: string
			/**
			 * A​u​t​r​e
			 */
			other: string
		}
		studentsCount: {
			/**
			 * M​o​i​n​s​ ​d​e​ ​1​0​0
			 */
			'0-100': string
			/**
			 * 1​0​0​-​5​0​0
			 */
			'100-500': string
			/**
			 * 5​0​0​-​1​ ​0​0​0
			 */
			'500-1000': string
			/**
			 * 1​ ​0​0​0​-​2​ ​0​0​0
			 */
			'1000-2000': string
			/**
			 * 2​ ​0​0​0​-​5​ ​0​0​0
			 */
			'2000-5000': string
			/**
			 * P​l​u​s​ ​d​e​ ​5​ ​0​0​0
			 */
			'5000+': string
		}
	}
	catalogs: {
		/**
		 * C​a​t​a​l​o​g​u​e​s
		 */
		title: string
		subjects: {
			/**
			 * M​a​t​i​è​r​e​s
			 */
			title: string
			/**
			 * R​e​c​h​e​r​c​h​e​r​ ​d​e​s​ ​m​a​t​i​è​r​e​s​.​.​.
			 */
			search: string
			/**
			 * C​a​t​é​g​o​r​i​e
			 */
			category: string
			/**
			 * T​o​u​t​e​s​ ​l​e​s​ ​c​a​t​é​g​o​r​i​e​s
			 */
			allCategories: string
			/**
			 * C​r​é​e​r​ ​u​n​e​ ​M​a​t​i​è​r​e
			 */
			create: string
			/**
			 * M​o​d​i​f​i​e​r​ ​l​a​ ​M​a​t​i​è​r​e
			 */
			edit: string
			/**
			 * M​a​t​h​é​m​a​t​i​q​u​e​s
			 */
			namePlaceholder: string
			/**
			 * M​a​t​h​s
			 */
			shortNamePlaceholder: string
			/**
			 * S​é​l​e​c​t​i​o​n​n​e​r​ ​u​n​e​ ​c​a​t​é​g​o​r​i​e
			 */
			selectCategory: string
		}
	}
	roles: {
		/**
		 * G​e​s​t​i​o​n​ ​d​e​s​ ​R​ô​l​e​s
		 */
		title: string
		/**
		 * C​o​n​f​i​g​u​r​e​z​ ​l​e​s​ ​p​e​r​m​i​s​s​i​o​n​s​ ​g​r​a​n​u​l​a​i​r​e​s​ ​e​t​ ​l​a​ ​h​i​é​r​a​r​c​h​i​e​ ​d​'​a​c​c​è​s​ ​p​o​u​r​ ​a​s​s​u​r​e​r​ ​l​a​ ​s​é​c​u​r​i​t​é​ ​e​t​ ​l​'​o​r​g​a​n​i​s​a​t​i​o​n​ ​d​e​ ​v​o​t​r​e​ ​p​l​a​t​e​f​o​r​m​e​.
		 */
		subtitle: string
		/**
		 * N​o​u​v​e​a​u​ ​R​ô​l​e
		 */
		create: string
		/**
		 * M​o​d​i​f​i​e​r​ ​l​e​ ​R​ô​l​e
		 */
		edit: string
		/**
		 * S​u​p​p​r​i​m​e​r​ ​l​e​ ​R​ô​l​e
		 */
		'delete': string
		/**
		 * N​o​m​ ​d​u​ ​R​ô​l​e
		 */
		name: string
		/**
		 * I​d​e​n​t​i​f​i​a​n​t​ ​(​S​l​u​g​)
		 */
		slug: string
		/**
		 * D​e​s​c​r​i​p​t​i​o​n​ ​&​ ​M​i​s​s​i​o​n
		 */
		description: string
		/**
		 * P​o​r​t​é​e
		 */
		scope: string
		/**
		 * M​a​t​r​i​c​e​ ​d​e​ ​P​e​r​m​i​s​s​i​o​n​s
		 */
		permissions: string
		/**
		 * R​ô​l​e​s​ ​P​l​a​t​e​f​o​r​m​e
		 */
		systemRoles: string
		/**
		 * R​ô​l​e​s​ ​É​c​o​l​e
		 */
		schoolRoles: string
		/**
		 * A​u​c​u​n​ ​r​ô​l​e​ ​d​é​f​i​n​i​.
		 */
		none: string
		/**
		 * S​u​p​p​r​e​s​s​i​o​n​ ​d​e​ ​R​ô​l​e
		 */
		confirmDelete: string
		/**
		 * V​o​u​s​ ​ê​t​e​s​ ​s​u​r​ ​l​e​ ​p​o​i​n​t​ ​d​e​ ​s​u​p​p​r​i​m​e​r​ ​l​e​ ​r​ô​l​e​ ​{​n​a​m​e​}​.
		 * @param {unknown} name
		 */
		deleteDescription: RequiredParams<'name'>
		/**
		 * A​t​t​e​n​t​i​o​n​ ​:​ ​C​e​t​t​e​ ​a​c​t​i​o​n​ ​e​s​t​ ​i​r​r​é​v​e​r​s​i​b​l​e​.​ ​T​o​u​s​ ​l​e​s​ ​u​t​i​l​i​s​a​t​e​u​r​s​ ​a​t​t​a​c​h​é​s​ ​à​ ​c​e​ ​r​ô​l​e​ ​p​e​r​d​r​o​n​t​ ​i​m​m​é​d​i​a​t​e​m​e​n​t​ ​t​o​u​t​e​s​ ​l​e​s​ ​p​e​r​m​i​s​s​i​o​n​s​ ​a​s​s​o​c​i​é​e​s​.
		 */
		deleteWarning: string
	}
	users: {
		/**
		 * U​t​i​l​i​s​a​t​e​u​r​s​ ​S​y​s​t​è​m​e
		 */
		title: string
		/**
		 * G​é​r​e​z​ ​l​e​s​ ​c​o​m​p​t​e​s​ ​a​d​m​i​n​i​s​t​r​a​t​i​f​s​ ​e​t​ ​s​u​p​e​r​v​i​s​e​z​ ​l​e​s​ ​p​r​i​v​i​l​è​g​e​s​ ​d​'​a​c​c​è​s​ ​g​l​o​b​a​u​x​ ​à​ ​l​a​ ​p​l​a​t​e​f​o​r​m​e​.
		 */
		subtitle: string
		/**
		 * R​e​c​h​e​r​c​h​e​r​ ​p​a​r​ ​n​o​m​,​ ​e​m​a​i​l​.​.​.
		 */
		search: string
		table: {
			/**
			 * U​t​i​l​i​s​a​t​e​u​r
			 */
			user: string
			/**
			 * S​t​a​t​u​t
			 */
			status: string
			/**
			 * R​ô​l​e​s​ ​S​y​s​t​è​m​e
			 */
			roles: string
			/**
			 * A​c​t​i​v​i​t​é
			 */
			activity: string
			/**
			 * A​c​t​i​o​n​s
			 */
			actions: string
		}
		/**
		 * A​u​c​u​n​ ​u​t​i​l​i​s​a​t​e​u​r​ ​t​r​o​u​v​é
		 */
		none: string
		/**
		 * A​j​u​s​t​e​z​ ​v​o​s​ ​f​i​l​t​r​e​s​ ​d​e​ ​r​e​c​h​e​r​c​h​e​ ​p​o​u​r​ ​t​r​o​u​v​e​r​ ​l​e​ ​c​o​m​p​t​e​ ​q​u​e​ ​v​o​u​s​ ​r​e​c​h​e​r​c​h​e​z​.
		 */
		noneDescription: string
		/**
		 * S​y​n​c​h​r​o​n​i​s​a​t​i​o​n​ ​d​e​s​ ​d​o​n​n​é​e​s​.​.​.
		 */
		syncing: string
		/**
		 * J​a​m​a​i​s
		 */
		neverLoggedIn: string
		/**
		 * A​u​t​o​r​i​s​a​t​i​o​n​s
		 */
		permissions: string
		/**
		 * A​u​t​o​r​i​s​a​t​i​o​n​s​ ​S​y​s​t​è​m​e
		 */
		permissionsTitle: string
		/**
		 * C​o​n​f​i​g​u​r​e​r​ ​l​e​s​ ​r​ô​l​e​s​ ​p​l​a​t​e​f​o​r​m​e​ ​p​o​u​r​ ​{​n​a​m​e​}
		 * @param {unknown} name
		 */
		permissionsSubtitle: RequiredParams<'name'>
		/**
		 * R​ô​l​e​s​ ​D​i​s​p​o​n​i​b​l​e​s
		 */
		availableRoles: string
		/**
		 * A​c​c​è​s​ ​m​i​s​ ​à​ ​j​o​u​r​ ​a​v​e​c​ ​s​u​c​c​è​s
		 */
		updateSuccess: string
		/**
		 * E​r​r​e​u​r​ ​l​o​r​s​ ​d​e​ ​l​a​ ​m​i​s​e​ ​à​ ​j​o​u​r​ ​d​e​s​ ​a​c​c​è​s
		 */
		updateError: string
	}
	whyYeko: {
		/**
		 * P​o​u​r​q​u​o​i​ ​C​h​o​i​s​i​r​ ​Y​e​k​o​ ​?
		 */
		title: string
		/**
		 * N​o​u​s​ ​f​o​u​r​n​i​s​s​o​n​s​ ​l​e​s​ ​o​u​t​i​l​s​ ​d​o​n​t​ ​v​o​u​s​ ​a​v​e​z​ ​b​e​s​o​i​n​ ​p​o​u​r​ ​r​é​u​s​s​i​r​ ​d​a​n​s​ ​u​n​ ​m​o​n​d​e​ ​n​u​m​é​r​i​q​u​e​.
		 */
		subtitle: string
		features: {
			lightning: {
				/**
				 * U​l​t​r​a​ ​R​a​p​i​d​e
				 */
				title: string
				/**
				 * O​p​t​i​m​i​s​é​ ​p​o​u​r​ ​l​a​ ​p​e​r​f​o​r​m​a​n​c​e​ ​e​t​ ​l​'​e​f​f​i​c​a​c​i​t​é​ ​d​a​n​s​ ​t​o​u​t​ ​c​e​ ​q​u​e​ ​v​o​u​s​ ​f​a​i​t​e​s​.
				 */
				description: string
			}
			secure: {
				/**
				 * S​é​c​u​r​i​t​é​ ​B​a​n​c​a​i​r​e
				 */
				title: string
				/**
				 * V​o​s​ ​d​o​n​n​é​e​s​ ​s​o​n​t​ ​c​r​y​p​t​é​e​s​ ​e​t​ ​p​r​o​t​é​g​é​e​s​ ​s​e​l​o​n​ ​l​e​s​ ​n​o​r​m​e​s​ ​l​e​s​ ​p​l​u​s​ ​s​t​r​i​c​t​e​s​ ​d​e​ ​l​'​i​n​d​u​s​t​r​i​e​.
				 */
				description: string
			}
			africa: {
				/**
				 * C​o​n​ç​u​ ​p​o​u​r​ ​l​'​A​f​r​i​q​u​e
				 */
				title: string
				/**
				 * A​d​a​p​t​é​ ​s​p​é​c​i​f​i​q​u​e​m​e​n​t​ ​a​u​x​ ​d​é​f​i​s​ ​u​n​i​q​u​e​s​ ​d​e​s​ ​i​n​s​t​i​t​u​t​i​o​n​s​ ​é​d​u​c​a​t​i​v​e​s​ ​e​n​ ​A​f​r​i​q​u​e​.
				 */
				description: string
			}
			mobile: {
				/**
				 * M​o​b​i​l​e​ ​F​i​r​s​t
				 */
				title: string
				/**
				 * A​c​c​é​d​e​z​ ​à​ ​t​o​u​t​ ​d​e​p​u​i​s​ ​v​o​t​r​e​ ​s​m​a​r​t​p​h​o​n​e​ ​a​v​e​c​ ​n​o​t​r​e​ ​p​l​a​t​e​f​o​r​m​e​ ​e​n​t​i​è​r​e​m​e​n​t​ ​r​e​s​p​o​n​s​i​v​e​.
				 */
				description: string
			}
		}
	}
}

export type TranslationFunctions = {
	nav: {
		/**
		 * Accueil
		 */
		home: () => LocalizedString
		/**
		 * Solutions
		 */
		solutions: () => LocalizedString
		benefits: {
			/**
			 * Conçu pour l'Efficacité
			 */
			title: () => LocalizedString
			/**
			 * Optimisez les opérations de votre école et concentrez-vous sur l'essentiel : l'éducation.
			 */
			subtitle: () => LocalizedString
			items: {
				timeSaving: {
					/**
					 * Gain de Temps
					 */
					title: () => LocalizedString
					/**
					 * Réduisez la charge de travail administrative de 50 % grâce à des processus automatisés.
					 */
					description: () => LocalizedString
				}
				costReduction: {
					/**
					 * Réduction des Coûts
					 */
					title: () => LocalizedString
					/**
					 * Minimisez les coûts opérationnels et les frais de paperasserie physique.
					 */
					description: () => LocalizedString
				}
				satisfaction: {
					/**
					 * Meilleure Satisfaction
					 */
					title: () => LocalizedString
					/**
					 * Améliorez la communication entre les enseignants, les élèves et les parents.
					 */
					description: () => LocalizedString
				}
				growth: {
					/**
					 * Croissance Évolutive
					 */
					title: () => LocalizedString
					/**
					 * Gérez facilement plusieurs écoles ou succursales à partir d'une seule plateforme.
					 */
					description: () => LocalizedString
				}
			}
		}
		pricing: {
			/**
			 * Plans Tarifaires
			 */
			title: () => LocalizedString
			/**
			 * Choisissez le meilleur plan pour votre institution.
			 */
			subtitle: () => LocalizedString
			/**
			 * Annuel
			 */
			annual: () => LocalizedString
			/**
			 * Mensuel
			 */
			monthly: () => LocalizedString
			/**
			 * Fonctionnalités
			 */
			features: () => LocalizedString
			/**
			 * Commencer
			 */
			getStarted: () => LocalizedString
			/**
			 * Contacter le service commercial
			 */
			contactSales: () => LocalizedString
			/**
			 * Contactez-nous
			 */
			contactUs: () => LocalizedString
			/**
			 * Choisir le plan
			 */
			cta: () => LocalizedString
			/**
			 * Les prix sont en monnaie locale. Des taxes peuvent s'appliquer.
			 */
			footer: () => LocalizedString
			plans: {
				starter: {
					/**
					 * Starter
					 */
					title: () => LocalizedString
					/**
					 * Parfait pour les petites écoles qui débutent.
					 */
					description: () => LocalizedString
					/**
					 * Gratuit
					 */
					price: () => LocalizedString
					features: {
						/**
						 * Jusqu'à 100 élèves
						 */
						'0': () => LocalizedString
						/**
						 * Gestion académique de base
						 */
						'1': () => LocalizedString
						/**
						 * Suivi des présences
						 */
						'2': () => LocalizedString
						/**
						 * Support par email
						 */
						'3': () => LocalizedString
					}
				}
				professional: {
					/**
					 * Professionnel
					 */
					title: () => LocalizedString
					/**
					 * Fonctionnalités avancées pour les institutions éducatives en croissance.
					 */
					description: () => LocalizedString
					/**
					 * 29$
					 */
					price: () => LocalizedString
					/**
					 * Le plus populaire
					 */
					popular: () => LocalizedString
					features: {
						/**
						 * Jusqu'à 1000 élèves
						 */
						'0': () => LocalizedString
						/**
						 * Gestion financière
						 */
						'1': () => LocalizedString
						/**
						 * Portail parents-enseignants
						 */
						'2': () => LocalizedString
						/**
						 * Support prioritaire
						 */
						'3': () => LocalizedString
					}
				}
				enterprise: {
					/**
					 * Entreprise
					 */
					title: () => LocalizedString
					/**
					 * Solutions sur mesure pour les grands réseaux et universités.
					 */
					description: () => LocalizedString
					/**
					 * Sur mesure
					 */
					price: () => LocalizedString
					features: {
						/**
						 * Élèves illimités
						 */
						'0': () => LocalizedString
						/**
						 * Intégrations personnalisées
						 */
						'1': () => LocalizedString
						/**
						 * Support multi-campus
						 */
						'2': () => LocalizedString
						/**
						 * Gestionnaire de compte dédié
						 */
						'3': () => LocalizedString
					}
				}
			}
		}
		/**
		 * Connexion
		 */
		login: () => LocalizedString
		/**
		 * Inscription
		 */
		signup: () => LocalizedString
		/**
		 * Tableau de bord
		 */
		dashboard: () => LocalizedString
		/**
		 * Déconnexion
		 */
		logout: () => LocalizedString
		/**
		 * transparence éducative
		 */
		tagline: () => LocalizedString
		/**
		 * Demander une démo
		 */
		requestDemo: () => LocalizedString
		/**
		 * Se connecter
		 */
		signIn: () => LocalizedString
		/**
		 * Se connecter avec Google
		 */
		signInWithGoogle: () => LocalizedString
		/**
		 * Navigation
		 */
		menuTitle: () => LocalizedString
		/**
		 * Explorez la plateforme Yeko
		 */
		menuDescription: () => LocalizedString
	}
	footerNav: {
		product: {
			/**
			 * Produit
			 */
			title: () => LocalizedString
			/**
			 * Fonctionnalités
			 */
			features: () => LocalizedString
			/**
			 * Tarifs
			 */
			pricing: () => LocalizedString
			/**
			 * À propos
			 */
			about: () => LocalizedString
			/**
			 * Contact
			 */
			contact: () => LocalizedString
		}
		resources: {
			/**
			 * Ressources
			 */
			title: () => LocalizedString
			/**
			 * Centre d'aide
			 */
			help: () => LocalizedString
			/**
			 * Politique de confidentialité
			 */
			privacy: () => LocalizedString
			/**
			 * Conditions d'utilisation
			 */
			terms: () => LocalizedString
			/**
			 * Sécurité
			 */
			security: () => LocalizedString
		}
		social: {
			/**
			 * Facebook
			 */
			facebook: () => LocalizedString
			/**
			 * Twitter
			 */
			twitter: () => LocalizedString
			/**
			 * LinkedIn
			 */
			linkedin: () => LocalizedString
		}
		/**
		 * Yeko - Propulser les écoles africaines grâce à l'innovation numérique.
		 */
		tagline: () => LocalizedString
		/**
		 * © {year} Yeko. Tous droits réservés.
		 */
		copyright: (arg: { year: number }) => LocalizedString
	}
	hero: {
		/**
		 * Modernisez Votre École
		 */
		title: () => LocalizedString
		/**
		 * Gagnez plus de 20 heures par semaine
		 */
		subtitle: () => LocalizedString
		/**
		 * Automatisez la gestion administrative, les communications et les paiements avec notre plateforme tout-en-un conçue pour les écoles modernes.
		 */
		description: () => LocalizedString
		cta: {
			/**
			 * Commencer Gratuitement
			 */
			primary: () => LocalizedString
			/**
			 * Voir la Démo
			 */
			secondary: () => LocalizedString
		}
		features: {
			/**
			 * Aucune carte bancaire requise
			 */
			'0': () => LocalizedString
			/**
			 * Configuration en 5 jours
			 */
			'1': () => LocalizedString
			/**
			 * Annulez à tout moment
			 */
			'2': () => LocalizedString
		}
		demo: {
			/**
			 * Aperçu du Tableau de Bord
			 */
			title: () => LocalizedString
			/**
			 * Aperçu en temps réel des performances de votre école
			 */
			description: () => LocalizedString
		}
	}
	painPoints: {
		/**
		 * Arrêtez de lutter avec des systèmes obsolètes
		 */
		title: () => LocalizedString
		/**
		 * Nous résolvons les défis les plus courants auxquels les écoles sont confrontées aujourd'hui.
		 */
		subtitle: () => LocalizedString
		items: {
			paperwork: {
				/**
				 * Paperasserie manuelle
				 */
				title: () => LocalizedString
				/**
				 * Plus de piles de papier et d'erreurs de saisie manuelle.
				 */
				description: () => LocalizedString
				/**
				 * Dossiers d'élèves numériques et tenue de registres automatisée.
				 */
				solution: () => LocalizedString
			}
			communication: {
				/**
				 * Mauvaise communication
				 */
				title: () => LocalizedString
				/**
				 * Contactez instantanément les parents et le personnel via des canaux intégrés.
				 */
				description: () => LocalizedString
				/**
				 * Notifications mobiles instantanées et messagerie unifiée.
				 */
				solution: () => LocalizedString
			}
			admin: {
				/**
				 * Charge administrative
				 */
				title: () => LocalizedString
				/**
				 * Réduisez le temps passé sur les tâches répétitives et concentrez-vous sur l'enseignement.
				 */
				description: () => LocalizedString
				/**
				 * Intégration d'outils en ligne et processus automatiques.
				 */
				solution: () => LocalizedString
			}
		}
	}
	socialProof: {
		/**
		 * Approuvé par des institutions éducatives à travers l'Afrique
		 */
		trustedBy: () => LocalizedString
		stats: {
			/**
			 * Écoles Partenaires
			 */
			schools: () => LocalizedString
			/**
			 * Élèves Actifs
			 */
			students: () => LocalizedString
			/**
			 * Satisfaction Parentale
			 */
			satisfaction: () => LocalizedString
			/**
			 * Pays
			 */
			countries: () => LocalizedString
		}
	}
	useCases: {
		/**
		 * Adapté à chaque partie prenante
		 */
		title: () => LocalizedString
		/**
		 * Notre plateforme rassemble tout le monde dans un écosystème numérique unifié.
		 */
		subtitle: () => LocalizedString
		stakeholders: {
			administrators: {
				/**
				 * Administrateurs
				 */
				title: () => LocalizedString
				/**
				 * Supervision et contrôle complets des opérations scolaires.
				 */
				description: () => LocalizedString
			}
			teachers: {
				/**
				 * Enseignants
				 */
				title: () => LocalizedString
				/**
				 * Notation, présence et planification des cours sans effort.
				 */
				description: () => LocalizedString
			}
			parents: {
				/**
				 * Parents
				 */
				title: () => LocalizedString
				/**
				 * Suivi en temps réel des progrès et des activités de leur enfant.
				 */
				description: () => LocalizedString
			}
			students: {
				/**
				 * Élèves
				 */
				title: () => LocalizedString
				/**
				 * Accès au matériel pédagogique et aperçu des performances.
				 */
				description: () => LocalizedString
			}
		}
	}
	common: {
		/**
		 * Enregistrer
		 */
		save: () => LocalizedString
		/**
		 * Annuler
		 */
		cancel: () => LocalizedString
		/**
		 * Supprimer
		 */
		'delete': () => LocalizedString
		/**
		 * Modifier
		 */
		edit: () => LocalizedString
		/**
		 * Créer
		 */
		create: () => LocalizedString
		/**
		 * Rechercher
		 */
		search: () => LocalizedString
		/**
		 * Chargement...
		 */
		loading: () => LocalizedString
		/**
		 * Aucun résultat
		 */
		noResults: () => LocalizedString
		/**
		 * Actions
		 */
		actions: () => LocalizedString
		/**
		 * Succès
		 */
		success: () => LocalizedString
		/**
		 * Erreur
		 */
		error: () => LocalizedString
		/**
		 * Réessayer
		 */
		retry: () => LocalizedString
		/**
		 * Fermer
		 */
		close: () => LocalizedString
		/**
		 * Ouvrir
		 */
		open: () => LocalizedString
		/**
		 * Oui
		 */
		yes: () => LocalizedString
		/**
		 * Non
		 */
		no: () => LocalizedString
		/**
		 * Confirmer
		 */
		confirm: () => LocalizedString
		/**
		 * Retour
		 */
		back: () => LocalizedString
		/**
		 * Suivant
		 */
		next: () => LocalizedString
		/**
		 * Précédent
		 */
		previous: () => LocalizedString
		/**
		 * Envoyer
		 */
		submit: () => LocalizedString
		/**
		 * Réinitialiser
		 */
		reset: () => LocalizedString
		/**
		 * Effacer
		 */
		clear: () => LocalizedString
		/**
		 * Sélectionner
		 */
		select: () => LocalizedString
		/**
		 * Tout sélectionner
		 */
		selectAll: () => LocalizedString
		/**
		 * Tout désélectionner
		 */
		deselectAll: () => LocalizedString
		/**
		 * Filtrer
		 */
		filter: () => LocalizedString
		/**
		 * Trier
		 */
		sort: () => LocalizedString
		/**
		 * Exporter
		 */
		'export': () => LocalizedString
		/**
		 * Importer
		 */
		'import': () => LocalizedString
		/**
		 * Télécharger
		 */
		download: () => LocalizedString
		/**
		 * Téléverser
		 */
		upload: () => LocalizedString
		/**
		 * Voir
		 */
		view: () => LocalizedString
		/**
		 * Détails
		 */
		details: () => LocalizedString
		/**
		 * Paramètres
		 */
		settings: () => LocalizedString
		/**
		 * Préférences
		 */
		preferences: () => LocalizedString
		/**
		 * Profil
		 */
		profile: () => LocalizedString
		/**
		 * Compte
		 */
		account: () => LocalizedString
		/**
		 * Aide
		 */
		help: () => LocalizedString
		/**
		 * Support
		 */
		support: () => LocalizedString
		/**
		 * Documentation
		 */
		documentation: () => LocalizedString
		/**
		 * À propos
		 */
		about: () => LocalizedString
		/**
		 * Version
		 */
		version: () => LocalizedString
		/**
		 * Langue
		 */
		language: () => LocalizedString
		/**
		 * Thème
		 */
		theme: () => LocalizedString
		/**
		 * Clair
		 */
		light: () => LocalizedString
		/**
		 * Sombre
		 */
		dark: () => LocalizedString
		/**
		 * Système
		 */
		system: () => LocalizedString
	}
	status: {
		/**
		 * Actif
		 */
		active: () => LocalizedString
		/**
		 * Inactif
		 */
		inactive: () => LocalizedString
		/**
		 * Suspendu
		 */
		suspended: () => LocalizedString
		/**
		 * Brouillon
		 */
		draft: () => LocalizedString
		/**
		 * Publié
		 */
		published: () => LocalizedString
		/**
		 * Archivé
		 */
		archived: () => LocalizedString
		/**
		 * En attente
		 */
		pending: () => LocalizedString
		/**
		 * Approuvé
		 */
		approved: () => LocalizedString
		/**
		 * Rejeté
		 */
		rejected: () => LocalizedString
		/**
		 * Terminé
		 */
		completed: () => LocalizedString
		/**
		 * En cours
		 */
		inProgress: () => LocalizedString
		/**
		 * Annulé
		 */
		cancelled: () => LocalizedString
	}
	errors: {
		/**
		 * Ce champ est obligatoire
		 */
		required: () => LocalizedString
		/**
		 * Email invalide
		 */
		invalidEmail: () => LocalizedString
		/**
		 * Numéro de téléphone invalide
		 */
		invalidPhone: () => LocalizedString
		/**
		 * URL invalide
		 */
		invalidUrl: () => LocalizedString
		/**
		 * Date invalide
		 */
		invalidDate: () => LocalizedString
		/**
		 * Nombre invalide
		 */
		invalidNumber: () => LocalizedString
		/**
		 * Minimum {count} caractères
		 */
		minLength: (arg: { count: unknown }) => LocalizedString
		/**
		 * Maximum {count} caractères
		 */
		maxLength: (arg: { count: unknown }) => LocalizedString
		/**
		 * Valeur minimale : {min}
		 */
		min: (arg: { min: unknown }) => LocalizedString
		/**
		 * Valeur maximale : {max}
		 */
		max: (arg: { max: unknown }) => LocalizedString
		/**
		 * Cette valeur existe déjà
		 */
		unique: () => LocalizedString
		/**
		 * Échec de la création
		 */
		createFailed: () => LocalizedString
		/**
		 * Échec de la mise à jour
		 */
		updateFailed: () => LocalizedString
		/**
		 * Échec de la suppression
		 */
		deleteFailed: () => LocalizedString
		/**
		 * Échec du chargement
		 */
		loadFailed: () => LocalizedString
		/**
		 * Échec de l'enregistrement
		 */
		saveFailed: () => LocalizedString
		/**
		 * Non autorisé
		 */
		unauthorized: () => LocalizedString
		/**
		 * Accès interdit
		 */
		forbidden: () => LocalizedString
		/**
		 * Non trouvé
		 */
		notFound: () => LocalizedString
		/**
		 * Erreur serveur
		 */
		serverError: () => LocalizedString
		/**
		 * Erreur réseau
		 */
		networkError: () => LocalizedString
		/**
		 * Délai dépassé
		 */
		timeout: () => LocalizedString
		/**
		 * Erreur inconnue
		 */
		unknown: () => LocalizedString
	}
	validation: {
		/**
		 * Ce champ est obligatoire
		 */
		required: () => LocalizedString
		/**
		 * Veuillez entrer un email valide
		 */
		email: () => LocalizedString
		/**
		 * Veuillez entrer un numéro de téléphone valide
		 */
		phone: () => LocalizedString
		/**
		 * Veuillez entrer une URL valide
		 */
		url: () => LocalizedString
		/**
		 * Veuillez entrer une date valide
		 */
		date: () => LocalizedString
		/**
		 * Veuillez entrer un nombre valide
		 */
		number: () => LocalizedString
		/**
		 * Veuillez entrer un nombre entier
		 */
		integer: () => LocalizedString
		/**
		 * La valeur doit être positive
		 */
		positive: () => LocalizedString
		/**
		 * La valeur doit être négative
		 */
		negative: () => LocalizedString
		/**
		 * Minimum {count} caractères requis
		 */
		minLength: (arg: { count: unknown }) => LocalizedString
		/**
		 * Maximum {count} caractères autorisés
		 */
		maxLength: (arg: { count: unknown }) => LocalizedString
		/**
		 * La valeur doit être d'au moins {min}
		 */
		min: (arg: { min: unknown }) => LocalizedString
		/**
		 * La valeur ne peut pas dépasser {max}
		 */
		max: (arg: { max: unknown }) => LocalizedString
		/**
		 * Format invalide
		 */
		pattern: () => LocalizedString
		/**
		 * Cette valeur doit être unique
		 */
		unique: () => LocalizedString
		/**
		 * Les valeurs ne correspondent pas
		 */
		match: () => LocalizedString
		/**
		 * Le mot de passe doit contenir au moins 8 caractères, une majuscule, une minuscule et un chiffre
		 */
		strongPassword: () => LocalizedString
	}
	schools: {
		/**
		 * Gestion des Écoles
		 */
		title: () => LocalizedString
		/**
		 * Gérez toutes vos écoles partenaires
		 */
		subtitle: () => LocalizedString
		/**
		 * Créer une École
		 */
		create: () => LocalizedString
		/**
		 * Modifier l'École
		 */
		edit: () => LocalizedString
		/**
		 * Supprimer l'École
		 */
		'delete': () => LocalizedString
		/**
		 * Voir l'École
		 */
		view: () => LocalizedString
		/**
		 * Liste des Écoles
		 */
		list: () => LocalizedString
		/**
		 * Rechercher une école
		 */
		search: () => LocalizedString
		/**
		 * Filtrer les écoles
		 */
		filter: () => LocalizedString
		/**
		 * Trier les écoles
		 */
		sort: () => LocalizedString
		/**
		 * Exporter les écoles
		 */
		'export': () => LocalizedString
		/**
		 * Importer les écoles
		 */
		'import': () => LocalizedString
		/**
		 * Nom de l'École
		 */
		name: () => LocalizedString
		/**
		 * Code de l'École
		 */
		code: () => LocalizedString
		/**
		 * Statut
		 */
		status: () => LocalizedString
		/**
		 * Adresse
		 */
		address: () => LocalizedString
		/**
		 * Téléphone
		 */
		phone: () => LocalizedString
		/**
		 * Email
		 */
		email: () => LocalizedString
		/**
		 * Site web
		 */
		website: () => LocalizedString
		/**
		 * Directeur
		 */
		director: () => LocalizedString
		/**
		 * Année de fondation
		 */
		foundedYear: () => LocalizedString
		/**
		 * Nombre d'élèves
		 */
		studentCount: () => LocalizedString
		/**
		 * Nombre d'enseignants
		 */
		teacherCount: () => LocalizedString
		/**
		 * Nombre de classes
		 */
		classCount: () => LocalizedString
		/**
		 * Description
		 */
		description: () => LocalizedString
		/**
		 * Notes
		 */
		notes: () => LocalizedString
		/**
		 * Créé le
		 */
		createdAt: () => LocalizedString
		/**
		 * Modifié le
		 */
		updatedAt: () => LocalizedString
		/**
		 * Êtes-vous sûr de vouloir supprimer {name} ?
		 */
		confirmDelete: (arg: { name: unknown }) => LocalizedString
		/**
		 * Cette action est irréversible. Toutes les données associées seront supprimées.
		 */
		deleteWarning: () => LocalizedString
		/**
		 * École créée avec succès
		 */
		created: () => LocalizedString
		/**
		 * École mise à jour avec succès
		 */
		updated: () => LocalizedString
		/**
		 * École supprimée avec succès
		 */
		deleted: () => LocalizedString
		/**
		 * École non trouvée
		 */
		notFound: () => LocalizedString
		/**
		 * Une école avec ce code existe déjà
		 */
		duplicate: () => LocalizedString
	}
	demoRequest: {
		/**
		 * Demander une Démo
		 */
		title: () => LocalizedString
		/**
		 * Découvrez comment Yeko peut transformer votre institution
		 */
		subtitle: () => LocalizedString
		form: {
			/**
			 * Nom Complet
			 */
			name: () => LocalizedString
			/**
			 * Adresse Email
			 */
			email: () => LocalizedString
			/**
			 * Numéro de Téléphone
			 */
			phone: () => LocalizedString
			/**
			 * Nom de l'École/Organisation
			 */
			schoolName: () => LocalizedString
			/**
			 * Type d'Établissement
			 */
			schoolType: () => LocalizedString
			/**
			 * Votre Rôle
			 */
			role: () => LocalizedString
			/**
			 * Nombre d'Élèves
			 */
			studentsCount: () => LocalizedString
			/**
			 * Informations Complémentaires
			 */
			message: () => LocalizedString
			/**
			 * Demander une Démo
			 */
			submit: () => LocalizedString
			/**
			 * Demande de Démo Reçue !
			 */
			success: () => LocalizedString
			/**
			 * Merci de votre intérêt pour Yeko ! Notre équipe vous contactera sous 24 heures pour planifier votre démo personnalisée.
			 */
			successDescription: () => LocalizedString
			/**
			 * Nous avons envoyé un email de confirmation à {email}.
			 */
			confirmationEmail: (arg: { email: unknown }) => LocalizedString
			/**
			 * Quelle est la suite ?
			 */
			whatNext: () => LocalizedString
			/**
			 * Notre équipe examinera votre demande et vous contactera sous 24 heures pour planifier une démonstration personnalisée adaptée aux besoins de votre établissement.
			 */
			whatNextDescription: () => LocalizedString
		}
		schoolTypes: {
			/**
			 * École Primaire
			 */
			primary: () => LocalizedString
			/**
			 * Collège / Lycée
			 */
			secondary: () => LocalizedString
			/**
			 * Enseignement Supérieur
			 */
			higherEducation: () => LocalizedString
			/**
			 * Formation Professionnelle
			 */
			vocational: () => LocalizedString
			/**
			 * Autre
			 */
			other: () => LocalizedString
		}
		roles: {
			/**
			 * Directeur / Chef d'établissement
			 */
			principal: () => LocalizedString
			/**
			 * Directeur Adjoint
			 */
			vicePrincipal: () => LocalizedString
			/**
			 * Administrateur
			 */
			administrator: () => LocalizedString
			/**
			 * Enseignant
			 */
			teacher: () => LocalizedString
			/**
			 * Directeur Informatique
			 */
			itDirector: () => LocalizedString
			/**
			 * Association de Parents
			 */
			parent: () => LocalizedString
			/**
			 * Autre
			 */
			other: () => LocalizedString
		}
		studentsCount: {
			/**
			 * Moins de 100
			 */
			'0-100': () => LocalizedString
			/**
			 * 100-500
			 */
			'100-500': () => LocalizedString
			/**
			 * 500-1 000
			 */
			'500-1000': () => LocalizedString
			/**
			 * 1 000-2 000
			 */
			'1000-2000': () => LocalizedString
			/**
			 * 2 000-5 000
			 */
			'2000-5000': () => LocalizedString
			/**
			 * Plus de 5 000
			 */
			'5000+': () => LocalizedString
		}
	}
	catalogs: {
		/**
		 * Catalogues
		 */
		title: () => LocalizedString
		subjects: {
			/**
			 * Matières
			 */
			title: () => LocalizedString
			/**
			 * Rechercher des matières...
			 */
			search: () => LocalizedString
			/**
			 * Catégorie
			 */
			category: () => LocalizedString
			/**
			 * Toutes les catégories
			 */
			allCategories: () => LocalizedString
			/**
			 * Créer une Matière
			 */
			create: () => LocalizedString
			/**
			 * Modifier la Matière
			 */
			edit: () => LocalizedString
			/**
			 * Mathématiques
			 */
			namePlaceholder: () => LocalizedString
			/**
			 * Maths
			 */
			shortNamePlaceholder: () => LocalizedString
			/**
			 * Sélectionner une catégorie
			 */
			selectCategory: () => LocalizedString
		}
	}
	roles: {
		/**
		 * Gestion des Rôles
		 */
		title: () => LocalizedString
		/**
		 * Configurez les permissions granulaires et la hiérarchie d'accès pour assurer la sécurité et l'organisation de votre plateforme.
		 */
		subtitle: () => LocalizedString
		/**
		 * Nouveau Rôle
		 */
		create: () => LocalizedString
		/**
		 * Modifier le Rôle
		 */
		edit: () => LocalizedString
		/**
		 * Supprimer le Rôle
		 */
		'delete': () => LocalizedString
		/**
		 * Nom du Rôle
		 */
		name: () => LocalizedString
		/**
		 * Identifiant (Slug)
		 */
		slug: () => LocalizedString
		/**
		 * Description & Mission
		 */
		description: () => LocalizedString
		/**
		 * Portée
		 */
		scope: () => LocalizedString
		/**
		 * Matrice de Permissions
		 */
		permissions: () => LocalizedString
		/**
		 * Rôles Plateforme
		 */
		systemRoles: () => LocalizedString
		/**
		 * Rôles École
		 */
		schoolRoles: () => LocalizedString
		/**
		 * Aucun rôle défini.
		 */
		none: () => LocalizedString
		/**
		 * Suppression de Rôle
		 */
		confirmDelete: () => LocalizedString
		/**
		 * Vous êtes sur le point de supprimer le rôle {name}.
		 */
		deleteDescription: (arg: { name: unknown }) => LocalizedString
		/**
		 * Attention : Cette action est irréversible. Tous les utilisateurs attachés à ce rôle perdront immédiatement toutes les permissions associées.
		 */
		deleteWarning: () => LocalizedString
	}
	users: {
		/**
		 * Utilisateurs Système
		 */
		title: () => LocalizedString
		/**
		 * Gérez les comptes administratifs et supervisez les privilèges d'accès globaux à la plateforme.
		 */
		subtitle: () => LocalizedString
		/**
		 * Rechercher par nom, email...
		 */
		search: () => LocalizedString
		table: {
			/**
			 * Utilisateur
			 */
			user: () => LocalizedString
			/**
			 * Statut
			 */
			status: () => LocalizedString
			/**
			 * Rôles Système
			 */
			roles: () => LocalizedString
			/**
			 * Activité
			 */
			activity: () => LocalizedString
			/**
			 * Actions
			 */
			actions: () => LocalizedString
		}
		/**
		 * Aucun utilisateur trouvé
		 */
		none: () => LocalizedString
		/**
		 * Ajustez vos filtres de recherche pour trouver le compte que vous recherchez.
		 */
		noneDescription: () => LocalizedString
		/**
		 * Synchronisation des données...
		 */
		syncing: () => LocalizedString
		/**
		 * Jamais
		 */
		neverLoggedIn: () => LocalizedString
		/**
		 * Autorisations
		 */
		permissions: () => LocalizedString
		/**
		 * Autorisations Système
		 */
		permissionsTitle: () => LocalizedString
		/**
		 * Configurer les rôles plateforme pour {name}
		 */
		permissionsSubtitle: (arg: { name: unknown }) => LocalizedString
		/**
		 * Rôles Disponibles
		 */
		availableRoles: () => LocalizedString
		/**
		 * Accès mis à jour avec succès
		 */
		updateSuccess: () => LocalizedString
		/**
		 * Erreur lors de la mise à jour des accès
		 */
		updateError: () => LocalizedString
	}
	whyYeko: {
		/**
		 * Pourquoi Choisir Yeko ?
		 */
		title: () => LocalizedString
		/**
		 * Nous fournissons les outils dont vous avez besoin pour réussir dans un monde numérique.
		 */
		subtitle: () => LocalizedString
		features: {
			lightning: {
				/**
				 * Ultra Rapide
				 */
				title: () => LocalizedString
				/**
				 * Optimisé pour la performance et l'efficacité dans tout ce que vous faites.
				 */
				description: () => LocalizedString
			}
			secure: {
				/**
				 * Sécurité Bancaire
				 */
				title: () => LocalizedString
				/**
				 * Vos données sont cryptées et protégées selon les normes les plus strictes de l'industrie.
				 */
				description: () => LocalizedString
			}
			africa: {
				/**
				 * Conçu pour l'Afrique
				 */
				title: () => LocalizedString
				/**
				 * Adapté spécifiquement aux défis uniques des institutions éducatives en Afrique.
				 */
				description: () => LocalizedString
			}
			mobile: {
				/**
				 * Mobile First
				 */
				title: () => LocalizedString
				/**
				 * Accédez à tout depuis votre smartphone avec notre plateforme entièrement responsive.
				 */
				description: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
