// Permission resources and actions
export const PERMISSION_RESOURCES = {
  USERS: 'users',
  TEACHERS: 'teachers',
  STAFF: 'staff',
  STUDENTS: 'students',
  CLASSES: 'classes',
  GRADES: 'grades',
  FINANCE: 'finance',
  REPORTS: 'reports',
  SETTINGS: 'settings',
} as const

export const PERMISSION_ACTIONS = {
  VIEW: 'view',
  CREATE: 'create',
  EDIT: 'edit',
  DELETE: 'delete',
  ASSIGN: 'assign',
  ENROLL: 'enroll',
  VALIDATE: 'validate',
  PROCESS_PAYMENT: 'process_payment',
  EXPORT: 'export',
} as const

// Permissions matrix structure
export const PERMISSIONS_MATRIX = {
  [PERMISSION_RESOURCES.USERS]: [
    PERMISSION_ACTIONS.VIEW,
    PERMISSION_ACTIONS.CREATE,
    PERMISSION_ACTIONS.EDIT,
    PERMISSION_ACTIONS.DELETE,
  ],
  [PERMISSION_RESOURCES.TEACHERS]: [
    PERMISSION_ACTIONS.VIEW,
    PERMISSION_ACTIONS.CREATE,
    PERMISSION_ACTIONS.EDIT,
    PERMISSION_ACTIONS.DELETE,
    PERMISSION_ACTIONS.ASSIGN,
  ],
  [PERMISSION_RESOURCES.STAFF]: [
    PERMISSION_ACTIONS.VIEW,
    PERMISSION_ACTIONS.CREATE,
    PERMISSION_ACTIONS.EDIT,
    PERMISSION_ACTIONS.DELETE,
  ],
  [PERMISSION_RESOURCES.STUDENTS]: [
    PERMISSION_ACTIONS.VIEW,
    PERMISSION_ACTIONS.CREATE,
    PERMISSION_ACTIONS.EDIT,
    PERMISSION_ACTIONS.DELETE,
    PERMISSION_ACTIONS.ENROLL,
  ],
  [PERMISSION_RESOURCES.CLASSES]: [
    PERMISSION_ACTIONS.VIEW,
    PERMISSION_ACTIONS.CREATE,
    PERMISSION_ACTIONS.EDIT,
    PERMISSION_ACTIONS.DELETE,
  ],
  [PERMISSION_RESOURCES.GRADES]: [
    PERMISSION_ACTIONS.VIEW,
    PERMISSION_ACTIONS.CREATE,
    PERMISSION_ACTIONS.EDIT,
    PERMISSION_ACTIONS.VALIDATE,
    PERMISSION_ACTIONS.DELETE,
  ],
  [PERMISSION_RESOURCES.FINANCE]: [
    PERMISSION_ACTIONS.VIEW,
    PERMISSION_ACTIONS.CREATE,
    PERMISSION_ACTIONS.EDIT,
    PERMISSION_ACTIONS.DELETE,
    PERMISSION_ACTIONS.PROCESS_PAYMENT,
  ],
  [PERMISSION_RESOURCES.REPORTS]: [
    PERMISSION_ACTIONS.VIEW,
    PERMISSION_ACTIONS.EXPORT,
  ],
  [PERMISSION_RESOURCES.SETTINGS]: [
    PERMISSION_ACTIONS.VIEW,
    PERMISSION_ACTIONS.EDIT,
  ],
} as const

// System role slugs
export const SYSTEM_ROLES = {
  SCHOOL_ADMINISTRATOR: 'school-administrator',
  ACADEMIC_COORDINATOR: 'academic-coordinator',
  DISCIPLINE_OFFICER: 'discipline-officer',
  ACCOUNTANT: 'accountant',
  CASHIER: 'cashier',
  REGISTRAR: 'registrar',
} as const

export type PermissionResource = typeof PERMISSION_RESOURCES[keyof typeof PERMISSION_RESOURCES]
export type PermissionAction = typeof PERMISSION_ACTIONS[keyof typeof PERMISSION_ACTIONS]
export type SystemRole = typeof SYSTEM_ROLES[keyof typeof SYSTEM_ROLES]
