/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthUsersRouteImport } from './routes/_auth/users'
import { Route as AuthStudentsRouteImport } from './routes/_auth/students'
import { Route as AuthSpacesRouteImport } from './routes/_auth/spaces'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthSchedulesRouteImport } from './routes/_auth/schedules'
import { Route as AuthProgramsRouteImport } from './routes/_auth/programs'
import { Route as AuthGradesRouteImport } from './routes/_auth/grades'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthConductsRouteImport } from './routes/_auth/conducts'
import { Route as AuthClassesRouteImport } from './routes/_auth/classes'
import { Route as AuthAccountingRouteImport } from './routes/_auth/accounting'
import { Route as AuthUsersIndexRouteImport } from './routes/_auth/users/index'
import { Route as AuthStudentsIndexRouteImport } from './routes/_auth/students/index'
import { Route as AuthSpacesIndexRouteImport } from './routes/_auth/spaces/index'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings/index'
import { Route as AuthGradesIndexRouteImport } from './routes/_auth/grades/index'
import { Route as AuthConductsIndexRouteImport } from './routes/_auth/conducts/index'
import { Route as AuthClassesIndexRouteImport } from './routes/_auth/classes/index'
import { Route as AuthAccountingIndexRouteImport } from './routes/_auth/accounting/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthStudentsParentsRouteImport } from './routes/_auth/students/parents'
import { Route as AuthStudentsNewRouteImport } from './routes/_auth/students/new'
import { Route as AuthStudentsEnrollmentsRouteImport } from './routes/_auth/students/enrollments'
import { Route as AuthStudentsBulkOperationsRouteImport } from './routes/_auth/students/bulk-operations'
import { Route as AuthSpacesAvailabilityRouteImport } from './routes/_auth/spaces/availability'
import { Route as AuthSettingsSchoolYearsRouteImport } from './routes/_auth/settings/school-years'
import { Route as AuthSettingsReportCardsRouteImport } from './routes/_auth/settings/report-cards'
import { Route as AuthSettingsProfileRouteImport } from './routes/_auth/settings/profile'
import { Route as AuthSettingsNotificationsRouteImport } from './routes/_auth/settings/notifications'
import { Route as AuthProgramsSubjectsRouteImport } from './routes/_auth/programs/subjects'
import { Route as AuthProgramsCurriculumProgressRouteImport } from './routes/_auth/programs/curriculum-progress'
import { Route as AuthProgramsCoefficientsRouteImport } from './routes/_auth/programs/coefficients'
import { Route as AuthGradesValidationsRouteImport } from './routes/_auth/grades/validations'
import { Route as AuthGradesStatisticsRouteImport } from './routes/_auth/grades/statistics'
import { Route as AuthGradesReportCardsRouteImport } from './routes/_auth/grades/report-cards'
import { Route as AuthGradesEntryRouteImport } from './routes/_auth/grades/entry'
import { Route as AuthConductsSettingsRouteImport } from './routes/_auth/conducts/settings'
import { Route as AuthClassesAssignmentsRouteImport } from './routes/_auth/classes/assignments'
import { Route as AuthAccountingStudentFeesRouteImport } from './routes/_auth/accounting/student-fees'
import { Route as AuthAccountingRefundsRouteImport } from './routes/_auth/accounting/refunds'
import { Route as AuthAccountingPaymentsRouteImport } from './routes/_auth/accounting/payments'
import { Route as AuthAccountingPaymentPlansRouteImport } from './routes/_auth/accounting/payment-plans'
import { Route as AuthAccountingFeeTypesRouteImport } from './routes/_auth/accounting/fee-types'
import { Route as AuthAccountingFeeStructuresRouteImport } from './routes/_auth/accounting/fee-structures'
import { Route as AuthAccountingDiscountsRouteImport } from './routes/_auth/accounting/discounts'
import { Route as AuthAccountingDashboardRouteImport } from './routes/_auth/accounting/dashboard'
import { Route as AuthAccountingAccountsRouteImport } from './routes/_auth/accounting/accounts'
import { Route as AuthUsersUsersIndexRouteImport } from './routes/_auth/users/users/index'
import { Route as AuthUsersTeachersIndexRouteImport } from './routes/_auth/users/teachers/index'
import { Route as AuthUsersStaffIndexRouteImport } from './routes/_auth/users/staff/index'
import { Route as AuthUsersRolesIndexRouteImport } from './routes/_auth/users/roles/index'
import { Route as AuthStudentsStudentIdIndexRouteImport } from './routes/_auth/students/$studentId/index'
import { Route as AuthSpacesClassroomsIndexRouteImport } from './routes/_auth/spaces/classrooms/index'
import { Route as AuthConductsTeacherAttendanceIndexRouteImport } from './routes/_auth/conducts/teacher-attendance/index'
import { Route as AuthConductsStudentAttendanceIndexRouteImport } from './routes/_auth/conducts/student-attendance/index'
import { Route as AuthConductsConductIndexRouteImport } from './routes/_auth/conducts/conduct/index'
import { Route as AuthConductsAlertsIndexRouteImport } from './routes/_auth/conducts/alerts/index'
import { Route as AuthClassesClassIdIndexRouteImport } from './routes/_auth/classes/$classId/index'
import { Route as AuthUsersUsersNewRouteImport } from './routes/_auth/users/users/new'
import { Route as AuthUsersUsersImportRouteImport } from './routes/_auth/users/users/import'
import { Route as AuthUsersTeachersNewRouteImport } from './routes/_auth/users/teachers/new'
import { Route as AuthUsersStaffNewRouteImport } from './routes/_auth/users/staff/new'
import { Route as AuthUsersRolesNewRouteImport } from './routes/_auth/users/roles/new'
import { Route as AuthStudentsStudentIdEditRouteImport } from './routes/_auth/students/$studentId/edit'
import { Route as AuthConductsTeacherAttendanceReportsRouteImport } from './routes/_auth/conducts/teacher-attendance/reports'
import { Route as AuthConductsStudentAttendanceStatisticsRouteImport } from './routes/_auth/conducts/student-attendance/statistics'
import { Route as AuthConductsStudentAttendanceHistoryRouteImport } from './routes/_auth/conducts/student-attendance/history'
import { Route as AuthConductsConductReportsRouteImport } from './routes/_auth/conducts/conduct/reports'
import { Route as AuthConductsConductNewRouteImport } from './routes/_auth/conducts/conduct/new'
import { Route as AuthConductsConductRecordIdRouteImport } from './routes/_auth/conducts/conduct/$recordId'
import { Route as AuthClassesClassIdEditRouteImport } from './routes/_auth/classes/$classId/edit'
import { Route as AuthUsersUsersUserIdIndexRouteImport } from './routes/_auth/users/users/$userId/index'
import { Route as AuthUsersTeachersTeacherIdIndexRouteImport } from './routes/_auth/users/teachers/$teacherId/index'
import { Route as AuthUsersStaffStaffIdIndexRouteImport } from './routes/_auth/users/staff/$staffId/index'
import { Route as AuthUsersRolesRoleIdIndexRouteImport } from './routes/_auth/users/roles/$roleId/index'
import { Route as AuthSpacesClassroomsClassroomIdIndexRouteImport } from './routes/_auth/spaces/classrooms/$classroomId/index'
import { Route as AuthUsersUsersUserIdEditRouteImport } from './routes/_auth/users/users/$userId/edit'
import { Route as AuthUsersTeachersTeacherIdEditRouteImport } from './routes/_auth/users/teachers/$teacherId/edit'
import { Route as AuthUsersStaffStaffIdEditRouteImport } from './routes/_auth/users/staff/$staffId/edit'
import { Route as AuthUsersRolesRoleIdEditRouteImport } from './routes/_auth/users/roles/$roleId/edit'
import { Route as AuthSpacesClassroomsClassroomIdEditRouteImport } from './routes/_auth/spaces/classrooms/$classroomId/edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUsersRoute = AuthUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStudentsRoute = AuthStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSpacesRoute = AuthSpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSchedulesRoute = AuthSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProgramsRoute = AuthProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGradesRoute = AuthGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConductsRoute = AuthConductsRouteImport.update({
  id: '/conducts',
  path: '/conducts',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClassesRoute = AuthClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountingRoute = AuthAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersIndexRoute = AuthUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthUsersRoute,
} as any)
const AuthStudentsIndexRoute = AuthStudentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthStudentsRoute,
} as any)
const AuthSpacesIndexRoute = AuthSpacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSpacesRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthGradesIndexRoute = AuthGradesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthGradesRoute,
} as any)
const AuthConductsIndexRoute = AuthConductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthConductsRoute,
} as any)
const AuthClassesIndexRoute = AuthClassesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthClassesRoute,
} as any)
const AuthAccountingIndexRoute = AuthAccountingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAccountingRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStudentsParentsRoute = AuthStudentsParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => AuthStudentsRoute,
} as any)
const AuthStudentsNewRoute = AuthStudentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthStudentsRoute,
} as any)
const AuthStudentsEnrollmentsRoute = AuthStudentsEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => AuthStudentsRoute,
} as any)
const AuthStudentsBulkOperationsRoute =
  AuthStudentsBulkOperationsRouteImport.update({
    id: '/bulk-operations',
    path: '/bulk-operations',
    getParentRoute: () => AuthStudentsRoute,
  } as any)
const AuthSpacesAvailabilityRoute = AuthSpacesAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => AuthSpacesRoute,
} as any)
const AuthSettingsSchoolYearsRoute = AuthSettingsSchoolYearsRouteImport.update({
  id: '/school-years',
  path: '/school-years',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsReportCardsRoute = AuthSettingsReportCardsRouteImport.update({
  id: '/report-cards',
  path: '/report-cards',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsProfileRoute = AuthSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsNotificationsRoute =
  AuthSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthSettingsRoute,
  } as any)
const AuthProgramsSubjectsRoute = AuthProgramsSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AuthProgramsRoute,
} as any)
const AuthProgramsCurriculumProgressRoute =
  AuthProgramsCurriculumProgressRouteImport.update({
    id: '/curriculum-progress',
    path: '/curriculum-progress',
    getParentRoute: () => AuthProgramsRoute,
  } as any)
const AuthProgramsCoefficientsRoute =
  AuthProgramsCoefficientsRouteImport.update({
    id: '/coefficients',
    path: '/coefficients',
    getParentRoute: () => AuthProgramsRoute,
  } as any)
const AuthGradesValidationsRoute = AuthGradesValidationsRouteImport.update({
  id: '/validations',
  path: '/validations',
  getParentRoute: () => AuthGradesRoute,
} as any)
const AuthGradesStatisticsRoute = AuthGradesStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AuthGradesRoute,
} as any)
const AuthGradesReportCardsRoute = AuthGradesReportCardsRouteImport.update({
  id: '/report-cards',
  path: '/report-cards',
  getParentRoute: () => AuthGradesRoute,
} as any)
const AuthGradesEntryRoute = AuthGradesEntryRouteImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => AuthGradesRoute,
} as any)
const AuthConductsSettingsRoute = AuthConductsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthConductsRoute,
} as any)
const AuthClassesAssignmentsRoute = AuthClassesAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AuthClassesRoute,
} as any)
const AuthAccountingStudentFeesRoute =
  AuthAccountingStudentFeesRouteImport.update({
    id: '/student-fees',
    path: '/student-fees',
    getParentRoute: () => AuthAccountingRoute,
  } as any)
const AuthAccountingRefundsRoute = AuthAccountingRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => AuthAccountingRoute,
} as any)
const AuthAccountingPaymentsRoute = AuthAccountingPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthAccountingRoute,
} as any)
const AuthAccountingPaymentPlansRoute =
  AuthAccountingPaymentPlansRouteImport.update({
    id: '/payment-plans',
    path: '/payment-plans',
    getParentRoute: () => AuthAccountingRoute,
  } as any)
const AuthAccountingFeeTypesRoute = AuthAccountingFeeTypesRouteImport.update({
  id: '/fee-types',
  path: '/fee-types',
  getParentRoute: () => AuthAccountingRoute,
} as any)
const AuthAccountingFeeStructuresRoute =
  AuthAccountingFeeStructuresRouteImport.update({
    id: '/fee-structures',
    path: '/fee-structures',
    getParentRoute: () => AuthAccountingRoute,
  } as any)
const AuthAccountingDiscountsRoute = AuthAccountingDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AuthAccountingRoute,
} as any)
const AuthAccountingDashboardRoute = AuthAccountingDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthAccountingRoute,
} as any)
const AuthAccountingAccountsRoute = AuthAccountingAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthAccountingRoute,
} as any)
const AuthUsersUsersIndexRoute = AuthUsersUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthUsersRoute,
} as any)
const AuthUsersTeachersIndexRoute = AuthUsersTeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => AuthUsersRoute,
} as any)
const AuthUsersStaffIndexRoute = AuthUsersStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AuthUsersRoute,
} as any)
const AuthUsersRolesIndexRoute = AuthUsersRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthUsersRoute,
} as any)
const AuthStudentsStudentIdIndexRoute =
  AuthStudentsStudentIdIndexRouteImport.update({
    id: '/$studentId/',
    path: '/$studentId/',
    getParentRoute: () => AuthStudentsRoute,
  } as any)
const AuthSpacesClassroomsIndexRoute =
  AuthSpacesClassroomsIndexRouteImport.update({
    id: '/classrooms/',
    path: '/classrooms/',
    getParentRoute: () => AuthSpacesRoute,
  } as any)
const AuthConductsTeacherAttendanceIndexRoute =
  AuthConductsTeacherAttendanceIndexRouteImport.update({
    id: '/teacher-attendance/',
    path: '/teacher-attendance/',
    getParentRoute: () => AuthConductsRoute,
  } as any)
const AuthConductsStudentAttendanceIndexRoute =
  AuthConductsStudentAttendanceIndexRouteImport.update({
    id: '/student-attendance/',
    path: '/student-attendance/',
    getParentRoute: () => AuthConductsRoute,
  } as any)
const AuthConductsConductIndexRoute =
  AuthConductsConductIndexRouteImport.update({
    id: '/conduct/',
    path: '/conduct/',
    getParentRoute: () => AuthConductsRoute,
  } as any)
const AuthConductsAlertsIndexRoute = AuthConductsAlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => AuthConductsRoute,
} as any)
const AuthClassesClassIdIndexRoute = AuthClassesClassIdIndexRouteImport.update({
  id: '/$classId/',
  path: '/$classId/',
  getParentRoute: () => AuthClassesRoute,
} as any)
const AuthUsersUsersNewRoute = AuthUsersUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AuthUsersRoute,
} as any)
const AuthUsersUsersImportRoute = AuthUsersUsersImportRouteImport.update({
  id: '/users/import',
  path: '/users/import',
  getParentRoute: () => AuthUsersRoute,
} as any)
const AuthUsersTeachersNewRoute = AuthUsersTeachersNewRouteImport.update({
  id: '/teachers/new',
  path: '/teachers/new',
  getParentRoute: () => AuthUsersRoute,
} as any)
const AuthUsersStaffNewRoute = AuthUsersStaffNewRouteImport.update({
  id: '/staff/new',
  path: '/staff/new',
  getParentRoute: () => AuthUsersRoute,
} as any)
const AuthUsersRolesNewRoute = AuthUsersRolesNewRouteImport.update({
  id: '/roles/new',
  path: '/roles/new',
  getParentRoute: () => AuthUsersRoute,
} as any)
const AuthStudentsStudentIdEditRoute =
  AuthStudentsStudentIdEditRouteImport.update({
    id: '/$studentId/edit',
    path: '/$studentId/edit',
    getParentRoute: () => AuthStudentsRoute,
  } as any)
const AuthConductsTeacherAttendanceReportsRoute =
  AuthConductsTeacherAttendanceReportsRouteImport.update({
    id: '/teacher-attendance/reports',
    path: '/teacher-attendance/reports',
    getParentRoute: () => AuthConductsRoute,
  } as any)
const AuthConductsStudentAttendanceStatisticsRoute =
  AuthConductsStudentAttendanceStatisticsRouteImport.update({
    id: '/student-attendance/statistics',
    path: '/student-attendance/statistics',
    getParentRoute: () => AuthConductsRoute,
  } as any)
const AuthConductsStudentAttendanceHistoryRoute =
  AuthConductsStudentAttendanceHistoryRouteImport.update({
    id: '/student-attendance/history',
    path: '/student-attendance/history',
    getParentRoute: () => AuthConductsRoute,
  } as any)
const AuthConductsConductReportsRoute =
  AuthConductsConductReportsRouteImport.update({
    id: '/conduct/reports',
    path: '/conduct/reports',
    getParentRoute: () => AuthConductsRoute,
  } as any)
const AuthConductsConductNewRoute = AuthConductsConductNewRouteImport.update({
  id: '/conduct/new',
  path: '/conduct/new',
  getParentRoute: () => AuthConductsRoute,
} as any)
const AuthConductsConductRecordIdRoute =
  AuthConductsConductRecordIdRouteImport.update({
    id: '/conduct/$recordId',
    path: '/conduct/$recordId',
    getParentRoute: () => AuthConductsRoute,
  } as any)
const AuthClassesClassIdEditRoute = AuthClassesClassIdEditRouteImport.update({
  id: '/$classId/edit',
  path: '/$classId/edit',
  getParentRoute: () => AuthClassesRoute,
} as any)
const AuthUsersUsersUserIdIndexRoute =
  AuthUsersUsersUserIdIndexRouteImport.update({
    id: '/users/$userId/',
    path: '/users/$userId/',
    getParentRoute: () => AuthUsersRoute,
  } as any)
const AuthUsersTeachersTeacherIdIndexRoute =
  AuthUsersTeachersTeacherIdIndexRouteImport.update({
    id: '/teachers/$teacherId/',
    path: '/teachers/$teacherId/',
    getParentRoute: () => AuthUsersRoute,
  } as any)
const AuthUsersStaffStaffIdIndexRoute =
  AuthUsersStaffStaffIdIndexRouteImport.update({
    id: '/staff/$staffId/',
    path: '/staff/$staffId/',
    getParentRoute: () => AuthUsersRoute,
  } as any)
const AuthUsersRolesRoleIdIndexRoute =
  AuthUsersRolesRoleIdIndexRouteImport.update({
    id: '/roles/$roleId/',
    path: '/roles/$roleId/',
    getParentRoute: () => AuthUsersRoute,
  } as any)
const AuthSpacesClassroomsClassroomIdIndexRoute =
  AuthSpacesClassroomsClassroomIdIndexRouteImport.update({
    id: '/classrooms/$classroomId/',
    path: '/classrooms/$classroomId/',
    getParentRoute: () => AuthSpacesRoute,
  } as any)
const AuthUsersUsersUserIdEditRoute =
  AuthUsersUsersUserIdEditRouteImport.update({
    id: '/users/$userId/edit',
    path: '/users/$userId/edit',
    getParentRoute: () => AuthUsersRoute,
  } as any)
const AuthUsersTeachersTeacherIdEditRoute =
  AuthUsersTeachersTeacherIdEditRouteImport.update({
    id: '/teachers/$teacherId/edit',
    path: '/teachers/$teacherId/edit',
    getParentRoute: () => AuthUsersRoute,
  } as any)
const AuthUsersStaffStaffIdEditRoute =
  AuthUsersStaffStaffIdEditRouteImport.update({
    id: '/staff/$staffId/edit',
    path: '/staff/$staffId/edit',
    getParentRoute: () => AuthUsersRoute,
  } as any)
const AuthUsersRolesRoleIdEditRoute =
  AuthUsersRolesRoleIdEditRouteImport.update({
    id: '/roles/$roleId/edit',
    path: '/roles/$roleId/edit',
    getParentRoute: () => AuthUsersRoute,
  } as any)
const AuthSpacesClassroomsClassroomIdEditRoute =
  AuthSpacesClassroomsClassroomIdEditRouteImport.update({
    id: '/classrooms/$classroomId/edit',
    path: '/classrooms/$classroomId/edit',
    getParentRoute: () => AuthSpacesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/accounting': typeof AuthAccountingRouteWithChildren
  '/classes': typeof AuthClassesRouteWithChildren
  '/conducts': typeof AuthConductsRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/grades': typeof AuthGradesRouteWithChildren
  '/programs': typeof AuthProgramsRouteWithChildren
  '/schedules': typeof AuthSchedulesRoute
  '/settings': typeof AuthSettingsRouteWithChildren
  '/spaces': typeof AuthSpacesRouteWithChildren
  '/students': typeof AuthStudentsRouteWithChildren
  '/users': typeof AuthUsersRouteWithChildren
  '/accounting/accounts': typeof AuthAccountingAccountsRoute
  '/accounting/dashboard': typeof AuthAccountingDashboardRoute
  '/accounting/discounts': typeof AuthAccountingDiscountsRoute
  '/accounting/fee-structures': typeof AuthAccountingFeeStructuresRoute
  '/accounting/fee-types': typeof AuthAccountingFeeTypesRoute
  '/accounting/payment-plans': typeof AuthAccountingPaymentPlansRoute
  '/accounting/payments': typeof AuthAccountingPaymentsRoute
  '/accounting/refunds': typeof AuthAccountingRefundsRoute
  '/accounting/student-fees': typeof AuthAccountingStudentFeesRoute
  '/classes/assignments': typeof AuthClassesAssignmentsRoute
  '/conducts/settings': typeof AuthConductsSettingsRoute
  '/grades/entry': typeof AuthGradesEntryRoute
  '/grades/report-cards': typeof AuthGradesReportCardsRoute
  '/grades/statistics': typeof AuthGradesStatisticsRoute
  '/grades/validations': typeof AuthGradesValidationsRoute
  '/programs/coefficients': typeof AuthProgramsCoefficientsRoute
  '/programs/curriculum-progress': typeof AuthProgramsCurriculumProgressRoute
  '/programs/subjects': typeof AuthProgramsSubjectsRoute
  '/settings/notifications': typeof AuthSettingsNotificationsRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/settings/report-cards': typeof AuthSettingsReportCardsRoute
  '/settings/school-years': typeof AuthSettingsSchoolYearsRoute
  '/spaces/availability': typeof AuthSpacesAvailabilityRoute
  '/students/bulk-operations': typeof AuthStudentsBulkOperationsRoute
  '/students/enrollments': typeof AuthStudentsEnrollmentsRoute
  '/students/new': typeof AuthStudentsNewRoute
  '/students/parents': typeof AuthStudentsParentsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/accounting/': typeof AuthAccountingIndexRoute
  '/classes/': typeof AuthClassesIndexRoute
  '/conducts/': typeof AuthConductsIndexRoute
  '/grades/': typeof AuthGradesIndexRoute
  '/settings/': typeof AuthSettingsIndexRoute
  '/spaces/': typeof AuthSpacesIndexRoute
  '/students/': typeof AuthStudentsIndexRoute
  '/users/': typeof AuthUsersIndexRoute
  '/classes/$classId/edit': typeof AuthClassesClassIdEditRoute
  '/conducts/conduct/$recordId': typeof AuthConductsConductRecordIdRoute
  '/conducts/conduct/new': typeof AuthConductsConductNewRoute
  '/conducts/conduct/reports': typeof AuthConductsConductReportsRoute
  '/conducts/student-attendance/history': typeof AuthConductsStudentAttendanceHistoryRoute
  '/conducts/student-attendance/statistics': typeof AuthConductsStudentAttendanceStatisticsRoute
  '/conducts/teacher-attendance/reports': typeof AuthConductsTeacherAttendanceReportsRoute
  '/students/$studentId/edit': typeof AuthStudentsStudentIdEditRoute
  '/users/roles/new': typeof AuthUsersRolesNewRoute
  '/users/staff/new': typeof AuthUsersStaffNewRoute
  '/users/teachers/new': typeof AuthUsersTeachersNewRoute
  '/users/users/import': typeof AuthUsersUsersImportRoute
  '/users/users/new': typeof AuthUsersUsersNewRoute
  '/classes/$classId': typeof AuthClassesClassIdIndexRoute
  '/conducts/alerts': typeof AuthConductsAlertsIndexRoute
  '/conducts/conduct': typeof AuthConductsConductIndexRoute
  '/conducts/student-attendance': typeof AuthConductsStudentAttendanceIndexRoute
  '/conducts/teacher-attendance': typeof AuthConductsTeacherAttendanceIndexRoute
  '/spaces/classrooms': typeof AuthSpacesClassroomsIndexRoute
  '/students/$studentId': typeof AuthStudentsStudentIdIndexRoute
  '/users/roles': typeof AuthUsersRolesIndexRoute
  '/users/staff': typeof AuthUsersStaffIndexRoute
  '/users/teachers': typeof AuthUsersTeachersIndexRoute
  '/users/users': typeof AuthUsersUsersIndexRoute
  '/spaces/classrooms/$classroomId/edit': typeof AuthSpacesClassroomsClassroomIdEditRoute
  '/users/roles/$roleId/edit': typeof AuthUsersRolesRoleIdEditRoute
  '/users/staff/$staffId/edit': typeof AuthUsersStaffStaffIdEditRoute
  '/users/teachers/$teacherId/edit': typeof AuthUsersTeachersTeacherIdEditRoute
  '/users/users/$userId/edit': typeof AuthUsersUsersUserIdEditRoute
  '/spaces/classrooms/$classroomId': typeof AuthSpacesClassroomsClassroomIdIndexRoute
  '/users/roles/$roleId': typeof AuthUsersRolesRoleIdIndexRoute
  '/users/staff/$staffId': typeof AuthUsersStaffStaffIdIndexRoute
  '/users/teachers/$teacherId': typeof AuthUsersTeachersTeacherIdIndexRoute
  '/users/users/$userId': typeof AuthUsersUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthDashboardRoute
  '/programs': typeof AuthProgramsRouteWithChildren
  '/schedules': typeof AuthSchedulesRoute
  '/accounting/accounts': typeof AuthAccountingAccountsRoute
  '/accounting/dashboard': typeof AuthAccountingDashboardRoute
  '/accounting/discounts': typeof AuthAccountingDiscountsRoute
  '/accounting/fee-structures': typeof AuthAccountingFeeStructuresRoute
  '/accounting/fee-types': typeof AuthAccountingFeeTypesRoute
  '/accounting/payment-plans': typeof AuthAccountingPaymentPlansRoute
  '/accounting/payments': typeof AuthAccountingPaymentsRoute
  '/accounting/refunds': typeof AuthAccountingRefundsRoute
  '/accounting/student-fees': typeof AuthAccountingStudentFeesRoute
  '/classes/assignments': typeof AuthClassesAssignmentsRoute
  '/conducts/settings': typeof AuthConductsSettingsRoute
  '/grades/entry': typeof AuthGradesEntryRoute
  '/grades/report-cards': typeof AuthGradesReportCardsRoute
  '/grades/statistics': typeof AuthGradesStatisticsRoute
  '/grades/validations': typeof AuthGradesValidationsRoute
  '/programs/coefficients': typeof AuthProgramsCoefficientsRoute
  '/programs/curriculum-progress': typeof AuthProgramsCurriculumProgressRoute
  '/programs/subjects': typeof AuthProgramsSubjectsRoute
  '/settings/notifications': typeof AuthSettingsNotificationsRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/settings/report-cards': typeof AuthSettingsReportCardsRoute
  '/settings/school-years': typeof AuthSettingsSchoolYearsRoute
  '/spaces/availability': typeof AuthSpacesAvailabilityRoute
  '/students/bulk-operations': typeof AuthStudentsBulkOperationsRoute
  '/students/enrollments': typeof AuthStudentsEnrollmentsRoute
  '/students/new': typeof AuthStudentsNewRoute
  '/students/parents': typeof AuthStudentsParentsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/accounting': typeof AuthAccountingIndexRoute
  '/classes': typeof AuthClassesIndexRoute
  '/conducts': typeof AuthConductsIndexRoute
  '/grades': typeof AuthGradesIndexRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/spaces': typeof AuthSpacesIndexRoute
  '/students': typeof AuthStudentsIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/classes/$classId/edit': typeof AuthClassesClassIdEditRoute
  '/conducts/conduct/$recordId': typeof AuthConductsConductRecordIdRoute
  '/conducts/conduct/new': typeof AuthConductsConductNewRoute
  '/conducts/conduct/reports': typeof AuthConductsConductReportsRoute
  '/conducts/student-attendance/history': typeof AuthConductsStudentAttendanceHistoryRoute
  '/conducts/student-attendance/statistics': typeof AuthConductsStudentAttendanceStatisticsRoute
  '/conducts/teacher-attendance/reports': typeof AuthConductsTeacherAttendanceReportsRoute
  '/students/$studentId/edit': typeof AuthStudentsStudentIdEditRoute
  '/users/roles/new': typeof AuthUsersRolesNewRoute
  '/users/staff/new': typeof AuthUsersStaffNewRoute
  '/users/teachers/new': typeof AuthUsersTeachersNewRoute
  '/users/users/import': typeof AuthUsersUsersImportRoute
  '/users/users/new': typeof AuthUsersUsersNewRoute
  '/classes/$classId': typeof AuthClassesClassIdIndexRoute
  '/conducts/alerts': typeof AuthConductsAlertsIndexRoute
  '/conducts/conduct': typeof AuthConductsConductIndexRoute
  '/conducts/student-attendance': typeof AuthConductsStudentAttendanceIndexRoute
  '/conducts/teacher-attendance': typeof AuthConductsTeacherAttendanceIndexRoute
  '/spaces/classrooms': typeof AuthSpacesClassroomsIndexRoute
  '/students/$studentId': typeof AuthStudentsStudentIdIndexRoute
  '/users/roles': typeof AuthUsersRolesIndexRoute
  '/users/staff': typeof AuthUsersStaffIndexRoute
  '/users/teachers': typeof AuthUsersTeachersIndexRoute
  '/users/users': typeof AuthUsersUsersIndexRoute
  '/spaces/classrooms/$classroomId/edit': typeof AuthSpacesClassroomsClassroomIdEditRoute
  '/users/roles/$roleId/edit': typeof AuthUsersRolesRoleIdEditRoute
  '/users/staff/$staffId/edit': typeof AuthUsersStaffStaffIdEditRoute
  '/users/teachers/$teacherId/edit': typeof AuthUsersTeachersTeacherIdEditRoute
  '/users/users/$userId/edit': typeof AuthUsersUsersUserIdEditRoute
  '/spaces/classrooms/$classroomId': typeof AuthSpacesClassroomsClassroomIdIndexRoute
  '/users/roles/$roleId': typeof AuthUsersRolesRoleIdIndexRoute
  '/users/staff/$staffId': typeof AuthUsersStaffStaffIdIndexRoute
  '/users/teachers/$teacherId': typeof AuthUsersTeachersTeacherIdIndexRoute
  '/users/users/$userId': typeof AuthUsersUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_auth/accounting': typeof AuthAccountingRouteWithChildren
  '/_auth/classes': typeof AuthClassesRouteWithChildren
  '/_auth/conducts': typeof AuthConductsRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/grades': typeof AuthGradesRouteWithChildren
  '/_auth/programs': typeof AuthProgramsRouteWithChildren
  '/_auth/schedules': typeof AuthSchedulesRoute
  '/_auth/settings': typeof AuthSettingsRouteWithChildren
  '/_auth/spaces': typeof AuthSpacesRouteWithChildren
  '/_auth/students': typeof AuthStudentsRouteWithChildren
  '/_auth/users': typeof AuthUsersRouteWithChildren
  '/_auth/accounting/accounts': typeof AuthAccountingAccountsRoute
  '/_auth/accounting/dashboard': typeof AuthAccountingDashboardRoute
  '/_auth/accounting/discounts': typeof AuthAccountingDiscountsRoute
  '/_auth/accounting/fee-structures': typeof AuthAccountingFeeStructuresRoute
  '/_auth/accounting/fee-types': typeof AuthAccountingFeeTypesRoute
  '/_auth/accounting/payment-plans': typeof AuthAccountingPaymentPlansRoute
  '/_auth/accounting/payments': typeof AuthAccountingPaymentsRoute
  '/_auth/accounting/refunds': typeof AuthAccountingRefundsRoute
  '/_auth/accounting/student-fees': typeof AuthAccountingStudentFeesRoute
  '/_auth/classes/assignments': typeof AuthClassesAssignmentsRoute
  '/_auth/conducts/settings': typeof AuthConductsSettingsRoute
  '/_auth/grades/entry': typeof AuthGradesEntryRoute
  '/_auth/grades/report-cards': typeof AuthGradesReportCardsRoute
  '/_auth/grades/statistics': typeof AuthGradesStatisticsRoute
  '/_auth/grades/validations': typeof AuthGradesValidationsRoute
  '/_auth/programs/coefficients': typeof AuthProgramsCoefficientsRoute
  '/_auth/programs/curriculum-progress': typeof AuthProgramsCurriculumProgressRoute
  '/_auth/programs/subjects': typeof AuthProgramsSubjectsRoute
  '/_auth/settings/notifications': typeof AuthSettingsNotificationsRoute
  '/_auth/settings/profile': typeof AuthSettingsProfileRoute
  '/_auth/settings/report-cards': typeof AuthSettingsReportCardsRoute
  '/_auth/settings/school-years': typeof AuthSettingsSchoolYearsRoute
  '/_auth/spaces/availability': typeof AuthSpacesAvailabilityRoute
  '/_auth/students/bulk-operations': typeof AuthStudentsBulkOperationsRoute
  '/_auth/students/enrollments': typeof AuthStudentsEnrollmentsRoute
  '/_auth/students/new': typeof AuthStudentsNewRoute
  '/_auth/students/parents': typeof AuthStudentsParentsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/accounting/': typeof AuthAccountingIndexRoute
  '/_auth/classes/': typeof AuthClassesIndexRoute
  '/_auth/conducts/': typeof AuthConductsIndexRoute
  '/_auth/grades/': typeof AuthGradesIndexRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
  '/_auth/spaces/': typeof AuthSpacesIndexRoute
  '/_auth/students/': typeof AuthStudentsIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
  '/_auth/classes/$classId/edit': typeof AuthClassesClassIdEditRoute
  '/_auth/conducts/conduct/$recordId': typeof AuthConductsConductRecordIdRoute
  '/_auth/conducts/conduct/new': typeof AuthConductsConductNewRoute
  '/_auth/conducts/conduct/reports': typeof AuthConductsConductReportsRoute
  '/_auth/conducts/student-attendance/history': typeof AuthConductsStudentAttendanceHistoryRoute
  '/_auth/conducts/student-attendance/statistics': typeof AuthConductsStudentAttendanceStatisticsRoute
  '/_auth/conducts/teacher-attendance/reports': typeof AuthConductsTeacherAttendanceReportsRoute
  '/_auth/students/$studentId/edit': typeof AuthStudentsStudentIdEditRoute
  '/_auth/users/roles/new': typeof AuthUsersRolesNewRoute
  '/_auth/users/staff/new': typeof AuthUsersStaffNewRoute
  '/_auth/users/teachers/new': typeof AuthUsersTeachersNewRoute
  '/_auth/users/users/import': typeof AuthUsersUsersImportRoute
  '/_auth/users/users/new': typeof AuthUsersUsersNewRoute
  '/_auth/classes/$classId/': typeof AuthClassesClassIdIndexRoute
  '/_auth/conducts/alerts/': typeof AuthConductsAlertsIndexRoute
  '/_auth/conducts/conduct/': typeof AuthConductsConductIndexRoute
  '/_auth/conducts/student-attendance/': typeof AuthConductsStudentAttendanceIndexRoute
  '/_auth/conducts/teacher-attendance/': typeof AuthConductsTeacherAttendanceIndexRoute
  '/_auth/spaces/classrooms/': typeof AuthSpacesClassroomsIndexRoute
  '/_auth/students/$studentId/': typeof AuthStudentsStudentIdIndexRoute
  '/_auth/users/roles/': typeof AuthUsersRolesIndexRoute
  '/_auth/users/staff/': typeof AuthUsersStaffIndexRoute
  '/_auth/users/teachers/': typeof AuthUsersTeachersIndexRoute
  '/_auth/users/users/': typeof AuthUsersUsersIndexRoute
  '/_auth/spaces/classrooms/$classroomId/edit': typeof AuthSpacesClassroomsClassroomIdEditRoute
  '/_auth/users/roles/$roleId/edit': typeof AuthUsersRolesRoleIdEditRoute
  '/_auth/users/staff/$staffId/edit': typeof AuthUsersStaffStaffIdEditRoute
  '/_auth/users/teachers/$teacherId/edit': typeof AuthUsersTeachersTeacherIdEditRoute
  '/_auth/users/users/$userId/edit': typeof AuthUsersUsersUserIdEditRoute
  '/_auth/spaces/classrooms/$classroomId/': typeof AuthSpacesClassroomsClassroomIdIndexRoute
  '/_auth/users/roles/$roleId/': typeof AuthUsersRolesRoleIdIndexRoute
  '/_auth/users/staff/$staffId/': typeof AuthUsersStaffStaffIdIndexRoute
  '/_auth/users/teachers/$teacherId/': typeof AuthUsersTeachersTeacherIdIndexRoute
  '/_auth/users/users/$userId/': typeof AuthUsersUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/accounting'
    | '/classes'
    | '/conducts'
    | '/dashboard'
    | '/grades'
    | '/programs'
    | '/schedules'
    | '/settings'
    | '/spaces'
    | '/students'
    | '/users'
    | '/accounting/accounts'
    | '/accounting/dashboard'
    | '/accounting/discounts'
    | '/accounting/fee-structures'
    | '/accounting/fee-types'
    | '/accounting/payment-plans'
    | '/accounting/payments'
    | '/accounting/refunds'
    | '/accounting/student-fees'
    | '/classes/assignments'
    | '/conducts/settings'
    | '/grades/entry'
    | '/grades/report-cards'
    | '/grades/statistics'
    | '/grades/validations'
    | '/programs/coefficients'
    | '/programs/curriculum-progress'
    | '/programs/subjects'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/report-cards'
    | '/settings/school-years'
    | '/spaces/availability'
    | '/students/bulk-operations'
    | '/students/enrollments'
    | '/students/new'
    | '/students/parents'
    | '/api/auth/$'
    | '/accounting/'
    | '/classes/'
    | '/conducts/'
    | '/grades/'
    | '/settings/'
    | '/spaces/'
    | '/students/'
    | '/users/'
    | '/classes/$classId/edit'
    | '/conducts/conduct/$recordId'
    | '/conducts/conduct/new'
    | '/conducts/conduct/reports'
    | '/conducts/student-attendance/history'
    | '/conducts/student-attendance/statistics'
    | '/conducts/teacher-attendance/reports'
    | '/students/$studentId/edit'
    | '/users/roles/new'
    | '/users/staff/new'
    | '/users/teachers/new'
    | '/users/users/import'
    | '/users/users/new'
    | '/classes/$classId'
    | '/conducts/alerts'
    | '/conducts/conduct'
    | '/conducts/student-attendance'
    | '/conducts/teacher-attendance'
    | '/spaces/classrooms'
    | '/students/$studentId'
    | '/users/roles'
    | '/users/staff'
    | '/users/teachers'
    | '/users/users'
    | '/spaces/classrooms/$classroomId/edit'
    | '/users/roles/$roleId/edit'
    | '/users/staff/$staffId/edit'
    | '/users/teachers/$teacherId/edit'
    | '/users/users/$userId/edit'
    | '/spaces/classrooms/$classroomId'
    | '/users/roles/$roleId'
    | '/users/staff/$staffId'
    | '/users/teachers/$teacherId'
    | '/users/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/dashboard'
    | '/programs'
    | '/schedules'
    | '/accounting/accounts'
    | '/accounting/dashboard'
    | '/accounting/discounts'
    | '/accounting/fee-structures'
    | '/accounting/fee-types'
    | '/accounting/payment-plans'
    | '/accounting/payments'
    | '/accounting/refunds'
    | '/accounting/student-fees'
    | '/classes/assignments'
    | '/conducts/settings'
    | '/grades/entry'
    | '/grades/report-cards'
    | '/grades/statistics'
    | '/grades/validations'
    | '/programs/coefficients'
    | '/programs/curriculum-progress'
    | '/programs/subjects'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/report-cards'
    | '/settings/school-years'
    | '/spaces/availability'
    | '/students/bulk-operations'
    | '/students/enrollments'
    | '/students/new'
    | '/students/parents'
    | '/api/auth/$'
    | '/accounting'
    | '/classes'
    | '/conducts'
    | '/grades'
    | '/settings'
    | '/spaces'
    | '/students'
    | '/users'
    | '/classes/$classId/edit'
    | '/conducts/conduct/$recordId'
    | '/conducts/conduct/new'
    | '/conducts/conduct/reports'
    | '/conducts/student-attendance/history'
    | '/conducts/student-attendance/statistics'
    | '/conducts/teacher-attendance/reports'
    | '/students/$studentId/edit'
    | '/users/roles/new'
    | '/users/staff/new'
    | '/users/teachers/new'
    | '/users/users/import'
    | '/users/users/new'
    | '/classes/$classId'
    | '/conducts/alerts'
    | '/conducts/conduct'
    | '/conducts/student-attendance'
    | '/conducts/teacher-attendance'
    | '/spaces/classrooms'
    | '/students/$studentId'
    | '/users/roles'
    | '/users/staff'
    | '/users/teachers'
    | '/users/users'
    | '/spaces/classrooms/$classroomId/edit'
    | '/users/roles/$roleId/edit'
    | '/users/staff/$staffId/edit'
    | '/users/teachers/$teacherId/edit'
    | '/users/users/$userId/edit'
    | '/spaces/classrooms/$classroomId'
    | '/users/roles/$roleId'
    | '/users/staff/$staffId'
    | '/users/teachers/$teacherId'
    | '/users/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/reset-password'
    | '/_auth/accounting'
    | '/_auth/classes'
    | '/_auth/conducts'
    | '/_auth/dashboard'
    | '/_auth/grades'
    | '/_auth/programs'
    | '/_auth/schedules'
    | '/_auth/settings'
    | '/_auth/spaces'
    | '/_auth/students'
    | '/_auth/users'
    | '/_auth/accounting/accounts'
    | '/_auth/accounting/dashboard'
    | '/_auth/accounting/discounts'
    | '/_auth/accounting/fee-structures'
    | '/_auth/accounting/fee-types'
    | '/_auth/accounting/payment-plans'
    | '/_auth/accounting/payments'
    | '/_auth/accounting/refunds'
    | '/_auth/accounting/student-fees'
    | '/_auth/classes/assignments'
    | '/_auth/conducts/settings'
    | '/_auth/grades/entry'
    | '/_auth/grades/report-cards'
    | '/_auth/grades/statistics'
    | '/_auth/grades/validations'
    | '/_auth/programs/coefficients'
    | '/_auth/programs/curriculum-progress'
    | '/_auth/programs/subjects'
    | '/_auth/settings/notifications'
    | '/_auth/settings/profile'
    | '/_auth/settings/report-cards'
    | '/_auth/settings/school-years'
    | '/_auth/spaces/availability'
    | '/_auth/students/bulk-operations'
    | '/_auth/students/enrollments'
    | '/_auth/students/new'
    | '/_auth/students/parents'
    | '/api/auth/$'
    | '/_auth/accounting/'
    | '/_auth/classes/'
    | '/_auth/conducts/'
    | '/_auth/grades/'
    | '/_auth/settings/'
    | '/_auth/spaces/'
    | '/_auth/students/'
    | '/_auth/users/'
    | '/_auth/classes/$classId/edit'
    | '/_auth/conducts/conduct/$recordId'
    | '/_auth/conducts/conduct/new'
    | '/_auth/conducts/conduct/reports'
    | '/_auth/conducts/student-attendance/history'
    | '/_auth/conducts/student-attendance/statistics'
    | '/_auth/conducts/teacher-attendance/reports'
    | '/_auth/students/$studentId/edit'
    | '/_auth/users/roles/new'
    | '/_auth/users/staff/new'
    | '/_auth/users/teachers/new'
    | '/_auth/users/users/import'
    | '/_auth/users/users/new'
    | '/_auth/classes/$classId/'
    | '/_auth/conducts/alerts/'
    | '/_auth/conducts/conduct/'
    | '/_auth/conducts/student-attendance/'
    | '/_auth/conducts/teacher-attendance/'
    | '/_auth/spaces/classrooms/'
    | '/_auth/students/$studentId/'
    | '/_auth/users/roles/'
    | '/_auth/users/staff/'
    | '/_auth/users/teachers/'
    | '/_auth/users/users/'
    | '/_auth/spaces/classrooms/$classroomId/edit'
    | '/_auth/users/roles/$roleId/edit'
    | '/_auth/users/staff/$staffId/edit'
    | '/_auth/users/teachers/$teacherId/edit'
    | '/_auth/users/users/$userId/edit'
    | '/_auth/spaces/classrooms/$classroomId/'
    | '/_auth/users/roles/$roleId/'
    | '/_auth/users/staff/$staffId/'
    | '/_auth/users/teachers/$teacherId/'
    | '/_auth/users/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/users': {
      id: '/_auth/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/students': {
      id: '/_auth/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthStudentsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/spaces': {
      id: '/_auth/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof AuthSpacesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/schedules': {
      id: '/_auth/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AuthSchedulesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/programs': {
      id: '/_auth/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof AuthProgramsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/grades': {
      id: '/_auth/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof AuthGradesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/conducts': {
      id: '/_auth/conducts'
      path: '/conducts'
      fullPath: '/conducts'
      preLoaderRoute: typeof AuthConductsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/classes': {
      id: '/_auth/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthClassesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/accounting': {
      id: '/_auth/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AuthAccountingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthUsersIndexRouteImport
      parentRoute: typeof AuthUsersRoute
    }
    '/_auth/students/': {
      id: '/_auth/students/'
      path: '/'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthStudentsIndexRouteImport
      parentRoute: typeof AuthStudentsRoute
    }
    '/_auth/spaces/': {
      id: '/_auth/spaces/'
      path: '/'
      fullPath: '/spaces/'
      preLoaderRoute: typeof AuthSpacesIndexRouteImport
      parentRoute: typeof AuthSpacesRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/grades/': {
      id: '/_auth/grades/'
      path: '/'
      fullPath: '/grades/'
      preLoaderRoute: typeof AuthGradesIndexRouteImport
      parentRoute: typeof AuthGradesRoute
    }
    '/_auth/conducts/': {
      id: '/_auth/conducts/'
      path: '/'
      fullPath: '/conducts/'
      preLoaderRoute: typeof AuthConductsIndexRouteImport
      parentRoute: typeof AuthConductsRoute
    }
    '/_auth/classes/': {
      id: '/_auth/classes/'
      path: '/'
      fullPath: '/classes/'
      preLoaderRoute: typeof AuthClassesIndexRouteImport
      parentRoute: typeof AuthClassesRoute
    }
    '/_auth/accounting/': {
      id: '/_auth/accounting/'
      path: '/'
      fullPath: '/accounting/'
      preLoaderRoute: typeof AuthAccountingIndexRouteImport
      parentRoute: typeof AuthAccountingRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/students/parents': {
      id: '/_auth/students/parents'
      path: '/parents'
      fullPath: '/students/parents'
      preLoaderRoute: typeof AuthStudentsParentsRouteImport
      parentRoute: typeof AuthStudentsRoute
    }
    '/_auth/students/new': {
      id: '/_auth/students/new'
      path: '/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof AuthStudentsNewRouteImport
      parentRoute: typeof AuthStudentsRoute
    }
    '/_auth/students/enrollments': {
      id: '/_auth/students/enrollments'
      path: '/enrollments'
      fullPath: '/students/enrollments'
      preLoaderRoute: typeof AuthStudentsEnrollmentsRouteImport
      parentRoute: typeof AuthStudentsRoute
    }
    '/_auth/students/bulk-operations': {
      id: '/_auth/students/bulk-operations'
      path: '/bulk-operations'
      fullPath: '/students/bulk-operations'
      preLoaderRoute: typeof AuthStudentsBulkOperationsRouteImport
      parentRoute: typeof AuthStudentsRoute
    }
    '/_auth/spaces/availability': {
      id: '/_auth/spaces/availability'
      path: '/availability'
      fullPath: '/spaces/availability'
      preLoaderRoute: typeof AuthSpacesAvailabilityRouteImport
      parentRoute: typeof AuthSpacesRoute
    }
    '/_auth/settings/school-years': {
      id: '/_auth/settings/school-years'
      path: '/school-years'
      fullPath: '/settings/school-years'
      preLoaderRoute: typeof AuthSettingsSchoolYearsRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/report-cards': {
      id: '/_auth/settings/report-cards'
      path: '/report-cards'
      fullPath: '/settings/report-cards'
      preLoaderRoute: typeof AuthSettingsReportCardsRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/profile': {
      id: '/_auth/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthSettingsProfileRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/notifications': {
      id: '/_auth/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthSettingsNotificationsRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/programs/subjects': {
      id: '/_auth/programs/subjects'
      path: '/subjects'
      fullPath: '/programs/subjects'
      preLoaderRoute: typeof AuthProgramsSubjectsRouteImport
      parentRoute: typeof AuthProgramsRoute
    }
    '/_auth/programs/curriculum-progress': {
      id: '/_auth/programs/curriculum-progress'
      path: '/curriculum-progress'
      fullPath: '/programs/curriculum-progress'
      preLoaderRoute: typeof AuthProgramsCurriculumProgressRouteImport
      parentRoute: typeof AuthProgramsRoute
    }
    '/_auth/programs/coefficients': {
      id: '/_auth/programs/coefficients'
      path: '/coefficients'
      fullPath: '/programs/coefficients'
      preLoaderRoute: typeof AuthProgramsCoefficientsRouteImport
      parentRoute: typeof AuthProgramsRoute
    }
    '/_auth/grades/validations': {
      id: '/_auth/grades/validations'
      path: '/validations'
      fullPath: '/grades/validations'
      preLoaderRoute: typeof AuthGradesValidationsRouteImport
      parentRoute: typeof AuthGradesRoute
    }
    '/_auth/grades/statistics': {
      id: '/_auth/grades/statistics'
      path: '/statistics'
      fullPath: '/grades/statistics'
      preLoaderRoute: typeof AuthGradesStatisticsRouteImport
      parentRoute: typeof AuthGradesRoute
    }
    '/_auth/grades/report-cards': {
      id: '/_auth/grades/report-cards'
      path: '/report-cards'
      fullPath: '/grades/report-cards'
      preLoaderRoute: typeof AuthGradesReportCardsRouteImport
      parentRoute: typeof AuthGradesRoute
    }
    '/_auth/grades/entry': {
      id: '/_auth/grades/entry'
      path: '/entry'
      fullPath: '/grades/entry'
      preLoaderRoute: typeof AuthGradesEntryRouteImport
      parentRoute: typeof AuthGradesRoute
    }
    '/_auth/conducts/settings': {
      id: '/_auth/conducts/settings'
      path: '/settings'
      fullPath: '/conducts/settings'
      preLoaderRoute: typeof AuthConductsSettingsRouteImport
      parentRoute: typeof AuthConductsRoute
    }
    '/_auth/classes/assignments': {
      id: '/_auth/classes/assignments'
      path: '/assignments'
      fullPath: '/classes/assignments'
      preLoaderRoute: typeof AuthClassesAssignmentsRouteImport
      parentRoute: typeof AuthClassesRoute
    }
    '/_auth/accounting/student-fees': {
      id: '/_auth/accounting/student-fees'
      path: '/student-fees'
      fullPath: '/accounting/student-fees'
      preLoaderRoute: typeof AuthAccountingStudentFeesRouteImport
      parentRoute: typeof AuthAccountingRoute
    }
    '/_auth/accounting/refunds': {
      id: '/_auth/accounting/refunds'
      path: '/refunds'
      fullPath: '/accounting/refunds'
      preLoaderRoute: typeof AuthAccountingRefundsRouteImport
      parentRoute: typeof AuthAccountingRoute
    }
    '/_auth/accounting/payments': {
      id: '/_auth/accounting/payments'
      path: '/payments'
      fullPath: '/accounting/payments'
      preLoaderRoute: typeof AuthAccountingPaymentsRouteImport
      parentRoute: typeof AuthAccountingRoute
    }
    '/_auth/accounting/payment-plans': {
      id: '/_auth/accounting/payment-plans'
      path: '/payment-plans'
      fullPath: '/accounting/payment-plans'
      preLoaderRoute: typeof AuthAccountingPaymentPlansRouteImport
      parentRoute: typeof AuthAccountingRoute
    }
    '/_auth/accounting/fee-types': {
      id: '/_auth/accounting/fee-types'
      path: '/fee-types'
      fullPath: '/accounting/fee-types'
      preLoaderRoute: typeof AuthAccountingFeeTypesRouteImport
      parentRoute: typeof AuthAccountingRoute
    }
    '/_auth/accounting/fee-structures': {
      id: '/_auth/accounting/fee-structures'
      path: '/fee-structures'
      fullPath: '/accounting/fee-structures'
      preLoaderRoute: typeof AuthAccountingFeeStructuresRouteImport
      parentRoute: typeof AuthAccountingRoute
    }
    '/_auth/accounting/discounts': {
      id: '/_auth/accounting/discounts'
      path: '/discounts'
      fullPath: '/accounting/discounts'
      preLoaderRoute: typeof AuthAccountingDiscountsRouteImport
      parentRoute: typeof AuthAccountingRoute
    }
    '/_auth/accounting/dashboard': {
      id: '/_auth/accounting/dashboard'
      path: '/dashboard'
      fullPath: '/accounting/dashboard'
      preLoaderRoute: typeof AuthAccountingDashboardRouteImport
      parentRoute: typeof AuthAccountingRoute
    }
    '/_auth/accounting/accounts': {
      id: '/_auth/accounting/accounts'
      path: '/accounts'
      fullPath: '/accounting/accounts'
      preLoaderRoute: typeof AuthAccountingAccountsRouteImport
      parentRoute: typeof AuthAccountingRoute
    }
    '/_auth/users/users/': {
      id: '/_auth/users/users/'
      path: '/users'
      fullPath: '/users/users'
      preLoaderRoute: typeof AuthUsersUsersIndexRouteImport
      parentRoute: typeof AuthUsersRoute
    }
    '/_auth/users/teachers/': {
      id: '/_auth/users/teachers/'
      path: '/teachers'
      fullPath: '/users/teachers'
      preLoaderRoute: typeof AuthUsersTeachersIndexRouteImport
      parentRoute: typeof AuthUsersRoute
    }
    '/_auth/users/staff/': {
      id: '/_auth/users/staff/'
      path: '/staff'
      fullPath: '/users/staff'
      preLoaderRoute: typeof AuthUsersStaffIndexRouteImport
      parentRoute: typeof AuthUsersRoute
    }
    '/_auth/users/roles/': {
      id: '/_auth/users/roles/'
      path: '/roles'
      fullPath: '/users/roles'
      preLoaderRoute: typeof AuthUsersRolesIndexRouteImport
      parentRoute: typeof AuthUsersRoute
    }
    '/_auth/students/$studentId/': {
      id: '/_auth/students/$studentId/'
      path: '/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AuthStudentsStudentIdIndexRouteImport
      parentRoute: typeof AuthStudentsRoute
    }
    '/_auth/spaces/classrooms/': {
      id: '/_auth/spaces/classrooms/'
      path: '/classrooms'
      fullPath: '/spaces/classrooms'
      preLoaderRoute: typeof AuthSpacesClassroomsIndexRouteImport
      parentRoute: typeof AuthSpacesRoute
    }
    '/_auth/conducts/teacher-attendance/': {
      id: '/_auth/conducts/teacher-attendance/'
      path: '/teacher-attendance'
      fullPath: '/conducts/teacher-attendance'
      preLoaderRoute: typeof AuthConductsTeacherAttendanceIndexRouteImport
      parentRoute: typeof AuthConductsRoute
    }
    '/_auth/conducts/student-attendance/': {
      id: '/_auth/conducts/student-attendance/'
      path: '/student-attendance'
      fullPath: '/conducts/student-attendance'
      preLoaderRoute: typeof AuthConductsStudentAttendanceIndexRouteImport
      parentRoute: typeof AuthConductsRoute
    }
    '/_auth/conducts/conduct/': {
      id: '/_auth/conducts/conduct/'
      path: '/conduct'
      fullPath: '/conducts/conduct'
      preLoaderRoute: typeof AuthConductsConductIndexRouteImport
      parentRoute: typeof AuthConductsRoute
    }
    '/_auth/conducts/alerts/': {
      id: '/_auth/conducts/alerts/'
      path: '/alerts'
      fullPath: '/conducts/alerts'
      preLoaderRoute: typeof AuthConductsAlertsIndexRouteImport
      parentRoute: typeof AuthConductsRoute
    }
    '/_auth/classes/$classId/': {
      id: '/_auth/classes/$classId/'
      path: '/$classId'
      fullPath: '/classes/$classId'
      preLoaderRoute: typeof AuthClassesClassIdIndexRouteImport
      parentRoute: typeof AuthClassesRoute
    }
    '/_auth/users/users/new': {
      id: '/_auth/users/users/new'
      path: '/users/new'
      fullPath: '/users/users/new'
      preLoaderRoute: typeof AuthUsersUsersNewRouteImport
      parentRoute: typeof AuthUsersRoute
    }
    '/_auth/users/users/import': {
      id: '/_auth/users/users/import'
      path: '/users/import'
      fullPath: '/users/users/import'
      preLoaderRoute: typeof AuthUsersUsersImportRouteImport
      parentRoute: typeof AuthUsersRoute
    }
    '/_auth/users/teachers/new': {
      id: '/_auth/users/teachers/new'
      path: '/teachers/new'
      fullPath: '/users/teachers/new'
      preLoaderRoute: typeof AuthUsersTeachersNewRouteImport
      parentRoute: typeof AuthUsersRoute
    }
    '/_auth/users/staff/new': {
      id: '/_auth/users/staff/new'
      path: '/staff/new'
      fullPath: '/users/staff/new'
      preLoaderRoute: typeof AuthUsersStaffNewRouteImport
      parentRoute: typeof AuthUsersRoute
    }
    '/_auth/users/roles/new': {
      id: '/_auth/users/roles/new'
      path: '/roles/new'
      fullPath: '/users/roles/new'
      preLoaderRoute: typeof AuthUsersRolesNewRouteImport
      parentRoute: typeof AuthUsersRoute
    }
    '/_auth/students/$studentId/edit': {
      id: '/_auth/students/$studentId/edit'
      path: '/$studentId/edit'
      fullPath: '/students/$studentId/edit'
      preLoaderRoute: typeof AuthStudentsStudentIdEditRouteImport
      parentRoute: typeof AuthStudentsRoute
    }
    '/_auth/conducts/teacher-attendance/reports': {
      id: '/_auth/conducts/teacher-attendance/reports'
      path: '/teacher-attendance/reports'
      fullPath: '/conducts/teacher-attendance/reports'
      preLoaderRoute: typeof AuthConductsTeacherAttendanceReportsRouteImport
      parentRoute: typeof AuthConductsRoute
    }
    '/_auth/conducts/student-attendance/statistics': {
      id: '/_auth/conducts/student-attendance/statistics'
      path: '/student-attendance/statistics'
      fullPath: '/conducts/student-attendance/statistics'
      preLoaderRoute: typeof AuthConductsStudentAttendanceStatisticsRouteImport
      parentRoute: typeof AuthConductsRoute
    }
    '/_auth/conducts/student-attendance/history': {
      id: '/_auth/conducts/student-attendance/history'
      path: '/student-attendance/history'
      fullPath: '/conducts/student-attendance/history'
      preLoaderRoute: typeof AuthConductsStudentAttendanceHistoryRouteImport
      parentRoute: typeof AuthConductsRoute
    }
    '/_auth/conducts/conduct/reports': {
      id: '/_auth/conducts/conduct/reports'
      path: '/conduct/reports'
      fullPath: '/conducts/conduct/reports'
      preLoaderRoute: typeof AuthConductsConductReportsRouteImport
      parentRoute: typeof AuthConductsRoute
    }
    '/_auth/conducts/conduct/new': {
      id: '/_auth/conducts/conduct/new'
      path: '/conduct/new'
      fullPath: '/conducts/conduct/new'
      preLoaderRoute: typeof AuthConductsConductNewRouteImport
      parentRoute: typeof AuthConductsRoute
    }
    '/_auth/conducts/conduct/$recordId': {
      id: '/_auth/conducts/conduct/$recordId'
      path: '/conduct/$recordId'
      fullPath: '/conducts/conduct/$recordId'
      preLoaderRoute: typeof AuthConductsConductRecordIdRouteImport
      parentRoute: typeof AuthConductsRoute
    }
    '/_auth/classes/$classId/edit': {
      id: '/_auth/classes/$classId/edit'
      path: '/$classId/edit'
      fullPath: '/classes/$classId/edit'
      preLoaderRoute: typeof AuthClassesClassIdEditRouteImport
      parentRoute: typeof AuthClassesRoute
    }
    '/_auth/users/users/$userId/': {
      id: '/_auth/users/users/$userId/'
      path: '/users/$userId'
      fullPath: '/users/users/$userId'
      preLoaderRoute: typeof AuthUsersUsersUserIdIndexRouteImport
      parentRoute: typeof AuthUsersRoute
    }
    '/_auth/users/teachers/$teacherId/': {
      id: '/_auth/users/teachers/$teacherId/'
      path: '/teachers/$teacherId'
      fullPath: '/users/teachers/$teacherId'
      preLoaderRoute: typeof AuthUsersTeachersTeacherIdIndexRouteImport
      parentRoute: typeof AuthUsersRoute
    }
    '/_auth/users/staff/$staffId/': {
      id: '/_auth/users/staff/$staffId/'
      path: '/staff/$staffId'
      fullPath: '/users/staff/$staffId'
      preLoaderRoute: typeof AuthUsersStaffStaffIdIndexRouteImport
      parentRoute: typeof AuthUsersRoute
    }
    '/_auth/users/roles/$roleId/': {
      id: '/_auth/users/roles/$roleId/'
      path: '/roles/$roleId'
      fullPath: '/users/roles/$roleId'
      preLoaderRoute: typeof AuthUsersRolesRoleIdIndexRouteImport
      parentRoute: typeof AuthUsersRoute
    }
    '/_auth/spaces/classrooms/$classroomId/': {
      id: '/_auth/spaces/classrooms/$classroomId/'
      path: '/classrooms/$classroomId'
      fullPath: '/spaces/classrooms/$classroomId'
      preLoaderRoute: typeof AuthSpacesClassroomsClassroomIdIndexRouteImport
      parentRoute: typeof AuthSpacesRoute
    }
    '/_auth/users/users/$userId/edit': {
      id: '/_auth/users/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/users/users/$userId/edit'
      preLoaderRoute: typeof AuthUsersUsersUserIdEditRouteImport
      parentRoute: typeof AuthUsersRoute
    }
    '/_auth/users/teachers/$teacherId/edit': {
      id: '/_auth/users/teachers/$teacherId/edit'
      path: '/teachers/$teacherId/edit'
      fullPath: '/users/teachers/$teacherId/edit'
      preLoaderRoute: typeof AuthUsersTeachersTeacherIdEditRouteImport
      parentRoute: typeof AuthUsersRoute
    }
    '/_auth/users/staff/$staffId/edit': {
      id: '/_auth/users/staff/$staffId/edit'
      path: '/staff/$staffId/edit'
      fullPath: '/users/staff/$staffId/edit'
      preLoaderRoute: typeof AuthUsersStaffStaffIdEditRouteImport
      parentRoute: typeof AuthUsersRoute
    }
    '/_auth/users/roles/$roleId/edit': {
      id: '/_auth/users/roles/$roleId/edit'
      path: '/roles/$roleId/edit'
      fullPath: '/users/roles/$roleId/edit'
      preLoaderRoute: typeof AuthUsersRolesRoleIdEditRouteImport
      parentRoute: typeof AuthUsersRoute
    }
    '/_auth/spaces/classrooms/$classroomId/edit': {
      id: '/_auth/spaces/classrooms/$classroomId/edit'
      path: '/classrooms/$classroomId/edit'
      fullPath: '/spaces/classrooms/$classroomId/edit'
      preLoaderRoute: typeof AuthSpacesClassroomsClassroomIdEditRouteImport
      parentRoute: typeof AuthSpacesRoute
    }
  }
}

interface AuthAccountingRouteChildren {
  AuthAccountingAccountsRoute: typeof AuthAccountingAccountsRoute
  AuthAccountingDashboardRoute: typeof AuthAccountingDashboardRoute
  AuthAccountingDiscountsRoute: typeof AuthAccountingDiscountsRoute
  AuthAccountingFeeStructuresRoute: typeof AuthAccountingFeeStructuresRoute
  AuthAccountingFeeTypesRoute: typeof AuthAccountingFeeTypesRoute
  AuthAccountingPaymentPlansRoute: typeof AuthAccountingPaymentPlansRoute
  AuthAccountingPaymentsRoute: typeof AuthAccountingPaymentsRoute
  AuthAccountingRefundsRoute: typeof AuthAccountingRefundsRoute
  AuthAccountingStudentFeesRoute: typeof AuthAccountingStudentFeesRoute
  AuthAccountingIndexRoute: typeof AuthAccountingIndexRoute
}

const AuthAccountingRouteChildren: AuthAccountingRouteChildren = {
  AuthAccountingAccountsRoute: AuthAccountingAccountsRoute,
  AuthAccountingDashboardRoute: AuthAccountingDashboardRoute,
  AuthAccountingDiscountsRoute: AuthAccountingDiscountsRoute,
  AuthAccountingFeeStructuresRoute: AuthAccountingFeeStructuresRoute,
  AuthAccountingFeeTypesRoute: AuthAccountingFeeTypesRoute,
  AuthAccountingPaymentPlansRoute: AuthAccountingPaymentPlansRoute,
  AuthAccountingPaymentsRoute: AuthAccountingPaymentsRoute,
  AuthAccountingRefundsRoute: AuthAccountingRefundsRoute,
  AuthAccountingStudentFeesRoute: AuthAccountingStudentFeesRoute,
  AuthAccountingIndexRoute: AuthAccountingIndexRoute,
}

const AuthAccountingRouteWithChildren = AuthAccountingRoute._addFileChildren(
  AuthAccountingRouteChildren,
)

interface AuthClassesRouteChildren {
  AuthClassesAssignmentsRoute: typeof AuthClassesAssignmentsRoute
  AuthClassesIndexRoute: typeof AuthClassesIndexRoute
  AuthClassesClassIdEditRoute: typeof AuthClassesClassIdEditRoute
  AuthClassesClassIdIndexRoute: typeof AuthClassesClassIdIndexRoute
}

const AuthClassesRouteChildren: AuthClassesRouteChildren = {
  AuthClassesAssignmentsRoute: AuthClassesAssignmentsRoute,
  AuthClassesIndexRoute: AuthClassesIndexRoute,
  AuthClassesClassIdEditRoute: AuthClassesClassIdEditRoute,
  AuthClassesClassIdIndexRoute: AuthClassesClassIdIndexRoute,
}

const AuthClassesRouteWithChildren = AuthClassesRoute._addFileChildren(
  AuthClassesRouteChildren,
)

interface AuthConductsRouteChildren {
  AuthConductsSettingsRoute: typeof AuthConductsSettingsRoute
  AuthConductsIndexRoute: typeof AuthConductsIndexRoute
  AuthConductsConductRecordIdRoute: typeof AuthConductsConductRecordIdRoute
  AuthConductsConductNewRoute: typeof AuthConductsConductNewRoute
  AuthConductsConductReportsRoute: typeof AuthConductsConductReportsRoute
  AuthConductsStudentAttendanceHistoryRoute: typeof AuthConductsStudentAttendanceHistoryRoute
  AuthConductsStudentAttendanceStatisticsRoute: typeof AuthConductsStudentAttendanceStatisticsRoute
  AuthConductsTeacherAttendanceReportsRoute: typeof AuthConductsTeacherAttendanceReportsRoute
  AuthConductsAlertsIndexRoute: typeof AuthConductsAlertsIndexRoute
  AuthConductsConductIndexRoute: typeof AuthConductsConductIndexRoute
  AuthConductsStudentAttendanceIndexRoute: typeof AuthConductsStudentAttendanceIndexRoute
  AuthConductsTeacherAttendanceIndexRoute: typeof AuthConductsTeacherAttendanceIndexRoute
}

const AuthConductsRouteChildren: AuthConductsRouteChildren = {
  AuthConductsSettingsRoute: AuthConductsSettingsRoute,
  AuthConductsIndexRoute: AuthConductsIndexRoute,
  AuthConductsConductRecordIdRoute: AuthConductsConductRecordIdRoute,
  AuthConductsConductNewRoute: AuthConductsConductNewRoute,
  AuthConductsConductReportsRoute: AuthConductsConductReportsRoute,
  AuthConductsStudentAttendanceHistoryRoute:
    AuthConductsStudentAttendanceHistoryRoute,
  AuthConductsStudentAttendanceStatisticsRoute:
    AuthConductsStudentAttendanceStatisticsRoute,
  AuthConductsTeacherAttendanceReportsRoute:
    AuthConductsTeacherAttendanceReportsRoute,
  AuthConductsAlertsIndexRoute: AuthConductsAlertsIndexRoute,
  AuthConductsConductIndexRoute: AuthConductsConductIndexRoute,
  AuthConductsStudentAttendanceIndexRoute:
    AuthConductsStudentAttendanceIndexRoute,
  AuthConductsTeacherAttendanceIndexRoute:
    AuthConductsTeacherAttendanceIndexRoute,
}

const AuthConductsRouteWithChildren = AuthConductsRoute._addFileChildren(
  AuthConductsRouteChildren,
)

interface AuthGradesRouteChildren {
  AuthGradesEntryRoute: typeof AuthGradesEntryRoute
  AuthGradesReportCardsRoute: typeof AuthGradesReportCardsRoute
  AuthGradesStatisticsRoute: typeof AuthGradesStatisticsRoute
  AuthGradesValidationsRoute: typeof AuthGradesValidationsRoute
  AuthGradesIndexRoute: typeof AuthGradesIndexRoute
}

const AuthGradesRouteChildren: AuthGradesRouteChildren = {
  AuthGradesEntryRoute: AuthGradesEntryRoute,
  AuthGradesReportCardsRoute: AuthGradesReportCardsRoute,
  AuthGradesStatisticsRoute: AuthGradesStatisticsRoute,
  AuthGradesValidationsRoute: AuthGradesValidationsRoute,
  AuthGradesIndexRoute: AuthGradesIndexRoute,
}

const AuthGradesRouteWithChildren = AuthGradesRoute._addFileChildren(
  AuthGradesRouteChildren,
)

interface AuthProgramsRouteChildren {
  AuthProgramsCoefficientsRoute: typeof AuthProgramsCoefficientsRoute
  AuthProgramsCurriculumProgressRoute: typeof AuthProgramsCurriculumProgressRoute
  AuthProgramsSubjectsRoute: typeof AuthProgramsSubjectsRoute
}

const AuthProgramsRouteChildren: AuthProgramsRouteChildren = {
  AuthProgramsCoefficientsRoute: AuthProgramsCoefficientsRoute,
  AuthProgramsCurriculumProgressRoute: AuthProgramsCurriculumProgressRoute,
  AuthProgramsSubjectsRoute: AuthProgramsSubjectsRoute,
}

const AuthProgramsRouteWithChildren = AuthProgramsRoute._addFileChildren(
  AuthProgramsRouteChildren,
)

interface AuthSettingsRouteChildren {
  AuthSettingsNotificationsRoute: typeof AuthSettingsNotificationsRoute
  AuthSettingsProfileRoute: typeof AuthSettingsProfileRoute
  AuthSettingsReportCardsRoute: typeof AuthSettingsReportCardsRoute
  AuthSettingsSchoolYearsRoute: typeof AuthSettingsSchoolYearsRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
}

const AuthSettingsRouteChildren: AuthSettingsRouteChildren = {
  AuthSettingsNotificationsRoute: AuthSettingsNotificationsRoute,
  AuthSettingsProfileRoute: AuthSettingsProfileRoute,
  AuthSettingsReportCardsRoute: AuthSettingsReportCardsRoute,
  AuthSettingsSchoolYearsRoute: AuthSettingsSchoolYearsRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
}

const AuthSettingsRouteWithChildren = AuthSettingsRoute._addFileChildren(
  AuthSettingsRouteChildren,
)

interface AuthSpacesRouteChildren {
  AuthSpacesAvailabilityRoute: typeof AuthSpacesAvailabilityRoute
  AuthSpacesIndexRoute: typeof AuthSpacesIndexRoute
  AuthSpacesClassroomsIndexRoute: typeof AuthSpacesClassroomsIndexRoute
  AuthSpacesClassroomsClassroomIdEditRoute: typeof AuthSpacesClassroomsClassroomIdEditRoute
  AuthSpacesClassroomsClassroomIdIndexRoute: typeof AuthSpacesClassroomsClassroomIdIndexRoute
}

const AuthSpacesRouteChildren: AuthSpacesRouteChildren = {
  AuthSpacesAvailabilityRoute: AuthSpacesAvailabilityRoute,
  AuthSpacesIndexRoute: AuthSpacesIndexRoute,
  AuthSpacesClassroomsIndexRoute: AuthSpacesClassroomsIndexRoute,
  AuthSpacesClassroomsClassroomIdEditRoute:
    AuthSpacesClassroomsClassroomIdEditRoute,
  AuthSpacesClassroomsClassroomIdIndexRoute:
    AuthSpacesClassroomsClassroomIdIndexRoute,
}

const AuthSpacesRouteWithChildren = AuthSpacesRoute._addFileChildren(
  AuthSpacesRouteChildren,
)

interface AuthStudentsRouteChildren {
  AuthStudentsBulkOperationsRoute: typeof AuthStudentsBulkOperationsRoute
  AuthStudentsEnrollmentsRoute: typeof AuthStudentsEnrollmentsRoute
  AuthStudentsNewRoute: typeof AuthStudentsNewRoute
  AuthStudentsParentsRoute: typeof AuthStudentsParentsRoute
  AuthStudentsIndexRoute: typeof AuthStudentsIndexRoute
  AuthStudentsStudentIdEditRoute: typeof AuthStudentsStudentIdEditRoute
  AuthStudentsStudentIdIndexRoute: typeof AuthStudentsStudentIdIndexRoute
}

const AuthStudentsRouteChildren: AuthStudentsRouteChildren = {
  AuthStudentsBulkOperationsRoute: AuthStudentsBulkOperationsRoute,
  AuthStudentsEnrollmentsRoute: AuthStudentsEnrollmentsRoute,
  AuthStudentsNewRoute: AuthStudentsNewRoute,
  AuthStudentsParentsRoute: AuthStudentsParentsRoute,
  AuthStudentsIndexRoute: AuthStudentsIndexRoute,
  AuthStudentsStudentIdEditRoute: AuthStudentsStudentIdEditRoute,
  AuthStudentsStudentIdIndexRoute: AuthStudentsStudentIdIndexRoute,
}

const AuthStudentsRouteWithChildren = AuthStudentsRoute._addFileChildren(
  AuthStudentsRouteChildren,
)

interface AuthUsersRouteChildren {
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
  AuthUsersRolesNewRoute: typeof AuthUsersRolesNewRoute
  AuthUsersStaffNewRoute: typeof AuthUsersStaffNewRoute
  AuthUsersTeachersNewRoute: typeof AuthUsersTeachersNewRoute
  AuthUsersUsersImportRoute: typeof AuthUsersUsersImportRoute
  AuthUsersUsersNewRoute: typeof AuthUsersUsersNewRoute
  AuthUsersRolesIndexRoute: typeof AuthUsersRolesIndexRoute
  AuthUsersStaffIndexRoute: typeof AuthUsersStaffIndexRoute
  AuthUsersTeachersIndexRoute: typeof AuthUsersTeachersIndexRoute
  AuthUsersUsersIndexRoute: typeof AuthUsersUsersIndexRoute
  AuthUsersRolesRoleIdEditRoute: typeof AuthUsersRolesRoleIdEditRoute
  AuthUsersStaffStaffIdEditRoute: typeof AuthUsersStaffStaffIdEditRoute
  AuthUsersTeachersTeacherIdEditRoute: typeof AuthUsersTeachersTeacherIdEditRoute
  AuthUsersUsersUserIdEditRoute: typeof AuthUsersUsersUserIdEditRoute
  AuthUsersRolesRoleIdIndexRoute: typeof AuthUsersRolesRoleIdIndexRoute
  AuthUsersStaffStaffIdIndexRoute: typeof AuthUsersStaffStaffIdIndexRoute
  AuthUsersTeachersTeacherIdIndexRoute: typeof AuthUsersTeachersTeacherIdIndexRoute
  AuthUsersUsersUserIdIndexRoute: typeof AuthUsersUsersUserIdIndexRoute
}

const AuthUsersRouteChildren: AuthUsersRouteChildren = {
  AuthUsersIndexRoute: AuthUsersIndexRoute,
  AuthUsersRolesNewRoute: AuthUsersRolesNewRoute,
  AuthUsersStaffNewRoute: AuthUsersStaffNewRoute,
  AuthUsersTeachersNewRoute: AuthUsersTeachersNewRoute,
  AuthUsersUsersImportRoute: AuthUsersUsersImportRoute,
  AuthUsersUsersNewRoute: AuthUsersUsersNewRoute,
  AuthUsersRolesIndexRoute: AuthUsersRolesIndexRoute,
  AuthUsersStaffIndexRoute: AuthUsersStaffIndexRoute,
  AuthUsersTeachersIndexRoute: AuthUsersTeachersIndexRoute,
  AuthUsersUsersIndexRoute: AuthUsersUsersIndexRoute,
  AuthUsersRolesRoleIdEditRoute: AuthUsersRolesRoleIdEditRoute,
  AuthUsersStaffStaffIdEditRoute: AuthUsersStaffStaffIdEditRoute,
  AuthUsersTeachersTeacherIdEditRoute: AuthUsersTeachersTeacherIdEditRoute,
  AuthUsersUsersUserIdEditRoute: AuthUsersUsersUserIdEditRoute,
  AuthUsersRolesRoleIdIndexRoute: AuthUsersRolesRoleIdIndexRoute,
  AuthUsersStaffStaffIdIndexRoute: AuthUsersStaffStaffIdIndexRoute,
  AuthUsersTeachersTeacherIdIndexRoute: AuthUsersTeachersTeacherIdIndexRoute,
  AuthUsersUsersUserIdIndexRoute: AuthUsersUsersUserIdIndexRoute,
}

const AuthUsersRouteWithChildren = AuthUsersRoute._addFileChildren(
  AuthUsersRouteChildren,
)

interface AuthRouteChildren {
  AuthAccountingRoute: typeof AuthAccountingRouteWithChildren
  AuthClassesRoute: typeof AuthClassesRouteWithChildren
  AuthConductsRoute: typeof AuthConductsRouteWithChildren
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthGradesRoute: typeof AuthGradesRouteWithChildren
  AuthProgramsRoute: typeof AuthProgramsRouteWithChildren
  AuthSchedulesRoute: typeof AuthSchedulesRoute
  AuthSettingsRoute: typeof AuthSettingsRouteWithChildren
  AuthSpacesRoute: typeof AuthSpacesRouteWithChildren
  AuthStudentsRoute: typeof AuthStudentsRouteWithChildren
  AuthUsersRoute: typeof AuthUsersRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAccountingRoute: AuthAccountingRouteWithChildren,
  AuthClassesRoute: AuthClassesRouteWithChildren,
  AuthConductsRoute: AuthConductsRouteWithChildren,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthGradesRoute: AuthGradesRouteWithChildren,
  AuthProgramsRoute: AuthProgramsRouteWithChildren,
  AuthSchedulesRoute: AuthSchedulesRoute,
  AuthSettingsRoute: AuthSettingsRouteWithChildren,
  AuthSpacesRoute: AuthSpacesRouteWithChildren,
  AuthStudentsRoute: AuthStudentsRouteWithChildren,
  AuthUsersRoute: AuthUsersRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
