/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthAppRouteImport } from './routes/_auth/app'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthAppHrRouteImport } from './routes/_auth/app/hr'
import { Route as AuthAppDashboardRouteImport } from './routes/_auth/app/dashboard'
import { Route as AuthAppHrIndexRouteImport } from './routes/_auth/app/hr/index'
import { Route as AuthAppHrUsersIndexRouteImport } from './routes/_auth/app/hr/users/index'
import { Route as AuthAppHrTeachersIndexRouteImport } from './routes/_auth/app/hr/teachers/index'
import { Route as AuthAppHrStaffIndexRouteImport } from './routes/_auth/app/hr/staff/index'
import { Route as AuthAppHrRolesIndexRouteImport } from './routes/_auth/app/hr/roles/index'
import { Route as AuthAppHrUsersNewRouteImport } from './routes/_auth/app/hr/users/new'
import { Route as AuthAppHrUsersImportRouteImport } from './routes/_auth/app/hr/users/import'
import { Route as AuthAppHrTeachersNewRouteImport } from './routes/_auth/app/hr/teachers/new'
import { Route as AuthAppHrStaffNewRouteImport } from './routes/_auth/app/hr/staff/new'
import { Route as AuthAppHrRolesNewRouteImport } from './routes/_auth/app/hr/roles/new'
import { Route as AuthAppHrUsersUserIdIndexRouteImport } from './routes/_auth/app/hr/users/$userId/index'
import { Route as AuthAppHrTeachersTeacherIdIndexRouteImport } from './routes/_auth/app/hr/teachers/$teacherId/index'
import { Route as AuthAppHrStaffStaffIdIndexRouteImport } from './routes/_auth/app/hr/staff/$staffId/index'
import { Route as AuthAppHrRolesRoleIdIndexRouteImport } from './routes/_auth/app/hr/roles/$roleId/index'
import { Route as AuthAppHrUsersUserIdEditRouteImport } from './routes/_auth/app/hr/users/$userId/edit'
import { Route as AuthAppHrTeachersTeacherIdEditRouteImport } from './routes/_auth/app/hr/teachers/$teacherId/edit'
import { Route as AuthAppHrStaffStaffIdEditRouteImport } from './routes/_auth/app/hr/staff/$staffId/edit'
import { Route as AuthAppHrRolesRoleIdEditRouteImport } from './routes/_auth/app/hr/roles/$roleId/edit'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppRoute = AuthAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppHrRoute = AuthAppHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppDashboardRoute = AuthAppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppHrIndexRoute = AuthAppHrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppHrRoute,
} as any)
const AuthAppHrUsersIndexRoute = AuthAppHrUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthAppHrRoute,
} as any)
const AuthAppHrTeachersIndexRoute = AuthAppHrTeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => AuthAppHrRoute,
} as any)
const AuthAppHrStaffIndexRoute = AuthAppHrStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AuthAppHrRoute,
} as any)
const AuthAppHrRolesIndexRoute = AuthAppHrRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthAppHrRoute,
} as any)
const AuthAppHrUsersNewRoute = AuthAppHrUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AuthAppHrRoute,
} as any)
const AuthAppHrUsersImportRoute = AuthAppHrUsersImportRouteImport.update({
  id: '/users/import',
  path: '/users/import',
  getParentRoute: () => AuthAppHrRoute,
} as any)
const AuthAppHrTeachersNewRoute = AuthAppHrTeachersNewRouteImport.update({
  id: '/teachers/new',
  path: '/teachers/new',
  getParentRoute: () => AuthAppHrRoute,
} as any)
const AuthAppHrStaffNewRoute = AuthAppHrStaffNewRouteImport.update({
  id: '/staff/new',
  path: '/staff/new',
  getParentRoute: () => AuthAppHrRoute,
} as any)
const AuthAppHrRolesNewRoute = AuthAppHrRolesNewRouteImport.update({
  id: '/roles/new',
  path: '/roles/new',
  getParentRoute: () => AuthAppHrRoute,
} as any)
const AuthAppHrUsersUserIdIndexRoute =
  AuthAppHrUsersUserIdIndexRouteImport.update({
    id: '/users/$userId/',
    path: '/users/$userId/',
    getParentRoute: () => AuthAppHrRoute,
  } as any)
const AuthAppHrTeachersTeacherIdIndexRoute =
  AuthAppHrTeachersTeacherIdIndexRouteImport.update({
    id: '/teachers/$teacherId/',
    path: '/teachers/$teacherId/',
    getParentRoute: () => AuthAppHrRoute,
  } as any)
const AuthAppHrStaffStaffIdIndexRoute =
  AuthAppHrStaffStaffIdIndexRouteImport.update({
    id: '/staff/$staffId/',
    path: '/staff/$staffId/',
    getParentRoute: () => AuthAppHrRoute,
  } as any)
const AuthAppHrRolesRoleIdIndexRoute =
  AuthAppHrRolesRoleIdIndexRouteImport.update({
    id: '/roles/$roleId/',
    path: '/roles/$roleId/',
    getParentRoute: () => AuthAppHrRoute,
  } as any)
const AuthAppHrUsersUserIdEditRoute =
  AuthAppHrUsersUserIdEditRouteImport.update({
    id: '/users/$userId/edit',
    path: '/users/$userId/edit',
    getParentRoute: () => AuthAppHrRoute,
  } as any)
const AuthAppHrTeachersTeacherIdEditRoute =
  AuthAppHrTeachersTeacherIdEditRouteImport.update({
    id: '/teachers/$teacherId/edit',
    path: '/teachers/$teacherId/edit',
    getParentRoute: () => AuthAppHrRoute,
  } as any)
const AuthAppHrStaffStaffIdEditRoute =
  AuthAppHrStaffStaffIdEditRouteImport.update({
    id: '/staff/$staffId/edit',
    path: '/staff/$staffId/edit',
    getParentRoute: () => AuthAppHrRoute,
  } as any)
const AuthAppHrRolesRoleIdEditRoute =
  AuthAppHrRolesRoleIdEditRouteImport.update({
    id: '/roles/$roleId/edit',
    path: '/roles/$roleId/edit',
    getParentRoute: () => AuthAppHrRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AuthAppRouteWithChildren
  '/app/dashboard': typeof AuthAppDashboardRoute
  '/app/hr': typeof AuthAppHrRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/hr/': typeof AuthAppHrIndexRoute
  '/app/hr/roles/new': typeof AuthAppHrRolesNewRoute
  '/app/hr/staff/new': typeof AuthAppHrStaffNewRoute
  '/app/hr/teachers/new': typeof AuthAppHrTeachersNewRoute
  '/app/hr/users/import': typeof AuthAppHrUsersImportRoute
  '/app/hr/users/new': typeof AuthAppHrUsersNewRoute
  '/app/hr/roles': typeof AuthAppHrRolesIndexRoute
  '/app/hr/staff': typeof AuthAppHrStaffIndexRoute
  '/app/hr/teachers': typeof AuthAppHrTeachersIndexRoute
  '/app/hr/users': typeof AuthAppHrUsersIndexRoute
  '/app/hr/roles/$roleId/edit': typeof AuthAppHrRolesRoleIdEditRoute
  '/app/hr/staff/$staffId/edit': typeof AuthAppHrStaffStaffIdEditRoute
  '/app/hr/teachers/$teacherId/edit': typeof AuthAppHrTeachersTeacherIdEditRoute
  '/app/hr/users/$userId/edit': typeof AuthAppHrUsersUserIdEditRoute
  '/app/hr/roles/$roleId': typeof AuthAppHrRolesRoleIdIndexRoute
  '/app/hr/staff/$staffId': typeof AuthAppHrStaffStaffIdIndexRoute
  '/app/hr/teachers/$teacherId': typeof AuthAppHrTeachersTeacherIdIndexRoute
  '/app/hr/users/$userId': typeof AuthAppHrUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AuthAppRouteWithChildren
  '/app/dashboard': typeof AuthAppDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/hr': typeof AuthAppHrIndexRoute
  '/app/hr/roles/new': typeof AuthAppHrRolesNewRoute
  '/app/hr/staff/new': typeof AuthAppHrStaffNewRoute
  '/app/hr/teachers/new': typeof AuthAppHrTeachersNewRoute
  '/app/hr/users/import': typeof AuthAppHrUsersImportRoute
  '/app/hr/users/new': typeof AuthAppHrUsersNewRoute
  '/app/hr/roles': typeof AuthAppHrRolesIndexRoute
  '/app/hr/staff': typeof AuthAppHrStaffIndexRoute
  '/app/hr/teachers': typeof AuthAppHrTeachersIndexRoute
  '/app/hr/users': typeof AuthAppHrUsersIndexRoute
  '/app/hr/roles/$roleId/edit': typeof AuthAppHrRolesRoleIdEditRoute
  '/app/hr/staff/$staffId/edit': typeof AuthAppHrStaffStaffIdEditRoute
  '/app/hr/teachers/$teacherId/edit': typeof AuthAppHrTeachersTeacherIdEditRoute
  '/app/hr/users/$userId/edit': typeof AuthAppHrUsersUserIdEditRoute
  '/app/hr/roles/$roleId': typeof AuthAppHrRolesRoleIdIndexRoute
  '/app/hr/staff/$staffId': typeof AuthAppHrStaffStaffIdIndexRoute
  '/app/hr/teachers/$teacherId': typeof AuthAppHrTeachersTeacherIdIndexRoute
  '/app/hr/users/$userId': typeof AuthAppHrUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/app': typeof AuthAppRouteWithChildren
  '/_auth/app/dashboard': typeof AuthAppDashboardRoute
  '/_auth/app/hr': typeof AuthAppHrRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/app/hr/': typeof AuthAppHrIndexRoute
  '/_auth/app/hr/roles/new': typeof AuthAppHrRolesNewRoute
  '/_auth/app/hr/staff/new': typeof AuthAppHrStaffNewRoute
  '/_auth/app/hr/teachers/new': typeof AuthAppHrTeachersNewRoute
  '/_auth/app/hr/users/import': typeof AuthAppHrUsersImportRoute
  '/_auth/app/hr/users/new': typeof AuthAppHrUsersNewRoute
  '/_auth/app/hr/roles/': typeof AuthAppHrRolesIndexRoute
  '/_auth/app/hr/staff/': typeof AuthAppHrStaffIndexRoute
  '/_auth/app/hr/teachers/': typeof AuthAppHrTeachersIndexRoute
  '/_auth/app/hr/users/': typeof AuthAppHrUsersIndexRoute
  '/_auth/app/hr/roles/$roleId/edit': typeof AuthAppHrRolesRoleIdEditRoute
  '/_auth/app/hr/staff/$staffId/edit': typeof AuthAppHrStaffStaffIdEditRoute
  '/_auth/app/hr/teachers/$teacherId/edit': typeof AuthAppHrTeachersTeacherIdEditRoute
  '/_auth/app/hr/users/$userId/edit': typeof AuthAppHrUsersUserIdEditRoute
  '/_auth/app/hr/roles/$roleId/': typeof AuthAppHrRolesRoleIdIndexRoute
  '/_auth/app/hr/staff/$staffId/': typeof AuthAppHrStaffStaffIdIndexRoute
  '/_auth/app/hr/teachers/$teacherId/': typeof AuthAppHrTeachersTeacherIdIndexRoute
  '/_auth/app/hr/users/$userId/': typeof AuthAppHrUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/dashboard'
    | '/app/hr'
    | '/api/auth/$'
    | '/app/hr/'
    | '/app/hr/roles/new'
    | '/app/hr/staff/new'
    | '/app/hr/teachers/new'
    | '/app/hr/users/import'
    | '/app/hr/users/new'
    | '/app/hr/roles'
    | '/app/hr/staff'
    | '/app/hr/teachers'
    | '/app/hr/users'
    | '/app/hr/roles/$roleId/edit'
    | '/app/hr/staff/$staffId/edit'
    | '/app/hr/teachers/$teacherId/edit'
    | '/app/hr/users/$userId/edit'
    | '/app/hr/roles/$roleId'
    | '/app/hr/staff/$staffId'
    | '/app/hr/teachers/$teacherId'
    | '/app/hr/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/dashboard'
    | '/api/auth/$'
    | '/app/hr'
    | '/app/hr/roles/new'
    | '/app/hr/staff/new'
    | '/app/hr/teachers/new'
    | '/app/hr/users/import'
    | '/app/hr/users/new'
    | '/app/hr/roles'
    | '/app/hr/staff'
    | '/app/hr/teachers'
    | '/app/hr/users'
    | '/app/hr/roles/$roleId/edit'
    | '/app/hr/staff/$staffId/edit'
    | '/app/hr/teachers/$teacherId/edit'
    | '/app/hr/users/$userId/edit'
    | '/app/hr/roles/$roleId'
    | '/app/hr/staff/$staffId'
    | '/app/hr/teachers/$teacherId'
    | '/app/hr/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/app'
    | '/_auth/app/dashboard'
    | '/_auth/app/hr'
    | '/api/auth/$'
    | '/_auth/app/hr/'
    | '/_auth/app/hr/roles/new'
    | '/_auth/app/hr/staff/new'
    | '/_auth/app/hr/teachers/new'
    | '/_auth/app/hr/users/import'
    | '/_auth/app/hr/users/new'
    | '/_auth/app/hr/roles/'
    | '/_auth/app/hr/staff/'
    | '/_auth/app/hr/teachers/'
    | '/_auth/app/hr/users/'
    | '/_auth/app/hr/roles/$roleId/edit'
    | '/_auth/app/hr/staff/$staffId/edit'
    | '/_auth/app/hr/teachers/$teacherId/edit'
    | '/_auth/app/hr/users/$userId/edit'
    | '/_auth/app/hr/roles/$roleId/'
    | '/_auth/app/hr/staff/$staffId/'
    | '/_auth/app/hr/teachers/$teacherId/'
    | '/_auth/app/hr/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/hr': {
      id: '/_auth/app/hr'
      path: '/hr'
      fullPath: '/app/hr'
      preLoaderRoute: typeof AuthAppHrRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/dashboard': {
      id: '/_auth/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthAppDashboardRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/hr/': {
      id: '/_auth/app/hr/'
      path: '/'
      fullPath: '/app/hr/'
      preLoaderRoute: typeof AuthAppHrIndexRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/users/': {
      id: '/_auth/app/hr/users/'
      path: '/users'
      fullPath: '/app/hr/users'
      preLoaderRoute: typeof AuthAppHrUsersIndexRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/teachers/': {
      id: '/_auth/app/hr/teachers/'
      path: '/teachers'
      fullPath: '/app/hr/teachers'
      preLoaderRoute: typeof AuthAppHrTeachersIndexRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/staff/': {
      id: '/_auth/app/hr/staff/'
      path: '/staff'
      fullPath: '/app/hr/staff'
      preLoaderRoute: typeof AuthAppHrStaffIndexRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/roles/': {
      id: '/_auth/app/hr/roles/'
      path: '/roles'
      fullPath: '/app/hr/roles'
      preLoaderRoute: typeof AuthAppHrRolesIndexRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/users/new': {
      id: '/_auth/app/hr/users/new'
      path: '/users/new'
      fullPath: '/app/hr/users/new'
      preLoaderRoute: typeof AuthAppHrUsersNewRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/users/import': {
      id: '/_auth/app/hr/users/import'
      path: '/users/import'
      fullPath: '/app/hr/users/import'
      preLoaderRoute: typeof AuthAppHrUsersImportRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/teachers/new': {
      id: '/_auth/app/hr/teachers/new'
      path: '/teachers/new'
      fullPath: '/app/hr/teachers/new'
      preLoaderRoute: typeof AuthAppHrTeachersNewRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/staff/new': {
      id: '/_auth/app/hr/staff/new'
      path: '/staff/new'
      fullPath: '/app/hr/staff/new'
      preLoaderRoute: typeof AuthAppHrStaffNewRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/roles/new': {
      id: '/_auth/app/hr/roles/new'
      path: '/roles/new'
      fullPath: '/app/hr/roles/new'
      preLoaderRoute: typeof AuthAppHrRolesNewRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/users/$userId/': {
      id: '/_auth/app/hr/users/$userId/'
      path: '/users/$userId'
      fullPath: '/app/hr/users/$userId'
      preLoaderRoute: typeof AuthAppHrUsersUserIdIndexRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/teachers/$teacherId/': {
      id: '/_auth/app/hr/teachers/$teacherId/'
      path: '/teachers/$teacherId'
      fullPath: '/app/hr/teachers/$teacherId'
      preLoaderRoute: typeof AuthAppHrTeachersTeacherIdIndexRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/staff/$staffId/': {
      id: '/_auth/app/hr/staff/$staffId/'
      path: '/staff/$staffId'
      fullPath: '/app/hr/staff/$staffId'
      preLoaderRoute: typeof AuthAppHrStaffStaffIdIndexRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/roles/$roleId/': {
      id: '/_auth/app/hr/roles/$roleId/'
      path: '/roles/$roleId'
      fullPath: '/app/hr/roles/$roleId'
      preLoaderRoute: typeof AuthAppHrRolesRoleIdIndexRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/users/$userId/edit': {
      id: '/_auth/app/hr/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/app/hr/users/$userId/edit'
      preLoaderRoute: typeof AuthAppHrUsersUserIdEditRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/teachers/$teacherId/edit': {
      id: '/_auth/app/hr/teachers/$teacherId/edit'
      path: '/teachers/$teacherId/edit'
      fullPath: '/app/hr/teachers/$teacherId/edit'
      preLoaderRoute: typeof AuthAppHrTeachersTeacherIdEditRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/staff/$staffId/edit': {
      id: '/_auth/app/hr/staff/$staffId/edit'
      path: '/staff/$staffId/edit'
      fullPath: '/app/hr/staff/$staffId/edit'
      preLoaderRoute: typeof AuthAppHrStaffStaffIdEditRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/roles/$roleId/edit': {
      id: '/_auth/app/hr/roles/$roleId/edit'
      path: '/roles/$roleId/edit'
      fullPath: '/app/hr/roles/$roleId/edit'
      preLoaderRoute: typeof AuthAppHrRolesRoleIdEditRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
  }
}

interface AuthAppHrRouteChildren {
  AuthAppHrIndexRoute: typeof AuthAppHrIndexRoute
  AuthAppHrRolesNewRoute: typeof AuthAppHrRolesNewRoute
  AuthAppHrStaffNewRoute: typeof AuthAppHrStaffNewRoute
  AuthAppHrTeachersNewRoute: typeof AuthAppHrTeachersNewRoute
  AuthAppHrUsersImportRoute: typeof AuthAppHrUsersImportRoute
  AuthAppHrUsersNewRoute: typeof AuthAppHrUsersNewRoute
  AuthAppHrRolesIndexRoute: typeof AuthAppHrRolesIndexRoute
  AuthAppHrStaffIndexRoute: typeof AuthAppHrStaffIndexRoute
  AuthAppHrTeachersIndexRoute: typeof AuthAppHrTeachersIndexRoute
  AuthAppHrUsersIndexRoute: typeof AuthAppHrUsersIndexRoute
  AuthAppHrRolesRoleIdEditRoute: typeof AuthAppHrRolesRoleIdEditRoute
  AuthAppHrStaffStaffIdEditRoute: typeof AuthAppHrStaffStaffIdEditRoute
  AuthAppHrTeachersTeacherIdEditRoute: typeof AuthAppHrTeachersTeacherIdEditRoute
  AuthAppHrUsersUserIdEditRoute: typeof AuthAppHrUsersUserIdEditRoute
  AuthAppHrRolesRoleIdIndexRoute: typeof AuthAppHrRolesRoleIdIndexRoute
  AuthAppHrStaffStaffIdIndexRoute: typeof AuthAppHrStaffStaffIdIndexRoute
  AuthAppHrTeachersTeacherIdIndexRoute: typeof AuthAppHrTeachersTeacherIdIndexRoute
  AuthAppHrUsersUserIdIndexRoute: typeof AuthAppHrUsersUserIdIndexRoute
}

const AuthAppHrRouteChildren: AuthAppHrRouteChildren = {
  AuthAppHrIndexRoute: AuthAppHrIndexRoute,
  AuthAppHrRolesNewRoute: AuthAppHrRolesNewRoute,
  AuthAppHrStaffNewRoute: AuthAppHrStaffNewRoute,
  AuthAppHrTeachersNewRoute: AuthAppHrTeachersNewRoute,
  AuthAppHrUsersImportRoute: AuthAppHrUsersImportRoute,
  AuthAppHrUsersNewRoute: AuthAppHrUsersNewRoute,
  AuthAppHrRolesIndexRoute: AuthAppHrRolesIndexRoute,
  AuthAppHrStaffIndexRoute: AuthAppHrStaffIndexRoute,
  AuthAppHrTeachersIndexRoute: AuthAppHrTeachersIndexRoute,
  AuthAppHrUsersIndexRoute: AuthAppHrUsersIndexRoute,
  AuthAppHrRolesRoleIdEditRoute: AuthAppHrRolesRoleIdEditRoute,
  AuthAppHrStaffStaffIdEditRoute: AuthAppHrStaffStaffIdEditRoute,
  AuthAppHrTeachersTeacherIdEditRoute: AuthAppHrTeachersTeacherIdEditRoute,
  AuthAppHrUsersUserIdEditRoute: AuthAppHrUsersUserIdEditRoute,
  AuthAppHrRolesRoleIdIndexRoute: AuthAppHrRolesRoleIdIndexRoute,
  AuthAppHrStaffStaffIdIndexRoute: AuthAppHrStaffStaffIdIndexRoute,
  AuthAppHrTeachersTeacherIdIndexRoute: AuthAppHrTeachersTeacherIdIndexRoute,
  AuthAppHrUsersUserIdIndexRoute: AuthAppHrUsersUserIdIndexRoute,
}

const AuthAppHrRouteWithChildren = AuthAppHrRoute._addFileChildren(
  AuthAppHrRouteChildren,
)

interface AuthAppRouteChildren {
  AuthAppDashboardRoute: typeof AuthAppDashboardRoute
  AuthAppHrRoute: typeof AuthAppHrRouteWithChildren
}

const AuthAppRouteChildren: AuthAppRouteChildren = {
  AuthAppDashboardRoute: AuthAppDashboardRoute,
  AuthAppHrRoute: AuthAppHrRouteWithChildren,
}

const AuthAppRouteWithChildren =
  AuthAppRoute._addFileChildren(AuthAppRouteChildren)

interface AuthRouteChildren {
  AuthAppRoute: typeof AuthAppRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAppRoute: AuthAppRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
