/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthAppRouteImport } from './routes/_auth/app'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthAppStudentsRouteImport } from './routes/_auth/app/students'
import { Route as AuthAppSpacesRouteImport } from './routes/_auth/app/spaces'
import { Route as AuthAppHrRouteImport } from './routes/_auth/app/hr'
import { Route as AuthAppDashboardRouteImport } from './routes/_auth/app/dashboard'
import { Route as AuthAppAcademicRouteImport } from './routes/_auth/app/academic'
import { Route as AuthAppStudentsIndexRouteImport } from './routes/_auth/app/students/index'
import { Route as AuthAppSpacesIndexRouteImport } from './routes/_auth/app/spaces/index'
import { Route as AuthAppHrIndexRouteImport } from './routes/_auth/app/hr/index'
import { Route as AuthAppAcademicIndexRouteImport } from './routes/_auth/app/academic/index'
import { Route as AuthAppStudentsParentsRouteImport } from './routes/_auth/app/students/parents'
import { Route as AuthAppStudentsNewRouteImport } from './routes/_auth/app/students/new'
import { Route as AuthAppStudentsEnrollmentsRouteImport } from './routes/_auth/app/students/enrollments'
import { Route as AuthAppSpacesAvailabilityRouteImport } from './routes/_auth/app/spaces/availability'
import { Route as AuthAppAcademicSubjectsRouteImport } from './routes/_auth/app/academic/subjects'
import { Route as AuthAppAcademicCoefficientsRouteImport } from './routes/_auth/app/academic/coefficients'
import { Route as AuthAppAcademicAssignmentsRouteImport } from './routes/_auth/app/academic/assignments'
import { Route as AuthAppStudentsStudentIdIndexRouteImport } from './routes/_auth/app/students/$studentId/index'
import { Route as AuthAppSpacesClassroomsIndexRouteImport } from './routes/_auth/app/spaces/classrooms/index'
import { Route as AuthAppHrUsersIndexRouteImport } from './routes/_auth/app/hr/users/index'
import { Route as AuthAppHrTeachersIndexRouteImport } from './routes/_auth/app/hr/teachers/index'
import { Route as AuthAppHrStaffIndexRouteImport } from './routes/_auth/app/hr/staff/index'
import { Route as AuthAppHrRolesIndexRouteImport } from './routes/_auth/app/hr/roles/index'
import { Route as AuthAppAcademicClassesIndexRouteImport } from './routes/_auth/app/academic/classes/index'
import { Route as AuthAppStudentsStudentIdEditRouteImport } from './routes/_auth/app/students/$studentId/edit'
import { Route as AuthAppHrUsersNewRouteImport } from './routes/_auth/app/hr/users/new'
import { Route as AuthAppHrUsersImportRouteImport } from './routes/_auth/app/hr/users/import'
import { Route as AuthAppHrTeachersNewRouteImport } from './routes/_auth/app/hr/teachers/new'
import { Route as AuthAppHrStaffNewRouteImport } from './routes/_auth/app/hr/staff/new'
import { Route as AuthAppHrRolesNewRouteImport } from './routes/_auth/app/hr/roles/new'
import { Route as AuthAppSpacesClassroomsClassroomIdIndexRouteImport } from './routes/_auth/app/spaces/classrooms/$classroomId/index'
import { Route as AuthAppHrUsersUserIdIndexRouteImport } from './routes/_auth/app/hr/users/$userId/index'
import { Route as AuthAppHrTeachersTeacherIdIndexRouteImport } from './routes/_auth/app/hr/teachers/$teacherId/index'
import { Route as AuthAppHrStaffStaffIdIndexRouteImport } from './routes/_auth/app/hr/staff/$staffId/index'
import { Route as AuthAppHrRolesRoleIdIndexRouteImport } from './routes/_auth/app/hr/roles/$roleId/index'
import { Route as AuthAppAcademicClassesClassIdIndexRouteImport } from './routes/_auth/app/academic/classes/$classId/index'
import { Route as AuthAppSpacesClassroomsClassroomIdEditRouteImport } from './routes/_auth/app/spaces/classrooms/$classroomId/edit'
import { Route as AuthAppHrUsersUserIdEditRouteImport } from './routes/_auth/app/hr/users/$userId/edit'
import { Route as AuthAppHrTeachersTeacherIdEditRouteImport } from './routes/_auth/app/hr/teachers/$teacherId/edit'
import { Route as AuthAppHrStaffStaffIdEditRouteImport } from './routes/_auth/app/hr/staff/$staffId/edit'
import { Route as AuthAppHrRolesRoleIdEditRouteImport } from './routes/_auth/app/hr/roles/$roleId/edit'
import { Route as AuthAppAcademicClassesClassIdEditRouteImport } from './routes/_auth/app/academic/classes/$classId/edit'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppRoute = AuthAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppStudentsRoute = AuthAppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppSpacesRoute = AuthAppSpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppHrRoute = AuthAppHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppDashboardRoute = AuthAppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppAcademicRoute = AuthAppAcademicRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppStudentsIndexRoute = AuthAppStudentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppStudentsRoute,
} as any)
const AuthAppSpacesIndexRoute = AuthAppSpacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppSpacesRoute,
} as any)
const AuthAppHrIndexRoute = AuthAppHrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppHrRoute,
} as any)
const AuthAppAcademicIndexRoute = AuthAppAcademicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppAcademicRoute,
} as any)
const AuthAppStudentsParentsRoute = AuthAppStudentsParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => AuthAppStudentsRoute,
} as any)
const AuthAppStudentsNewRoute = AuthAppStudentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthAppStudentsRoute,
} as any)
const AuthAppStudentsEnrollmentsRoute =
  AuthAppStudentsEnrollmentsRouteImport.update({
    id: '/enrollments',
    path: '/enrollments',
    getParentRoute: () => AuthAppStudentsRoute,
  } as any)
const AuthAppSpacesAvailabilityRoute =
  AuthAppSpacesAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthAppSpacesRoute,
  } as any)
const AuthAppAcademicSubjectsRoute = AuthAppAcademicSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AuthAppAcademicRoute,
} as any)
const AuthAppAcademicCoefficientsRoute =
  AuthAppAcademicCoefficientsRouteImport.update({
    id: '/coefficients',
    path: '/coefficients',
    getParentRoute: () => AuthAppAcademicRoute,
  } as any)
const AuthAppAcademicAssignmentsRoute =
  AuthAppAcademicAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthAppAcademicRoute,
  } as any)
const AuthAppStudentsStudentIdIndexRoute =
  AuthAppStudentsStudentIdIndexRouteImport.update({
    id: '/$studentId/',
    path: '/$studentId/',
    getParentRoute: () => AuthAppStudentsRoute,
  } as any)
const AuthAppSpacesClassroomsIndexRoute =
  AuthAppSpacesClassroomsIndexRouteImport.update({
    id: '/classrooms/',
    path: '/classrooms/',
    getParentRoute: () => AuthAppSpacesRoute,
  } as any)
const AuthAppHrUsersIndexRoute = AuthAppHrUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthAppHrRoute,
} as any)
const AuthAppHrTeachersIndexRoute = AuthAppHrTeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => AuthAppHrRoute,
} as any)
const AuthAppHrStaffIndexRoute = AuthAppHrStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AuthAppHrRoute,
} as any)
const AuthAppHrRolesIndexRoute = AuthAppHrRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthAppHrRoute,
} as any)
const AuthAppAcademicClassesIndexRoute =
  AuthAppAcademicClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => AuthAppAcademicRoute,
  } as any)
const AuthAppStudentsStudentIdEditRoute =
  AuthAppStudentsStudentIdEditRouteImport.update({
    id: '/$studentId/edit',
    path: '/$studentId/edit',
    getParentRoute: () => AuthAppStudentsRoute,
  } as any)
const AuthAppHrUsersNewRoute = AuthAppHrUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AuthAppHrRoute,
} as any)
const AuthAppHrUsersImportRoute = AuthAppHrUsersImportRouteImport.update({
  id: '/users/import',
  path: '/users/import',
  getParentRoute: () => AuthAppHrRoute,
} as any)
const AuthAppHrTeachersNewRoute = AuthAppHrTeachersNewRouteImport.update({
  id: '/teachers/new',
  path: '/teachers/new',
  getParentRoute: () => AuthAppHrRoute,
} as any)
const AuthAppHrStaffNewRoute = AuthAppHrStaffNewRouteImport.update({
  id: '/staff/new',
  path: '/staff/new',
  getParentRoute: () => AuthAppHrRoute,
} as any)
const AuthAppHrRolesNewRoute = AuthAppHrRolesNewRouteImport.update({
  id: '/roles/new',
  path: '/roles/new',
  getParentRoute: () => AuthAppHrRoute,
} as any)
const AuthAppSpacesClassroomsClassroomIdIndexRoute =
  AuthAppSpacesClassroomsClassroomIdIndexRouteImport.update({
    id: '/classrooms/$classroomId/',
    path: '/classrooms/$classroomId/',
    getParentRoute: () => AuthAppSpacesRoute,
  } as any)
const AuthAppHrUsersUserIdIndexRoute =
  AuthAppHrUsersUserIdIndexRouteImport.update({
    id: '/users/$userId/',
    path: '/users/$userId/',
    getParentRoute: () => AuthAppHrRoute,
  } as any)
const AuthAppHrTeachersTeacherIdIndexRoute =
  AuthAppHrTeachersTeacherIdIndexRouteImport.update({
    id: '/teachers/$teacherId/',
    path: '/teachers/$teacherId/',
    getParentRoute: () => AuthAppHrRoute,
  } as any)
const AuthAppHrStaffStaffIdIndexRoute =
  AuthAppHrStaffStaffIdIndexRouteImport.update({
    id: '/staff/$staffId/',
    path: '/staff/$staffId/',
    getParentRoute: () => AuthAppHrRoute,
  } as any)
const AuthAppHrRolesRoleIdIndexRoute =
  AuthAppHrRolesRoleIdIndexRouteImport.update({
    id: '/roles/$roleId/',
    path: '/roles/$roleId/',
    getParentRoute: () => AuthAppHrRoute,
  } as any)
const AuthAppAcademicClassesClassIdIndexRoute =
  AuthAppAcademicClassesClassIdIndexRouteImport.update({
    id: '/classes/$classId/',
    path: '/classes/$classId/',
    getParentRoute: () => AuthAppAcademicRoute,
  } as any)
const AuthAppSpacesClassroomsClassroomIdEditRoute =
  AuthAppSpacesClassroomsClassroomIdEditRouteImport.update({
    id: '/classrooms/$classroomId/edit',
    path: '/classrooms/$classroomId/edit',
    getParentRoute: () => AuthAppSpacesRoute,
  } as any)
const AuthAppHrUsersUserIdEditRoute =
  AuthAppHrUsersUserIdEditRouteImport.update({
    id: '/users/$userId/edit',
    path: '/users/$userId/edit',
    getParentRoute: () => AuthAppHrRoute,
  } as any)
const AuthAppHrTeachersTeacherIdEditRoute =
  AuthAppHrTeachersTeacherIdEditRouteImport.update({
    id: '/teachers/$teacherId/edit',
    path: '/teachers/$teacherId/edit',
    getParentRoute: () => AuthAppHrRoute,
  } as any)
const AuthAppHrStaffStaffIdEditRoute =
  AuthAppHrStaffStaffIdEditRouteImport.update({
    id: '/staff/$staffId/edit',
    path: '/staff/$staffId/edit',
    getParentRoute: () => AuthAppHrRoute,
  } as any)
const AuthAppHrRolesRoleIdEditRoute =
  AuthAppHrRolesRoleIdEditRouteImport.update({
    id: '/roles/$roleId/edit',
    path: '/roles/$roleId/edit',
    getParentRoute: () => AuthAppHrRoute,
  } as any)
const AuthAppAcademicClassesClassIdEditRoute =
  AuthAppAcademicClassesClassIdEditRouteImport.update({
    id: '/classes/$classId/edit',
    path: '/classes/$classId/edit',
    getParentRoute: () => AuthAppAcademicRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AuthAppRouteWithChildren
  '/app/academic': typeof AuthAppAcademicRouteWithChildren
  '/app/dashboard': typeof AuthAppDashboardRoute
  '/app/hr': typeof AuthAppHrRouteWithChildren
  '/app/spaces': typeof AuthAppSpacesRouteWithChildren
  '/app/students': typeof AuthAppStudentsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof AuthAppIndexRoute
  '/app/academic/assignments': typeof AuthAppAcademicAssignmentsRoute
  '/app/academic/coefficients': typeof AuthAppAcademicCoefficientsRoute
  '/app/academic/subjects': typeof AuthAppAcademicSubjectsRoute
  '/app/spaces/availability': typeof AuthAppSpacesAvailabilityRoute
  '/app/students/enrollments': typeof AuthAppStudentsEnrollmentsRoute
  '/app/students/new': typeof AuthAppStudentsNewRoute
  '/app/students/parents': typeof AuthAppStudentsParentsRoute
  '/app/academic/': typeof AuthAppAcademicIndexRoute
  '/app/hr/': typeof AuthAppHrIndexRoute
  '/app/spaces/': typeof AuthAppSpacesIndexRoute
  '/app/students/': typeof AuthAppStudentsIndexRoute
  '/app/hr/roles/new': typeof AuthAppHrRolesNewRoute
  '/app/hr/staff/new': typeof AuthAppHrStaffNewRoute
  '/app/hr/teachers/new': typeof AuthAppHrTeachersNewRoute
  '/app/hr/users/import': typeof AuthAppHrUsersImportRoute
  '/app/hr/users/new': typeof AuthAppHrUsersNewRoute
  '/app/students/$studentId/edit': typeof AuthAppStudentsStudentIdEditRoute
  '/app/academic/classes': typeof AuthAppAcademicClassesIndexRoute
  '/app/hr/roles': typeof AuthAppHrRolesIndexRoute
  '/app/hr/staff': typeof AuthAppHrStaffIndexRoute
  '/app/hr/teachers': typeof AuthAppHrTeachersIndexRoute
  '/app/hr/users': typeof AuthAppHrUsersIndexRoute
  '/app/spaces/classrooms': typeof AuthAppSpacesClassroomsIndexRoute
  '/app/students/$studentId': typeof AuthAppStudentsStudentIdIndexRoute
  '/app/academic/classes/$classId/edit': typeof AuthAppAcademicClassesClassIdEditRoute
  '/app/hr/roles/$roleId/edit': typeof AuthAppHrRolesRoleIdEditRoute
  '/app/hr/staff/$staffId/edit': typeof AuthAppHrStaffStaffIdEditRoute
  '/app/hr/teachers/$teacherId/edit': typeof AuthAppHrTeachersTeacherIdEditRoute
  '/app/hr/users/$userId/edit': typeof AuthAppHrUsersUserIdEditRoute
  '/app/spaces/classrooms/$classroomId/edit': typeof AuthAppSpacesClassroomsClassroomIdEditRoute
  '/app/academic/classes/$classId': typeof AuthAppAcademicClassesClassIdIndexRoute
  '/app/hr/roles/$roleId': typeof AuthAppHrRolesRoleIdIndexRoute
  '/app/hr/staff/$staffId': typeof AuthAppHrStaffStaffIdIndexRoute
  '/app/hr/teachers/$teacherId': typeof AuthAppHrTeachersTeacherIdIndexRoute
  '/app/hr/users/$userId': typeof AuthAppHrUsersUserIdIndexRoute
  '/app/spaces/classrooms/$classroomId': typeof AuthAppSpacesClassroomsClassroomIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/dashboard': typeof AuthAppDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
  '/app/academic/assignments': typeof AuthAppAcademicAssignmentsRoute
  '/app/academic/coefficients': typeof AuthAppAcademicCoefficientsRoute
  '/app/academic/subjects': typeof AuthAppAcademicSubjectsRoute
  '/app/spaces/availability': typeof AuthAppSpacesAvailabilityRoute
  '/app/students/enrollments': typeof AuthAppStudentsEnrollmentsRoute
  '/app/students/new': typeof AuthAppStudentsNewRoute
  '/app/students/parents': typeof AuthAppStudentsParentsRoute
  '/app/academic': typeof AuthAppAcademicIndexRoute
  '/app/hr': typeof AuthAppHrIndexRoute
  '/app/spaces': typeof AuthAppSpacesIndexRoute
  '/app/students': typeof AuthAppStudentsIndexRoute
  '/app/hr/roles/new': typeof AuthAppHrRolesNewRoute
  '/app/hr/staff/new': typeof AuthAppHrStaffNewRoute
  '/app/hr/teachers/new': typeof AuthAppHrTeachersNewRoute
  '/app/hr/users/import': typeof AuthAppHrUsersImportRoute
  '/app/hr/users/new': typeof AuthAppHrUsersNewRoute
  '/app/students/$studentId/edit': typeof AuthAppStudentsStudentIdEditRoute
  '/app/academic/classes': typeof AuthAppAcademicClassesIndexRoute
  '/app/hr/roles': typeof AuthAppHrRolesIndexRoute
  '/app/hr/staff': typeof AuthAppHrStaffIndexRoute
  '/app/hr/teachers': typeof AuthAppHrTeachersIndexRoute
  '/app/hr/users': typeof AuthAppHrUsersIndexRoute
  '/app/spaces/classrooms': typeof AuthAppSpacesClassroomsIndexRoute
  '/app/students/$studentId': typeof AuthAppStudentsStudentIdIndexRoute
  '/app/academic/classes/$classId/edit': typeof AuthAppAcademicClassesClassIdEditRoute
  '/app/hr/roles/$roleId/edit': typeof AuthAppHrRolesRoleIdEditRoute
  '/app/hr/staff/$staffId/edit': typeof AuthAppHrStaffStaffIdEditRoute
  '/app/hr/teachers/$teacherId/edit': typeof AuthAppHrTeachersTeacherIdEditRoute
  '/app/hr/users/$userId/edit': typeof AuthAppHrUsersUserIdEditRoute
  '/app/spaces/classrooms/$classroomId/edit': typeof AuthAppSpacesClassroomsClassroomIdEditRoute
  '/app/academic/classes/$classId': typeof AuthAppAcademicClassesClassIdIndexRoute
  '/app/hr/roles/$roleId': typeof AuthAppHrRolesRoleIdIndexRoute
  '/app/hr/staff/$staffId': typeof AuthAppHrStaffStaffIdIndexRoute
  '/app/hr/teachers/$teacherId': typeof AuthAppHrTeachersTeacherIdIndexRoute
  '/app/hr/users/$userId': typeof AuthAppHrUsersUserIdIndexRoute
  '/app/spaces/classrooms/$classroomId': typeof AuthAppSpacesClassroomsClassroomIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/app': typeof AuthAppRouteWithChildren
  '/_auth/app/academic': typeof AuthAppAcademicRouteWithChildren
  '/_auth/app/dashboard': typeof AuthAppDashboardRoute
  '/_auth/app/hr': typeof AuthAppHrRouteWithChildren
  '/_auth/app/spaces': typeof AuthAppSpacesRouteWithChildren
  '/_auth/app/students': typeof AuthAppStudentsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_auth/app/academic/assignments': typeof AuthAppAcademicAssignmentsRoute
  '/_auth/app/academic/coefficients': typeof AuthAppAcademicCoefficientsRoute
  '/_auth/app/academic/subjects': typeof AuthAppAcademicSubjectsRoute
  '/_auth/app/spaces/availability': typeof AuthAppSpacesAvailabilityRoute
  '/_auth/app/students/enrollments': typeof AuthAppStudentsEnrollmentsRoute
  '/_auth/app/students/new': typeof AuthAppStudentsNewRoute
  '/_auth/app/students/parents': typeof AuthAppStudentsParentsRoute
  '/_auth/app/academic/': typeof AuthAppAcademicIndexRoute
  '/_auth/app/hr/': typeof AuthAppHrIndexRoute
  '/_auth/app/spaces/': typeof AuthAppSpacesIndexRoute
  '/_auth/app/students/': typeof AuthAppStudentsIndexRoute
  '/_auth/app/hr/roles/new': typeof AuthAppHrRolesNewRoute
  '/_auth/app/hr/staff/new': typeof AuthAppHrStaffNewRoute
  '/_auth/app/hr/teachers/new': typeof AuthAppHrTeachersNewRoute
  '/_auth/app/hr/users/import': typeof AuthAppHrUsersImportRoute
  '/_auth/app/hr/users/new': typeof AuthAppHrUsersNewRoute
  '/_auth/app/students/$studentId/edit': typeof AuthAppStudentsStudentIdEditRoute
  '/_auth/app/academic/classes/': typeof AuthAppAcademicClassesIndexRoute
  '/_auth/app/hr/roles/': typeof AuthAppHrRolesIndexRoute
  '/_auth/app/hr/staff/': typeof AuthAppHrStaffIndexRoute
  '/_auth/app/hr/teachers/': typeof AuthAppHrTeachersIndexRoute
  '/_auth/app/hr/users/': typeof AuthAppHrUsersIndexRoute
  '/_auth/app/spaces/classrooms/': typeof AuthAppSpacesClassroomsIndexRoute
  '/_auth/app/students/$studentId/': typeof AuthAppStudentsStudentIdIndexRoute
  '/_auth/app/academic/classes/$classId/edit': typeof AuthAppAcademicClassesClassIdEditRoute
  '/_auth/app/hr/roles/$roleId/edit': typeof AuthAppHrRolesRoleIdEditRoute
  '/_auth/app/hr/staff/$staffId/edit': typeof AuthAppHrStaffStaffIdEditRoute
  '/_auth/app/hr/teachers/$teacherId/edit': typeof AuthAppHrTeachersTeacherIdEditRoute
  '/_auth/app/hr/users/$userId/edit': typeof AuthAppHrUsersUserIdEditRoute
  '/_auth/app/spaces/classrooms/$classroomId/edit': typeof AuthAppSpacesClassroomsClassroomIdEditRoute
  '/_auth/app/academic/classes/$classId/': typeof AuthAppAcademicClassesClassIdIndexRoute
  '/_auth/app/hr/roles/$roleId/': typeof AuthAppHrRolesRoleIdIndexRoute
  '/_auth/app/hr/staff/$staffId/': typeof AuthAppHrStaffStaffIdIndexRoute
  '/_auth/app/hr/teachers/$teacherId/': typeof AuthAppHrTeachersTeacherIdIndexRoute
  '/_auth/app/hr/users/$userId/': typeof AuthAppHrUsersUserIdIndexRoute
  '/_auth/app/spaces/classrooms/$classroomId/': typeof AuthAppSpacesClassroomsClassroomIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/academic'
    | '/app/dashboard'
    | '/app/hr'
    | '/app/spaces'
    | '/app/students'
    | '/api/auth/$'
    | '/app/'
    | '/app/academic/assignments'
    | '/app/academic/coefficients'
    | '/app/academic/subjects'
    | '/app/spaces/availability'
    | '/app/students/enrollments'
    | '/app/students/new'
    | '/app/students/parents'
    | '/app/academic/'
    | '/app/hr/'
    | '/app/spaces/'
    | '/app/students/'
    | '/app/hr/roles/new'
    | '/app/hr/staff/new'
    | '/app/hr/teachers/new'
    | '/app/hr/users/import'
    | '/app/hr/users/new'
    | '/app/students/$studentId/edit'
    | '/app/academic/classes'
    | '/app/hr/roles'
    | '/app/hr/staff'
    | '/app/hr/teachers'
    | '/app/hr/users'
    | '/app/spaces/classrooms'
    | '/app/students/$studentId'
    | '/app/academic/classes/$classId/edit'
    | '/app/hr/roles/$roleId/edit'
    | '/app/hr/staff/$staffId/edit'
    | '/app/hr/teachers/$teacherId/edit'
    | '/app/hr/users/$userId/edit'
    | '/app/spaces/classrooms/$classroomId/edit'
    | '/app/academic/classes/$classId'
    | '/app/hr/roles/$roleId'
    | '/app/hr/staff/$staffId'
    | '/app/hr/teachers/$teacherId'
    | '/app/hr/users/$userId'
    | '/app/spaces/classrooms/$classroomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/dashboard'
    | '/api/auth/$'
    | '/app'
    | '/app/academic/assignments'
    | '/app/academic/coefficients'
    | '/app/academic/subjects'
    | '/app/spaces/availability'
    | '/app/students/enrollments'
    | '/app/students/new'
    | '/app/students/parents'
    | '/app/academic'
    | '/app/hr'
    | '/app/spaces'
    | '/app/students'
    | '/app/hr/roles/new'
    | '/app/hr/staff/new'
    | '/app/hr/teachers/new'
    | '/app/hr/users/import'
    | '/app/hr/users/new'
    | '/app/students/$studentId/edit'
    | '/app/academic/classes'
    | '/app/hr/roles'
    | '/app/hr/staff'
    | '/app/hr/teachers'
    | '/app/hr/users'
    | '/app/spaces/classrooms'
    | '/app/students/$studentId'
    | '/app/academic/classes/$classId/edit'
    | '/app/hr/roles/$roleId/edit'
    | '/app/hr/staff/$staffId/edit'
    | '/app/hr/teachers/$teacherId/edit'
    | '/app/hr/users/$userId/edit'
    | '/app/spaces/classrooms/$classroomId/edit'
    | '/app/academic/classes/$classId'
    | '/app/hr/roles/$roleId'
    | '/app/hr/staff/$staffId'
    | '/app/hr/teachers/$teacherId'
    | '/app/hr/users/$userId'
    | '/app/spaces/classrooms/$classroomId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/app'
    | '/_auth/app/academic'
    | '/_auth/app/dashboard'
    | '/_auth/app/hr'
    | '/_auth/app/spaces'
    | '/_auth/app/students'
    | '/api/auth/$'
    | '/_auth/app/'
    | '/_auth/app/academic/assignments'
    | '/_auth/app/academic/coefficients'
    | '/_auth/app/academic/subjects'
    | '/_auth/app/spaces/availability'
    | '/_auth/app/students/enrollments'
    | '/_auth/app/students/new'
    | '/_auth/app/students/parents'
    | '/_auth/app/academic/'
    | '/_auth/app/hr/'
    | '/_auth/app/spaces/'
    | '/_auth/app/students/'
    | '/_auth/app/hr/roles/new'
    | '/_auth/app/hr/staff/new'
    | '/_auth/app/hr/teachers/new'
    | '/_auth/app/hr/users/import'
    | '/_auth/app/hr/users/new'
    | '/_auth/app/students/$studentId/edit'
    | '/_auth/app/academic/classes/'
    | '/_auth/app/hr/roles/'
    | '/_auth/app/hr/staff/'
    | '/_auth/app/hr/teachers/'
    | '/_auth/app/hr/users/'
    | '/_auth/app/spaces/classrooms/'
    | '/_auth/app/students/$studentId/'
    | '/_auth/app/academic/classes/$classId/edit'
    | '/_auth/app/hr/roles/$roleId/edit'
    | '/_auth/app/hr/staff/$staffId/edit'
    | '/_auth/app/hr/teachers/$teacherId/edit'
    | '/_auth/app/hr/users/$userId/edit'
    | '/_auth/app/spaces/classrooms/$classroomId/edit'
    | '/_auth/app/academic/classes/$classId/'
    | '/_auth/app/hr/roles/$roleId/'
    | '/_auth/app/hr/staff/$staffId/'
    | '/_auth/app/hr/teachers/$teacherId/'
    | '/_auth/app/hr/users/$userId/'
    | '/_auth/app/spaces/classrooms/$classroomId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/students': {
      id: '/_auth/app/students'
      path: '/students'
      fullPath: '/app/students'
      preLoaderRoute: typeof AuthAppStudentsRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/spaces': {
      id: '/_auth/app/spaces'
      path: '/spaces'
      fullPath: '/app/spaces'
      preLoaderRoute: typeof AuthAppSpacesRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/hr': {
      id: '/_auth/app/hr'
      path: '/hr'
      fullPath: '/app/hr'
      preLoaderRoute: typeof AuthAppHrRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/dashboard': {
      id: '/_auth/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthAppDashboardRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/academic': {
      id: '/_auth/app/academic'
      path: '/academic'
      fullPath: '/app/academic'
      preLoaderRoute: typeof AuthAppAcademicRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/students/': {
      id: '/_auth/app/students/'
      path: '/'
      fullPath: '/app/students/'
      preLoaderRoute: typeof AuthAppStudentsIndexRouteImport
      parentRoute: typeof AuthAppStudentsRoute
    }
    '/_auth/app/spaces/': {
      id: '/_auth/app/spaces/'
      path: '/'
      fullPath: '/app/spaces/'
      preLoaderRoute: typeof AuthAppSpacesIndexRouteImport
      parentRoute: typeof AuthAppSpacesRoute
    }
    '/_auth/app/hr/': {
      id: '/_auth/app/hr/'
      path: '/'
      fullPath: '/app/hr/'
      preLoaderRoute: typeof AuthAppHrIndexRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/academic/': {
      id: '/_auth/app/academic/'
      path: '/'
      fullPath: '/app/academic/'
      preLoaderRoute: typeof AuthAppAcademicIndexRouteImport
      parentRoute: typeof AuthAppAcademicRoute
    }
    '/_auth/app/students/parents': {
      id: '/_auth/app/students/parents'
      path: '/parents'
      fullPath: '/app/students/parents'
      preLoaderRoute: typeof AuthAppStudentsParentsRouteImport
      parentRoute: typeof AuthAppStudentsRoute
    }
    '/_auth/app/students/new': {
      id: '/_auth/app/students/new'
      path: '/new'
      fullPath: '/app/students/new'
      preLoaderRoute: typeof AuthAppStudentsNewRouteImport
      parentRoute: typeof AuthAppStudentsRoute
    }
    '/_auth/app/students/enrollments': {
      id: '/_auth/app/students/enrollments'
      path: '/enrollments'
      fullPath: '/app/students/enrollments'
      preLoaderRoute: typeof AuthAppStudentsEnrollmentsRouteImport
      parentRoute: typeof AuthAppStudentsRoute
    }
    '/_auth/app/spaces/availability': {
      id: '/_auth/app/spaces/availability'
      path: '/availability'
      fullPath: '/app/spaces/availability'
      preLoaderRoute: typeof AuthAppSpacesAvailabilityRouteImport
      parentRoute: typeof AuthAppSpacesRoute
    }
    '/_auth/app/academic/subjects': {
      id: '/_auth/app/academic/subjects'
      path: '/subjects'
      fullPath: '/app/academic/subjects'
      preLoaderRoute: typeof AuthAppAcademicSubjectsRouteImport
      parentRoute: typeof AuthAppAcademicRoute
    }
    '/_auth/app/academic/coefficients': {
      id: '/_auth/app/academic/coefficients'
      path: '/coefficients'
      fullPath: '/app/academic/coefficients'
      preLoaderRoute: typeof AuthAppAcademicCoefficientsRouteImport
      parentRoute: typeof AuthAppAcademicRoute
    }
    '/_auth/app/academic/assignments': {
      id: '/_auth/app/academic/assignments'
      path: '/assignments'
      fullPath: '/app/academic/assignments'
      preLoaderRoute: typeof AuthAppAcademicAssignmentsRouteImport
      parentRoute: typeof AuthAppAcademicRoute
    }
    '/_auth/app/students/$studentId/': {
      id: '/_auth/app/students/$studentId/'
      path: '/$studentId'
      fullPath: '/app/students/$studentId'
      preLoaderRoute: typeof AuthAppStudentsStudentIdIndexRouteImport
      parentRoute: typeof AuthAppStudentsRoute
    }
    '/_auth/app/spaces/classrooms/': {
      id: '/_auth/app/spaces/classrooms/'
      path: '/classrooms'
      fullPath: '/app/spaces/classrooms'
      preLoaderRoute: typeof AuthAppSpacesClassroomsIndexRouteImport
      parentRoute: typeof AuthAppSpacesRoute
    }
    '/_auth/app/hr/users/': {
      id: '/_auth/app/hr/users/'
      path: '/users'
      fullPath: '/app/hr/users'
      preLoaderRoute: typeof AuthAppHrUsersIndexRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/teachers/': {
      id: '/_auth/app/hr/teachers/'
      path: '/teachers'
      fullPath: '/app/hr/teachers'
      preLoaderRoute: typeof AuthAppHrTeachersIndexRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/staff/': {
      id: '/_auth/app/hr/staff/'
      path: '/staff'
      fullPath: '/app/hr/staff'
      preLoaderRoute: typeof AuthAppHrStaffIndexRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/roles/': {
      id: '/_auth/app/hr/roles/'
      path: '/roles'
      fullPath: '/app/hr/roles'
      preLoaderRoute: typeof AuthAppHrRolesIndexRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/academic/classes/': {
      id: '/_auth/app/academic/classes/'
      path: '/classes'
      fullPath: '/app/academic/classes'
      preLoaderRoute: typeof AuthAppAcademicClassesIndexRouteImport
      parentRoute: typeof AuthAppAcademicRoute
    }
    '/_auth/app/students/$studentId/edit': {
      id: '/_auth/app/students/$studentId/edit'
      path: '/$studentId/edit'
      fullPath: '/app/students/$studentId/edit'
      preLoaderRoute: typeof AuthAppStudentsStudentIdEditRouteImport
      parentRoute: typeof AuthAppStudentsRoute
    }
    '/_auth/app/hr/users/new': {
      id: '/_auth/app/hr/users/new'
      path: '/users/new'
      fullPath: '/app/hr/users/new'
      preLoaderRoute: typeof AuthAppHrUsersNewRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/users/import': {
      id: '/_auth/app/hr/users/import'
      path: '/users/import'
      fullPath: '/app/hr/users/import'
      preLoaderRoute: typeof AuthAppHrUsersImportRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/teachers/new': {
      id: '/_auth/app/hr/teachers/new'
      path: '/teachers/new'
      fullPath: '/app/hr/teachers/new'
      preLoaderRoute: typeof AuthAppHrTeachersNewRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/staff/new': {
      id: '/_auth/app/hr/staff/new'
      path: '/staff/new'
      fullPath: '/app/hr/staff/new'
      preLoaderRoute: typeof AuthAppHrStaffNewRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/roles/new': {
      id: '/_auth/app/hr/roles/new'
      path: '/roles/new'
      fullPath: '/app/hr/roles/new'
      preLoaderRoute: typeof AuthAppHrRolesNewRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/spaces/classrooms/$classroomId/': {
      id: '/_auth/app/spaces/classrooms/$classroomId/'
      path: '/classrooms/$classroomId'
      fullPath: '/app/spaces/classrooms/$classroomId'
      preLoaderRoute: typeof AuthAppSpacesClassroomsClassroomIdIndexRouteImport
      parentRoute: typeof AuthAppSpacesRoute
    }
    '/_auth/app/hr/users/$userId/': {
      id: '/_auth/app/hr/users/$userId/'
      path: '/users/$userId'
      fullPath: '/app/hr/users/$userId'
      preLoaderRoute: typeof AuthAppHrUsersUserIdIndexRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/teachers/$teacherId/': {
      id: '/_auth/app/hr/teachers/$teacherId/'
      path: '/teachers/$teacherId'
      fullPath: '/app/hr/teachers/$teacherId'
      preLoaderRoute: typeof AuthAppHrTeachersTeacherIdIndexRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/staff/$staffId/': {
      id: '/_auth/app/hr/staff/$staffId/'
      path: '/staff/$staffId'
      fullPath: '/app/hr/staff/$staffId'
      preLoaderRoute: typeof AuthAppHrStaffStaffIdIndexRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/roles/$roleId/': {
      id: '/_auth/app/hr/roles/$roleId/'
      path: '/roles/$roleId'
      fullPath: '/app/hr/roles/$roleId'
      preLoaderRoute: typeof AuthAppHrRolesRoleIdIndexRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/academic/classes/$classId/': {
      id: '/_auth/app/academic/classes/$classId/'
      path: '/classes/$classId'
      fullPath: '/app/academic/classes/$classId'
      preLoaderRoute: typeof AuthAppAcademicClassesClassIdIndexRouteImport
      parentRoute: typeof AuthAppAcademicRoute
    }
    '/_auth/app/spaces/classrooms/$classroomId/edit': {
      id: '/_auth/app/spaces/classrooms/$classroomId/edit'
      path: '/classrooms/$classroomId/edit'
      fullPath: '/app/spaces/classrooms/$classroomId/edit'
      preLoaderRoute: typeof AuthAppSpacesClassroomsClassroomIdEditRouteImport
      parentRoute: typeof AuthAppSpacesRoute
    }
    '/_auth/app/hr/users/$userId/edit': {
      id: '/_auth/app/hr/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/app/hr/users/$userId/edit'
      preLoaderRoute: typeof AuthAppHrUsersUserIdEditRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/teachers/$teacherId/edit': {
      id: '/_auth/app/hr/teachers/$teacherId/edit'
      path: '/teachers/$teacherId/edit'
      fullPath: '/app/hr/teachers/$teacherId/edit'
      preLoaderRoute: typeof AuthAppHrTeachersTeacherIdEditRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/staff/$staffId/edit': {
      id: '/_auth/app/hr/staff/$staffId/edit'
      path: '/staff/$staffId/edit'
      fullPath: '/app/hr/staff/$staffId/edit'
      preLoaderRoute: typeof AuthAppHrStaffStaffIdEditRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/hr/roles/$roleId/edit': {
      id: '/_auth/app/hr/roles/$roleId/edit'
      path: '/roles/$roleId/edit'
      fullPath: '/app/hr/roles/$roleId/edit'
      preLoaderRoute: typeof AuthAppHrRolesRoleIdEditRouteImport
      parentRoute: typeof AuthAppHrRoute
    }
    '/_auth/app/academic/classes/$classId/edit': {
      id: '/_auth/app/academic/classes/$classId/edit'
      path: '/classes/$classId/edit'
      fullPath: '/app/academic/classes/$classId/edit'
      preLoaderRoute: typeof AuthAppAcademicClassesClassIdEditRouteImport
      parentRoute: typeof AuthAppAcademicRoute
    }
  }
}

interface AuthAppAcademicRouteChildren {
  AuthAppAcademicAssignmentsRoute: typeof AuthAppAcademicAssignmentsRoute
  AuthAppAcademicCoefficientsRoute: typeof AuthAppAcademicCoefficientsRoute
  AuthAppAcademicSubjectsRoute: typeof AuthAppAcademicSubjectsRoute
  AuthAppAcademicIndexRoute: typeof AuthAppAcademicIndexRoute
  AuthAppAcademicClassesIndexRoute: typeof AuthAppAcademicClassesIndexRoute
  AuthAppAcademicClassesClassIdEditRoute: typeof AuthAppAcademicClassesClassIdEditRoute
  AuthAppAcademicClassesClassIdIndexRoute: typeof AuthAppAcademicClassesClassIdIndexRoute
}

const AuthAppAcademicRouteChildren: AuthAppAcademicRouteChildren = {
  AuthAppAcademicAssignmentsRoute: AuthAppAcademicAssignmentsRoute,
  AuthAppAcademicCoefficientsRoute: AuthAppAcademicCoefficientsRoute,
  AuthAppAcademicSubjectsRoute: AuthAppAcademicSubjectsRoute,
  AuthAppAcademicIndexRoute: AuthAppAcademicIndexRoute,
  AuthAppAcademicClassesIndexRoute: AuthAppAcademicClassesIndexRoute,
  AuthAppAcademicClassesClassIdEditRoute:
    AuthAppAcademicClassesClassIdEditRoute,
  AuthAppAcademicClassesClassIdIndexRoute:
    AuthAppAcademicClassesClassIdIndexRoute,
}

const AuthAppAcademicRouteWithChildren = AuthAppAcademicRoute._addFileChildren(
  AuthAppAcademicRouteChildren,
)

interface AuthAppHrRouteChildren {
  AuthAppHrIndexRoute: typeof AuthAppHrIndexRoute
  AuthAppHrRolesNewRoute: typeof AuthAppHrRolesNewRoute
  AuthAppHrStaffNewRoute: typeof AuthAppHrStaffNewRoute
  AuthAppHrTeachersNewRoute: typeof AuthAppHrTeachersNewRoute
  AuthAppHrUsersImportRoute: typeof AuthAppHrUsersImportRoute
  AuthAppHrUsersNewRoute: typeof AuthAppHrUsersNewRoute
  AuthAppHrRolesIndexRoute: typeof AuthAppHrRolesIndexRoute
  AuthAppHrStaffIndexRoute: typeof AuthAppHrStaffIndexRoute
  AuthAppHrTeachersIndexRoute: typeof AuthAppHrTeachersIndexRoute
  AuthAppHrUsersIndexRoute: typeof AuthAppHrUsersIndexRoute
  AuthAppHrRolesRoleIdEditRoute: typeof AuthAppHrRolesRoleIdEditRoute
  AuthAppHrStaffStaffIdEditRoute: typeof AuthAppHrStaffStaffIdEditRoute
  AuthAppHrTeachersTeacherIdEditRoute: typeof AuthAppHrTeachersTeacherIdEditRoute
  AuthAppHrUsersUserIdEditRoute: typeof AuthAppHrUsersUserIdEditRoute
  AuthAppHrRolesRoleIdIndexRoute: typeof AuthAppHrRolesRoleIdIndexRoute
  AuthAppHrStaffStaffIdIndexRoute: typeof AuthAppHrStaffStaffIdIndexRoute
  AuthAppHrTeachersTeacherIdIndexRoute: typeof AuthAppHrTeachersTeacherIdIndexRoute
  AuthAppHrUsersUserIdIndexRoute: typeof AuthAppHrUsersUserIdIndexRoute
}

const AuthAppHrRouteChildren: AuthAppHrRouteChildren = {
  AuthAppHrIndexRoute: AuthAppHrIndexRoute,
  AuthAppHrRolesNewRoute: AuthAppHrRolesNewRoute,
  AuthAppHrStaffNewRoute: AuthAppHrStaffNewRoute,
  AuthAppHrTeachersNewRoute: AuthAppHrTeachersNewRoute,
  AuthAppHrUsersImportRoute: AuthAppHrUsersImportRoute,
  AuthAppHrUsersNewRoute: AuthAppHrUsersNewRoute,
  AuthAppHrRolesIndexRoute: AuthAppHrRolesIndexRoute,
  AuthAppHrStaffIndexRoute: AuthAppHrStaffIndexRoute,
  AuthAppHrTeachersIndexRoute: AuthAppHrTeachersIndexRoute,
  AuthAppHrUsersIndexRoute: AuthAppHrUsersIndexRoute,
  AuthAppHrRolesRoleIdEditRoute: AuthAppHrRolesRoleIdEditRoute,
  AuthAppHrStaffStaffIdEditRoute: AuthAppHrStaffStaffIdEditRoute,
  AuthAppHrTeachersTeacherIdEditRoute: AuthAppHrTeachersTeacherIdEditRoute,
  AuthAppHrUsersUserIdEditRoute: AuthAppHrUsersUserIdEditRoute,
  AuthAppHrRolesRoleIdIndexRoute: AuthAppHrRolesRoleIdIndexRoute,
  AuthAppHrStaffStaffIdIndexRoute: AuthAppHrStaffStaffIdIndexRoute,
  AuthAppHrTeachersTeacherIdIndexRoute: AuthAppHrTeachersTeacherIdIndexRoute,
  AuthAppHrUsersUserIdIndexRoute: AuthAppHrUsersUserIdIndexRoute,
}

const AuthAppHrRouteWithChildren = AuthAppHrRoute._addFileChildren(
  AuthAppHrRouteChildren,
)

interface AuthAppSpacesRouteChildren {
  AuthAppSpacesAvailabilityRoute: typeof AuthAppSpacesAvailabilityRoute
  AuthAppSpacesIndexRoute: typeof AuthAppSpacesIndexRoute
  AuthAppSpacesClassroomsIndexRoute: typeof AuthAppSpacesClassroomsIndexRoute
  AuthAppSpacesClassroomsClassroomIdEditRoute: typeof AuthAppSpacesClassroomsClassroomIdEditRoute
  AuthAppSpacesClassroomsClassroomIdIndexRoute: typeof AuthAppSpacesClassroomsClassroomIdIndexRoute
}

const AuthAppSpacesRouteChildren: AuthAppSpacesRouteChildren = {
  AuthAppSpacesAvailabilityRoute: AuthAppSpacesAvailabilityRoute,
  AuthAppSpacesIndexRoute: AuthAppSpacesIndexRoute,
  AuthAppSpacesClassroomsIndexRoute: AuthAppSpacesClassroomsIndexRoute,
  AuthAppSpacesClassroomsClassroomIdEditRoute:
    AuthAppSpacesClassroomsClassroomIdEditRoute,
  AuthAppSpacesClassroomsClassroomIdIndexRoute:
    AuthAppSpacesClassroomsClassroomIdIndexRoute,
}

const AuthAppSpacesRouteWithChildren = AuthAppSpacesRoute._addFileChildren(
  AuthAppSpacesRouteChildren,
)

interface AuthAppStudentsRouteChildren {
  AuthAppStudentsEnrollmentsRoute: typeof AuthAppStudentsEnrollmentsRoute
  AuthAppStudentsNewRoute: typeof AuthAppStudentsNewRoute
  AuthAppStudentsParentsRoute: typeof AuthAppStudentsParentsRoute
  AuthAppStudentsIndexRoute: typeof AuthAppStudentsIndexRoute
  AuthAppStudentsStudentIdEditRoute: typeof AuthAppStudentsStudentIdEditRoute
  AuthAppStudentsStudentIdIndexRoute: typeof AuthAppStudentsStudentIdIndexRoute
}

const AuthAppStudentsRouteChildren: AuthAppStudentsRouteChildren = {
  AuthAppStudentsEnrollmentsRoute: AuthAppStudentsEnrollmentsRoute,
  AuthAppStudentsNewRoute: AuthAppStudentsNewRoute,
  AuthAppStudentsParentsRoute: AuthAppStudentsParentsRoute,
  AuthAppStudentsIndexRoute: AuthAppStudentsIndexRoute,
  AuthAppStudentsStudentIdEditRoute: AuthAppStudentsStudentIdEditRoute,
  AuthAppStudentsStudentIdIndexRoute: AuthAppStudentsStudentIdIndexRoute,
}

const AuthAppStudentsRouteWithChildren = AuthAppStudentsRoute._addFileChildren(
  AuthAppStudentsRouteChildren,
)

interface AuthAppRouteChildren {
  AuthAppAcademicRoute: typeof AuthAppAcademicRouteWithChildren
  AuthAppDashboardRoute: typeof AuthAppDashboardRoute
  AuthAppHrRoute: typeof AuthAppHrRouteWithChildren
  AuthAppSpacesRoute: typeof AuthAppSpacesRouteWithChildren
  AuthAppStudentsRoute: typeof AuthAppStudentsRouteWithChildren
  AuthAppIndexRoute: typeof AuthAppIndexRoute
}

const AuthAppRouteChildren: AuthAppRouteChildren = {
  AuthAppAcademicRoute: AuthAppAcademicRouteWithChildren,
  AuthAppDashboardRoute: AuthAppDashboardRoute,
  AuthAppHrRoute: AuthAppHrRouteWithChildren,
  AuthAppSpacesRoute: AuthAppSpacesRouteWithChildren,
  AuthAppStudentsRoute: AuthAppStudentsRouteWithChildren,
  AuthAppIndexRoute: AuthAppIndexRoute,
}

const AuthAppRouteWithChildren =
  AuthAppRoute._addFileChildren(AuthAppRouteChildren)

interface AuthRouteChildren {
  AuthAppRoute: typeof AuthAppRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAppRoute: AuthAppRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
