import { ILocalization } from './tr';

const resource: ILocalization = {
  hello: 'translated hello',
  name: 'Ali Burhan Keskin',
  confirm: 'Confirm',
  cancel: 'Cancel',
  generalActivityIndicatorText: 'Loading...',
  pleaseWait: 'Please wait... ',
  generalErrorText: 'An error occurred, please try again later.',
  search: 'Search',
  noInternet: 'No Internet Connection',
  yes: 'Yes',
  no: 'No',
  exit: 'Exit',
  brand: 'Brand',
  published: 'Published',
  min: 'min',
  piece: 'Piece',
  time: 'Time',
  description: 'Description',
  send: 'Send',
  next: 'Next',
  previous: 'Previous',
  retry: 'Retry',

  navigation: {
    home: 'Home Page',
    profile: 'Profile',
    settings: 'Settings',
    post: 'Post',
  },
  welcome: 'Welcome!',
  welcomeBack: 'Welcome back!',
  email: 'Email',
  password: 'Password',
  forgotPassword: 'Forgot password?',
  login: 'Login',
  or: 'or',
  loginWithGoogle: 'Login with Google',
  dontHaveAccount: "Don't have an account?",
  register: 'Register',
  googleLoginNotImplemented: 'Google login is not yet implemented.',
  forgotPasswordNotImplemented: 'Forgot password functionality is not yet implemented.',
  createAccount: 'Create Account',
  fullName: 'Full Name',
  invalidEmail: 'Invalid Email',
  confirmPassword: 'Confirm Password',
  passwordsDoNotMatch: 'Passwords do not match',
  acceptTerms: 'I accept the',
  termsAndConditions: 'Terms and Conditions',
  termsAndConditionsNotImplemented: 'Terms and Conditions are not yet implemented.',
  registrationSuccessful: 'Registration successful!',
  back: 'Back',
};

export default resource;
