// Generated by Wrangler by running `wrangler types --env-interface Env`

declare namespace Cloudflare {
  interface Env {
    MY_VAR: string
    DATABASE_HOST: string
    DATABASE_USERNAME: string
    DATABASE_PASSWORD: string
    BETTER_AUTH_SECRET: string
    GOOGLE_CLIENT_ID: string
    GOOGLE_CLIENT_SECRET: string
  }
}

interface Env extends Cloudflare.Env { }

declare module 'cloudflare:workers' {
  export const env: Env
}
