/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as DemoRequestRouteImport } from './routes/demo-request'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthAppDashboardRouteImport } from './routes/_auth/app/dashboard'
import { Route as AuthAppAnalyticsRouteImport } from './routes/_auth/app/analytics'
import { Route as AuthAppUsersIndexRouteImport } from './routes/_auth/app/users/index'
import { Route as AuthAppSupportIndexRouteImport } from './routes/_auth/app/support/index'
import { Route as AuthAppSchoolsIndexRouteImport } from './routes/_auth/app/schools/index'
import { Route as AuthAppRolesIndexRouteImport } from './routes/_auth/app/roles/index'
import { Route as AuthAppCatalogsIndexRouteImport } from './routes/_auth/app/catalogs/index'
import { Route as AuthAppAnalyticsIndexRouteImport } from './routes/_auth/app/analytics/index'
import { Route as AuthAppSchoolsCreateRouteImport } from './routes/_auth/app/schools/create'
import { Route as AuthAppSchoolsSchoolIdRouteImport } from './routes/_auth/app/schools/$schoolId'
import { Route as AuthAppPolarSubscriptionsRouteImport } from './routes/_auth/app/polar/subscriptions'
import { Route as AuthAppPolarPortalRouteImport } from './routes/_auth/app/polar/portal'
import { Route as AuthAppCatalogsTracksRouteImport } from './routes/_auth/app/catalogs/tracks'
import { Route as AuthAppCatalogsSubjectsRouteImport } from './routes/_auth/app/catalogs/subjects'
import { Route as AuthAppCatalogsSchoolYearsRouteImport } from './routes/_auth/app/catalogs/school-years'
import { Route as AuthAppCatalogsProgramsRouteImport } from './routes/_auth/app/catalogs/programs'
import { Route as AuthAppCatalogsGradesRouteImport } from './routes/_auth/app/catalogs/grades'
import { Route as AuthAppCatalogsFeeTypeTemplatesRouteImport } from './routes/_auth/app/catalogs/fee-type-templates'
import { Route as AuthAppCatalogsCoefficientsRouteImport } from './routes/_auth/app/catalogs/coefficients'
import { Route as AuthAppSchoolsSchoolIdEditRouteImport } from './routes/_auth/app/schools/$schoolId_.edit'
import { Route as AuthAppPolarCheckoutSuccessRouteImport } from './routes/_auth/app/polar/checkout.success'
import { Route as AuthAppCatalogsProgramsProgramIdRouteImport } from './routes/_auth/app/catalogs/programs/$programId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRequestRoute = DemoRequestRouteImport.update({
  id: '/demo-request',
  path: '/demo-request',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppDashboardRoute = AuthAppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppAnalyticsRoute = AuthAppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppUsersIndexRoute = AuthAppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppSupportIndexRoute = AuthAppSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppSchoolsIndexRoute = AuthAppSchoolsIndexRouteImport.update({
  id: '/schools/',
  path: '/schools/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppRolesIndexRoute = AuthAppRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppCatalogsIndexRoute = AuthAppCatalogsIndexRouteImport.update({
  id: '/catalogs/',
  path: '/catalogs/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppAnalyticsIndexRoute = AuthAppAnalyticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppAnalyticsRoute,
} as any)
const AuthAppSchoolsCreateRoute = AuthAppSchoolsCreateRouteImport.update({
  id: '/schools/create',
  path: '/schools/create',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppSchoolsSchoolIdRoute = AuthAppSchoolsSchoolIdRouteImport.update({
  id: '/schools/$schoolId',
  path: '/schools/$schoolId',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppPolarSubscriptionsRoute =
  AuthAppPolarSubscriptionsRouteImport.update({
    id: '/polar/subscriptions',
    path: '/polar/subscriptions',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppPolarPortalRoute = AuthAppPolarPortalRouteImport.update({
  id: '/polar/portal',
  path: '/polar/portal',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppCatalogsTracksRoute = AuthAppCatalogsTracksRouteImport.update({
  id: '/catalogs/tracks',
  path: '/catalogs/tracks',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppCatalogsSubjectsRoute = AuthAppCatalogsSubjectsRouteImport.update({
  id: '/catalogs/subjects',
  path: '/catalogs/subjects',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppCatalogsSchoolYearsRoute =
  AuthAppCatalogsSchoolYearsRouteImport.update({
    id: '/catalogs/school-years',
    path: '/catalogs/school-years',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppCatalogsProgramsRoute = AuthAppCatalogsProgramsRouteImport.update({
  id: '/catalogs/programs',
  path: '/catalogs/programs',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppCatalogsGradesRoute = AuthAppCatalogsGradesRouteImport.update({
  id: '/catalogs/grades',
  path: '/catalogs/grades',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppCatalogsFeeTypeTemplatesRoute =
  AuthAppCatalogsFeeTypeTemplatesRouteImport.update({
    id: '/catalogs/fee-type-templates',
    path: '/catalogs/fee-type-templates',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppCatalogsCoefficientsRoute =
  AuthAppCatalogsCoefficientsRouteImport.update({
    id: '/catalogs/coefficients',
    path: '/catalogs/coefficients',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppSchoolsSchoolIdEditRoute =
  AuthAppSchoolsSchoolIdEditRouteImport.update({
    id: '/schools/$schoolId_/edit',
    path: '/schools/$schoolId/edit',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppPolarCheckoutSuccessRoute =
  AuthAppPolarCheckoutSuccessRouteImport.update({
    id: '/polar/checkout/success',
    path: '/polar/checkout/success',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppCatalogsProgramsProgramIdRoute =
  AuthAppCatalogsProgramsProgramIdRouteImport.update({
    id: '/$programId',
    path: '/$programId',
    getParentRoute: () => AuthAppCatalogsProgramsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo-request': typeof DemoRequestRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/app/analytics': typeof AuthAppAnalyticsRouteWithChildren
  '/app/dashboard': typeof AuthAppDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof AuthAppIndexRoute
  '/app/catalogs/coefficients': typeof AuthAppCatalogsCoefficientsRoute
  '/app/catalogs/fee-type-templates': typeof AuthAppCatalogsFeeTypeTemplatesRoute
  '/app/catalogs/grades': typeof AuthAppCatalogsGradesRoute
  '/app/catalogs/programs': typeof AuthAppCatalogsProgramsRouteWithChildren
  '/app/catalogs/school-years': typeof AuthAppCatalogsSchoolYearsRoute
  '/app/catalogs/subjects': typeof AuthAppCatalogsSubjectsRoute
  '/app/catalogs/tracks': typeof AuthAppCatalogsTracksRoute
  '/app/polar/portal': typeof AuthAppPolarPortalRoute
  '/app/polar/subscriptions': typeof AuthAppPolarSubscriptionsRoute
  '/app/schools/$schoolId': typeof AuthAppSchoolsSchoolIdRoute
  '/app/schools/create': typeof AuthAppSchoolsCreateRoute
  '/app/analytics/': typeof AuthAppAnalyticsIndexRoute
  '/app/catalogs/': typeof AuthAppCatalogsIndexRoute
  '/app/roles/': typeof AuthAppRolesIndexRoute
  '/app/schools/': typeof AuthAppSchoolsIndexRoute
  '/app/support/': typeof AuthAppSupportIndexRoute
  '/app/users/': typeof AuthAppUsersIndexRoute
  '/app/catalogs/programs/$programId': typeof AuthAppCatalogsProgramsProgramIdRoute
  '/app/polar/checkout/success': typeof AuthAppPolarCheckoutSuccessRoute
  '/app/schools/$schoolId/edit': typeof AuthAppSchoolsSchoolIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo-request': typeof DemoRequestRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app/dashboard': typeof AuthAppDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
  '/app/catalogs/coefficients': typeof AuthAppCatalogsCoefficientsRoute
  '/app/catalogs/fee-type-templates': typeof AuthAppCatalogsFeeTypeTemplatesRoute
  '/app/catalogs/grades': typeof AuthAppCatalogsGradesRoute
  '/app/catalogs/programs': typeof AuthAppCatalogsProgramsRouteWithChildren
  '/app/catalogs/school-years': typeof AuthAppCatalogsSchoolYearsRoute
  '/app/catalogs/subjects': typeof AuthAppCatalogsSubjectsRoute
  '/app/catalogs/tracks': typeof AuthAppCatalogsTracksRoute
  '/app/polar/portal': typeof AuthAppPolarPortalRoute
  '/app/polar/subscriptions': typeof AuthAppPolarSubscriptionsRoute
  '/app/schools/$schoolId': typeof AuthAppSchoolsSchoolIdRoute
  '/app/schools/create': typeof AuthAppSchoolsCreateRoute
  '/app/analytics': typeof AuthAppAnalyticsIndexRoute
  '/app/catalogs': typeof AuthAppCatalogsIndexRoute
  '/app/roles': typeof AuthAppRolesIndexRoute
  '/app/schools': typeof AuthAppSchoolsIndexRoute
  '/app/support': typeof AuthAppSupportIndexRoute
  '/app/users': typeof AuthAppUsersIndexRoute
  '/app/catalogs/programs/$programId': typeof AuthAppCatalogsProgramsProgramIdRoute
  '/app/polar/checkout/success': typeof AuthAppPolarCheckoutSuccessRoute
  '/app/schools/$schoolId/edit': typeof AuthAppSchoolsSchoolIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/demo-request': typeof DemoRequestRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_auth/app/analytics': typeof AuthAppAnalyticsRouteWithChildren
  '/_auth/app/dashboard': typeof AuthAppDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_auth/app/catalogs/coefficients': typeof AuthAppCatalogsCoefficientsRoute
  '/_auth/app/catalogs/fee-type-templates': typeof AuthAppCatalogsFeeTypeTemplatesRoute
  '/_auth/app/catalogs/grades': typeof AuthAppCatalogsGradesRoute
  '/_auth/app/catalogs/programs': typeof AuthAppCatalogsProgramsRouteWithChildren
  '/_auth/app/catalogs/school-years': typeof AuthAppCatalogsSchoolYearsRoute
  '/_auth/app/catalogs/subjects': typeof AuthAppCatalogsSubjectsRoute
  '/_auth/app/catalogs/tracks': typeof AuthAppCatalogsTracksRoute
  '/_auth/app/polar/portal': typeof AuthAppPolarPortalRoute
  '/_auth/app/polar/subscriptions': typeof AuthAppPolarSubscriptionsRoute
  '/_auth/app/schools/$schoolId': typeof AuthAppSchoolsSchoolIdRoute
  '/_auth/app/schools/create': typeof AuthAppSchoolsCreateRoute
  '/_auth/app/analytics/': typeof AuthAppAnalyticsIndexRoute
  '/_auth/app/catalogs/': typeof AuthAppCatalogsIndexRoute
  '/_auth/app/roles/': typeof AuthAppRolesIndexRoute
  '/_auth/app/schools/': typeof AuthAppSchoolsIndexRoute
  '/_auth/app/support/': typeof AuthAppSupportIndexRoute
  '/_auth/app/users/': typeof AuthAppUsersIndexRoute
  '/_auth/app/catalogs/programs/$programId': typeof AuthAppCatalogsProgramsProgramIdRoute
  '/_auth/app/polar/checkout/success': typeof AuthAppPolarCheckoutSuccessRoute
  '/_auth/app/schools/$schoolId_/edit': typeof AuthAppSchoolsSchoolIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo-request'
    | '/unauthorized'
    | '/app'
    | '/app/analytics'
    | '/app/dashboard'
    | '/api/auth/$'
    | '/app/'
    | '/app/catalogs/coefficients'
    | '/app/catalogs/fee-type-templates'
    | '/app/catalogs/grades'
    | '/app/catalogs/programs'
    | '/app/catalogs/school-years'
    | '/app/catalogs/subjects'
    | '/app/catalogs/tracks'
    | '/app/polar/portal'
    | '/app/polar/subscriptions'
    | '/app/schools/$schoolId'
    | '/app/schools/create'
    | '/app/analytics/'
    | '/app/catalogs/'
    | '/app/roles/'
    | '/app/schools/'
    | '/app/support/'
    | '/app/users/'
    | '/app/catalogs/programs/$programId'
    | '/app/polar/checkout/success'
    | '/app/schools/$schoolId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo-request'
    | '/unauthorized'
    | '/app/dashboard'
    | '/api/auth/$'
    | '/app'
    | '/app/catalogs/coefficients'
    | '/app/catalogs/fee-type-templates'
    | '/app/catalogs/grades'
    | '/app/catalogs/programs'
    | '/app/catalogs/school-years'
    | '/app/catalogs/subjects'
    | '/app/catalogs/tracks'
    | '/app/polar/portal'
    | '/app/polar/subscriptions'
    | '/app/schools/$schoolId'
    | '/app/schools/create'
    | '/app/analytics'
    | '/app/catalogs'
    | '/app/roles'
    | '/app/schools'
    | '/app/support'
    | '/app/users'
    | '/app/catalogs/programs/$programId'
    | '/app/polar/checkout/success'
    | '/app/schools/$schoolId/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/demo-request'
    | '/unauthorized'
    | '/_auth/app'
    | '/_auth/app/analytics'
    | '/_auth/app/dashboard'
    | '/api/auth/$'
    | '/_auth/app/'
    | '/_auth/app/catalogs/coefficients'
    | '/_auth/app/catalogs/fee-type-templates'
    | '/_auth/app/catalogs/grades'
    | '/_auth/app/catalogs/programs'
    | '/_auth/app/catalogs/school-years'
    | '/_auth/app/catalogs/subjects'
    | '/_auth/app/catalogs/tracks'
    | '/_auth/app/polar/portal'
    | '/_auth/app/polar/subscriptions'
    | '/_auth/app/schools/$schoolId'
    | '/_auth/app/schools/create'
    | '/_auth/app/analytics/'
    | '/_auth/app/catalogs/'
    | '/_auth/app/roles/'
    | '/_auth/app/schools/'
    | '/_auth/app/support/'
    | '/_auth/app/users/'
    | '/_auth/app/catalogs/programs/$programId'
    | '/_auth/app/polar/checkout/success'
    | '/_auth/app/schools/$schoolId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DemoRequestRoute: typeof DemoRequestRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-request': {
      id: '/demo-request'
      path: '/demo-request'
      fullPath: '/demo-request'
      preLoaderRoute: typeof DemoRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/dashboard': {
      id: '/_auth/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthAppDashboardRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/analytics': {
      id: '/_auth/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AuthAppAnalyticsRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/users/': {
      id: '/_auth/app/users/'
      path: '/users'
      fullPath: '/app/users/'
      preLoaderRoute: typeof AuthAppUsersIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/support/': {
      id: '/_auth/app/support/'
      path: '/support'
      fullPath: '/app/support/'
      preLoaderRoute: typeof AuthAppSupportIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/schools/': {
      id: '/_auth/app/schools/'
      path: '/schools'
      fullPath: '/app/schools/'
      preLoaderRoute: typeof AuthAppSchoolsIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/roles/': {
      id: '/_auth/app/roles/'
      path: '/roles'
      fullPath: '/app/roles/'
      preLoaderRoute: typeof AuthAppRolesIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/catalogs/': {
      id: '/_auth/app/catalogs/'
      path: '/catalogs'
      fullPath: '/app/catalogs/'
      preLoaderRoute: typeof AuthAppCatalogsIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/analytics/': {
      id: '/_auth/app/analytics/'
      path: '/'
      fullPath: '/app/analytics/'
      preLoaderRoute: typeof AuthAppAnalyticsIndexRouteImport
      parentRoute: typeof AuthAppAnalyticsRoute
    }
    '/_auth/app/schools/create': {
      id: '/_auth/app/schools/create'
      path: '/schools/create'
      fullPath: '/app/schools/create'
      preLoaderRoute: typeof AuthAppSchoolsCreateRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/schools/$schoolId': {
      id: '/_auth/app/schools/$schoolId'
      path: '/schools/$schoolId'
      fullPath: '/app/schools/$schoolId'
      preLoaderRoute: typeof AuthAppSchoolsSchoolIdRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/polar/subscriptions': {
      id: '/_auth/app/polar/subscriptions'
      path: '/polar/subscriptions'
      fullPath: '/app/polar/subscriptions'
      preLoaderRoute: typeof AuthAppPolarSubscriptionsRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/polar/portal': {
      id: '/_auth/app/polar/portal'
      path: '/polar/portal'
      fullPath: '/app/polar/portal'
      preLoaderRoute: typeof AuthAppPolarPortalRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/catalogs/tracks': {
      id: '/_auth/app/catalogs/tracks'
      path: '/catalogs/tracks'
      fullPath: '/app/catalogs/tracks'
      preLoaderRoute: typeof AuthAppCatalogsTracksRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/catalogs/subjects': {
      id: '/_auth/app/catalogs/subjects'
      path: '/catalogs/subjects'
      fullPath: '/app/catalogs/subjects'
      preLoaderRoute: typeof AuthAppCatalogsSubjectsRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/catalogs/school-years': {
      id: '/_auth/app/catalogs/school-years'
      path: '/catalogs/school-years'
      fullPath: '/app/catalogs/school-years'
      preLoaderRoute: typeof AuthAppCatalogsSchoolYearsRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/catalogs/programs': {
      id: '/_auth/app/catalogs/programs'
      path: '/catalogs/programs'
      fullPath: '/app/catalogs/programs'
      preLoaderRoute: typeof AuthAppCatalogsProgramsRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/catalogs/grades': {
      id: '/_auth/app/catalogs/grades'
      path: '/catalogs/grades'
      fullPath: '/app/catalogs/grades'
      preLoaderRoute: typeof AuthAppCatalogsGradesRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/catalogs/fee-type-templates': {
      id: '/_auth/app/catalogs/fee-type-templates'
      path: '/catalogs/fee-type-templates'
      fullPath: '/app/catalogs/fee-type-templates'
      preLoaderRoute: typeof AuthAppCatalogsFeeTypeTemplatesRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/catalogs/coefficients': {
      id: '/_auth/app/catalogs/coefficients'
      path: '/catalogs/coefficients'
      fullPath: '/app/catalogs/coefficients'
      preLoaderRoute: typeof AuthAppCatalogsCoefficientsRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/schools/$schoolId_/edit': {
      id: '/_auth/app/schools/$schoolId_/edit'
      path: '/schools/$schoolId/edit'
      fullPath: '/app/schools/$schoolId/edit'
      preLoaderRoute: typeof AuthAppSchoolsSchoolIdEditRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/polar/checkout/success': {
      id: '/_auth/app/polar/checkout/success'
      path: '/polar/checkout/success'
      fullPath: '/app/polar/checkout/success'
      preLoaderRoute: typeof AuthAppPolarCheckoutSuccessRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/catalogs/programs/$programId': {
      id: '/_auth/app/catalogs/programs/$programId'
      path: '/$programId'
      fullPath: '/app/catalogs/programs/$programId'
      preLoaderRoute: typeof AuthAppCatalogsProgramsProgramIdRouteImport
      parentRoute: typeof AuthAppCatalogsProgramsRoute
    }
  }
}

interface AuthAppAnalyticsRouteChildren {
  AuthAppAnalyticsIndexRoute: typeof AuthAppAnalyticsIndexRoute
}

const AuthAppAnalyticsRouteChildren: AuthAppAnalyticsRouteChildren = {
  AuthAppAnalyticsIndexRoute: AuthAppAnalyticsIndexRoute,
}

const AuthAppAnalyticsRouteWithChildren =
  AuthAppAnalyticsRoute._addFileChildren(AuthAppAnalyticsRouteChildren)

interface AuthAppCatalogsProgramsRouteChildren {
  AuthAppCatalogsProgramsProgramIdRoute: typeof AuthAppCatalogsProgramsProgramIdRoute
}

const AuthAppCatalogsProgramsRouteChildren: AuthAppCatalogsProgramsRouteChildren =
  {
    AuthAppCatalogsProgramsProgramIdRoute:
      AuthAppCatalogsProgramsProgramIdRoute,
  }

const AuthAppCatalogsProgramsRouteWithChildren =
  AuthAppCatalogsProgramsRoute._addFileChildren(
    AuthAppCatalogsProgramsRouteChildren,
  )

interface AuthAppRouteRouteChildren {
  AuthAppAnalyticsRoute: typeof AuthAppAnalyticsRouteWithChildren
  AuthAppDashboardRoute: typeof AuthAppDashboardRoute
  AuthAppIndexRoute: typeof AuthAppIndexRoute
  AuthAppCatalogsCoefficientsRoute: typeof AuthAppCatalogsCoefficientsRoute
  AuthAppCatalogsFeeTypeTemplatesRoute: typeof AuthAppCatalogsFeeTypeTemplatesRoute
  AuthAppCatalogsGradesRoute: typeof AuthAppCatalogsGradesRoute
  AuthAppCatalogsProgramsRoute: typeof AuthAppCatalogsProgramsRouteWithChildren
  AuthAppCatalogsSchoolYearsRoute: typeof AuthAppCatalogsSchoolYearsRoute
  AuthAppCatalogsSubjectsRoute: typeof AuthAppCatalogsSubjectsRoute
  AuthAppCatalogsTracksRoute: typeof AuthAppCatalogsTracksRoute
  AuthAppPolarPortalRoute: typeof AuthAppPolarPortalRoute
  AuthAppPolarSubscriptionsRoute: typeof AuthAppPolarSubscriptionsRoute
  AuthAppSchoolsSchoolIdRoute: typeof AuthAppSchoolsSchoolIdRoute
  AuthAppSchoolsCreateRoute: typeof AuthAppSchoolsCreateRoute
  AuthAppCatalogsIndexRoute: typeof AuthAppCatalogsIndexRoute
  AuthAppRolesIndexRoute: typeof AuthAppRolesIndexRoute
  AuthAppSchoolsIndexRoute: typeof AuthAppSchoolsIndexRoute
  AuthAppSupportIndexRoute: typeof AuthAppSupportIndexRoute
  AuthAppUsersIndexRoute: typeof AuthAppUsersIndexRoute
  AuthAppPolarCheckoutSuccessRoute: typeof AuthAppPolarCheckoutSuccessRoute
  AuthAppSchoolsSchoolIdEditRoute: typeof AuthAppSchoolsSchoolIdEditRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppAnalyticsRoute: AuthAppAnalyticsRouteWithChildren,
  AuthAppDashboardRoute: AuthAppDashboardRoute,
  AuthAppIndexRoute: AuthAppIndexRoute,
  AuthAppCatalogsCoefficientsRoute: AuthAppCatalogsCoefficientsRoute,
  AuthAppCatalogsFeeTypeTemplatesRoute: AuthAppCatalogsFeeTypeTemplatesRoute,
  AuthAppCatalogsGradesRoute: AuthAppCatalogsGradesRoute,
  AuthAppCatalogsProgramsRoute: AuthAppCatalogsProgramsRouteWithChildren,
  AuthAppCatalogsSchoolYearsRoute: AuthAppCatalogsSchoolYearsRoute,
  AuthAppCatalogsSubjectsRoute: AuthAppCatalogsSubjectsRoute,
  AuthAppCatalogsTracksRoute: AuthAppCatalogsTracksRoute,
  AuthAppPolarPortalRoute: AuthAppPolarPortalRoute,
  AuthAppPolarSubscriptionsRoute: AuthAppPolarSubscriptionsRoute,
  AuthAppSchoolsSchoolIdRoute: AuthAppSchoolsSchoolIdRoute,
  AuthAppSchoolsCreateRoute: AuthAppSchoolsCreateRoute,
  AuthAppCatalogsIndexRoute: AuthAppCatalogsIndexRoute,
  AuthAppRolesIndexRoute: AuthAppRolesIndexRoute,
  AuthAppSchoolsIndexRoute: AuthAppSchoolsIndexRoute,
  AuthAppSupportIndexRoute: AuthAppSupportIndexRoute,
  AuthAppUsersIndexRoute: AuthAppUsersIndexRoute,
  AuthAppPolarCheckoutSuccessRoute: AuthAppPolarCheckoutSuccessRoute,
  AuthAppSchoolsSchoolIdEditRoute: AuthAppSchoolsSchoolIdEditRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DemoRequestRoute: DemoRequestRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
