/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthAppRouteImport } from './routes/_auth/app'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthAppSessionsRouteImport } from './routes/_auth/app/sessions'
import { Route as AuthAppScheduleRouteImport } from './routes/_auth/app/schedule'
import { Route as AuthAppNotificationsRouteImport } from './routes/_auth/app/notifications'
import { Route as AuthAppMessagesRouteImport } from './routes/_auth/app/messages'
import { Route as AuthAppHomeworkRouteImport } from './routes/_auth/app/homework'
import { Route as AuthAppGradesRouteImport } from './routes/_auth/app/grades'
import { Route as AuthAppClassesRouteImport } from './routes/_auth/app/classes'
import { Route as AuthAppAttendanceRouteImport } from './routes/_auth/app/attendance'
import { Route as AuthAppSessionsSessionIdRouteImport } from './routes/_auth/app/sessions.$sessionId'
import { Route as AuthAppMessagesComposeRouteImport } from './routes/_auth/app/messages.compose'
import { Route as AuthAppMessagesMessageIdRouteImport } from './routes/_auth/app/messages.$messageId'
import { Route as AuthAppHomeworkNewRouteImport } from './routes/_auth/app/homework.new'
import { Route as AuthAppHomeworkHomeworkIdRouteImport } from './routes/_auth/app/homework.$homeworkId'
import { Route as AuthAppStudentsStudentIdParentsRouteImport } from './routes/_auth/app/students.$studentId.parents'
import { Route as AuthAppStudentsStudentIdNotesRouteImport } from './routes/_auth/app/students.$studentId.notes'
import { Route as AuthAppGradesClassIdSubjectIdRouteImport } from './routes/_auth/app/grades.$classId.$subjectId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppRoute = AuthAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppSessionsRoute = AuthAppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppScheduleRoute = AuthAppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppNotificationsRoute = AuthAppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppMessagesRoute = AuthAppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppHomeworkRoute = AuthAppHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppGradesRoute = AuthAppGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppClassesRoute = AuthAppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppAttendanceRoute = AuthAppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppSessionsSessionIdRoute =
  AuthAppSessionsSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AuthAppSessionsRoute,
  } as any)
const AuthAppMessagesComposeRoute = AuthAppMessagesComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => AuthAppMessagesRoute,
} as any)
const AuthAppMessagesMessageIdRoute =
  AuthAppMessagesMessageIdRouteImport.update({
    id: '/$messageId',
    path: '/$messageId',
    getParentRoute: () => AuthAppMessagesRoute,
  } as any)
const AuthAppHomeworkNewRoute = AuthAppHomeworkNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthAppHomeworkRoute,
} as any)
const AuthAppHomeworkHomeworkIdRoute =
  AuthAppHomeworkHomeworkIdRouteImport.update({
    id: '/$homeworkId',
    path: '/$homeworkId',
    getParentRoute: () => AuthAppHomeworkRoute,
  } as any)
const AuthAppStudentsStudentIdParentsRoute =
  AuthAppStudentsStudentIdParentsRouteImport.update({
    id: '/students/$studentId/parents',
    path: '/students/$studentId/parents',
    getParentRoute: () => AuthAppRoute,
  } as any)
const AuthAppStudentsStudentIdNotesRoute =
  AuthAppStudentsStudentIdNotesRouteImport.update({
    id: '/students/$studentId/notes',
    path: '/students/$studentId/notes',
    getParentRoute: () => AuthAppRoute,
  } as any)
const AuthAppGradesClassIdSubjectIdRoute =
  AuthAppGradesClassIdSubjectIdRouteImport.update({
    id: '/$classId/$subjectId',
    path: '/$classId/$subjectId',
    getParentRoute: () => AuthAppGradesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AuthAppRouteWithChildren
  '/app/attendance': typeof AuthAppAttendanceRoute
  '/app/classes': typeof AuthAppClassesRoute
  '/app/grades': typeof AuthAppGradesRouteWithChildren
  '/app/homework': typeof AuthAppHomeworkRouteWithChildren
  '/app/messages': typeof AuthAppMessagesRouteWithChildren
  '/app/notifications': typeof AuthAppNotificationsRoute
  '/app/schedule': typeof AuthAppScheduleRoute
  '/app/sessions': typeof AuthAppSessionsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof AuthAppIndexRoute
  '/app/homework/$homeworkId': typeof AuthAppHomeworkHomeworkIdRoute
  '/app/homework/new': typeof AuthAppHomeworkNewRoute
  '/app/messages/$messageId': typeof AuthAppMessagesMessageIdRoute
  '/app/messages/compose': typeof AuthAppMessagesComposeRoute
  '/app/sessions/$sessionId': typeof AuthAppSessionsSessionIdRoute
  '/app/grades/$classId/$subjectId': typeof AuthAppGradesClassIdSubjectIdRoute
  '/app/students/$studentId/notes': typeof AuthAppStudentsStudentIdNotesRoute
  '/app/students/$studentId/parents': typeof AuthAppStudentsStudentIdParentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/attendance': typeof AuthAppAttendanceRoute
  '/app/classes': typeof AuthAppClassesRoute
  '/app/grades': typeof AuthAppGradesRouteWithChildren
  '/app/homework': typeof AuthAppHomeworkRouteWithChildren
  '/app/messages': typeof AuthAppMessagesRouteWithChildren
  '/app/notifications': typeof AuthAppNotificationsRoute
  '/app/schedule': typeof AuthAppScheduleRoute
  '/app/sessions': typeof AuthAppSessionsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
  '/app/homework/$homeworkId': typeof AuthAppHomeworkHomeworkIdRoute
  '/app/homework/new': typeof AuthAppHomeworkNewRoute
  '/app/messages/$messageId': typeof AuthAppMessagesMessageIdRoute
  '/app/messages/compose': typeof AuthAppMessagesComposeRoute
  '/app/sessions/$sessionId': typeof AuthAppSessionsSessionIdRoute
  '/app/grades/$classId/$subjectId': typeof AuthAppGradesClassIdSubjectIdRoute
  '/app/students/$studentId/notes': typeof AuthAppStudentsStudentIdNotesRoute
  '/app/students/$studentId/parents': typeof AuthAppStudentsStudentIdParentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/app': typeof AuthAppRouteWithChildren
  '/_auth/app/attendance': typeof AuthAppAttendanceRoute
  '/_auth/app/classes': typeof AuthAppClassesRoute
  '/_auth/app/grades': typeof AuthAppGradesRouteWithChildren
  '/_auth/app/homework': typeof AuthAppHomeworkRouteWithChildren
  '/_auth/app/messages': typeof AuthAppMessagesRouteWithChildren
  '/_auth/app/notifications': typeof AuthAppNotificationsRoute
  '/_auth/app/schedule': typeof AuthAppScheduleRoute
  '/_auth/app/sessions': typeof AuthAppSessionsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_auth/app/homework/$homeworkId': typeof AuthAppHomeworkHomeworkIdRoute
  '/_auth/app/homework/new': typeof AuthAppHomeworkNewRoute
  '/_auth/app/messages/$messageId': typeof AuthAppMessagesMessageIdRoute
  '/_auth/app/messages/compose': typeof AuthAppMessagesComposeRoute
  '/_auth/app/sessions/$sessionId': typeof AuthAppSessionsSessionIdRoute
  '/_auth/app/grades/$classId/$subjectId': typeof AuthAppGradesClassIdSubjectIdRoute
  '/_auth/app/students/$studentId/notes': typeof AuthAppStudentsStudentIdNotesRoute
  '/_auth/app/students/$studentId/parents': typeof AuthAppStudentsStudentIdParentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/app'
    | '/app/attendance'
    | '/app/classes'
    | '/app/grades'
    | '/app/homework'
    | '/app/messages'
    | '/app/notifications'
    | '/app/schedule'
    | '/app/sessions'
    | '/api/auth/$'
    | '/app/'
    | '/app/homework/$homeworkId'
    | '/app/homework/new'
    | '/app/messages/$messageId'
    | '/app/messages/compose'
    | '/app/sessions/$sessionId'
    | '/app/grades/$classId/$subjectId'
    | '/app/students/$studentId/notes'
    | '/app/students/$studentId/parents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/attendance'
    | '/app/classes'
    | '/app/grades'
    | '/app/homework'
    | '/app/messages'
    | '/app/notifications'
    | '/app/schedule'
    | '/app/sessions'
    | '/api/auth/$'
    | '/app'
    | '/app/homework/$homeworkId'
    | '/app/homework/new'
    | '/app/messages/$messageId'
    | '/app/messages/compose'
    | '/app/sessions/$sessionId'
    | '/app/grades/$classId/$subjectId'
    | '/app/students/$studentId/notes'
    | '/app/students/$studentId/parents'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/app'
    | '/_auth/app/attendance'
    | '/_auth/app/classes'
    | '/_auth/app/grades'
    | '/_auth/app/homework'
    | '/_auth/app/messages'
    | '/_auth/app/notifications'
    | '/_auth/app/schedule'
    | '/_auth/app/sessions'
    | '/api/auth/$'
    | '/_auth/app/'
    | '/_auth/app/homework/$homeworkId'
    | '/_auth/app/homework/new'
    | '/_auth/app/messages/$messageId'
    | '/_auth/app/messages/compose'
    | '/_auth/app/sessions/$sessionId'
    | '/_auth/app/grades/$classId/$subjectId'
    | '/_auth/app/students/$studentId/notes'
    | '/_auth/app/students/$studentId/parents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/sessions': {
      id: '/_auth/app/sessions'
      path: '/sessions'
      fullPath: '/app/sessions'
      preLoaderRoute: typeof AuthAppSessionsRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/schedule': {
      id: '/_auth/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AuthAppScheduleRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/notifications': {
      id: '/_auth/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthAppNotificationsRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/messages': {
      id: '/_auth/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AuthAppMessagesRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/homework': {
      id: '/_auth/app/homework'
      path: '/homework'
      fullPath: '/app/homework'
      preLoaderRoute: typeof AuthAppHomeworkRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/grades': {
      id: '/_auth/app/grades'
      path: '/grades'
      fullPath: '/app/grades'
      preLoaderRoute: typeof AuthAppGradesRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/classes': {
      id: '/_auth/app/classes'
      path: '/classes'
      fullPath: '/app/classes'
      preLoaderRoute: typeof AuthAppClassesRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/attendance': {
      id: '/_auth/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AuthAppAttendanceRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/sessions/$sessionId': {
      id: '/_auth/app/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/app/sessions/$sessionId'
      preLoaderRoute: typeof AuthAppSessionsSessionIdRouteImport
      parentRoute: typeof AuthAppSessionsRoute
    }
    '/_auth/app/messages/compose': {
      id: '/_auth/app/messages/compose'
      path: '/compose'
      fullPath: '/app/messages/compose'
      preLoaderRoute: typeof AuthAppMessagesComposeRouteImport
      parentRoute: typeof AuthAppMessagesRoute
    }
    '/_auth/app/messages/$messageId': {
      id: '/_auth/app/messages/$messageId'
      path: '/$messageId'
      fullPath: '/app/messages/$messageId'
      preLoaderRoute: typeof AuthAppMessagesMessageIdRouteImport
      parentRoute: typeof AuthAppMessagesRoute
    }
    '/_auth/app/homework/new': {
      id: '/_auth/app/homework/new'
      path: '/new'
      fullPath: '/app/homework/new'
      preLoaderRoute: typeof AuthAppHomeworkNewRouteImport
      parentRoute: typeof AuthAppHomeworkRoute
    }
    '/_auth/app/homework/$homeworkId': {
      id: '/_auth/app/homework/$homeworkId'
      path: '/$homeworkId'
      fullPath: '/app/homework/$homeworkId'
      preLoaderRoute: typeof AuthAppHomeworkHomeworkIdRouteImport
      parentRoute: typeof AuthAppHomeworkRoute
    }
    '/_auth/app/students/$studentId/parents': {
      id: '/_auth/app/students/$studentId/parents'
      path: '/students/$studentId/parents'
      fullPath: '/app/students/$studentId/parents'
      preLoaderRoute: typeof AuthAppStudentsStudentIdParentsRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/students/$studentId/notes': {
      id: '/_auth/app/students/$studentId/notes'
      path: '/students/$studentId/notes'
      fullPath: '/app/students/$studentId/notes'
      preLoaderRoute: typeof AuthAppStudentsStudentIdNotesRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/grades/$classId/$subjectId': {
      id: '/_auth/app/grades/$classId/$subjectId'
      path: '/$classId/$subjectId'
      fullPath: '/app/grades/$classId/$subjectId'
      preLoaderRoute: typeof AuthAppGradesClassIdSubjectIdRouteImport
      parentRoute: typeof AuthAppGradesRoute
    }
  }
}

interface AuthAppGradesRouteChildren {
  AuthAppGradesClassIdSubjectIdRoute: typeof AuthAppGradesClassIdSubjectIdRoute
}

const AuthAppGradesRouteChildren: AuthAppGradesRouteChildren = {
  AuthAppGradesClassIdSubjectIdRoute: AuthAppGradesClassIdSubjectIdRoute,
}

const AuthAppGradesRouteWithChildren = AuthAppGradesRoute._addFileChildren(
  AuthAppGradesRouteChildren,
)

interface AuthAppHomeworkRouteChildren {
  AuthAppHomeworkHomeworkIdRoute: typeof AuthAppHomeworkHomeworkIdRoute
  AuthAppHomeworkNewRoute: typeof AuthAppHomeworkNewRoute
}

const AuthAppHomeworkRouteChildren: AuthAppHomeworkRouteChildren = {
  AuthAppHomeworkHomeworkIdRoute: AuthAppHomeworkHomeworkIdRoute,
  AuthAppHomeworkNewRoute: AuthAppHomeworkNewRoute,
}

const AuthAppHomeworkRouteWithChildren = AuthAppHomeworkRoute._addFileChildren(
  AuthAppHomeworkRouteChildren,
)

interface AuthAppMessagesRouteChildren {
  AuthAppMessagesMessageIdRoute: typeof AuthAppMessagesMessageIdRoute
  AuthAppMessagesComposeRoute: typeof AuthAppMessagesComposeRoute
}

const AuthAppMessagesRouteChildren: AuthAppMessagesRouteChildren = {
  AuthAppMessagesMessageIdRoute: AuthAppMessagesMessageIdRoute,
  AuthAppMessagesComposeRoute: AuthAppMessagesComposeRoute,
}

const AuthAppMessagesRouteWithChildren = AuthAppMessagesRoute._addFileChildren(
  AuthAppMessagesRouteChildren,
)

interface AuthAppSessionsRouteChildren {
  AuthAppSessionsSessionIdRoute: typeof AuthAppSessionsSessionIdRoute
}

const AuthAppSessionsRouteChildren: AuthAppSessionsRouteChildren = {
  AuthAppSessionsSessionIdRoute: AuthAppSessionsSessionIdRoute,
}

const AuthAppSessionsRouteWithChildren = AuthAppSessionsRoute._addFileChildren(
  AuthAppSessionsRouteChildren,
)

interface AuthAppRouteChildren {
  AuthAppAttendanceRoute: typeof AuthAppAttendanceRoute
  AuthAppClassesRoute: typeof AuthAppClassesRoute
  AuthAppGradesRoute: typeof AuthAppGradesRouteWithChildren
  AuthAppHomeworkRoute: typeof AuthAppHomeworkRouteWithChildren
  AuthAppMessagesRoute: typeof AuthAppMessagesRouteWithChildren
  AuthAppNotificationsRoute: typeof AuthAppNotificationsRoute
  AuthAppScheduleRoute: typeof AuthAppScheduleRoute
  AuthAppSessionsRoute: typeof AuthAppSessionsRouteWithChildren
  AuthAppIndexRoute: typeof AuthAppIndexRoute
  AuthAppStudentsStudentIdNotesRoute: typeof AuthAppStudentsStudentIdNotesRoute
  AuthAppStudentsStudentIdParentsRoute: typeof AuthAppStudentsStudentIdParentsRoute
}

const AuthAppRouteChildren: AuthAppRouteChildren = {
  AuthAppAttendanceRoute: AuthAppAttendanceRoute,
  AuthAppClassesRoute: AuthAppClassesRoute,
  AuthAppGradesRoute: AuthAppGradesRouteWithChildren,
  AuthAppHomeworkRoute: AuthAppHomeworkRouteWithChildren,
  AuthAppMessagesRoute: AuthAppMessagesRouteWithChildren,
  AuthAppNotificationsRoute: AuthAppNotificationsRoute,
  AuthAppScheduleRoute: AuthAppScheduleRoute,
  AuthAppSessionsRoute: AuthAppSessionsRouteWithChildren,
  AuthAppIndexRoute: AuthAppIndexRoute,
  AuthAppStudentsStudentIdNotesRoute: AuthAppStudentsStudentIdNotesRoute,
  AuthAppStudentsStudentIdParentsRoute: AuthAppStudentsStudentIdParentsRoute,
}

const AuthAppRouteWithChildren =
  AuthAppRoute._addFileChildren(AuthAppRouteChildren)

interface AuthRouteChildren {
  AuthAppRoute: typeof AuthAppRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAppRoute: AuthAppRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
