/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthAppRouteImport } from './routes/_auth/app'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthAppSessionRouteImport } from './routes/_auth/app/session'
import { Route as AuthAppProfileRouteImport } from './routes/_auth/app/profile'
import { Route as AuthAppNotificationsRouteImport } from './routes/_auth/app/notifications'
import { Route as AuthAppHomeworkRouteImport } from './routes/_auth/app/homework'
import { Route as AuthAppGradesRouteImport } from './routes/_auth/app/grades'
import { Route as AuthAppClassesRouteImport } from './routes/_auth/app/classes'
import { Route as AuthAppChatRouteImport } from './routes/_auth/app/chat'
import { Route as AuthAppAttendanceRouteImport } from './routes/_auth/app/attendance'
import { Route as AuthAppSchoolsIndexRouteImport } from './routes/_auth/app/schools.index'
import { Route as AuthAppSessionsSessionIdRouteImport } from './routes/_auth/app/sessions.$sessionId'
import { Route as AuthAppHomeworkNewRouteImport } from './routes/_auth/app/homework.new'
import { Route as AuthAppHomeworkHomeworkIdRouteImport } from './routes/_auth/app/homework.$homeworkId'
import { Route as AuthAppChatComposeRouteImport } from './routes/_auth/app/chat.compose'
import { Route as AuthAppChatMessageIdRouteImport } from './routes/_auth/app/chat.$messageId'
import { Route as AuthAppStudentsStudentIdParentsRouteImport } from './routes/_auth/app/students.$studentId.parents'
import { Route as AuthAppStudentsStudentIdNotesRouteImport } from './routes/_auth/app/students.$studentId.notes'
import { Route as AuthAppSchoolsSchoolIdClassesRouteImport } from './routes/_auth/app/schools.$schoolId.classes'
import { Route as AuthAppGradesClassIdSubjectIdRouteImport } from './routes/_auth/app/grades.$classId.$subjectId'
import { Route as AuthAppSchoolsSchoolIdClassClassIdRouteImport } from './routes/_auth/app/schools.$schoolId.class.$classId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppRoute = AuthAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppSessionRoute = AuthAppSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppProfileRoute = AuthAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppNotificationsRoute = AuthAppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppHomeworkRoute = AuthAppHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppGradesRoute = AuthAppGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppClassesRoute = AuthAppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppChatRoute = AuthAppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppAttendanceRoute = AuthAppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppSchoolsIndexRoute = AuthAppSchoolsIndexRouteImport.update({
  id: '/schools/',
  path: '/schools/',
  getParentRoute: () => AuthAppRoute,
} as any)
const AuthAppSessionsSessionIdRoute =
  AuthAppSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => AuthAppRoute,
  } as any)
const AuthAppHomeworkNewRoute = AuthAppHomeworkNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthAppHomeworkRoute,
} as any)
const AuthAppHomeworkHomeworkIdRoute =
  AuthAppHomeworkHomeworkIdRouteImport.update({
    id: '/$homeworkId',
    path: '/$homeworkId',
    getParentRoute: () => AuthAppHomeworkRoute,
  } as any)
const AuthAppChatComposeRoute = AuthAppChatComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => AuthAppChatRoute,
} as any)
const AuthAppChatMessageIdRoute = AuthAppChatMessageIdRouteImport.update({
  id: '/$messageId',
  path: '/$messageId',
  getParentRoute: () => AuthAppChatRoute,
} as any)
const AuthAppStudentsStudentIdParentsRoute =
  AuthAppStudentsStudentIdParentsRouteImport.update({
    id: '/students/$studentId/parents',
    path: '/students/$studentId/parents',
    getParentRoute: () => AuthAppRoute,
  } as any)
const AuthAppStudentsStudentIdNotesRoute =
  AuthAppStudentsStudentIdNotesRouteImport.update({
    id: '/students/$studentId/notes',
    path: '/students/$studentId/notes',
    getParentRoute: () => AuthAppRoute,
  } as any)
const AuthAppSchoolsSchoolIdClassesRoute =
  AuthAppSchoolsSchoolIdClassesRouteImport.update({
    id: '/schools/$schoolId/classes',
    path: '/schools/$schoolId/classes',
    getParentRoute: () => AuthAppRoute,
  } as any)
const AuthAppGradesClassIdSubjectIdRoute =
  AuthAppGradesClassIdSubjectIdRouteImport.update({
    id: '/$classId/$subjectId',
    path: '/$classId/$subjectId',
    getParentRoute: () => AuthAppGradesRoute,
  } as any)
const AuthAppSchoolsSchoolIdClassClassIdRoute =
  AuthAppSchoolsSchoolIdClassClassIdRouteImport.update({
    id: '/schools/$schoolId/class/$classId',
    path: '/schools/$schoolId/class/$classId',
    getParentRoute: () => AuthAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app': typeof AuthAppRouteWithChildren
  '/app/attendance': typeof AuthAppAttendanceRoute
  '/app/chat': typeof AuthAppChatRouteWithChildren
  '/app/classes': typeof AuthAppClassesRoute
  '/app/grades': typeof AuthAppGradesRouteWithChildren
  '/app/homework': typeof AuthAppHomeworkRouteWithChildren
  '/app/notifications': typeof AuthAppNotificationsRoute
  '/app/profile': typeof AuthAppProfileRoute
  '/app/session': typeof AuthAppSessionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof AuthAppIndexRoute
  '/app/chat/$messageId': typeof AuthAppChatMessageIdRoute
  '/app/chat/compose': typeof AuthAppChatComposeRoute
  '/app/homework/$homeworkId': typeof AuthAppHomeworkHomeworkIdRoute
  '/app/homework/new': typeof AuthAppHomeworkNewRoute
  '/app/sessions/$sessionId': typeof AuthAppSessionsSessionIdRoute
  '/app/schools/': typeof AuthAppSchoolsIndexRoute
  '/app/grades/$classId/$subjectId': typeof AuthAppGradesClassIdSubjectIdRoute
  '/app/schools/$schoolId/classes': typeof AuthAppSchoolsSchoolIdClassesRoute
  '/app/students/$studentId/notes': typeof AuthAppStudentsStudentIdNotesRoute
  '/app/students/$studentId/parents': typeof AuthAppStudentsStudentIdParentsRoute
  '/app/schools/$schoolId/class/$classId': typeof AuthAppSchoolsSchoolIdClassClassIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/attendance': typeof AuthAppAttendanceRoute
  '/app/chat': typeof AuthAppChatRouteWithChildren
  '/app/classes': typeof AuthAppClassesRoute
  '/app/grades': typeof AuthAppGradesRouteWithChildren
  '/app/homework': typeof AuthAppHomeworkRouteWithChildren
  '/app/notifications': typeof AuthAppNotificationsRoute
  '/app/profile': typeof AuthAppProfileRoute
  '/app/session': typeof AuthAppSessionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
  '/app/chat/$messageId': typeof AuthAppChatMessageIdRoute
  '/app/chat/compose': typeof AuthAppChatComposeRoute
  '/app/homework/$homeworkId': typeof AuthAppHomeworkHomeworkIdRoute
  '/app/homework/new': typeof AuthAppHomeworkNewRoute
  '/app/sessions/$sessionId': typeof AuthAppSessionsSessionIdRoute
  '/app/schools': typeof AuthAppSchoolsIndexRoute
  '/app/grades/$classId/$subjectId': typeof AuthAppGradesClassIdSubjectIdRoute
  '/app/schools/$schoolId/classes': typeof AuthAppSchoolsSchoolIdClassesRoute
  '/app/students/$studentId/notes': typeof AuthAppStudentsStudentIdNotesRoute
  '/app/students/$studentId/parents': typeof AuthAppStudentsStudentIdParentsRoute
  '/app/schools/$schoolId/class/$classId': typeof AuthAppSchoolsSchoolIdClassClassIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_auth/app': typeof AuthAppRouteWithChildren
  '/_auth/app/attendance': typeof AuthAppAttendanceRoute
  '/_auth/app/chat': typeof AuthAppChatRouteWithChildren
  '/_auth/app/classes': typeof AuthAppClassesRoute
  '/_auth/app/grades': typeof AuthAppGradesRouteWithChildren
  '/_auth/app/homework': typeof AuthAppHomeworkRouteWithChildren
  '/_auth/app/notifications': typeof AuthAppNotificationsRoute
  '/_auth/app/profile': typeof AuthAppProfileRoute
  '/_auth/app/session': typeof AuthAppSessionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_auth/app/chat/$messageId': typeof AuthAppChatMessageIdRoute
  '/_auth/app/chat/compose': typeof AuthAppChatComposeRoute
  '/_auth/app/homework/$homeworkId': typeof AuthAppHomeworkHomeworkIdRoute
  '/_auth/app/homework/new': typeof AuthAppHomeworkNewRoute
  '/_auth/app/sessions/$sessionId': typeof AuthAppSessionsSessionIdRoute
  '/_auth/app/schools/': typeof AuthAppSchoolsIndexRoute
  '/_auth/app/grades/$classId/$subjectId': typeof AuthAppGradesClassIdSubjectIdRoute
  '/_auth/app/schools/$schoolId/classes': typeof AuthAppSchoolsSchoolIdClassesRoute
  '/_auth/app/students/$studentId/notes': typeof AuthAppStudentsStudentIdNotesRoute
  '/_auth/app/students/$studentId/parents': typeof AuthAppStudentsStudentIdParentsRoute
  '/_auth/app/schools/$schoolId/class/$classId': typeof AuthAppSchoolsSchoolIdClassClassIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/app'
    | '/app/attendance'
    | '/app/chat'
    | '/app/classes'
    | '/app/grades'
    | '/app/homework'
    | '/app/notifications'
    | '/app/profile'
    | '/app/session'
    | '/api/auth/$'
    | '/app/'
    | '/app/chat/$messageId'
    | '/app/chat/compose'
    | '/app/homework/$homeworkId'
    | '/app/homework/new'
    | '/app/sessions/$sessionId'
    | '/app/schools/'
    | '/app/grades/$classId/$subjectId'
    | '/app/schools/$schoolId/classes'
    | '/app/students/$studentId/notes'
    | '/app/students/$studentId/parents'
    | '/app/schools/$schoolId/class/$classId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/attendance'
    | '/app/chat'
    | '/app/classes'
    | '/app/grades'
    | '/app/homework'
    | '/app/notifications'
    | '/app/profile'
    | '/app/session'
    | '/api/auth/$'
    | '/app'
    | '/app/chat/$messageId'
    | '/app/chat/compose'
    | '/app/homework/$homeworkId'
    | '/app/homework/new'
    | '/app/sessions/$sessionId'
    | '/app/schools'
    | '/app/grades/$classId/$subjectId'
    | '/app/schools/$schoolId/classes'
    | '/app/students/$studentId/notes'
    | '/app/students/$studentId/parents'
    | '/app/schools/$schoolId/class/$classId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/signup'
    | '/_auth/app'
    | '/_auth/app/attendance'
    | '/_auth/app/chat'
    | '/_auth/app/classes'
    | '/_auth/app/grades'
    | '/_auth/app/homework'
    | '/_auth/app/notifications'
    | '/_auth/app/profile'
    | '/_auth/app/session'
    | '/api/auth/$'
    | '/_auth/app/'
    | '/_auth/app/chat/$messageId'
    | '/_auth/app/chat/compose'
    | '/_auth/app/homework/$homeworkId'
    | '/_auth/app/homework/new'
    | '/_auth/app/sessions/$sessionId'
    | '/_auth/app/schools/'
    | '/_auth/app/grades/$classId/$subjectId'
    | '/_auth/app/schools/$schoolId/classes'
    | '/_auth/app/students/$studentId/notes'
    | '/_auth/app/students/$studentId/parents'
    | '/_auth/app/schools/$schoolId/class/$classId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/session': {
      id: '/_auth/app/session'
      path: '/session'
      fullPath: '/app/session'
      preLoaderRoute: typeof AuthAppSessionRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/profile': {
      id: '/_auth/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthAppProfileRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/notifications': {
      id: '/_auth/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthAppNotificationsRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/homework': {
      id: '/_auth/app/homework'
      path: '/homework'
      fullPath: '/app/homework'
      preLoaderRoute: typeof AuthAppHomeworkRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/grades': {
      id: '/_auth/app/grades'
      path: '/grades'
      fullPath: '/app/grades'
      preLoaderRoute: typeof AuthAppGradesRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/classes': {
      id: '/_auth/app/classes'
      path: '/classes'
      fullPath: '/app/classes'
      preLoaderRoute: typeof AuthAppClassesRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/chat': {
      id: '/_auth/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AuthAppChatRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/attendance': {
      id: '/_auth/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AuthAppAttendanceRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/schools/': {
      id: '/_auth/app/schools/'
      path: '/schools'
      fullPath: '/app/schools/'
      preLoaderRoute: typeof AuthAppSchoolsIndexRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/sessions/$sessionId': {
      id: '/_auth/app/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/app/sessions/$sessionId'
      preLoaderRoute: typeof AuthAppSessionsSessionIdRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/homework/new': {
      id: '/_auth/app/homework/new'
      path: '/new'
      fullPath: '/app/homework/new'
      preLoaderRoute: typeof AuthAppHomeworkNewRouteImport
      parentRoute: typeof AuthAppHomeworkRoute
    }
    '/_auth/app/homework/$homeworkId': {
      id: '/_auth/app/homework/$homeworkId'
      path: '/$homeworkId'
      fullPath: '/app/homework/$homeworkId'
      preLoaderRoute: typeof AuthAppHomeworkHomeworkIdRouteImport
      parentRoute: typeof AuthAppHomeworkRoute
    }
    '/_auth/app/chat/compose': {
      id: '/_auth/app/chat/compose'
      path: '/compose'
      fullPath: '/app/chat/compose'
      preLoaderRoute: typeof AuthAppChatComposeRouteImport
      parentRoute: typeof AuthAppChatRoute
    }
    '/_auth/app/chat/$messageId': {
      id: '/_auth/app/chat/$messageId'
      path: '/$messageId'
      fullPath: '/app/chat/$messageId'
      preLoaderRoute: typeof AuthAppChatMessageIdRouteImport
      parentRoute: typeof AuthAppChatRoute
    }
    '/_auth/app/students/$studentId/parents': {
      id: '/_auth/app/students/$studentId/parents'
      path: '/students/$studentId/parents'
      fullPath: '/app/students/$studentId/parents'
      preLoaderRoute: typeof AuthAppStudentsStudentIdParentsRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/students/$studentId/notes': {
      id: '/_auth/app/students/$studentId/notes'
      path: '/students/$studentId/notes'
      fullPath: '/app/students/$studentId/notes'
      preLoaderRoute: typeof AuthAppStudentsStudentIdNotesRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/schools/$schoolId/classes': {
      id: '/_auth/app/schools/$schoolId/classes'
      path: '/schools/$schoolId/classes'
      fullPath: '/app/schools/$schoolId/classes'
      preLoaderRoute: typeof AuthAppSchoolsSchoolIdClassesRouteImport
      parentRoute: typeof AuthAppRoute
    }
    '/_auth/app/grades/$classId/$subjectId': {
      id: '/_auth/app/grades/$classId/$subjectId'
      path: '/$classId/$subjectId'
      fullPath: '/app/grades/$classId/$subjectId'
      preLoaderRoute: typeof AuthAppGradesClassIdSubjectIdRouteImport
      parentRoute: typeof AuthAppGradesRoute
    }
    '/_auth/app/schools/$schoolId/class/$classId': {
      id: '/_auth/app/schools/$schoolId/class/$classId'
      path: '/schools/$schoolId/class/$classId'
      fullPath: '/app/schools/$schoolId/class/$classId'
      preLoaderRoute: typeof AuthAppSchoolsSchoolIdClassClassIdRouteImport
      parentRoute: typeof AuthAppRoute
    }
  }
}

interface AuthAppChatRouteChildren {
  AuthAppChatMessageIdRoute: typeof AuthAppChatMessageIdRoute
  AuthAppChatComposeRoute: typeof AuthAppChatComposeRoute
}

const AuthAppChatRouteChildren: AuthAppChatRouteChildren = {
  AuthAppChatMessageIdRoute: AuthAppChatMessageIdRoute,
  AuthAppChatComposeRoute: AuthAppChatComposeRoute,
}

const AuthAppChatRouteWithChildren = AuthAppChatRoute._addFileChildren(
  AuthAppChatRouteChildren,
)

interface AuthAppGradesRouteChildren {
  AuthAppGradesClassIdSubjectIdRoute: typeof AuthAppGradesClassIdSubjectIdRoute
}

const AuthAppGradesRouteChildren: AuthAppGradesRouteChildren = {
  AuthAppGradesClassIdSubjectIdRoute: AuthAppGradesClassIdSubjectIdRoute,
}

const AuthAppGradesRouteWithChildren = AuthAppGradesRoute._addFileChildren(
  AuthAppGradesRouteChildren,
)

interface AuthAppHomeworkRouteChildren {
  AuthAppHomeworkHomeworkIdRoute: typeof AuthAppHomeworkHomeworkIdRoute
  AuthAppHomeworkNewRoute: typeof AuthAppHomeworkNewRoute
}

const AuthAppHomeworkRouteChildren: AuthAppHomeworkRouteChildren = {
  AuthAppHomeworkHomeworkIdRoute: AuthAppHomeworkHomeworkIdRoute,
  AuthAppHomeworkNewRoute: AuthAppHomeworkNewRoute,
}

const AuthAppHomeworkRouteWithChildren = AuthAppHomeworkRoute._addFileChildren(
  AuthAppHomeworkRouteChildren,
)

interface AuthAppRouteChildren {
  AuthAppAttendanceRoute: typeof AuthAppAttendanceRoute
  AuthAppChatRoute: typeof AuthAppChatRouteWithChildren
  AuthAppClassesRoute: typeof AuthAppClassesRoute
  AuthAppGradesRoute: typeof AuthAppGradesRouteWithChildren
  AuthAppHomeworkRoute: typeof AuthAppHomeworkRouteWithChildren
  AuthAppNotificationsRoute: typeof AuthAppNotificationsRoute
  AuthAppProfileRoute: typeof AuthAppProfileRoute
  AuthAppSessionRoute: typeof AuthAppSessionRoute
  AuthAppIndexRoute: typeof AuthAppIndexRoute
  AuthAppSessionsSessionIdRoute: typeof AuthAppSessionsSessionIdRoute
  AuthAppSchoolsIndexRoute: typeof AuthAppSchoolsIndexRoute
  AuthAppSchoolsSchoolIdClassesRoute: typeof AuthAppSchoolsSchoolIdClassesRoute
  AuthAppStudentsStudentIdNotesRoute: typeof AuthAppStudentsStudentIdNotesRoute
  AuthAppStudentsStudentIdParentsRoute: typeof AuthAppStudentsStudentIdParentsRoute
  AuthAppSchoolsSchoolIdClassClassIdRoute: typeof AuthAppSchoolsSchoolIdClassClassIdRoute
}

const AuthAppRouteChildren: AuthAppRouteChildren = {
  AuthAppAttendanceRoute: AuthAppAttendanceRoute,
  AuthAppChatRoute: AuthAppChatRouteWithChildren,
  AuthAppClassesRoute: AuthAppClassesRoute,
  AuthAppGradesRoute: AuthAppGradesRouteWithChildren,
  AuthAppHomeworkRoute: AuthAppHomeworkRouteWithChildren,
  AuthAppNotificationsRoute: AuthAppNotificationsRoute,
  AuthAppProfileRoute: AuthAppProfileRoute,
  AuthAppSessionRoute: AuthAppSessionRoute,
  AuthAppIndexRoute: AuthAppIndexRoute,
  AuthAppSessionsSessionIdRoute: AuthAppSessionsSessionIdRoute,
  AuthAppSchoolsIndexRoute: AuthAppSchoolsIndexRoute,
  AuthAppSchoolsSchoolIdClassesRoute: AuthAppSchoolsSchoolIdClassesRoute,
  AuthAppStudentsStudentIdNotesRoute: AuthAppStudentsStudentIdNotesRoute,
  AuthAppStudentsStudentIdParentsRoute: AuthAppStudentsStudentIdParentsRoute,
  AuthAppSchoolsSchoolIdClassClassIdRoute:
    AuthAppSchoolsSchoolIdClassClassIdRoute,
}

const AuthAppRouteWithChildren =
  AuthAppRoute._addFileChildren(AuthAppRouteChildren)

interface AuthRouteChildren {
  AuthAppRoute: typeof AuthAppRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAppRoute: AuthAppRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
